LPS-150036 Create Application Products Chart
pt-liferay-solutions/liferay-portal pull request #1267
Opened 2022-04-20 19:30 UTC by joanagrego

2022-04-20 19:31 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-04-20 19:32 UTC, joanagrego commented
ci:test:sf

2022-04-20 19:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-source-format/1009/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1009/jenkins-report.html">here</a>.</b></p>

2022-04-20 19:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/250d317b64e993cd03b6de183317969650e5f03e">250d317b64e993cd03b6de183317969650e5f03e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joanagrego/liferay-portal/tree/LPS-146248">LPS-146248</a><br/>Branch GIT ID: <a href="https://github.com/joanagrego/liferay-portal/commit/9b9b7ecc76dff0ce660f74e27d971d3c2c3e6d10">9b9b7ecc76dff0ce660f74e27d971d3c2c3e6d10</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/1009/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1009/jenkins-report.html">here</a>.</h5></details></html>

2022-04-20 19:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-source-format/1009/">test-portal-source-format#1009</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1009/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1267">pt-liferay-solutions#1267</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1689618700">[master] ci:test:sf - joanagrego &gt; pt-liferay-solutions - PR#1267 - 2022-04-20[12:34:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/2677/">publish-testray-report#2677</a><br/></div></div>

2022-04-22 13:13 UTC, silasbsi requested changes
Looks good to me, but needs some adjustments.

2022-04-22 13:13 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife-ap/src/main/resources/site-initializer/fragments/src/agent-portal/fragments/applications-products/index.js
> +								return `<div class="d-flex applications-products-tooltip p-2"'><spam class="d-flex w-100 mr-2">${title}</spam> <spam>${percent}%</spam></div>`;
Please, remove it `'`.

```javascript
return `<div class="d-flex applications-products-tooltip p-2"><spam class="d-flex w-100 mr-2">${title}</spam> <spam>${percent}%</spam></div>`;
```

2022-04-22 13:23 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/src/main/resources/site-initializer/fragments/src/agent-portal/fragments/applications-products/index.css
> +.applications-products-tooltip {
Sure!

2022-04-22 13:24 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/src/main/resources/site-initializer/fragments/src/agent-portal/fragments/applications-products/index.js
> +				productQuotesResult?.value?.data?.items?.map((item, index) => {
Done!

2022-04-22 13:25 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/src/main/resources/site-initializer/fragments/src/agent-portal/fragments/applications-products/index.js
> +					let [productName] = Object.values(item.name);
You're right!

2022-04-22 13:25 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/src/main/resources/site-initializer/fragments/src/agent-portal/fragments/applications-products/index.js
> +
ok

2022-04-22 13:29 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/src/main/resources/site-initializer/fragments/src/agent-portal/fragments/applications-products/index.js
> +								return `<div class="d-flex applications-products-tooltip p-2"'><spam class="d-flex w-100 mr-2">${title}</spam> <spam>${percent}%</spam></div>`;
done

2022-04-22 13:38 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/src/main/resources/site-initializer/fragments/src/agent-portal/fragments/applications-products/index.css
> +	background-color: #fff;
Yeah! bg-neutral-0 on dialect. I'll change it.

2022-04-22 14:07 UTC, silasbsi commented
LGTM :fire:

2022-04-22 14:08 UTC, silasbsi approved these changes

2022-04-22 14:08 UTC, silasbsi commented
ci:test:sf

2022-04-22 14:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/662733049702144f8835991bf299ed7e4ea73e73">662733049702144f8835991bf299ed7e4ea73e73</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joanagrego/liferay-portal/tree/LPS-146248">LPS-146248</a><br/>Branch GIT ID: <a href="https://github.com/joanagrego/liferay-portal/commit/d5c520bf1df53b142c92c7e524203cc9f3fdc1fc">d5c520bf1df53b142c92c7e524203cc9f3fdc1fc</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/3666/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/3666/jenkins-report.html">here</a>.</h5></details></html>

2022-04-22 14:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/3666/">test-portal-source-format#3666</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/3666/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1267">pt-liferay-solutions#1267</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1694304471">[master] ci:test:sf - joanagrego &gt; pt-liferay-solutions - PR#1267 - 2022-04-22[07:09:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/2423/">publish-testray-report#2423</a><br/></div></div>

2022-04-22 14:42 UTC, silasbsi commented
ci:forward

2022-04-22 14:42 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-04-22 14:42 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:sf`

2022-04-22 14:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/3017/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3017/jenkins-report.html">here</a>.</b></p>

2022-04-22 16:30 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/3017//consoleFull)

2022-04-22 16:30 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/116463
[Console](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/3017//consoleFull)

2022-04-22 16:30 UTC, closed without merging

2022-04-22 16:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/3017/">test-portal-acceptance-pullrequest(master)#3017</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3017/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1267">pt-liferay-solutions#1267</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1694956874">[master] ci:test:relevant - joanagrego &gt; pt-liferay-solutions - PR#1267 - 2022-04-22[07:42:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/7986/">publish-testray-report#7986</a><br/></div></div>