[LPS 154920] Sales Page Low Code without the welcome banner
pt-liferay-solutions/liferay-portal pull request #1592
Opened 2022-07-05 19:51 UTC by ytuik

2022-07-06 12:34 UTC, jairmedeiros requested changes
Oi @ytuik @thaynam. 

- O padrão de nome de arquivos (imagens e afins) precisa ser "nome-da-imagem.png", ao invés de "Rabate-Sale-Icon.png".
- É interessante verificar se esses ícones também são utilizados por outras páginas como marketing, pq ai, poderíamos escolhar um nome de diretório melhor, como: "documents/group/quick-links-resources/".
- Notei que o caminho dos fragments está incorreto. Comparado com o [CP](https://github.com/pt-liferay-solutions/liferay-portal/tree/master/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/resources/site-initializer/fragments/group), é necessário adicionar a pasta da collection, que foi removida. Dessa forma, o correto é "fragments/group/partner-portal/algum-fragment". Sendo o partner-portal o collection.
- Foi adicionado nos fragments a pasta de sales-container. Essa não seria para gerar a página do sales? Se não será utilizado o fragment-composition, é preciso apagá-lo.

2022-07-06 12:34 UTC, jairmedeiros commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
Oi @ytuik, acredito que o source format acabou alterando um arquivo de fora do nosso projeto. Pode desfazer essa alteração?

2022-07-06 12:34 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/partner-portal/fragments/group/clay-icon-link/fragment.json
> +	"name": "ClayIcon",
O nome do fragment que está na pasta é "clay-icon-link" e o name está "ClayIcon". É importante que essas informações batam, então seria interessante ou alterar o nome da pasta para clay-icon e adicionar esse espaço no name, ou seja, "Clay Icon". Ou alterar o name para ficar "Clay Icon Link".

```suggestion
	"name": "Clay Icon Link",
```

2022-07-06 12:34 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/04_sales/page-definition.json
> +																	"classPK": "[$DOCUMENT_FILE_ENTRY_ID:/site-initializer/documents/group/resources-pdf/Liferay Service Partner - Referral Program Guide 2022.pdf$]"
Esse PDF referenciado não está nesta PR. É importante adicioná-lo.

2022-07-06 12:34 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/04_sales/page-definition.json
> +																	"classPK": "[$DOCUMENT_FILE_ENTRY_ID:/site-initializer/documents/group/resources-pdf/Liferay Service Partner - Reseller Program Guide 2022.pdf$]"
Esse PDF referenciado não está nesta PR. É importante adicioná-lo.

2022-07-06 12:34 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/04_sales/page-definition.json
> +																	"classPK": "[$DOCUMENT_FILE_ENTRY_ID:/site-initializer/documents/group/resources-pdf/Liferay Service Partner Program Rules of Engagement.pdf$]"
Esse PDF referenciado não está nesta PR. É importante adicioná-lo.

2022-07-06 12:34 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/04_sales/page-definition.json
> +																							"fieldValue": "PRM-1"
Este fieldValue está referenciando o nome do site, como esse é um valor dinâmico, precisamos ter um replace pelo site-initializer, assim como temos para os documents

2022-07-06 12:34 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/04_sales/page-definition.json
> +																							"fieldValue": "PRM-1"
Este fieldValue está referenciando o nome do site, como esse é um valor dinâmico, precisamos ter um replace pelo site-initializer, assim como temos para os documents

2022-07-06 12:34 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/04_sales/page-definition.json
> +																							"fieldValue": "PRM-1"
Este fieldValue está referenciando o nome do site, como esse é um valor dinâmico, precisamos ter um replace pelo site-initializer, assim como temos para os documents

2022-07-06 12:34 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/04_sales/page-definition.json
> +																							"fieldValue": "PRM-1"
Este fieldValue está referenciando o nome do site, como esse é um valor dinâmico, precisamos ter um replace pelo site-initializer, assim como temos para os documents

2022-07-06 12:34 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/04_sales/page-definition.json
> +																				"iconLink": "/home",
Ao invés do link "/home", não seria melhor o mapping para a página de fato, assim como foi feito para os outros casos?

2022-07-06 12:34 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/04_sales/page-definition.json
> +																							"fieldValue": "PRM-1"
Este fieldValue está referenciando o nome do site, como esse é um valor dinâmico, precisamos ter um replace pelo site-initializer, assim como temos para os documents

2022-07-06 12:34 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/04_sales/page-definition.json
> +																							"fieldValue": "PRM-1"
Este fieldValue está referenciando o nome do site, como esse é um valor dinâmico, precisamos ter um replace pelo site-initializer, assim como temos para os documents

2022-07-06 12:34 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/04_sales/page-definition.json
> +																							"fieldValue": "PRM-1"
Este fieldValue está referenciando o nome do site, como esse é um valor dinâmico, precisamos ter um replace pelo site-initializer, assim como temos para os documents

2022-07-06 12:34 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/04_sales/page-definition.json
> +																							"fieldValue": "PRM-1"
Este fieldValue está referenciando o nome do site, como esse é um valor dinâmico, precisamos ter um replace pelo site-initializer, assim como temos para os documents

2022-07-06 23:29 UTC, ytuik commented
Hi All, I made the requested changes and the master of this Repo is not updated, so there's more commits than expected on this PR,as i don't have the necessaries permissions i'll wait to the Repo be updated so i can fix it

2022-07-07 11:36 UTC, jairmedeiros commented
> Hi All, I made the requested changes and the master of this Repo is not updated, so there's more commits than expected on this PR,as i don't have the necessaries permissions i'll wait to the Repo be updated so i can fix it

Oi @ytuik. Atualizei a master, mas ainda é necessário que vc tente dar o fetch/rebase novamente. Caso a PR ainda fique com commits de outras pessoas, vai ser necessário fechar e abrir uma nova PR da mesma branch.

Além disso, é importante que os commits sigam o padrão de "LPS-12345 Descrição da PR".

2022-07-07 19:59 UTC, jairmedeiros requested changes
Oi @ytuik @thaynam.

- Vi o nome dos arquivos de PDF e estão fora do padrão.
> O padrão de nome de arquivos (imagens e afins) precisa ser "nome-da-imagem.png", ao invés de "Rabate-Sale-Icon.png".

- O arquivo collection.json precisa está na pasta do collection (partner-portal).
- O [page-definition](modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/02_marketing/page-definition.json) do marketing foi apagado, é isso msm?
- Não vi nenhuma referencia ao fragment Clay Icon Link da página, é isso mesmo?

2022-07-08 13:55 UTC, ytuik commented
Corrigido a questão da referência do Clay Icon e os nomes do arquivos PDF, sobre a questão da pagina de Marketing não faz diferença ela ser apagada no meu pois o commit dessa pagina ainda será enviada por outra pessoa, mas ainda assim eu coloquei a versão padrão dela de novo

2022-07-08 14:38 UTC, jairmedeiros approved these changes

2022-07-08 14:38 UTC, jairmedeiros commented
ci:forward

2022-07-08 14:38 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-07-08 14:42 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5b3978bb2cb86fb721630f39256982fc0bacc4ed">5b3978bb2cb86fb721630f39256982fc0bacc4ed</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ytuik/liferay-portal/tree/LPS-154920">LPS-154920</a><br/>Branch GIT ID: <a href="https://github.com/ytuik/liferay-portal/commit/5bec6df7a142c34edc2bd43582165c2e35c755da">5bec6df7a142c34edc2bd43582165c2e35c755da</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/2785/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2785/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/partner-portal/fragments/clay-icon-link/configuration.json expected:&lt;...
     [java]       "fields": [
     [java]         [\{
     [java]           "dataType": "string",
     [java]           "defaultValue": "check-circle",
     [java]           "label": "icon-name",
     [java]           "name": "iconName",
     [java]           "type": "text"
     [java]         \},
     [java]         \{
     [java]           "dataType": "string",
     [java]           "defaultValue": "",
     [java]           "label": "icon-link",
     [java]           "name": "iconLink",
     [java]           "type": "text"
     [java]         \}
     [java]       ]]
     [java]     \}
     [java]   ]
     [java] \}&gt; but was:&lt;...
     [java]       "fields": [
     [java]         [
     [java]         \{
     [java]           "dataType": "string",
     [java]           "defaultValue": "check-circle",
     [java]           "label": "icon-name",
     [java]           "name": "iconName",
     [java]           "type": "text"
     [java]         \},
     [java]                 \{
     [java]           "dataType": "string",
     [java]           "defaultValue": "",
     [java]           "label": "icon-link",
     [java]           "name": "iconLink",
     [java]           "type": "text"
     [java]         \}
     [java]       ]    ]
     [java]     \}
     [java]   ]
     [java] \}&gt;
     [java] 2: Truncated message :
     [java] ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/04_sales/page-definition.json expected:&lt;...ller Program Guide"
     [java] [                                      \}
     [java]                                     \}
     [java]                                   \}
     [java]                                 \}
     [java]                               ],
     [java]                               "fragmentStyle": \{
     [java]                                 "fontWeight": "fontWeightBold",
     [java]                                 "textColor": "linkColor"
     [java]                               \},
     [java]                               "indexed": true
     [java]                             \},
     [java]                             "type": "Fragment"
     [java]                           \}
     [java]                         ],
     [java]                         "type": "Section"
     [java]                       \}
     [java]                     ],
     [java]                     "type": "Column"
     [java]                   \},
     [java]                   \{
     [java]                     "definition": \{
     [java]                       "columnViewports": [
     [java]                         \{
     [java]                           "columnViewportDefinition": \{</pre></details></html>

2022-07-08 14:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/2785/">test-portal-source-format#2785</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2785/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1592">pt-liferay-solutions#1592</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1900576711">[master] ci:test:sf - ytuik &gt; pt-liferay-solutions - PR#1592 - 2022-07-08[07:39:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/10294/">publish-testray-report#10294</a><br/></div></div>

2022-07-08 15:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3576/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3576/jenkins-report.html">here</a>.</b></p>

2022-07-08 17:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3576/">test-portal-acceptance-pullrequest(master)#3576</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3576/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1592">pt-liferay-solutions#1592</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1900774360">[master] ci:test:relevant - ytuik &gt; pt-liferay-solutions - PR#1592 - 2022-07-08[08:32:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9331/">publish-testray-report#9331</a><br/></div></div>

2022-07-08 17:45 UTC, jairmedeiros commented
ci:forward

2022-07-08 17:45 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-07-08 17:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/2083/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2083/jenkins-report.html">here</a>.</b></p>

2022-07-08 17:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3300/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3300/jenkins-report.html">here</a>.</b></p>

2022-07-08 17:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/03ececc28b5d2e6597bda4bf139bb6f67a8a5bef">03ececc28b5d2e6597bda4bf139bb6f67a8a5bef</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ytuik/liferay-portal/tree/LPS-154920">LPS-154920</a><br/>Branch GIT ID: <a href="https://github.com/ytuik/liferay-portal/commit/e725b18952ae194a3afb2aa595830c3b7bc0bb8b">e725b18952ae194a3afb2aa595830c3b7bc0bb8b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/2083/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2083/jenkins-report.html">here</a>.</h5></details></html>

2022-07-08 17:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/2083/">test-portal-source-format#2083</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2083/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1592">pt-liferay-solutions#1592</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1900785738">[master] ci:test:sf - ytuik &gt; pt-liferay-solutions - PR#1592 - 2022-07-08[10:46:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/7898/">publish-testray-report#7898</a><br/></div></div>

2022-07-08 19:38 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 25 out of 26 jobs passed</h3><h3>:x: ci:test:relevant - 43 out of 46 jobs passed in 1 hour 49 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3523">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1377401_3300</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/03ececc28b5d2e6597bda4bf139bb6f67a8a5bef">03ececc28b5d2e6597bda4bf139bb6f67a8a5bef</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/992c32b7a49d3ab42fdbef48cf73cc3ce23703b1">992c32b7a49d3ab42fdbef48cf73cc3ce23703b1</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3521">Acceptance Upstream DXP (master) #3521</a></p><details><summary><strong>ci:test:stable - 25 out of 26 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41809/"><strike>functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</strike></a></li></ul></li></ul></div><details><summary><strong>25 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/46484/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/102408/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/43357/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/91608/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/44125/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93446/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41807/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41808/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/35562/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/39473/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/87922/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41415/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/39666/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93451/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/49149/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/111183/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/77730/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/111196/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/57633/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/111187/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/39671/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/107830/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/42661/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/44128/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/107832/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 43 out of 46 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3300/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/102897/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41809/"><strike>functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</strike></a></li></ul></li></ul></div><details><summary><strong>43 Successful Jobs:</strong></summary><ul><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/102388/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/46004/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/107823/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/46484/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/111181/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/37140/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullreque [...]

2022-07-08 19:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3300/">test-portal-acceptance-pullrequest(master)#3300</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3300/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1592">pt-liferay-solutions#1592</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1900869303">[master] ci:test:relevant - ytuik &gt; pt-liferay-solutions - PR#1592 - 2022-07-08[10:48:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/7903/">publish-testray-report#7903</a><br/></div></div>

2022-07-08 20:57 UTC, jairmedeiros commented
ci:forward

2022-07-08 20:57 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-07-08 20:57 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:sf`

2022-07-08 22:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/3613/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3613/jenkins-report.html">here</a>.</b></p>

2022-07-09 02:24 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 26 out of 26 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 45 out of 46 jobs passed in 3 hours 34 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f14dbf37b961ca055706e944c98f1979c7ac8984">f14dbf37b961ca055706e944c98f1979c7ac8984</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6ffdc2b666457c2641fe5741239344d62589bb32">6ffdc2b666457c2641fe5741239344d62589bb32</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3524">Acceptance Upstream DXP (master) #3524</a></p><details><summary><strong>ci:test:stable - 26 out of 26 jobs PASSED</strong></summary><details><summary><strong>26 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/108726/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/44947/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/46998/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41842/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/112192/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/44936/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/108742/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/46741/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/88736/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/44944/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/44521/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/46662/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/92990/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/103294/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/44940/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/92983/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/105702/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/108832/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106551/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/103316/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/49627/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41850/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/112177/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/49626/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/100045/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/94258/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 44 out of 46 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/3613/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/43799/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li></ul></div><details><summary><strong>44 Successful Jobs:</strong></summary><ul><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/44510/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/39388/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/46455/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/108726/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/37491/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/47263/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/108731/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/43565/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/39843/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/44947/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/46998/">functional-upgrade-tomcat90-mysql57-jdk8 [...]

2022-07-09 02:25 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/3613//consoleFull)

2022-07-09 02:25 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/120139
[Console](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/3613//consoleFull)

2022-07-09 02:25 UTC, closed without merging

2022-07-09 02:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/3613/">test-portal-acceptance-pullrequest(master)#3613</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3613/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1592">pt-liferay-solutions#1592</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1901411067">[master] ci:test:relevant - ytuik &gt; pt-liferay-solutions - PR#1592 - 2022-07-08[15:50:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/9716/">publish-testray-report#9716</a><br/></div></div>