LPS-137740 Get Application ID by cookie or session storage
pt-liferay-solutions/liferay-portal pull request #161
Opened 2021-08-20 17:40 UTC by RodrigoCavalcantii

2021-08-20 18:16 UTC, kevenleone requested changes
About the implementation, this action to get a cookie even being very particular, and used one single time, but could be used a function for it.

Something like:

`getCookie(name) {}`

2021-08-20 18:17 UTC, kevenleone commented
Hey @RodrigoCavalcantii , I found some implementation that could help us with that:

<img width="768" alt="image" src="https://user-images.githubusercontent.com/22279592/130276668-c4b913af-36dc-46aa-93a8-a6f59f1c9392.png">

From: https://daily-dev-tips.com/posts/vanilla-javascript-cookies-%F0%9F%8D%AA/

2021-08-20 18:19 UTC, kevenleone commented
And this other one:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/22279592/130276766-a342fce7-b72f-4c2d-b3fa-21287278e98b.png">

It's looks like better

From: https://gomakethings.com/how-to-set-and-get-cookies-with-vanilla-js/

2021-08-20 18:21 UTC, kevenleone commented
@RodrigoCavalcantii , you did a good job on that, this is just a suggestion for improvement.
Because is simpler to understand the code scoped in a function

2021-08-20 19:29 UTC, RodrigoCavalcantii commented
> @RodrigoCavalcantii , you did a good job on that, this is just a suggestion for improvement.
> Because is simpler to understand the code scoped in a function

Yes sure, I agree. I’m gonna do it now !

2021-08-23 11:30 UTC, kevenleone commented
Just starting reviewing :)

2021-08-23 11:37 UTC, kevenleone requested changes
Hey @RodrigoCavalcantii , I did some observations to the code, it's good, just some improvements to do

2021-08-23 11:37 UTC, kevenleone commented on modules/apps/site/site-insurance-site-initializer/src/main/zippableResources/fragments/raylife/fragments/get-in-touch/index.js
> +		return cookie.substring(name.length, cookie.length);
Wrong spacing, tab is missing here

2021-08-23 11:37 UTC, kevenleone commented on modules/apps/site/site-insurance-site-initializer/src/main/zippableResources/fragments/raylife/fragments/get-in-touch/index.js
> +if(getCookie(nameCookie) != undefined && getCookie(nameCookie) != "" )
this line could be replaced just for `if (getCookie(nameCookie)) {}`

Any string inside this variable or function return, is already true

2021-08-23 11:37 UTC, kevenleone commented on modules/apps/site/site-insurance-site-initializer/src/main/zippableResources/fragments/raylife/fragments/get-in-touch/index.js
> +if(getCookie(nameCookie) != undefined && getCookie(nameCookie) != "" )
Also, you are using `getCookie` 3 times, you could assign to one variable, and use it

2021-08-23 11:46 UTC, kevenleone commented
Resent: #167

2021-08-23 11:46 UTC, closed without merging