LPS-157848
pt-liferay-solutions/liferay-portal pull request #1618
Opened 2022-07-08 17:31 UTC by eliasantosf

2022-07-08 17:31 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-07-08 17:33 UTC, eliasantosf commented
ci:test:sf

2022-07-08 17:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/876/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/876/jenkins-report.html">here</a>.</b></p>

2022-07-08 17:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/03ececc28b5d2e6597bda4bf139bb6f67a8a5bef">03ececc28b5d2e6597bda4bf139bb6f67a8a5bef</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eliasantosf/liferay-portal/tree/LPS-157848">LPS-157848</a><br/>Branch GIT ID: <a href="https://github.com/eliasantosf/liferay-portal/commit/a3e656c42903e07b0d955fbc802f4280a7c3cf43">a3e656c42903e07b0d955fbc802f4280a7c3cf43</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/876/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/876/jenkins-report.html">here</a>.</h5></details></html>

2022-07-08 17:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/876/">test-portal-source-format#876</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/876/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1618">pt-liferay-solutions#1618</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1900774463">[master] ci:test:sf - eliasantosf &gt; pt-liferay-solutions - PR#1618 - 2022-07-08[10:33:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/3557/">publish-testray-report#3557</a><br/></div></div>

2022-07-11 11:47 UTC, silasbsi requested changes
LGTM :fire: But needs some adjustments.

2022-07-11 11:47 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/routes/applications/forms/steps/DriverInfo.tsx
> +							{relationToContactOptions.map((item) => (
Please, change all .map parameter names.

```suggestion
							{relationToContactOptions.map((relationToContactOption) => (
```

2022-07-11 13:46 UTC, eliasantosf commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/routes/applications/forms/steps/DriverInfo.tsx
> +							{relationToContactOptions.map((item) => (
Done!

2022-07-11 13:46 UTC, eliasantosf commented
ci:test:sf

2022-07-11 13:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2572/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2572/jenkins-report.html">here</a>.</b></p>

2022-07-11 13:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/64e30a3d6793ecde6b0c64840870872978fbd877">64e30a3d6793ecde6b0c64840870872978fbd877</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eliasantosf/liferay-portal/tree/LPS-157848">LPS-157848</a><br/>Branch GIT ID: <a href="https://github.com/eliasantosf/liferay-portal/commit/5efe4dc204328f3675f74d56a0e20cf0b1580fb8">5efe4dc204328f3675f74d56a0e20cf0b1580fb8</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2572/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2572/jenkins-report.html">here</a>.</h5></details></html>

2022-07-11 13:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2572/">test-portal-source-format#2572</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2572/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1618">pt-liferay-solutions#1618</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1902840611">[master] ci:test:sf - eliasantosf &gt; pt-liferay-solutions - PR#1618 - 2022-07-11[06:46:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9391/">publish-testray-report#9391</a><br/></div></div>

2022-07-11 13:57 UTC, eliasantosf commented
ci:test:sf

2022-07-11 13:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/882/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/882/jenkins-report.html">here</a>.</b></p>

2022-07-11 14:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/64e30a3d6793ecde6b0c64840870872978fbd877">64e30a3d6793ecde6b0c64840870872978fbd877</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eliasantosf/liferay-portal/tree/LPS-157848">LPS-157848</a><br/>Branch GIT ID: <a href="https://github.com/eliasantosf/liferay-portal/commit/e442df75a9cafd694951e0d77a5c3a116df6d496">e442df75a9cafd694951e0d77a5c3a116df6d496</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/882/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/882/jenkins-report.html">here</a>.</h5></details></html>

2022-07-12 22:30 UTC, eliasantosf commented
ci:test:sf

2022-07-12 22:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/1641/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1641/jenkins-report.html">here</a>.</b></p>

2022-07-12 22:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ed0f57bfa307ed2781fdd54c5b638882fa731e38">ed0f57bfa307ed2781fdd54c5b638882fa731e38</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eliasantosf/liferay-portal/tree/LPS-157848">LPS-157848</a><br/>Branch GIT ID: <a href="https://github.com/eliasantosf/liferay-portal/commit/32086b7265f113b6e15218c17d4379d76f52f9d1">32086b7265f113b6e15218c17d4379d76f52f9d1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1641/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1641/jenkins-report.html">here</a>.</h5></details></html>

2022-07-12 22:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1641/">test-portal-source-format#1641</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1641/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1618">pt-liferay-solutions#1618</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1904529844">[master] ci:test:sf - eliasantosf &gt; pt-liferay-solutions - PR#1618 - 2022-07-12[15:30:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/5213/">publish-testray-report#5213</a><br/></div></div>

2022-07-25 19:19 UTC, closed without merging