LPS-158682 Migrate Runs Table from GraphQL to Rest
pt-liferay-solutions/liferay-portal pull request #1679
Opened 2022-07-20 20:16 UTC by rafaelfs98

2022-07-21 18:59 UTC, silasbsi requested changes
LGTM :+1: But needs some adjustments.

2022-07-21 18:59 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-testray/extra/remote-app/src/pages/Project/Routines/Builds/Inner/Run.tsx
> +				transformData = {getRunTransformData}
Please, remove these spaces.
```suggestion
				transformData={getRunTransformData}
```

2022-07-21 18:59 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-testray/extra/remote-app/src/services/rest/TestrayRun.ts
> +const runsResource = '/runs';
Please, remove this line and put this value in this file [/Run.tsx](https://github.com/pt-liferay-solutions/liferay-portal/pull/1679/files#diff-3da1171b0efc0d6fd85e267123946f392a9b28171f571cb3623a47a2a2fd2f21) resource property directly.

2022-07-22 13:41 UTC, welitonpe approved these changes
LGTM

2022-07-22 13:52 UTC, welitonpe commented
Just starting reviewing :)

2022-07-22 14:30 UTC, silasbsi approved these changes

2022-07-22 14:31 UTC, silasbsi commented
LGTM :1st_place_medal:  Thanks :smile:

2022-07-29 20:19 UTC, kevenleone commented
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/1755

2022-07-29 20:19 UTC, closed without merging