LPS-158755
pt-liferay-solutions/liferay-portal pull request #1733
Opened 2022-07-26 17:56 UTC by edbbarros

2022-07-26 18:19 UTC, edbbarros commented
Sub-task: [LPS-158755](https://issues.liferay.com/browse/LPS-158755)

2022-07-26 18:21 UTC, edbbarros commented
ci:test:sf

2022-07-26 18:42 UTC, eliasantosf commented
ci:test:sf

2022-07-26 18:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/2795/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/2795/jenkins-report.html">here</a>.</b></p>

2022-07-26 18:45 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e9a5492319dcfab370b8c5ae5cf26b79237f8531">e9a5492319dcfab370b8c5ae5cf26b79237f8531</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/edbbarros/liferay-portal/tree/LPS-158755">LPS-158755</a><br/>Branch GIT ID: <a href="https://github.com/edbbarros/liferay-portal/commit/8e149429099af75deead3c2657bbd98b5d968cc8">8e149429099af75deead3c2657bbd98b5d968cc8</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/2795/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/2795/jenkins-report.html">here</a>.</h5><pre>     [exec] yarn install v1.13.0
     [exec] [1/4] Resolving packages...
     [exec] warning Resolution field "@types/html-minifier-terser@5.1.0" is incompatible with requested version "@types/html-minifier-terser@^6.0.0"
     [exec] success Already up-to-date.
     [exec] Done in 1.10s.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ liferay-npm-scripts check
     [exec] apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/routes/applications/forms/steps/Coverage/CoverageInfoForm.tsx: BAD
     [exec] apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/routes/applications/pages/NewApplication/NewApplicationAuto/index.tsx: BAD
     [exec] Prettier checked 3 files, 2 files have problems
     [exec] 
     [exec] 1 of 3 jobs failed
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2022-07-26 18:45:03.500.
     [exec] 3 actionable tasks: 2 executed, 1 up-to-date
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2022-07-26-11-44-52.html
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:208)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:263)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:206)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)</pre></details></html>

2022-07-26 18:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/2795/">test-portal-source-format#2795</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/2795/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1733">pt-liferay-solutions#1733</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1917769730">[master] ci:test:sf - edbbarros &gt; pt-liferay-solutions - PR#1733 - 2022-07-26[11:42:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/10136/">publish-testray-report#10136</a><br/></div></div>

2022-07-26 19:17 UTC, edbbarros commented
ci:test:sf

2022-07-26 19:18 UTC, eliasantosf commented
ci:test:sf

2022-07-26 19:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/5736/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/5736/jenkins-report.html">here</a>.</b></p>

2022-07-26 19:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e9a5492319dcfab370b8c5ae5cf26b79237f8531">e9a5492319dcfab370b8c5ae5cf26b79237f8531</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/edbbarros/liferay-portal/tree/LPS-158755">LPS-158755</a><br/>Branch GIT ID: <a href="https://github.com/edbbarros/liferay-portal/commit/89ee15b5c42e193a8a6bde6873d5d6c1267bd8d5">89ee15b5c42e193a8a6bde6873d5d6c1267bd8d5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/5736/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/5736/jenkins-report.html">here</a>.</h5></details></html>

2022-07-26 19:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-source-format/5736/">test-portal-source-format#5736</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/5736/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1733">pt-liferay-solutions#1733</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1917800496">[master] ci:test:sf - edbbarros &gt; pt-liferay-solutions - PR#1733 - 2022-07-26[12:18:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/2582/">publish-testray-report#2582</a><br/></div></div>

2022-07-27 12:57 UTC, silasbsi commented
Just starting reviewing :)

2022-07-27 21:04 UTC, joanagrego requested changes
Nice job! I added some suggestions. Please, change the commit name for the pattern we use.

2022-07-28 11:23 UTC, edbbarros commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/routes/applications/forms/steps/Coverage/CoverageInfoForm.tsx
> +				CHOOSE YOUR COVERAGES
Done!

2022-07-28 13:12 UTC, eliasantosf approved these changes
LGTM :fire: Thanks @edbbarros

2022-07-28 13:16 UTC, edbbarros commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/routes/applications/forms/steps/Coverage/CoverageInfoForm.tsx
> +	}, [form]);
it is needed to call the function "handleSaveChanges" with the parameter (form).

2022-07-28 13:56 UTC, joanagrego approved these changes

2022-07-28 13:56 UTC, joanagrego commented
ci:test:sf

2022-07-28 14:00 UTC, joanagrego commented
ci:test:sf

2022-07-28 14:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/1350/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/1350/jenkins-report.html">here</a>.</b></p>

2022-07-28 14:02 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d8db1236a59f326ae49b0186205b7a3d5f9cc693">d8db1236a59f326ae49b0186205b7a3d5f9cc693</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/edbbarros/liferay-portal/tree/LPS-158755">LPS-158755</a><br/>Branch GIT ID: <a href="https://github.com/edbbarros/liferay-portal/commit/a48b8922d75bd39b9cb30297495a70459b521187">a48b8922d75bd39b9cb30297495a70459b521187</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/1350/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/1350/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-raylife-ap/src/main/resources/site-initializer/layouts/6_app-edit/page-definition.json expected:&lt;...  "fragmentFields": [[
     [java]               ],
     [java]               "indexed": true
     [java]             \},
     [java]             "pageElements": [
     [java]               \{
     [java]                 "pageElements": [
     [java]                   \{
     [java]                     "definition": \{
     [java]                       "fragment": \{
     [java]                         "key": "BASIC_COMPONENT-heading"
     [java]                       \},
     [java]                       "fragmentConfig": \{
     [java]                         "headingLevel": "h3"
     [java]                       \},
     [java]                       "fragmentFields": [
     [java]                         \{
     [java]                           "id": "element-text",
     [java]                           "value": \{
     [java]                             "fragmentLink": \{
     [java]                             ]\},
     [java]                             "te...&gt; but was:&lt;...  "fragmentFields": [[],
     [java]               "indexed": true
     [java]             \},
     [java]             "pageElements": [
     [java]               \{
     [java]                 "pageElements": [
     [java]                   \{
     [java]                     "definition": \{
     [java]                       "fragment": \{
     [java]                         "key": "BASIC_COMPONENT-heading"
     [java]                       \},
     [java]                       "fragmentConfig": \{
     [java]                         "headingLevel": "h3"
     [java]                       \},
     [java]                       "fragmentFields": [
     [java]                         \{
     [java]                           "id": "element-text",
     [java]                           "value": \{
     [java]                             "fragmentLink": \{]\},
     [java]                             "te...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:442)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:284)
[stopwatch] [run.batch.test.action: 1:20.710 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:450: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:593: Java returned: 1
      [get] Getting: http://test-1-33/job/test-portal-source-format/1350//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20220728070231162.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20220728070231162.txt</pre></details></html>

2022-07-28 14:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/1868/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1868/jenkins-report.html">here</a>.</b></p>

2022-07-28 14:04 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d8db1236a59f326ae49b0186205b7a3d5f9cc693">d8db1236a59f326ae49b0186205b7a3d5f9cc693</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/edbbarros/liferay-portal/tree/LPS-158755">LPS-158755</a><br/>Branch GIT ID: <a href="https://github.com/edbbarros/liferay-portal/commit/a48b8922d75bd39b9cb30297495a70459b521187">a48b8922d75bd39b9cb30297495a70459b521187</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1868/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1868/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-raylife-ap/src/main/resources/site-initializer/layouts/6_app-edit/page-definition.json expected:&lt;...  "fragmentFields": [[
     [java]               ],
     [java]               "indexed": true
     [java]             \},
     [java]             "pageElements": [
     [java]               \{
     [java]                 "pageElements": [
     [java]                   \{
     [java]                     "definition": \{
     [java]                       "fragment": \{
     [java]                         "key": "BASIC_COMPONENT-heading"
     [java]                       \},
     [java]                       "fragmentConfig": \{
     [java]                         "headingLevel": "h3"
     [java]                       \},
     [java]                       "fragmentFields": [
     [java]                         \{
     [java]                           "id": "element-text",
     [java]                           "value": \{
     [java]                             "fragmentLink": \{
     [java]                             ]\},
     [java]                             "te...&gt; but was:&lt;...  "fragmentFields": [[],
     [java]               "indexed": true
     [java]             \},
     [java]             "pageElements": [
     [java]               \{
     [java]                 "pageElements": [
     [java]                   \{
     [java]                     "definition": \{
     [java]                       "fragment": \{
     [java]                         "key": "BASIC_COMPONENT-heading"
     [java]                       \},
     [java]                       "fragmentConfig": \{
     [java]                         "headingLevel": "h3"
     [java]                       \},
     [java]                       "fragmentFields": [
     [java]                         \{
     [java]                           "id": "element-text",
     [java]                           "value": \{
     [java]                             "fragmentLink": \{]\},
     [java]                             "te...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:442)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:284)
[stopwatch] [run.batch.test.action: 55.141 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:450: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:593: Java returned: 1
      [get] Getting: http://test-1-38/job/test-portal-source-format/1868//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20220728070404924.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20220728070404924.txt</pre></details></html>

2022-07-28 14:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/1350/">test-portal-source-format#1350</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/1350/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1733">pt-liferay-solutions#1733</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1926487565">[master] ci:test:sf - edbbarros &gt; pt-liferay-solutions - PR#1733 - 2022-07-28[06:57:22]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/5165/">publish-testray-report#5165</a><br/></div></div>

2022-07-28 14:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1868/">test-portal-source-format#1868</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1868/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1733">pt-liferay-solutions#1733</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1926487948">[master] ci:test:sf - edbbarros &gt; pt-liferay-solutions - PR#1733 - 2022-07-28[07:00:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/6017/">publish-testray-report#6017</a><br/></div></div>

2022-07-28 16:44 UTC, edbbarros commented
ci:test:sf

2022-07-28 16:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/2909/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/2909/jenkins-report.html">here</a>.</b></p>

2022-07-28 16:47 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e99998bd2f03915320f020742555ccd15b5733fa">e99998bd2f03915320f020742555ccd15b5733fa</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/edbbarros/liferay-portal/tree/LPS-158755">LPS-158755</a><br/>Branch GIT ID: <a href="https://github.com/edbbarros/liferay-portal/commit/3ecb06dd006a2cf08bd5adcdc11fc19e64554065">3ecb06dd006a2cf08bd5adcdc11fc19e64554065</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/2909/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/2909/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-raylife-ap/src/main/resources/site-initializer/layouts/6_app-edit/page-definition.json expected:&lt;...  "fragmentFields": [[
     [java]               ],
     [java]               "indexed": true
     [java]             \},
     [java]             "pageElements": [
     [java]               \{
     [java]                 "pageElements": [
     [java]                   \{
     [java]                     "definition": \{
     [java]                       "fragment": \{
     [java]                         "key": "BASIC_COMPONENT-heading"
     [java]                       \},
     [java]                       "fragmentConfig": \{
     [java]                         "headingLevel": "h3"
     [java]                       \},
     [java]                       "fragmentFields": [
     [java]                         \{
     [java]                           "id": "element-text",
     [java]                           "value": \{
     [java]                             "fragmentLink": \{
     [java]                             ]\},
     [java]                             "te...&gt; but was:&lt;...  "fragmentFields": [[],
     [java]               "indexed": true
     [java]             \},
     [java]             "pageElements": [
     [java]               \{
     [java]                 "pageElements": [
     [java]                   \{
     [java]                     "definition": \{
     [java]                       "fragment": \{
     [java]                         "key": "BASIC_COMPONENT-heading"
     [java]                       \},
     [java]                       "fragmentConfig": \{
     [java]                         "headingLevel": "h3"
     [java]                       \},
     [java]                       "fragmentFields": [
     [java]                         \{
     [java]                           "id": "element-text",
     [java]                           "value": \{
     [java]                             "fragmentLink": \{]\},
     [java]                             "te...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:442)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:284)
[stopwatch] [run.batch.test.action: 1:00.202 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:450: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:593: Java returned: 1
      [get] Getting: http://test-1-27/job/test-portal-source-format/2909//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20220728094730279.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20220728094730279.txt</pre></details></html>

2022-07-28 16:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/2909/">test-portal-source-format#2909</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/2909/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1733">pt-liferay-solutions#1733</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1927618619">[master] ci:test:sf - edbbarros &gt; pt-liferay-solutions - PR#1733 - 2022-07-28[09:44:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/10652/">publish-testray-report#10652</a><br/></div></div>

2022-07-28 16:52 UTC, edbbarros commented
ci:test:sf

2022-07-28 16:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/2825/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/2825/jenkins-report.html">here</a>.</b></p>

2022-07-28 16:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e99998bd2f03915320f020742555ccd15b5733fa">e99998bd2f03915320f020742555ccd15b5733fa</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/edbbarros/liferay-portal/tree/LPS-158755">LPS-158755</a><br/>Branch GIT ID: <a href="https://github.com/edbbarros/liferay-portal/commit/ec749634bcceed01e3601ddfb4c6e5517fadffa7">ec749634bcceed01e3601ddfb4c6e5517fadffa7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/2825/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/2825/jenkins-report.html">here</a>.</h5></details></html>

2022-07-28 17:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/2825/">test-portal-source-format#2825</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/2825/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1733">pt-liferay-solutions#1733</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1927708049">[master] ci:test:sf - edbbarros &gt; pt-liferay-solutions - PR#1733 - 2022-07-28[09:52:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/10213/">publish-testray-report#10213</a><br/></div></div>

2022-07-28 22:51 UTC, silasbsi approved these changes
LGTM :1st_place_medal: Thanks @edbbarros

2022-07-28 22:52 UTC, silasbsi commented
ci:forward

2022-07-28 22:52 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-07-28 22:52 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:sf`

2022-07-29 00:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/2418/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2418/jenkins-report.html">here</a>.</b></p>

2022-07-29 04:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 26 out of 26 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 47 out of 49 jobs passed in 4 hours 14 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5bd6c053d131da3f345d3c4343860f6ac18bf9c2">5bd6c053d131da3f345d3c4343860f6ac18bf9c2</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/46e17c1d34e3a5a75bb6e251317b74a224d5252b">46e17c1d34e3a5a75bb6e251317b74a224d5252b</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1929621882">EE Development Acceptance (master) - 3609 - 2022-07-28[12:39:25]</a></p><details><summary><strong>ci:test:stable - 26 out of 26 jobs PASSED</strong></summary><details><summary><strong>26 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/141697/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126441/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/147830/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/55184/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/154226/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/58129/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/59377/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/154229/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/105852/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/145953/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/63761/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/65216/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121787/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/65045/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/141707/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/54390/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121782/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/141709/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137277/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/141710/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/129112/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/145498/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/145486/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/145951/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/54391/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/147816/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 46 out of 49 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/2418/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/147829/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/145957/"><strike>modules-integration-mysql57-jdk8/0/2</strike></a></li></ul></li></ul></div><details><summary><strong>46 Successful Jobs:</strong></summary><ul><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/59375/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/63762/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/63515/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/141697/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/64220/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/129108/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/59842/">functional-tomcat90-mysql57-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/145945/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/57713/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https:// [...]

2022-07-29 04:29 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/2418//consoleFull)

2022-07-29 04:29 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/121010
[Console](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/2418//consoleFull)

2022-07-29 04:29 UTC, closed without merging

2022-07-29 04:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/2418/">test-portal-acceptance-pullrequest(master)#2418</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2418/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/1733">pt-liferay-solutions#1733</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1929934803">[master] ci:test:relevant - edbbarros &gt; pt-liferay-solutions - PR#1733 - 2022-07-28[17:15:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/6263/">publish-testray-report#6263</a><br/></div></div>