LPS-159021 [PRM] Components Date Picker
pt-liferay-solutions/liferay-portal pull request #1734
Opened 2022-07-26 20:15 UTC by joaosvassis

2022-07-26 20:15 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-07-27 16:44 UTC, jairmedeiros requested changes
@joaosvassis. Parabéns pelo commit.

É importante seguir o padrão de estrutura de pastas, como exemplo [aqui](https://github.com/pt-liferay-solutions/liferay-portal/tree/master/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/home/components/ProjectsList), do Customer Portal.

2022-07-27 16:44 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/package.json
> +		"formik": "^2.2.9",
Oi @joaosvassis. Pq foi adicionado o formik?

2022-07-27 16:44 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/components/DatePicker/index.tsx
> +	return <ClayDatePicker spritemap={getIconSpriteMap()} {...props} />;
Esse componente funciona pelo Provider? É interessante evitarmos usar o spritemap.

2022-07-27 16:44 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/utils/getIconSpriteMap.ts
> +	const pathThemeImages = Liferay.ThemeDisplay.getPathThemeImages();
```suggestion
	const pathThemeImages = Liferay.ThemeDisplay.getPathThemeImages();

```

2022-07-28 13:54 UTC, joaosvassis commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/package.json
> +		"formik": "^2.2.9",
Oi @jairmedeiros, Adicionei por engano

2022-07-28 13:55 UTC, joaosvassis commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/components/DatePicker/index.tsx
> +	return <ClayDatePicker spritemap={getIconSpriteMap()} {...props} />;
Funciona sim, obrigado!

2022-08-01 17:30 UTC, closed without merging