LPS-155671 [PRM] Search Page
pt-liferay-solutions/liferay-portal pull request #1886
Opened 2022-08-15 23:04 UTC by ytuik

2022-08-16 14:53 UTC, jairmedeiros requested changes

2022-08-16 14:53 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layout-page-templates/master-pages/main-template/page-definition.json
> +		"css": "/*Source Serif Pro*/\n@font-face {\n\tfont-display: swap;\n\tfont-family: 'Source Sans Pro';\n\tfont-style: normal;\n\tfont-weight: 400;\n\tsrc: url(/documents/d/prm-01/sourcesanspro-regula
This setting is necessary? @ytuik @EuniceTravassos

2022-08-16 14:53 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/08_search/page-definition.json
> +										"value": "banner_background_partner_portal.svg"
The file name need to be dash-case: banner-background-partner-portal.svg

2022-08-16 14:53 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/08_search/page-definition.json
> +												"classPK": "[$DOCUMENT_FILE_ENTRY_ID:/site-initializer/documents/group/banner_background_partner_portal.svg$]"
```suggestion
												"classPK": "[$DOCUMENT_FILE_ENTRY_ID:/site-initializer/documents/group/banner-background-partner-portal.svg$]"
```

2022-08-16 14:53 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/08_search/page-definition.json
> +									}
```suggestion
									{
										"actionKeys": [],
										"roleKey": "Guest"
									}
```

Guest cannot have permissions

2022-08-16 14:53 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layout-page-templates/master-pages/main-template/page-definition.json
> -																	}
This placeholder was removed, it is right? @ytuik @EuniceTravassos

2022-08-16 14:53 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layout-page-templates/master-pages/main-template/page-definition.json
> +														"iconName": "search"
I think this doesn't works outside localhost. We need to mapping to page.

2022-08-16 14:53 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layout-page-templates/master-pages/main-template/page-definition.json
> -													]
This placeholder was removed, it is right?

2022-08-16 14:53 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layout-page-templates/master-pages/content-template/page-definition.json
> +		"css": "/*Source Serif Pro*/\n@font-face {\n\tfont-display: swap;\n\tfont-family: 'Source Sans Pro';\n\tfont-style: normal;\n\tfont-weight: 400;\n\tsrc: url(/documents/d/prm-01/sourcesanspro-regula
This setting is necessary?

2022-08-16 14:53 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layout-page-templates/master-pages/content-template/page-definition.json
> +													},
I think that we need to mapping a page

2022-08-16 16:53 UTC, jackelyneaquino commented
jackelyneaquino

2022-08-16 16:53 UTC, EuniceTravassos commented
Just starting reviewing :)

2022-08-16 20:51 UTC, closed without merging

2022-09-05 14:42 UTC, jackelyneaquino commented
jackelyneaquino