LPS-160835 [PRM] Create fields startDate and endDate in object mdfrequests
pt-liferay-solutions/liferay-portal pull request #1910
Opened 2022-08-17 18:30 UTC by joaosvassis

2022-08-17 18:30 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-08-17 21:26 UTC, jairmedeiros requested changes

2022-08-17 21:26 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Review/utils/GetTotalBudget.tsx
> +const GetTotalBudget = (values: MDFRequest) => {
```suggestion
export default function getTotalBudget = (mdfRequest: MDFRequest) => {
```

2022-08-17 21:26 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Review/utils/GetTotalBudget.tsx
> +export default GetTotalBudget;
```suggestion
```

2022-08-17 21:26 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Review/utils/GetTotalBudget.tsx
> +	return totalBudget;
```suggestion
	return useMemo(
		() =>
			values.activities.reduce(
				(previousValue: number, currentValue: MDFRequestActivity) => {
					const sumBudgets = currentValue.budgets.reduce<number>(
						(previousValue, currentValue) =>
							previousValue + +currentValue.cost,
						0
					);

					return previousValue + sumBudgets;
				},
				0
			),
		[values.activities]
	);
```

2022-08-17 21:26 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/services/liferay/object/mdf-requests/createMDFRequest.ts
> +const getDateActivities = (mdfRequest: MDFRequest) => {
@joaosvassis, should be good add this function in utils directory with the interface too.

2022-08-18 17:47 UTC, jairmedeiros requested changes

2022-08-18 17:47 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/hooks/useTotalBudget.tsx
> +const useTotalBudget = (mdfRequest: MDFRequest) => {
```suggestion
export default function useTotalBudget(mdfRequest: MDFRequest) {
```

2022-08-18 17:47 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/hooks/useTotalBudget.tsx
> +export default useTotalBudget;
```suggestion
```

2022-08-18 17:47 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/services/liferay/object/mdf-requests/createMDFRequest.ts
> +
```suggestion
```

2022-08-18 19:14 UTC, closed without merging

2022-08-18 19:35 UTC, DiogoNo commented
Just starting reviewing :)