LPS-159029 My Activities Page needs a refresh
pt-liferay-solutions/liferay-portal pull request #2027
Opened 2022-08-30 18:57 UTC by TalitaFraga

2022-08-30 18:58 UTC, TalitaFraga commented
ci: test:sf

2022-08-30 18:59 UTC, TalitaFraga commented
ci:test:sf

2022-08-30 19:05 UTC, TalitaFraga commented
ci:test:sf

2022-08-30 19:08 UTC, TalitaFraga commented
ci:test:sf

2022-08-30 20:12 UTC, Claudionilton commented
ci:test:sf

2022-08-30 20:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/4471/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4471/jenkins-report.html">here</a>.</b></p>

2022-08-30 20:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/592273d0c55f9fddb41e1e615a176aba3a7133bb">592273d0c55f9fddb41e1e615a176aba3a7133bb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/TalitaFraga/liferay-portal/tree/LPS-159029">LPS-159029</a><br/>Branch GIT ID: <a href="https://github.com/TalitaFraga/liferay-portal/commit/70bf78355619f27d594ee55abe5d49bebafeceb3">70bf78355619f27d594ee55abe5d49bebafeceb3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/4471/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4471/jenkins-report.html">here</a>.</h5></details></html>

2022-08-30 20:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/4471/">test-portal-source-format#4471</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4471/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2027">pt-liferay-solutions#2027</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1962350147">[master] ci:test:sf - TalitaFraga &gt; pt-liferay-solutions - PR#2027 - 2022-08-30[13:16:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/2688/">publish-testray-report#2688</a><br/></div></div>

2022-09-02 12:26 UTC, kevenleone requested changes
@TalitaFraga , @Claudionilton could you please take a look? thanks

2022-09-02 12:26 UTC, kevenleone commented on modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/components/Comments.es.js
> +			});
Hard coded values

```suggestion
			deleteCacheKey(getUserActivityQuery, {
				filter: `creatorId eq ${context.userId}`,
				page: 1,
				pageSize: 20,
				siteKey: context.siteKey,
			});
```

2022-09-02 12:26 UTC, kevenleone commented on modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/pages/questions/Question.es.js
> +				});
```suggestion
				deleteCacheKey(getUserActivityQuery, {
					filter: `creatorId eq ${context.userId}`,
					page: 1,
					pageSize: 20,
					siteKey: context.siteKey,
				});
```

2022-09-02 12:26 UTC, kevenleone commented on modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/pages/questions/Question.es.js
> +												pageSize={pageSize}
```suggestion
											
```

2022-09-06 20:00 UTC, TalitaFraga commented
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/2070

2022-09-06 20:00 UTC, closed without merging