LPS-161297 [PRM] Made the table, header and add the comment on the Detail MDF Page
pt-liferay-solutions/liferay-portal pull request #2059
Opened 2022-09-01 22:31 UTC by ytuik

2022-09-02 14:08 UTC, DiogoNo requested changes

2022-09-02 14:08 UTC, DiogoNo commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-request-manager-status/index.js
> +		}
```suggestion
		if (response.ok) {
			const result = response.json();

			const hasRoleBriefs = result?.roleBriefs?.reduce((_, role) => {
				return ROLE_TYPES.includes(role.name) ? true : false;
			});

			if (hasRoleBriefs) {
				managerButtons.classList.toggle('d-none');
				managerButtons.classList.toggle('d-flex');
			}
			return ; 
		}
		
		Liferay.Util.openToast({
				message: 'An unexpected error occured.',
				type: 'danger',
			});
```

2022-09-02 14:08 UTC, DiogoNo commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-request-manager-status/index.js
> +		}
seria legal fazer uma tratativa de erro se ele nao entrar no if

2022-09-02 14:08 UTC, DiogoNo commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-details-date-period/index.js
> +		}
```suggestion
		if (response.ok) {
			const data = response.json();
			const startDate = new Intl.DateTimeFormat(
				`${Liferay.ThemeDisplay.getBCP47LanguageId()}`,
				{day: 'numeric', month: 'short'}
			).format(new Date(data.minDateActivity));
			const endDate = new Intl.DateTimeFormat(
				`${Liferay.ThemeDisplay.getBCP47LanguageId()}`,
				{day: 'numeric', month: 'short', year: 'numeric'}
			).format(new Date(data.maxDateActivity));
	
			document.getElementById(
				'dateField'
			).innerHTML = `${startDate} - ${endDate}`;
		
				return;
		}
		
		Liferay.Util.openToast({
				message: 'An unexpected error occured.',
				type: 'danger',
			});
```

2022-09-02 18:40 UTC, DiogoNo commented
Just starting reviewing :)

2022-09-05 00:46 UTC, jairmedeiros requested changes

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-details-summary/index.html
> +</div>
```suggestion
<div class="d-flex justify-content-around">
	<div class="align-items-center d-flex flex-column text-paragraph">
		<p class="text-neutral-8">Funding Periods</p>
		<p class="text-neutral-9" id="dateField"></p>
	</div>
	
	<div class="align-items-center d-flex flex-column">
		<p class="text-neutral-8">Total Cost</p>
		<p class="text-neutral-9" id="totalCost"></p>
	</div>
	
		<div class="align-items-center d-flex flex-column">
		<p class="text-neutral-8">Requested Cost</p>
		<p class="text-neutral-9" id="requestedCost"></p>
	</div>
	
</div>
```

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/detail-view-table/index.html
> +<table class="table table-borderless w-100">
@ytuik, eh preciso corrigir a indentaçao.

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-details-summary/index.js
> +			}
@ytuik. Melhor centralizar essa configuracao em uma const fora desta funcao, visto que repete.

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Activities/Activities.tsx
> +							)
@ytuik @joaosvassis @thaynam. eh melhor a funcao onSaveAsDraft passar o RequestStatus.DRAFT ao inves de quem esta chamando, para evitar repetir o codigo.

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Goals/Goals.tsx
> +							)
@ytuik @joaosvassis @thaynam. eh melhor a funcao onSaveAsDraft passar o RequestStatus.DRAFT ao inves de quem esta chamando, para evitar repetir o codigo.

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Review/Review.tsx
> +									)
@ytuik @joaosvassis @thaynam. eh melhor a funcao onSaveAsDraft passar o RequestStatus.DRAFT ao inves de quem esta chamando, para evitar repetir o codigo.

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-details-summary/index.js
> +const getMDFRequest = async () => {
```suggestion
const updateMDFDetailsSummary = async () => {
```

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-details-summary/index.js
> +getMDFRequest();
```suggestion
updateMDFDetailsSummary();
```

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-request-manager-status/index.js
> +const updateStatusToApproved = fragmentElement.querySelector('.st-approved');
@ytuik @joaosvassis. Devemos evitar resumir ou colocar siglas nas classes/ids.
Alem disso, provavelmente esta classe nao esta aplicando nenhum estilo, entao eh melhor usar o querySelector com id.

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-request-manager-status/index.js
> +		).innerHTML = `Status : ${data.requestStatus}`;
```suggestion
		).innerHTML = `Status: ${data.requestStatus}`;
```

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-request-manager-status/index.js
> +const handleFetch = (status) => {
```suggestion
const updateStatus = (status) => {
```

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-request-manager-status/index.js
> +		body: `{"requestStatus": "${status}"}`,
@ytuik @joaosvassis. Este body nao deveria estar com a estrutura como string. Vamos passar o object corretamente.

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-request-manager-status/index.js
> +	});
Devemos evitar o uso de then, de acordo com o padrao que temos. O mais correto eh utilizar o await na funcao fetch.

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-request-manager-status/index.js
> +];
@ytuik. Estes valores poderiam vim de algum configuration? Seria melhor para tornar editavel/dinamico para o futuro.

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-request-manager-status/index.js
> +];
O melhor, na verdade, seria definir a permission diretamente no low-code, ao editar a pagina.

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/activities-list-panel/index.js
> +	};
@DiogoNo. Este dateOptions poderia estar fora deste componente e renomeado para DATE_FORMAT_OPTION.
Com isso, poderia simplicar o retorno deste component, passando direto sem o `return`.

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/activities-list-panel/index.js
> +			{activities?.items.length === 0 ? (
```suggestion
			{!activities?.items.length ? (
```

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/activities-list-panel/index.js
> +
@DiogoNo. Seria interessante adicionar um estado para o loading e colocar aqui.

```
if (loading) {
  return <>Loading...</>;
}
```

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layout-page-templates/display-page-templates/mdfdetails-template/page-definition.json
> +																		"ar_SA": "Campaign MDF Request ",
```suggestion
																		"ar_SA": "Campaign MDF Request",
```

Ajusta o espaçamento para os outros!

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layout-page-templates/display-page-templates/mdfdetails-template/page-definition.json
> +																				"ar_SA": "Date Submitted: ",
```suggestion
																				"ar_SA": "Date Submitted:",
```

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layout-page-templates/display-page-templates/mdfdetails-template/page-definition.json
> +																				"ar_SA": ", Last Modified: ",
```suggestion
																				"ar_SA": ", Last Modified:",
```

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layout-page-templates/display-page-templates/mdfdetails-template/page-definition.json
> +																				"ar_SA": "Date Submitted: ",
Ajusta o espaçamento para os outros!

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layout-page-templates/display-page-templates/mdfdetails-template/page-definition.json
> +																				"ar_SA": ", Last Modified: ",
Ajusta o espaçamento para os outros!

2022-09-05 00:46 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layout-page-templates/display-page-templates/mdfdetails-template/page-definition.json
> +	},
@ytuik,compara esse settings com outras paginas, acho que nao precisa da parte de `themeSettings`.

2022-09-05 00:48 UTC, jairmedeiros commented
@ytuik @joaosvassis @DiogoNo. Verifiquem nos fragments que tiverem requisiçao para adicionar o toast de erro caso o request.ok seja falso!

2022-09-05 00:50 UTC, jairmedeiros commented
@ytuik, eh melhor separar o fragment que mostra o status do que atualiza. Podemos, para esse segundo, que atualiza, colocar a permissao pelo low-code ao inves de ter o some!

2022-09-05 14:33 UTC, ytuik commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layout-page-templates/display-page-templates/mdfdetails-template/page-definition.json
> +	},
Chequei aqui e todos os page templates tem esse theme setting

2022-09-05 14:43 UTC, jackelyneaquino commented
jackelyneaquino

2022-09-05 14:44 UTC, jackelyneaquino commented
jackelyneaquino

2022-09-05 18:24 UTC, DiogoNo commented
Just starting reviewing :)

2022-09-05 21:01 UTC, EuniceTravassos commented
Just starting reviewing :)

2022-09-06 15:41 UTC, jairmedeiros approved these changes

2022-09-06 15:41 UTC, jairmedeiros commented
ci:forward

2022-09-06 15:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/2741/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2741/jenkins-report.html">here</a>.</b></p>

2022-09-06 15:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9321b7a035b98af0e0ab6032161ddb768eb0ba4c">9321b7a035b98af0e0ab6032161ddb768eb0ba4c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ytuik/liferay-portal/tree/LPS-161297">LPS-161297</a><br/>Branch GIT ID: <a href="https://github.com/ytuik/liferay-portal/commit/b35cd5ce87576302962c2efe48661dea4ec64279">b35cd5ce87576302962c2efe48661dea4ec64279</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/3969/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/3969/jenkins-report.html">here</a>.</h5></details></html>

2022-09-06 15:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-source-format/3969/">test-portal-source-format#3969</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/3969/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2059">pt-liferay-solutions#2059</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1968423817">[master] ci:test:sf - ytuik &gt; pt-liferay-solutions - PR#2059 - 2022-09-06[08:41:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/4070/">publish-testray-report#4070</a><br/></div></div>

2022-09-06 17:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 26 out of 26 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 47 out of 47 jobs passed in 1 hour 31 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9321b7a035b98af0e0ab6032161ddb768eb0ba4c">9321b7a035b98af0e0ab6032161ddb768eb0ba4c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b020949fc0fe26a38c3fe0c0d59cd6f884502f29">b020949fc0fe26a38c3fe0c0d59cd6f884502f29</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1967966691">EE Development Acceptance (master) - 3768 - 2022-09-05[17:36:02]</a></p><details><summary><strong>ci:test:stable - 26 out of 26 jobs PASSED</strong></summary><details><summary><strong>26 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/192587/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/189251/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222332/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222330/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208840/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/192589/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/186489/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208841/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/81215/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208531/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/186490/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/222331/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/219020/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/229038/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/189250/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/204983/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/162475/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/229040/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/219021/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/192591/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/190276/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/204984/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208527/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/229039/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/192590/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208528/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 47 out of 47 jobs PASSED</strong></summary><details><summary><strong>47 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/2741/">test-portal-acceptance-pullrequest(master)</a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/216319/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/186486/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/162476/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/215309/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/192587/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208526/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/190273/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/192588/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/215307/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/215306/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/186487/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/189251/">functiona [...]

2022-09-06 17:12 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/2741//consoleFull)

2022-09-06 17:13 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/122698
[Console](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/2741//consoleFull)

2022-09-06 17:13 UTC, closed without merging

2022-09-06 17:15 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/2741/">test-portal-acceptance-pullrequest(master)#2741</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2741/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2059">pt-liferay-solutions#2059</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1968511684">[master] ci:test:relevant - ytuik &gt; pt-liferay-solutions - PR#2059 - 2022-09-06[08:41:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/6889/">publish-testray-report#6889</a><br/></div></div>