LPS-162655 [PRM] Create Objects MDF Claim
pt-liferay-solutions/liferay-portal pull request #2114
Opened 2022-09-09 13:43 UTC by joaosvassis

2022-09-09 13:43 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-09-09 14:08 UTC, ytuik approved these changes

2022-09-09 14:38 UTC, thaynam requested changes

2022-09-09 14:38 UTC, thaynam commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/object-definitions/mdf-claim.json
> +			"required": false,
```suggestion
			"label": {
				"en_US": "MDF Requested Amount"
			},
			"name": "mdfRequestedAmount",
			"required": false,
```

2022-09-09 17:30 UTC, ytuik commented
Just starting reviewing :)

2022-09-11 00:02 UTC, jairmedeiros requested changes
@ytuik @thaynam @joaosvassis.

Guys, preciso que redobrem a atencao nesses pontos. A intencao eh que nao precisemos revisitar esses arquivos novamente.

2022-09-12 13:36 UTC, DiogoNo commented
Just starting reviewing :)

2022-09-12 13:36 UTC, DiogoNo commented
Just starting reviewing :)

2022-09-12 14:10 UTC, closed without merging