LPS-161176 [CP 2.0] Unit Test WIP
pt-liferay-solutions/liferay-portal pull request #2118
Opened 2022-09-09 20:25 UTC by joaodamasceno2001

2022-09-09 20:25 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-09-09 20:26 UTC, joaodamasceno2001 commented
ci:test:sf

2022-09-09 20:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3069/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3069/jenkins-report.html">here</a>.</b></p>

2022-09-09 20:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/de1f94753f627f03c15b14b2478dae91d613778b">de1f94753f627f03c15b14b2478dae91d613778b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joaodamasceno2001/liferay-portal/tree/LPS-161176">LPS-161176</a><br/>Branch GIT ID: <a href="https://github.com/joaodamasceno2001/liferay-portal/commit/c601660a406e932e76cefdea0e966fee68beb310">c601660a406e932e76cefdea0e966fee68beb310</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3069/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3069/jenkins-report.html">here</a>.</h5></details></html>

2022-09-09 20:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3069/">test-portal-source-format#3069</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3069/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2118">pt-liferay-solutions#2118</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1972397741">[master] ci:test:sf - joaodamasceno2001 &gt; pt-liferay-solutions - PR#2118 - 2022-09-09[13:26:22]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/11389/">publish-testray-report#11389</a><br/></div></div>

2022-09-12 12:54 UTC, claricebrasil requested changes

2022-09-12 14:29 UTC, joaodamasceno2001 commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/Project/TeamMembers/components/ManageProductUsers/ManageProductUsers.test.js
> +	beforeEach(() => {
I belive that, if we are gonna use "mockedProps" more than once, we have to use this beforeEach.

2022-09-12 14:36 UTC, joaodamasceno2001 commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/Project/TeamMembers/components/ManageProductUsers/ManageProductUsers.test.js
> +		const {queryByTestId} = render(
I am testing the return of component "MangeProductUsers.js", I created an id and I am using it with  queryByTestId. I think it`s a nice way to find the element using an Id

2022-09-12 14:39 UTC, joaodamasceno2001 commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/Project/TeamMembers/components/ManageProductUsers/ManageProductUsers.test.js
> +		expect(queryByTestId('test-id')).toBeFalsy();
I thought about that, but if this button only appears when the project is "Active", so I only created a test to this case, but I can created others case too.

2022-09-12 17:08 UTC, claricebrasil commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/Project/TeamMembers/components/ManageProductUsers/ManageProductUsers.test.js
> +	beforeEach(() => {
beforeEach is recommended when you want to reset the global data for each block of test. If is not the case, you can just mock the data and pass it as props for the component

2022-09-12 17:11 UTC, claricebrasil commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/Project/TeamMembers/components/ManageProductUsers/ManageProductUsers.test.js
> +		const {queryByTestId} = render(
Ok, nice.. you can also find by className or by the text too, if you don't want to add an ID for the element

2022-09-12 17:13 UTC, claricebrasil commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/Project/TeamMembers/components/ManageProductUsers/ManageProductUsers.test.js
> +		expect(queryByTestId('test-id')).toBeFalsy();
Just to make sure every possible case is been tested, I believe would be nice to test with the in-progress status too

2022-09-12 17:14 UTC, joaodamasceno2001 commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/Project/TeamMembers/components/ManageProductUsers/ManageProductUsers.test.js
> +	beforeEach(() => {
Right, this is what I want, I am reseting the mockedProps for each block of test.

2022-09-12 18:37 UTC, joaodamasceno2001 commented
ci:test:sf

2022-09-12 18:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/2968/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2968/jenkins-report.html">here</a>.</b></p>

2022-09-12 18:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6e4f802fa12f983f6be9d199184e157ebbe262be">6e4f802fa12f983f6be9d199184e157ebbe262be</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joaodamasceno2001/liferay-portal/tree/LPS-161176">LPS-161176</a><br/>Branch GIT ID: <a href="https://github.com/joaodamasceno2001/liferay-portal/commit/0939e6e99a49f745d4494dd0b73560e8a40f3725">0939e6e99a49f745d4494dd0b73560e8a40f3725</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/2968/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2968/jenkins-report.html">here</a>.</h5></details></html>

2022-09-12 18:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/2968/">test-portal-source-format#2968</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2968/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2118">pt-liferay-solutions#2118</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1974348841">[master] ci:test:sf - joaodamasceno2001 &gt; pt-liferay-solutions - PR#2118 - 2022-09-12[11:37:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/11571/">publish-testray-report#11571</a><br/></div></div>

2022-09-12 19:09 UTC, claricebrasil approved these changes
Nice job, João!

2022-09-12 20:49 UTC, jairmedeiros requested changes

2022-09-12 21:06 UTC, claricebrasil commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/Project/TeamMembers/components/ManageProductUsers/ManageProductUsers.js
> +					data-testid="test-id"
oi Jair, não usamos! Por mais que não seja tão indicado, em últimos casos podemos pegar o elemento pelo nome da classe que nesse caso tem uma classe específica pra ele.

2022-09-14 03:20 UTC, closed without merging