LPS-162413 [PRM] Create the Claim Reimbursement Form
pt-liferay-solutions/liferay-portal pull request #2141
Opened 2022-09-13 13:38 UTC by joaosvassis

2022-09-13 13:39 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-09-16 13:37 UTC, thaynam approved these changes

2022-09-19 17:02 UTC, ytuik commented
ci:test:sf

2022-09-20 00:25 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/main.tsx
> +	[AppRouteType.MDF_CLAIM_FORM]: <MDFClaimFormik />,
@joaosvassis, eh importante seguirmos o padrao do projeto, ao inves de haver um componente direto com Formik, utilize-o dentro de um component. O AppRouteComponent nao precisa saber que eh um component Formik logo de cara.

2022-09-20 00:29 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/services/liferay/object/activity/useGetActivityToBudgets.ts
> +			liferayFetcher<LiferayItems<MDFRequestActivityDTO[]>>(url, token)
@joaosvassis, o endpoint indica que eh uma lista de budgets, porem a tipagem indica que eh uma lista de activities. Eh isto mesmo?

2022-09-20 00:30 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/services/liferay/object/activity/useGetActivityToBudgets.ts
> +export default function useGetActivityToBudgets(id: number) {
@joaosvassis, eh importante seguir o padrao do projeto para casos como este, conforme `useGetTacticsByTypeActivityId`. Ou seja, o metodo deveria ser renomeado para `useGetBudgetsByActivityId`.

2022-09-20 00:30 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/services/liferay/object/activity/useGetActivityToBudgets.ts
> +			liferayFetcher<LiferayItems<MDFRequestActivityDTO[]>>(url, token)
Seguindo pelo padrao do metodo `useGetTacticsByTypeActivityId`, de fato nao esta tao claro.

2022-09-20 00:33 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/interfaces/dto/mdfClaimDTO.ts
> +export default interface MDFClaimDTO extends MDFClaim {}
@joaosvassis, a interface DTO so deve ser utilizada quanto ha uma diferença entre o valor recebido pela API e o que eh tratado pelo front-end. Seguindo o padrao do projeto, por exemplo, o Tactic nao possui um TacticDTO.

2022-09-20 00:35 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/utils/dto/mdf-claim/getDTOFromMDFClaim.ts
> +export function getDTOFromMDFClaim(mdfClaim: MDFClaim) {
@joaosvassis, este metodo eh realmente necessario? Visto que a unica mudanca eh o nome do campo, pq o mesmo ja nao poderia estar com o nome correto?

2022-09-20 00:36 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/services/liferay/object/mdf-requests/useGetMDFRequestToActivities.ts
> +export default function useGetMDFRequestToActivities(id: number) {
@joaosvassis, mesmo ponto de atencao do metodo `useGetActivityToBudgets`.

2022-09-20 00:37 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/services/liferay/object/mdf-claim/createMDFClaim.ts
> +	const dtoMDFClaim = getDTOFromMDFClaim(mdfClaim);
@joaosvassis, conforme discutido no arquivo deste metodo. Talvez nao precise nem dele.

2022-09-20 00:38 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/MDFClaimForm.tsx
> +}: PRMFormikPageProps & mdfClaimProps<MDFClaim>) => {
@joaosvassis, todas as tipagens sao no padrao de CamelCase. Ou seja, `MDFClaimProps`.

2022-09-20 00:39 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/MDFClaimForm.tsx
> +	}, [errors]);
@joaosvassis, o return nao eh necessario.

2022-09-20 00:40 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/MDFClaimForm.tsx
> +		<PRMForm className="mb-4" name="NEW" title="Reimbursement Claim">
@joaosvassis, a prop name precisa ser em uppercase?

2022-09-20 00:41 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/MDFClaimForm.tsx
> +				</div>
@joaosvassis, eh melhor o component ja ter o classname que voce espera, ou passar como prop, ao inves de haver essa div.

2022-09-20 00:43 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/MDFClaimForm.tsx
> +							(!isValid && !isObjectEmpty(claimErrors)) ||
@joaosvassis, o isValid ja valida se nao tem erros, nao compreendi o pq usar o `isObjectEmpty(claimErrors)`, pode me explicar pf?

2022-09-20 00:44 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/MDFClaimForm.tsx
> +					</Button>
@joaosvassis, o botao de Cancel nao vai ter nenhuma açao?

2022-09-20 00:44 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/components/MDFClaimFormik/MDFClaimFormik.tsx
> +	return (
@joaosvassis, o retorno nao eh necessario.

2022-09-20 00:49 UTC, jairmedeiros requested changes
Joao, parabens pela PR, muita coisa foi feita, mas notei que ainda muita coisa esta fora do nosso padrao. Peço que tenha mais cuidado para as proximas PRs.

2022-09-20 00:49 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/utils/submitForm.ts
> +	const dtoMDFClaim = await createMDFClaim(values);
@joaosvassis, se a variavel nao ta sendo utilizada, o metodo nao precisa estar atribuido.

2022-09-20 00:49 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/interfaces/mdfClaimProps.ts
> +export default interface mdfClaimProps<T> {
`MDFClaimProps`. @joaosvassis, de acordo com o padrao do projeto, todos os tipos/interfaces possuem o nome em CamelCase.

2022-09-20 00:55 UTC, jairmedeiros requested changes

2022-09-20 00:55 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/03_marketing/03_mdf-claim/page.json
> +		"en_US": "/marketing/mdf-claim"
```suggestion
		"en_US": "/marketing/mdf-claims"
```

2022-09-20 00:55 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/03_marketing/03_mdf-claim/01_new/page.json
> +		"en_US": "/marketing/mdf-claim/new"
```suggestion
		"en_US": "/marketing/mdf-claims/new"
```

2022-09-20 00:55 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/03_marketing/03_mdf-claim/page-definition.json
> +{
@joaosvassis, `03_mdf-claims` pode ser um nome melhor, o que acha? Visto que vai ser a listagem.

2022-09-21 17:29 UTC, ytuik commented
Just starting reviewing :)

2022-09-22 13:55 UTC, ytuik commented
Just starting reviewing :)

2022-09-22 20:32 UTC, closed without merging