LPS-163132
pt-liferay-solutions/liferay-portal pull request #2157
Opened 2022-09-14 21:48 UTC by juliocezarjc

2022-09-14 21:48 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-09-14 21:49 UTC, juliocezarjc commented
ci:test:sf

2022-09-14 21:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/3009/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3009/jenkins-report.html">here</a>.</b></p>

2022-09-14 21:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c50d5d1f43d9cc4afa2de010abd5ace6f47a1ce4">c50d5d1f43d9cc4afa2de010abd5ace6f47a1ce4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliocezarjc/liferay-portal/tree/LPS-163132">LPS-163132</a><br/>Branch GIT ID: <a href="https://github.com/juliocezarjc/liferay-portal/commit/4c6891b30cb02aeab0ba321470da0ba683c50bcb">4c6891b30cb02aeab0ba321470da0ba683c50bcb</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3009/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3009/jenkins-report.html">here</a>.</h5></details></html>

2022-09-14 21:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/3009/">test-portal-source-format#3009</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/3009/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2157">pt-liferay-solutions#2157</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1977405098">[master] ci:test:sf - juliocezarjc &gt; pt-liferay-solutions - PR#2157 - 2022-09-14[14:50:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/11723/">publish-testray-report#11723</a><br/></div></div>

2022-09-15 03:53 UTC, JoMaAlves requested changes
🛠️ Needs some changes 🛠️

2022-09-15 03:53 UTC, JoMaAlves commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/fragments/group/evp/collection.json
> +	"name": "EVP"
Could you change the name to:
```suggestion
	"name": "EVP Fragments"
```

2022-09-15 03:53 UTC, JoMaAlves commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/fragments/group/evp/fragments/evp-process-title/index.css
> +	min-width: 0ch !important;
Is this line really necessary?

2022-09-15 03:53 UTC, JoMaAlves commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/fragments/group/evp/fragments/evp-process-title/index.html
> +<div class="align-items-center d-flex evp-process">
Could you rename the class to: 
```suggestion
<div class="align-items-center d-flex evp-process-title">
```

2022-09-15 03:53 UTC, JoMaAlves commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/fragments/group/evp/fragments/evp-process-title/index.css
> +.evp-process .number-process{
Could you rename the class to:
```suggestion
.evp-process-title .number-process{
```

2022-09-15 03:53 UTC, JoMaAlves commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/fragments/group/evp/fragments/evp-process-title/index.css
> +.evp-process .number-process{
The same for the ones below

2022-09-15 03:53 UTC, JoMaAlves commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/fragments/group/evp/fragments/evp-process-title/index.css
> + width:40px
Fix the indentation here.

2022-09-15 03:53 UTC, JoMaAlves commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/fragments/group/evp/fragments/evp-process-title/index.html
> +</div>
Fix the indentation here.

2022-09-15 16:59 UTC, JoMaAlves commented
Just starting reviewing :)

2022-09-15 18:20 UTC, closed without merging