LPS-163462 [PRM] Create Contact Table
pt-liferay-solutions/liferay-portal pull request #2202
Opened 2022-09-20 16:11 UTC by EuniceTravassos

2022-09-20 16:11 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-09-20 16:51 UTC, DiogoNo requested changes

2022-09-20 16:51 UTC, DiogoNo commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/object-relationships/user-to-mdf-requests.json
> +	"name": "userToMDFRequest",
```suggestion
	"name": "userToMDFRequests",
```

2022-09-20 16:51 UTC, DiogoNo commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layout-page-templates/display-page-templates/mdf-request-details-template/page-definition.json
> +																"separatorColor": ""
```suggestion
																
```
tag sem valor

2022-09-20 16:51 UTC, DiogoNo commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/interfaces/dto/mdfRequestDTO.ts
> +	r_userToMDFRequest_userId?: number;
```suggestion
	r_userToMDFRequests_user?: User;
	r_userToMDFRequests_userId?: number;
```

2022-09-21 13:24 UTC, ytuik reviewed
Please check this changes

2022-09-21 13:24 UTC, ytuik commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layout-page-templates/display-page-templates/mdf-request-details-template/display-page-template.json
>  {
This archive should not be on the PR

2022-09-21 19:46 UTC, thaynam commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layout-page-templates/display-page-templates/mdf-request-details-template/display-page-template.json
> +		"className": "com.liferay.object.model.ObjectDefinition#44503"
este arquivo nao deveria estar aqui

2022-09-21 20:04 UTC, thaynam commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/services/liferay/object/mdf-requests/useGetMDFRequests.ts
> +			`/o/${LiferayAPIs.OBJECT}/mdfrequests?nestedFields=accountEntry,user&page=${page}&pageSize=${pageSize}`,
esta mudanca nao e necessaria pro MDF Request Listing.

2022-09-21 20:11 UTC, thaynam commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-request-info-contact/index.html
> +				<p class="text-neutral-10" id="firstName" type="rich-text">
esta faltando a tag do editable. veja: https://learn.liferay.com/dxp/latest/en/site-building/developer-guide/reference/fragments/fragment-specific-tags-reference.html#making-text-editable

2022-09-21 20:24 UTC, thaynam commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-request-info-contact/index.js
> +		`/o/c/mdfrequests/${mdfRequestId}?nestedFields=accountEntry,user`,
o accountEntry nao e necessario aqui

2022-09-21 20:35 UTC, EuniceTravassos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-request-info-contact/index.html
> +				<p class="text-neutral-10" id="firstName" type="rich-text">
Nao estamos usando editable para esta tabela de info pq os campos e dados ja vão vir da requisição

2022-09-22 18:32 UTC, closed without merging