LPS-163462 [PRM] Create contact table from MDF Request Detail
pt-liferay-solutions/liferay-portal pull request #2236
Opened 2022-09-22 18:40 UTC by EuniceTravassos

2022-09-22 19:42 UTC, ytuik commented
ci:test:sf

2022-09-22 19:49 UTC, jairmedeiros requested changes

2022-09-22 19:49 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-request-info-contact/index.js
> +		fragmentElement.querySelector('#infoEmail').innerHTML = `${infoEmail}`;
```suggestion
		fragmentElement.querySelector('#firstName').innerHTML = htmlUtil.escape(firstName);
		fragmentElement.querySelector('#infoEmail').innerHTML = htmlUtil.escape(infoEmail);
```

2022-09-22 20:36 UTC, jairmedeiros requested changes

2022-09-22 20:36 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-request-info-contact/index.js
> +/* eslint-disable no-undef */
```suggestion
```

2022-09-22 20:36 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-request-info-contact/index.js
> + */
```suggestion
```

2022-09-22 20:36 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/partner-portal/fragments/mdf-request-info-contact/index.js
> +	if (response.ok) {
```suggestion
	);

	if (response.ok) {
```

2022-09-27 14:38 UTC, EuniceTravassos commented
Just starting reviewing :)

2022-09-27 17:09 UTC, closed without merging