LPS-164398 & LPS-164292 [PRM] Salesforce Integration with MDF Request Activities
pt-liferay-solutions/liferay-portal pull request #2325
Opened 2022-09-30 20:25 UTC by thaynam

2022-09-30 20:25 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-10-04 19:03 UTC, jairmedeiros requested changes

2022-10-06 11:04 UTC, jairmedeiros requested changes

2022-10-06 11:06 UTC, jairmedeiros commented
Eh importante ficar claro que nao guardamos nenhuma informacao de companyName, ela so existe como label para o usuario. Para nos, guardamos o ID do account que representa aquela company.

2022-10-06 13:25 UTC, thaynam commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/interfaces/dto/mdfRequestActivityDTO.ts
> +	mdfRequestExternalReferenceCodeSF?: string;
externalReferenceCodeSF e o ID da Activity no SF, 
mdfRequestExternalReferenceCodeSF e o ID do mdfRequest que esta Activity pertence.

2022-10-06 21:57 UTC, thaynam commented
ci:test:sf

2022-10-06 21:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/4533/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4533/jenkins-report.html">here</a>.</b></p>

2022-10-06 22:01 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bce7b4fc06572b19c99153637ab246edaab68842">bce7b4fc06572b19c99153637ab246edaab68842</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaynam/liferay-portal/tree/LPS-164398-salesforce-integration-with-mdf-request-activities">LPS-164398-salesforce-integration-with-mdf-request-activities</a><br/>Branch GIT ID: <a href="https://github.com/thaynam/liferay-portal/commit/69e72ea525f49eb820f21b1b93d538d1d2e93765">69e72ea525f49eb820f21b1b93d538d1d2e93765</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/4533/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4533/jenkins-report.html">here</a>.</h5></details></html>

2022-10-06 22:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/4533/">test-portal-source-format#4533</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4533/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2325">pt-liferay-solutions#2325</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2000132059">[master] ci:test:sf - thaynam &gt; pt-liferay-solutions - PR#2325 - 2022-10-06[14:57:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/2794/">publish-testray-report#2794</a><br/></div></div>

2022-10-10 14:33 UTC, thaynam commented
ci:forward

2022-10-10 14:33 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-10-10 14:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/5316/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5316/jenkins-report.html">here</a>.</b></p>

2022-10-10 14:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/4333/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4333/jenkins-report.html">here</a>.</b></p>

2022-10-10 14:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f393dc9ab747829c6345d12b9ce545fff30c67d9">f393dc9ab747829c6345d12b9ce545fff30c67d9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaynam/liferay-portal/tree/LPS-164398-salesforce-integration-with-mdf-request-activities">LPS-164398-salesforce-integration-with-mdf-request-activities</a><br/>Branch GIT ID: <a href="https://github.com/thaynam/liferay-portal/commit/c5db46d67643aac66733f5bc747ea59c4c8f5e29">c5db46d67643aac66733f5bc747ea59c4c8f5e29</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/4333/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4333/jenkins-report.html">here</a>.</h5></details></html>

2022-10-10 14:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/4333/">test-portal-source-format#4333</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4333/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2325">pt-liferay-solutions#2325</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2002484875">[master] ci:test:sf - thaynam &gt; pt-liferay-solutions - PR#2325 - 2022-10-10[07:33:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/16037/">publish-testray-report#16037</a><br/></div></div>

2022-10-10 19:51 UTC, thaynam commented
ci:forward

2022-10-10 19:51 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-10-10 19:51 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-10-10 19:52 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-32.liferay.com/job/forward-pullrequest/683//consoleFull)

2022-10-10 20:21 UTC, jairmedeiros commented
ci:forward

2022-10-11 09:02 UTC, thaynam commented
ci:forward

2022-10-11 09:02 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-10-11 09:03 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-27.liferay.com/job/forward-pullrequest/598//consoleFull)

2022-10-11 09:03 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/124362
[Console](https://test-1-27.liferay.com/job/forward-pullrequest/598//consoleFull)

2022-10-11 09:03 UTC, closed without merging