LPS-154929 [PRM] Deal Registration
pt-liferay-solutions/liferay-portal pull request #2353
Opened 2022-10-05 14:30 UTC by DiogoNo

2022-10-05 14:48 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-10-06 11:38 UTC, jairmedeiros requested changes

2022-10-06 11:38 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Goals/hooks/useDynamicFieldEntries.ts
> +		LiferayPicklistName.SALES_PROJECT_INFORMATION,
```suggestion
		LiferayPicklistName.PROJECT_CATEGORIES,
		LiferayPicklistName.PROJECT_INFORMATIONS,
```

2022-10-06 11:38 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/SalesRequestForm/SalesRequestForm.tsx
> +		</div>
```suggestion
					<PRMFormik
						initialValues={{} as DealRegistration}
						onSubmit={onSubmit}
					>
						{StepFormComponent[step]}
					</PRMFormik>
```

2022-10-06 11:38 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/SalesRequestForm/SalesRequestForm.tsx
> +const SalesRequestForm = () => {
```suggestion
const DealRegistrationForm = () => {
```
Lembre de alterar o nome da pasta e do arquivo.

2022-10-06 11:38 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/SalesRequestForm/steps/General/index.tsx
> +/**
A logica deve estar no arquivo General.tsx

O Arquivo index.ts como referencia

2022-10-06 11:38 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/SalesRequestForm/steps/Review/index.tsx
> +				<PRMForm.Footer>
```suggestion
				<PRMForm.Footer className="bg-neutral-0">
```

Eh necessario editar o PRMForm.Footer para aceitar a prop className

2022-10-06 11:38 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/SalesRequestForm/steps/Review/index.tsx
> +		</>
```suggestion
		</>
```

2022-10-06 11:38 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/SalesRequestForm/steps/Review/index.tsx
> +			<PRMForm name="general" title="Deal Registration">
Melhor juntar tudo e nao usar o name="general" title="Deal Registration", mesmo que fique um pouco diferente do figma.

2022-10-06 11:39 UTC, jairmedeiros commented
@DiogoNo. Esta sendo criado um fragment que nao eh utilizado. Pode remover pf?
Alem disso, tem um yarn-error.log, pode remover tbm pf?

Melhor enviar a pagina e as definioes de json em um outro PR. Pode remove pf?

2022-10-11 14:11 UTC, EuniceTravassos requested changes

2022-10-11 14:11 UTC, EuniceTravassos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/enums/liferayPicklistName.ts
> +	PROJECT_INFORMATION = 'Project Information',
```suggestion
	PROJECT_INFORMATION = 'Project Informations',
```
o definition precisa estar no plural.

2022-10-13 13:31 UTC, jairmedeiros requested changes

2022-10-13 13:31 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/DealRegistrationForm/hooks/useDynamicFieldEntries.ts
> +		LiferayPicklistName.PROJECT_INFORMATION,
```suggestion
		LiferayPicklistName.PROJECT_INFORMATIONS,
```

2022-10-13 14:06 UTC, closed without merging