LPS-164946 [PRM] JSON definitions deal Registration
pt-liferay-solutions/liferay-portal pull request #2359
Opened 2022-10-06 15:29 UTC by DiogoNo

2022-10-07 14:29 UTC, ytuik reviewed
LGTM

2022-10-10 15:25 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/08_sales_page/page.json
> +{
essa pagina de dashboard nao seria para o graficos?

2022-10-10 15:32 UTC, jairmedeiros requested changes

2022-10-10 15:32 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/08_sales_page/page.json
> +{
essa pagina de dashboard nao seria para o graficos?

2022-10-10 15:32 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/layouts/08_sales_page/page.json
> +{
caso seja, melhor mandar isso em outra PR.

Alem disso, eh importante que os nomes sejam os mesmos, da pasta com o json.

Ou seja, a pasta deveria se chamar 08_dashboard

2022-10-10 15:32 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/list-type-definitions/project-information.json
> +	"name": "ProjectInfromation",
```suggestion
	"name": "ProjectInformations",
```

2022-10-10 15:32 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/list-type-definitions/project-information.json
> +		"en-US": "Project Information"
```suggestion
		"en-US": "Project Informations"
```

2022-10-10 15:32 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/object-definitions/deal-registration.json
> +			"name": "projecttNeed",
```suggestion
			"name": "projectNeed",
```

2022-10-10 15:32 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/object-definitions/deal-registration.json
> +{
Varios dos picklists definidos nao estao sendo usados aqui, eh isso msm?

por exemplo: Project informations, etc.

2022-10-10 15:32 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/list-type-definitions/project-information.json
> +{
Importante renomear o arquivo de project-information para project-informations

2022-10-11 14:56 UTC, closed without merging