LPS-162412 [PRM] Open Claim form in MDFRequest Detail
pt-liferay-solutions/liferay-portal pull request #2360
Opened 2022-10-06 15:34 UTC by DiogoNo

2022-10-06 22:05 UTC, thaynam commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/mdf-request-detail-collection/new-claim-button/index.js
> +const mdfRequestedId = +currentPath[currentPath.length - 1];
mdfRequestdId

2022-10-06 22:06 UTC, thaynam commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/mdf-request-detail-collection/new-claim-button/index.js
> +		`${SITE_URL}/marketing/mdf-claim/new/#/mdfrequest/${mdfRequestedId}`
mdfRequestId

2022-10-07 11:33 UTC, gabsprates commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/mdf-request-detail-collection/new-claim-button/index.js
> +const mdfRequestedId = +currentPath[currentPath.length - 1];
Thinking about the result of our build process, and browser support, is it possible using [`Array.prototype.at()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at)?

2022-10-07 11:38 UTC, gabsprates commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/mdf-request-detail-collection/new-claim-button/index.js
> +const mdfRequestedId = +currentPath[currentPath.length - 1];
Hmm, I just noticed this is a fragment. Does fragments code goes through some (e.g.: babel) build processes?

2022-10-10 15:21 UTC, jairmedeiros requested changes

2022-10-10 15:21 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/services/liferay/object/mdf-requests/useGetMDFRequestById.ts
> +export default function useGetMDFRequestById(id: number | string | undefined) {
```suggestion
export default function useGetMDFRequestById(id: number | undefined) {
```

2022-10-11 13:34 UTC, jackelyneaquino commented
jackelyneaquino

2022-10-11 13:41 UTC, jackelyneaquino commented
jackelyneaquino

2022-10-11 16:40 UTC, closed without merging