LPS-163903 [PRM] Add submit, cancel and save as draft behavior
pt-liferay-solutions/liferay-portal pull request #2390
Opened 2022-10-11 22:49 UTC by joaosvassis

2022-10-11 22:49 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-10-13 20:42 UTC, ytuik commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/interfaces/dto/mdfClaimActivityDTO.ts
> +	totalCost?: number;
Provavelmente o CI vai reclamar pelo parametros não estarem em ordem alfabetica, um yarn format resolve isso

2022-10-13 20:42 UTC, ytuik commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/interfaces/dto/mdfClaimActivityDTO.ts
> +	totalCost?: number;
a formatação também não está parecendo certa

2022-10-13 20:42 UTC, ytuik commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/interfaces/dto/mdfClaimBudgetDTO.ts
> +	r_mdfClaimActivityToMdfClaimBudgets_c_mdfClaimActivityId?: number;
Vai dar problema no CI também

2022-10-13 20:42 UTC, ytuik commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/interfaces/dto/mdfClaimDocumentsDTO.ts
> +	fileSize?: number;
Parâmetros fora da ordem

2022-10-13 20:42 UTC, ytuik commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/interfaces/mdfClaim.ts
> +	r_mdfRequestToMdfClaims_c_mdfRequestId: number;
parâmetro fora da ordem

2022-10-13 20:42 UTC, ytuik commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/interfaces/mdfClaimBudget.ts
> +	id?: number;
parâmetro fora da ordem

2022-10-13 20:42 UTC, ytuik commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/services/liferay/object/mdf-claim-documents/createMDFClaimDocuments.ts
> +	file?: File,
parâmetro fora da ordem

2022-10-13 20:42 UTC, ytuik commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/components/MDFClaimPage/MDFClaimPage.tsx
>  					small
porque o required foi removido aqui?

2022-10-14 12:42 UTC, joaosvassis commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/components/MDFClaimPage/MDFClaimPage.tsx
>  					small
Entao, ele estava dando um problema no submit.

2022-10-14 13:53 UTC, jairmedeiros requested changes

2022-10-14 13:53 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/utils/dto/mdf-claim-documents/getDTOFromMDFClaimDocuments.ts
> +	url?: string,
```suggestion
	file: File,
	url: string,
```

2022-10-14 13:53 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/services/liferay/object/mdf-claim-documents/createMDFClaimDocuments.ts
> +	const url = file?.name;
O URL viria daqui msm?

2022-10-14 17:52 UTC, joaosvassis commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/services/liferay/object/claim-budgets/createMDFClaimActivityBudgets.ts
> +	activityId: number,
Está quebrando quando coloco o ? no activityId.

2022-10-14 19:12 UTC, closed without merging

2022-10-14 20:00 UTC, joaosvassis commented
resent https://github.com/pt-liferay-solutions/liferay-portal/pull/2407