LPS-162414 [PRM] Create Upload dropzone
pt-liferay-solutions/liferay-portal pull request #2401
Opened 2022-10-13 19:50 UTC by biellopes00

2022-10-13 20:15 UTC, kevenleone requested changes

2022-10-13 20:15 UTC, kevenleone commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/package.json
> +		"react-dom": "^18.2.0",
@biellopes00 can you remove this change? or rebase with my PR?

https://github.com/pt-liferay-solutions/liferay-portal/pull/2398

I already sent this fix

2022-10-17 12:53 UTC, DiogoNo requested changes

2022-10-17 12:53 UTC, DiogoNo commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/MDFClaimForm.tsx
> +	const {data: mdfRequest, isValidating} = useGetMDFRequestById(48386);
Ja existe uma abordagem que pega esse id dinamicamente, da um rebase com a master e resolve o conflito para corrigir

2022-10-17 12:58 UTC, DiogoNo requested changes

2022-10-17 12:58 UTC, DiogoNo commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/MDFClaimForm.tsx
> +	const {data: mdfRequest, isValidating} = useGetMDFRequestById(48386);
Na master ja existe uma abordagem em que pega esse valor dinamicamente, da rebase com a master e resolve os conflitos

2022-10-17 13:45 UTC, ytuik reviewed
LGTM

2022-10-17 16:57 UTC, jairmedeiros requested changes

2022-10-17 16:57 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/components/MDFClaimPage/components/ActivityClaimPanel/ActivityClaimPanel.tsx
> +						}
```suggestion
						onAccept={(value: File[]) => 
							setFieldValue(
								`activities[${activityIndex}].contents`,
								value
							)
						}
```

Nao seria um array de files? Visto que pode adicionar mais de um.

2022-10-17 16:57 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/DragAndDrop/DragAndDrop.tsx
> +	const {acceptedFiles, getInputProps, getRootProps, open} = useDropzone({
```suggestion
	IProps) => {

	const {acceptedFiles, getInputProps, getRootProps, open} = useDropzone({
```

2022-10-17 16:57 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/DragAndDrop/DragAndDrop.tsx
> +							{`File:${file.name} Type:${file.type} Size:${file.size} bytes`}{' '}
```suggestion
							File: {file.name} Type: {file.type} Size: {file.size} bytes
```

2022-10-17 16:57 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/DragAndDrop/DragAndDrop.tsx
> +						<li key={i}>
```suggestion
					{acceptedFiles?.map((file, index) => (
						<li key={index}>
```

2022-10-17 16:57 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/DragAndDrop/DragAndDrop.tsx
> +						type: 'file',
```suggestion
```

2022-10-18 14:26 UTC, jairmedeiros requested changes

2022-10-18 14:26 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/components/MDFClaimPage/components/ActivityClaimPanel/ActivityClaimPanel.tsx
> +import React, {useCallback, useState} from 'react';
```suggestion
import {useCallback, useState} from 'react';
```

2022-10-18 14:26 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/DragAndDrop/DragAndDrop.tsx
> +	const {acceptedFiles, getInputProps, getRootProps, open} = useDropzone({
```suggestion
	IProps) => {
	
	const {acceptedFiles, getInputProps, getRootProps, open} = useDropzone({
```

Atençao com os espaçamentos

2022-10-18 20:52 UTC, closed without merging