LPS-165547 Fixed Scroll overlay, outside Click of breadcrumb, inside input key behavior,set breadcrumb item context
pt-liferay-solutions/liferay-portal pull request #2402
Opened 2022-10-13 21:42 UTC by welitonpe

2022-10-13 21:42 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-10-13 21:43 UTC, welitonpe commented
ci:test:sf

2022-10-13 21:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/2829/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/2829/jenkins-report.html">here</a>.</b></p>

2022-10-13 21:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1dcf56d8a945ed677d6db6110a7f54c822adc852">1dcf56d8a945ed677d6db6110a7f54c822adc852</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/F">F</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/fd8383db9d189fbe31c6296c7d266f1d4ddd0c4a">fd8383db9d189fbe31c6296c7d266f1d4ddd0c4a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/2829/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/2829/jenkins-report.html">here</a>.</h5></details></html>

2022-10-13 21:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/2829/">test-portal-source-format#2829</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/2829/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2402">pt-liferay-solutions#2402</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2006153899">[master] ci:test:sf - welitonpe &gt; pt-liferay-solutions - PR#2402 - 2022-10-13[14:47:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/9669/">publish-testray-report#9669</a><br/></div></div>

2022-10-14 12:57 UTC, kevenleone requested changes
LGTM 🔥

2022-10-14 12:57 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/BreadcrumbFinder/index.tsx
> +			></div>
```suggestion
			<div
				className="breadcrumb-finder-overlay overlay"
				onClick={() => setActive((active) => !active)}
			/>
```

2022-10-14 12:57 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/BreadcrumbFinder/index.tsx
>  			id="breadcrumbFinderContainer"
Maybe remove this id

```suggestion
			className="breadcrumb-finder-container breadcrumb-finder-navigator"
			id="breadcrumbFinderContainer"
```

2022-10-14 12:57 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/BreadcrumbFinder/index.tsx
>  										onBackscape();
Early return

```suggestion
										return onBackscape();
```

2022-10-14 12:57 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/BreadcrumbFinder/index.tsx
> +					<ul className="list-unstyled" ref={ulRef}>
```suggestion
					<ul className="list-unstyled" ref={listRef}>
```

2022-10-14 12:57 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/BreadcrumbFinder/index.tsx
> +								ref={tabRefs[itemIndex]}
```suggestion
								ref={listItemsRef[itemIndex]}
```

2022-10-14 12:57 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/BreadcrumbFinder/useBreadcrumbFinder.ts
> +const ON_CLICK_ROW_ENABLED = true;
This line can be removed

```suggestion

```

2022-10-14 12:57 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/BreadcrumbFinder/useBreadcrumbFinder.ts
> +	);
```suggestion
	const listItemsRef = useMemo(
		() =>
			Array.from({length: items.length}).map(() =>
				createRef<HTMLLIElement>()
			),
		[items.length]
	);
```

2022-10-14 12:57 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/BreadcrumbFinder/useBreadcrumbFinder.ts
> +				top: liElement.current.offsetTop - 90,
Create variable for this magic number, 90

```suggestion
				top: liElement.current.offsetTop - 90,
```

2022-10-14 12:57 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/BreadcrumbFinder/useBreadcrumbFinder.ts
> +	}, []);
Simplify

```suggestion
	const onEscape = useCallback(() => setActive(false), []);
```

2022-10-14 12:57 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/BreadcrumbFinder/useBreadcrumbFinder.ts
> +		}, 10);
```suggestion
		}, CREATE_VARIABLE_FOR_THIS);
```

2022-10-14 12:57 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/hooks/useBreadcrumb.ts
> +			)}&nestedFields=case,r_runToCaseResult_c_runId&pageSize=1000`,
```suggestion
			)}&nestedFields=case&pageSize=1000`,
```

2022-10-14 12:57 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/styles/components/_breadcrumb_finder.scss
> +
I think this is not scoped by any css

2022-10-14 17:21 UTC, closed without merging