LPS-163903 [PRM] Add submit, cancel and save as draft behavior
pt-liferay-solutions/liferay-portal pull request #2407
Opened 2022-10-14 19:16 UTC by joaosvassis

Resent https://github.com/pt-liferay-solutions/liferay-portal/pull/2390

2022-10-14 19:16 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-10-17 12:46 UTC, DiogoNo requested changes

2022-10-17 12:46 UTC, DiogoNo commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/enums/prmPageRoute.ts
> +	MDF_CLAIM_LISTING = 'marketing/mdf-claim',
```suggestion
	MDF_CLAIM_LISTING = 'marketing/mdf-claims',
```

nao deveria ser no plural?

2022-10-17 12:46 UTC, DiogoNo commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/utils/submitForm.ts
> +// import {PRMPageRoute} from '../../../common/enums/prmPageRoute';
nao esquecer de tirar os comentarios

2022-10-17 12:46 UTC, DiogoNo commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/utils/submitForm.ts
> +// import {Liferay} from '../../../common/services/liferay';
comentario aqui tambem

2022-10-17 12:46 UTC, DiogoNo commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/utils/submitForm.ts
> +	// Liferay.Util.navigate(`${siteURL}/${PRMPageRoute.MDF_CLAIM_LISTING}`);
comentario aqui tambem

2022-10-17 12:46 UTC, DiogoNo commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/MDFClaimForm.tsx
> +	const {data: mdfRequest, isValidating} = useGetMDFRequestById(45281);
acredito que a abordagem de pegar esse id dinamicamente ja esta presente na master.

2022-10-17 15:05 UTC, jairmedeiros requested changes

2022-10-17 15:05 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/utils/submitForm.ts
> +							0
```suggestion
							dtoActivity?.id,
```
Precisa encontrar uma forma que nao precise passar esses 0

2022-10-17 16:50 UTC, ytuik commented
Just starting reviewing :)

2022-10-17 20:08 UTC, ytuik commented
resent on  PR [2417](https://github.com/pt-liferay-solutions/liferay-portal/pull/2417)

2022-10-17 20:08 UTC, closed without merging