Update Rest of Structures
pt-liferay-solutions/liferay-portal pull request #245
Opened 2021-09-14 20:34 UTC by kevenleone

2021-09-14 20:34 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-09-14 21:07 UTC, silasbsi requested changes
LGTM. Mas existem alguns pequenos ajustes para serem feitos.

2021-09-14 21:07 UTC, silasbsi commented on modules/apps/site/site-insurance-site-initializer/src/main/resources/com/liferay/site/insurance/site/initializer/internal/dependencies/journal-articles/tip-article-16/journal_article.xml
> +const address = raylifeApplicationForm.basics.businessInformation.business.location;
Acredito ser necessario colocar ? para os casos do raylifeApplicationForm vir undefined.
```suggestion
const address = raylifeApplicationForm?.basics?.businessInformation?.business?.location;
```

2021-09-14 21:07 UTC, silasbsi commented on modules/apps/site/site-insurance-site-initializer/src/main/resources/com/liferay/site/insurance/site/initializer/internal/dependencies/journal-articles/tip-article-16/journal_article.xml
> +const product = raylifeApplicationForm.basics.product;
Acredito ser necessario colocar ? para os casos do raylifeApplicationForm vir undefined.

```suggestion
const product = raylifeApplicationForm?.basics?.product;
```

2021-09-14 21:07 UTC, silasbsi commented on modules/apps/site/site-insurance-site-initializer/src/main/zippableResources/fragments/raylife/fragments/tip-container/index.js
> +
Retirar linha em branco e ordenar variaveis em ordem alfabetica

2021-09-15 11:51 UTC, kevenleone commented on modules/apps/site/site-insurance-site-initializer/src/main/resources/com/liferay/site/insurance/site/initializer/internal/dependencies/journal-articles/tip-article-16/journal_article.json
> +	"articleId": "quote-comparsion-profile-template",
Okay

2021-09-15 11:51 UTC, kevenleone commented on modules/apps/site/site-insurance-site-initializer/src/main/resources/com/liferay/site/insurance/site/initializer/internal/dependencies/journal-articles/tip-article-16/journal_article.json
> +	"name": "Quote Comparsion Profile"
Okay

2021-09-15 11:52 UTC, kevenleone commented on modules/apps/site/site-insurance-site-initializer/src/main/resources/com/liferay/site/insurance/site/initializer/internal/dependencies/journal-articles/tip-article-16/journal_article.xml
> +const address = raylifeApplicationForm.basics.businessInformation.business.location;
Okay

2021-09-15 11:52 UTC, kevenleone commented on modules/apps/site/site-insurance-site-initializer/src/main/resources/com/liferay/site/insurance/site/initializer/internal/dependencies/journal-articles/tip-article-16/journal_article.xml
> +const product = raylifeApplicationForm.basics.product;
Okay

2021-09-15 13:41 UTC, merged