LPS-165524 [PRM] Create yup validation for MDF claim Budgets WIP
pt-liferay-solutions/liferay-portal pull request #2484
Opened 2022-10-25 13:26 UTC by DiogoNo

2022-10-25 13:26 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-10-25 14:56 UTC, ytuik commented
Just starting reviewing :)

2022-10-25 19:01 UTC, ytuik commented
Just starting reviewing :)

2022-10-26 14:32 UTC, jairmedeiros requested changes

2022-10-26 20:58 UTC, closed without merging