LPS-135247 Adjust to open and use the new fragment and web content at the raylife application.
pt-liferay-solutions/liferay-portal pull request #250
Opened 2021-09-16 19:39 UTC by kevenleone

2021-09-16 19:39 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-09-17 13:23 UTC, silasbsi requested changes
Existem alguns ajustes a serem feitos. Qualquer dúvida posso esclarece-las.

2021-09-17 13:23 UTC, silasbsi commented on modules/apps/site/site-insurance-site-initializer/src/main/resources/com/liferay/site/insurance/site/initializer/internal/dependencies/ddm-templates/quote-card/ddm_template.ftl
> -		width: 215px;
Este bloco foi sobrescrito por engano, ao meu ver.

```
        width: 215px;
	height: 56px;
	transition: background 0.2s;
}
```

2021-09-17 13:23 UTC, silasbsi commented on modules/apps/site/site-insurance-site-initializer/src/main/resources/com/liferay/site/insurance/site/initializer/internal/dependencies/ddm-templates/quote-card/ddm_template.ftl
> -	#quote-comparison #purchase.most-popular:hover {
Este bloco foi sobrescrito por engano, ao meu ver.

```
#quote-comparison #purchase.most-popular:hover {
   background: #295ccc;
   padding: 16px 18px;
}
```

2021-09-17 13:23 UTC, silasbsi commented on modules/apps/site/site-insurance-site-initializer/src/main/resources/com/liferay/site/insurance/site/initializer/internal/dependencies/ddm-templates/quote-card/ddm_template.ftl
> -			<div class="d-flex justify-content-center">
Este trecho do html foi sobrescrito, pois foram feitas modificações no mesmo ponto do código. Sendo assim necessário mesclar as duas soluções.

```
<div class="d-flex justify-content-center">
				<button type="button" id="purchase"
					<#if (mostPopular.getData())?? && mostPopular.getData() != "">
						class="most-popular"
					</#if>
					onclick="event.preventDefault();">PURCHASE THIS POLICY</button>
			</div>
```

2021-09-17 13:23 UTC, silasbsi commented on modules/apps/site/site-insurance-site-initializer/src/main/zippableResources/fragments/raylife/fragments/selected-quote/index.css
> +.quote-comparison H1 {
Recomendo mudar o nome desta classe, por ser o mesmo nome usado no ID da tela anterior a essa. Podendo causar um problema de entendimento em algum dev que no futuro venha a fazer manutenção nas duas telas.

Poderia ser algo do tipo:
```suggestion
.quote-comparison-selected H1 {
```

Após a mudança, favor modificar em todos lugares que utilizarem este mesmo nome dentro do contexto da página que estiver trabalhando.

2021-09-17 13:23 UTC, silasbsi commented on modules/apps/site/site-insurance-site-initializer/src/main/zippableResources/fragments/raylife/fragments/selected-quote/index.html
> +	<div class="quote-application">
Modificar o nome da class para um nome indique a qual escopo ela está sendo aplicada.

Poderia ser algo do tipo:
```suggestion
	<div class="quote-comparison-selected-application">
```
Ajustar também outros pontos que fazem uso desta class.

2021-09-17 13:23 UTC, silasbsi commented on modules/apps/site/site-insurance-site-initializer/src/main/zippableResources/fragments/raylife/fragments/selected-quote/index.html
> +		<b class="content-agent-text-your-application" id="content-agent-text-your-application">APPLICATION #WLM-RNK-ANF</b>
Modificar o nome da class e do ID para um que indique a qual escopo ele está sendo aplicado e ajustar os pontos onde fazem uso deles.

2021-09-17 13:53 UTC, kevenleone commented
@agnosmelo take a look into @silasbsi comments, please

2021-09-20 21:03 UTC, closed without merging