LPS-166832
pt-liferay-solutions/liferay-portal pull request #2518
Opened 2022-10-28 14:23 UTC by joelrocha68

2022-10-28 14:23 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-10-28 14:25 UTC, joelrocha68 commented
ci:test:sf

2022-10-28 14:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/965/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/965/jenkins-report.html">here</a>.</b></p>

2022-10-28 14:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2724a20e90011d514932f6c4a05c37fa1326fe78">2724a20e90011d514932f6c4a05c37fa1326fe78</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joelrocha68/liferay-portal/tree/LPS-166832">LPS-166832</a><br/>Branch GIT ID: <a href="https://github.com/joelrocha68/liferay-portal/commit/4f3e96b4714349fad169b51a28e89646bce07051">4f3e96b4714349fad169b51a28e89646bce07051</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/965/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/965/jenkins-report.html">here</a>.</h5></details></html>

2022-10-28 14:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/965/">test-portal-source-format#965</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/965/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2518">pt-liferay-solutions#2518</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2022066246">[master] ci:test:sf - joelrocha68 &gt; pt-liferay-solutions - PR#2518 - 2022-10-28[07:25:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/3032/">publish-testray-report#3032</a><br/></div></div>

2022-10-28 17:52 UTC, AfonsoHSantos requested changes

2022-10-28 17:52 UTC, AfonsoHSantos commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray-test/src/testFunctional/tests/TestrayTeamAdministrator.testcase
> +				version = "");
Hi @joelrocha68, on this macro, you don't need to use an empty variable. What do you think of use the `isSet` function?

2022-10-31 18:46 UTC, AfonsoHSantos approved these changes

2022-11-01 11:33 UTC, joelrocha68 commented
ci:forward

2022-11-01 11:34 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-11-01 11:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/6410/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6410/jenkins-report.html">here</a>.</b></p>

2022-11-01 11:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/4519/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4519/jenkins-report.html">here</a>.</b></p>

2022-11-01 11:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d09001c4cc3a4e9c121586c6b95384aa820c6235">d09001c4cc3a4e9c121586c6b95384aa820c6235</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joelrocha68/liferay-portal/tree/LPS-166832">LPS-166832</a><br/>Branch GIT ID: <a href="https://github.com/joelrocha68/liferay-portal/commit/ff241a0d3966c8eef0899fe43f6a557871a8774e">ff241a0d3966c8eef0899fe43f6a557871a8774e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/4519/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4519/jenkins-report.html">here</a>.</h5></details></html>

2022-11-01 11:37 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-32.liferay.com/job/test-portal-source-format/4519//consoleFull)

2022-11-01 11:38 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/6410//consoleFull)

2022-11-01 11:38 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/125600
[Console](https://test-1-32.liferay.com/job/test-portal-source-format/4519//consoleFull)

2022-11-01 11:38 UTC, closed without merging

2022-11-01 11:38 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/125601
[Console](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/6410//consoleFull)

2022-11-01 11:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/4519/">test-portal-source-format#4519</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4519/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2518">pt-liferay-solutions#2518</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2027503026">[master] ci:test:sf - joelrocha68 &gt; pt-liferay-solutions - PR#2518 - 2022-11-01[04:34:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/16589/">publish-testray-report#16589</a><br/></div></div>