LPS-162414 [PRM] Create the Dropzone List for the MDF Claim Form
pt-liferay-solutions/liferay-portal pull request #2528
Opened 2022-10-28 20:48 UTC by ytuik

2022-10-31 20:59 UTC, jairmedeiros requested changes

2022-10-31 20:59 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/components/MDFClaimPage/components/ActivityClaimPanel/ActivityClaimPanel.tsx
> +							fieldValue={`activities[${activityIndex}].contents`}
```suggestion
							name={`activities[${activityIndex}].contents`}
```

2022-10-31 20:59 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimForm/components/MDFClaimPage/components/ActivityClaimPanel/ActivityClaimPanel.tsx
> +							files={activity.documents}
```suggestion
							value={activity.documents}
```

2022-10-31 20:59 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/InputMultipleFiles/InputMultipleFiles.tsx
> +	files: File[];
```suggestion
```

2022-10-31 20:59 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/InputMultipleFiles/InputMultipleFiles.tsx
> +		<>
```suggestion
```

2022-10-31 20:59 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/InputMultipleFiles/InputMultipleFiles.tsx
> +		</>
```suggestion
```

2022-10-31 20:59 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/InputMultipleFilesListing/components/ListFiles/ListFiles.tsx
> +			{files?.map((file, index) => (
```suggestion
			{files.map((file, index) => (
```

2022-10-31 20:59 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/InputMultipleFilesListing/components/ListFiles/ListFiles.tsx
> +							{(file.size / 1000).toFixed(2)} Kb
```suggestion
							{(file.size / 1000).toFixed(2)} KB
```

2022-10-31 20:59 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/InputMultipleFilesListing/components/ListFiles/ListFiles.tsx
> +	arrayHelpers: ArrayHelpers;
```suggestion
	arrayHelpers: ArrayHelpers<File>;
```

2022-10-31 20:59 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/InputMultipleFilesListing/InputMultipleFilesListing.tsx
> +	files?: File[];
```suggestion
	files: File[];
```

2022-10-31 20:59 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/InputMultipleFilesListing/InputMultipleFilesListing.tsx
> +	fieldValue: string;
```suggestion
	name: string;
```

2022-10-31 20:59 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/InputMultipleFilesListing/InputMultipleFilesListing.tsx
> +	return (
```suggestion
}: IProps) => (
```

2022-11-01 13:27 UTC, ytuik commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/InputMultipleFilesListing/components/ListFiles/ListFiles.tsx
> +	arrayHelpers: ArrayHelpers;
Infelizmente n funciona colocar a tipagem

2022-11-01 13:29 UTC, ytuik commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/InputMultipleFilesListing/InputMultipleFilesListing.tsx
> +	files?: File[];
por haver a possibilidade do save as draft n ter documento, o file precisa ser opcional

2022-11-01 13:55 UTC, jairmedeiros requested changes

2022-11-01 13:55 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/InputMultipleFilesListing/InputMultipleFilesListing.tsx
> +		<PRMFormik.Array component={ListFiles} files={value} name={name} />
```suggestion
		{value && <PRMFormik.Array component={ListFiles} files={value} name={name} />}
```

2022-11-01 13:55 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/PRMForm/components/fields/InputMultipleFilesListing/InputMultipleFilesListing.tsx
> +		/>
```suggestion
		/>

```

2022-11-01 14:00 UTC, jairmedeiros approved these changes

2022-11-01 14:00 UTC, jairmedeiros commented
ci:forward

2022-11-01 14:00 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-11-01 14:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/4543/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4543/jenkins-report.html">here</a>.</b></p>

2022-11-01 14:03 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2e1381f9732e18b04de4b7dc3a469e54e197217d">2e1381f9732e18b04de4b7dc3a469e54e197217d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ytuik/liferay-portal/tree/LPS-162414-Create-Dropzone-List">LPS-162414-Create-Dropzone-List</a><br/>Branch GIT ID: <a href="https://github.com/ytuik/liferay-portal/commit/b6e2fa41cf4d5dd6755db321e1d5d85d2fe97000">b6e2fa41cf4d5dd6755db321e1d5d85d2fe97000</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/4543/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4543/jenkins-report.html">here</a>.</h5></details></html>

2022-11-01 14:26 UTC, DiogoNo commented
Just starting reviewing :)

2022-11-01 14:49 UTC, jairmedeiros commented
ci:close

2022-11-01 14:49 UTC, closed without merging

2022-11-01 14:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/4543/">test-portal-source-format#4543</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4543/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2528">pt-liferay-solutions#2528</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2027580040">[master] ci:test:sf - ytuik &gt; pt-liferay-solutions - PR#2528 - 2022-11-01[07:00:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/16641/">publish-testray-report#16641</a><br/></div></div>

2022-11-01 15:12 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/6436//consoleFull)

2022-11-01 15:12 UTC, liferay-continuous-integration commented
Closed pull request will not be forwarded.

2022-11-01 18:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/6436/">test-portal-acceptance-pullrequest(master)#6436</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6436/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2528">pt-liferay-solutions#2528</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2027886329">[master] ci:test:relevant - ytuik &gt; pt-liferay-solutions - PR#2528 - 2022-11-01[07:00:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/16680/">publish-testray-report#16680</a><br/></div></div>