LPS-166339 Updated Rest IMPL yup schema and types
pt-liferay-solutions/liferay-portal pull request #2629
Opened 2022-11-09 20:50 UTC by welitonpe

2022-11-09 20:50 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-11-10 13:53 UTC, rafaelfs98 commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/services/rest/TestrayIssues.ts
> +			nestedFields: '',
```suggestion
			
```

2022-11-10 13:55 UTC, rafaelfs98 commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/services/rest/TestrayIssues.ts
> +		const response = await this.getAll(searchUtil.eq('name', name));
```suggestion
		const issuesResponse = await this.getAll(searchUtil.eq('name', name));
```

2022-11-10 13:55 UTC, welitonpe commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/schema/yup.ts
> +	}),
```suggestion
	caseResultIssues: yup.object({
		caseResultId: yup.string(),
		issueId: yup.string(),
		name: yup.string(),
	}),
```

2022-11-10 13:55 UTC, welitonpe commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/services/rest/TestrayCaseResult.ts
> +				?.items.map(({issue}: any) => issue.name) || [];
```suggestion
				?.items.map(({issue}: TestrayIssue) => issue.name) || [];
```

2022-11-10 13:55 UTC, welitonpe commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/services/rest/TestrayCaseResult.ts
> +		}
Need a correct error message.

2022-11-10 13:55 UTC, welitonpe commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/services/rest/TestrayCaseresultsIssues.ts
> +				issue: r_issueToCaseResultsIssues_c_issueId,
Need to change to correct keys
```suggestion
				caseResultId: r_caseResultToCaseResultsIssues_c_caseResultId,
				issueId: r_issueToCaseResultsIssues_c_issueId,
```

2022-11-10 13:55 UTC, welitonpe commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/services/rest/TestrayCaseresultsIssues.ts
> +				};
Need to change to correct keys

```suggestion
			transformData: (caseResultsIssue) => {
				return {
					...caseResultsIssue,
					caseResultId: caseResultsIssue?.r_caseResultToCaseResultsIssues_c_caseResultId
						? {
								...caseResultsIssue.r_caseResultToCaseResultsIssues_c_caseResultId,
						  }
						: undefined,
					issueId: caseResultsIssue?.r_issueToCaseResultsIssues_c_issueId
						? {
								...caseResultsIssue.r_issueToCaseResultsIssues_c_issueId,
						  }
						: undefined,
				};
```

2022-11-10 13:55 UTC, welitonpe commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/services/rest/TestrayIssues.ts
> +			transformData: (issues) => ({...issues}),
Nedd to finish this implementation.

2022-11-10 13:55 UTC, welitonpe commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/services/rest/types.ts
> +};
Need to bring more information
```suggestion
export type TestrayIssue = {
	name: string;
};
```

2022-11-10 14:02 UTC, rafaelfs98 commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/services/rest/TestrayIssues.ts
> +		if ((response?.totalCount ?? 0) > 0) {
```suggestion
		if ((issueResponse?.totalCount ?? 0) > 0) {
```

2022-11-10 14:03 UTC, rafaelfs98 commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/services/rest/TestrayIssues.ts
> +			return response?.items[0];
```suggestion
			return issueResponse?.items[0];
```

2022-11-10 14:03 UTC, rafaelfs98 commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/services/rest/TestrayCaseresultsIssues.ts
> +					caseResult: caseResultsIssue?.r_caseResultToCaseResultsIssues_c_caseResultId
```suggestion
					caseResultId: caseResultsIssue?.r_caseResultToCaseResultsIssues_c_caseResultId
```

2022-11-10 14:04 UTC, rafaelfs98 commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/services/rest/TestrayCaseresultsIssues.ts
> +					issue: caseResultsIssue?.r_issueToCaseResultsIssues_c_issueId
```suggestion
					issueId: caseResultsIssue?.r_issueToCaseResultsIssues_c_issueId
```

2022-11-10 14:07 UTC, rafaelfs98 reviewed
Just starting reviewing :)

2022-11-10 14:27 UTC, samuelleolopes approved these changes

2022-11-14 18:14 UTC, rafaelfs98 approved these changes
LGTM :fire:

2022-11-14 18:44 UTC, samuelleolopes approved these changes

2022-11-14 18:48 UTC, kevenleone requested changes
Good Job @welitonpe 🏎️ 

I left some comments 💯 

The rest looks fine, well done!

2022-11-14 18:48 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/context/AppPropertiesContext.tsx
> +	route: '',
We don't use route

```suggestion
	
```

2022-11-14 18:48 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/context/AppPropertiesContext.tsx
> +type AppContextProviderProps = {children: JSX.Element; properties: any};
Create a Type for Properties

```suggestion
type ApplicationContextProviderProps = {children: JSX.Element; properties: Properties};
```

2022-11-14 18:48 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/context/AppPropertiesContext.tsx
> +export const AppPropertiesContext = createContext(Properties);
Rename file extension to: `ApplicationContextProvider.tsx`

and:

```suggestion
export const ApplicationPropertiesContext = createContext(defaultProperties);
```

2022-11-14 18:48 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/context/AppPropertiesContext.tsx
> +const Properties = {
Should not start with upperCase

```suggestion
const defaultProperties = {
```

2022-11-14 18:48 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/context/AppPropertiesContext.tsx
> +	</AppPropertiesContext.Provider>
```suggestion
	<ApplicationPropertiesContext.Provider value={properties}>
		{children}
	</ApplicationPropertiesContext.Provider>
```

2022-11-14 18:48 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/context/AppPropertiesContext.tsx
> +export default AppContextProvider;
```suggestion
export default ApplicationContextProvider;
```

2022-11-14 18:48 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/context/AppPropertiesContext.tsx
> +const AppContextProvider: React.FC<AppContextProviderProps> = ({
```suggestion
const ApplicationContextProvider: React.FC< ApplicationContextProviderProps> = ({
```

2022-11-14 18:48 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/main.tsx
> +import AppContextProvider from './context/AppPropertiesContext';
```suggestion
import ApplicationContextProvider from './context/ApplicationContextProvider';
```

2022-11-14 18:48 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/main.tsx
> +					</AppContextProvider>
```suggestion
					<ApplicationContextProvider properties={properties}>
						<AccountContextProvider>
							<ClayIconProvider>
								<TestrayRouter />
							</ClayIconProvider>
						</AccountContextProvider>
					</ApplicationContextProvider>
```

2022-11-14 18:48 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Routines/Builds/Inner/CaseResult/CaseResultEditTest.tsx
>  		mutateCaseResult: KeyedMutator<any>;
Add Type to KeyedMutator

```suggestion
		mutateCaseResult: KeyedMutator<TestrayCaseResult>;
```

2022-11-14 18:48 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Routines/Builds/Inner/CaseResult/CaseResultEditTest.tsx
> +	const caseResultIssueList = caseResultsIssues
```suggestion
	const issues = caseResultsIssues
```

2022-11-14 18:48 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Routines/Builds/Inner/CaseResult/CaseResultEditTest.tsx
> +	const caseResultIssueList = caseResultsIssues
Do not use List as name of a List, it's redundant 😸

2022-11-14 18:48 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Routines/Builds/Inner/CaseResult/CaseResultEditTest.tsx
> +		caseResultsIssues,
Add default value to avoid using `?`

```suggestion
		caseResultsIssues = [],
```

2022-11-14 18:48 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Routines/Builds/Inner/CaseResult/CaseResultEditTest.tsx
> +		?.map(
```suggestion
		.map(
```

2022-11-14 18:48 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Routines/Builds/Inner/CaseResult/CaseResultEditTest.tsx
> +					issues: caseResultIssueList,
```suggestion
					issues,
```

2022-11-14 18:48 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Routines/Builds/Inner/CaseResult/index.tsx
> +import {AppPropertiesContext} from '../../../../../../context/AppPropertiesContext';
```suggestion
import {ApplicationPropertiesContext} from '../../../../../../context/ApplicationContextProvider';
```

2022-11-14 21:20 UTC, welitonpe commented
CI:test:sf

2022-11-14 23:22 UTC, kevenleone commented
ci:forward

2022-11-14 23:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/5375/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5375/jenkins-report.html">here</a>.</b></p>

2022-11-14 23:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/3887/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/3887/jenkins-report.html">here</a>.</b></p>

2022-11-14 23:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/64c44d3bc4029fe95db0b1075e02ff52211af987">64c44d3bc4029fe95db0b1075e02ff52211af987</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/LPS-166339">LPS-166339</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/9ff38217f9190aaeec957f6deb74a34f90d5f17b">9ff38217f9190aaeec957f6deb74a34f90d5f17b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/3887/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/3887/jenkins-report.html">here</a>.</h5></details></html>

2022-11-14 23:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/3887/">test-portal-source-format#3887</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/3887/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2629">pt-liferay-solutions#2629</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2054022515">[master] ci:test:sf - welitonpe &gt; pt-liferay-solutions - PR#2629 - 2022-11-14[15:22:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/14587/">publish-testray-report#14587</a><br/></div></div>

2022-11-15 01:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 48 out of 48 jobs passed in 2 hours 13 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/64c44d3bc4029fe95db0b1075e02ff52211af987">64c44d3bc4029fe95db0b1075e02ff52211af987</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c85d411fc2befddfbdb1d7f45a12f0d6df10b1b9">c85d411fc2befddfbdb1d7f45a12f0d6df10b1b9</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2054022568">EE Development Acceptance (master) - 4023 - 2022-11-14[10:06:24]</a></p><details><summary><strong>ci:test:stable - 27 out of 27 jobs PASSED</strong></summary><details><summary><strong>27 Successful Jobs:</strong></summary><ul><li>central-requirements-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/303857/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106955/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/340566/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/322949/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/288851/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106957/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/328193/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/277899/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309722/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/302568/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/168152/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/298759/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106958/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/278362/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/322947/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/288852/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/340565/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/318240/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/288853/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106959/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/328195/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/328194/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/318238/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106953/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/322948/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/273825/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/340561/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 48 out of 48 jobs PASSED</strong></summary><details><summary><strong>48 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/5375/">test-portal-acceptance-pullrequest(master)</a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/303857/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106954/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>empty-temp-dir-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/277900/">empty-temp-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/254743/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106955/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/298758/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/322946/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106956/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/298757/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/277897/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/288850/">functional-upgrade-tomcat90-mysql57-jdk8/0/ [...]

2022-11-15 01:37 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/5375//consoleFull)

2022-11-15 01:37 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/126241
[Console](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/5375//consoleFull)

2022-11-15 01:37 UTC, closed without merging

2022-11-15 01:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/5375/">test-portal-acceptance-pullrequest(master)#5375</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5375/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2629">pt-liferay-solutions#2629</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2054417871">[master] ci:test:relevant - welitonpe &gt; pt-liferay-solutions - PR#2629 - 2022-11-14[15:22:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/13798/">publish-testray-report#13798</a><br/></div></div>