LPS-168193
pt-liferay-solutions/liferay-portal pull request #2675
Opened 2022-11-14 21:29 UTC by eliasantosf

2022-11-14 21:29 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-11-14 21:29 UTC, eliasantosf commented
ci:test:sf

2022-11-14 21:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/1350/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1350/jenkins-report.html">here</a>.</b></p>

2022-11-14 21:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c85d411fc2befddfbdb1d7f45a12f0d6df10b1b9">c85d411fc2befddfbdb1d7f45a12f0d6df10b1b9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eliasantosf/liferay-portal/tree/LPS-168193">LPS-168193</a><br/>Branch GIT ID: <a href="https://github.com/eliasantosf/liferay-portal/commit/feeb0c0b51cafb3c8cc1e494225870218a639fb3">feeb0c0b51cafb3c8cc1e494225870218a639fb3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1350/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1350/jenkins-report.html">here</a>.</h5></details></html>

2022-11-14 21:34 UTC, eliasantosf commented
ci:test:sf

2022-11-14 21:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1350/">test-portal-source-format#1350</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1350/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2675">pt-liferay-solutions#2675</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2053632135">[master] ci:test:sf - eliasantosf &gt; pt-liferay-solutions - PR#2675 - 2022-11-14[13:29:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/5374/">publish-testray-report#5374</a><br/></div></div>

2022-11-14 21:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c85d411fc2befddfbdb1d7f45a12f0d6df10b1b9">c85d411fc2befddfbdb1d7f45a12f0d6df10b1b9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eliasantosf/liferay-portal/tree/LPS-168193">LPS-168193</a><br/>Branch GIT ID: <a href="https://github.com/eliasantosf/liferay-portal/commit/feeb0c0b51cafb3c8cc1e494225870218a639fb3">feeb0c0b51cafb3c8cc1e494225870218a639fb3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1351/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1351/jenkins-report.html">here</a>.</h5></details></html>

2022-11-14 21:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1351/">test-portal-source-format#1351</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1351/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/2675">pt-liferay-solutions#2675</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2053632199">[master] ci:test:sf - eliasantosf &gt; pt-liferay-solutions - PR#2675 - 2022-11-14[13:34:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/5375/">publish-testray-report#5375</a><br/></div></div>

2022-11-16 12:22 UTC, joanagrego commented
Just starting reviewing :)

2022-11-16 12:41 UTC, joanagrego requested changes
Nice job! A added some suggestions :)

2022-11-16 12:41 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/routes/claims/pages/ClaimsTable/index.tsx
> +		r_policyToClaims_c_raylifePolicyId: any;
Is it possible to type it correctly?

2022-11-16 12:41 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/routes/claims/pages/ClaimsTable/index.tsx
> +	}
We have two very similar functions here. What do you think to turn it into a generic one?

2022-11-16 12:41 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/routes/claims/pages/ClaimsTable/index.tsx
> +			const claimList: TableContentType[] | any = [];
Is it possible to type it correctly? Let's try to do not to use the "any" type.

2022-11-17 22:09 UTC, closed without merging