LPS-168725 SF
pt-liferay-solutions/liferay-portal pull request #2790
Opened 2022-11-25 21:17 UTC by Elvinho

2022-11-25 21:17 UTC, Elvinho commented
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-168725 Add info when the original post has changed</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-168725">Add info when the original post has changed</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Story</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>0/3 Completed</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Development</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Elvison Victor</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Lucas Soares</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-169363 Add indexable boolean to MessageBoardMessage</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-169363">Add indexable boolean to MessageBoardMessage</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Peer Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Gleice Lisbino</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Gleice Lisbino</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

11 files changed, 140 insertions(+), 8 deletions(-)

![](https://raw.githubusercontent.com/kevenleone/gh/main/images/looks-good.gif)

2022-11-25 21:17 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-11-28 18:40 UTC, caiosouza15 commented
I think it would be nice to rename the PR like this: LPS [Question] pr title.

2022-11-28 19:02 UTC, kevenleone requested changes
Good job guys, @Elvinho , @gleicelisbino 

@Elvinho I left some suggestions about FE

2022-11-28 19:02 UTC, kevenleone commented on modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/components/Answer.es.js
> +							) : null}
```suggestion
							{answer.hasModified && (
								<span>({Liferay.Language.get('edited')})</span>
							)}
```

2022-11-28 19:02 UTC, kevenleone commented on modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/utils/client.es.js
>  				headline
order

```suggestion
				dateModified
				friendlyUrlPath
				hasModified
				headline
```

2022-11-28 19:02 UTC, kevenleone commented
@joseabelenda can you see the changes in backend?

2022-11-28 20:59 UTC, gleicelisbino commented
Thank you @kevenleone

2022-11-28 21:02 UTC, gleicelisbino commented
@Elvinho Submit only your changes, please. Because the back-end changes need more commits that already send to @joseabelenda @kevenleone

2022-11-30 13:45 UTC, closed without merging