LPS-168338
pt-liferay-solutions/liferay-portal pull request #2811
Opened 2022-11-29 16:40 UTC by juliocezar96

2022-11-29 16:50 UTC, brenobcos commented
Just starting reviewing :)

2022-11-30 12:39 UTC, kevenleone requested changes
The code looks good, but I left suggestions for you according to the created pattern

@juliocezar96

2022-11-30 12:39 UTC, kevenleone commented on modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/components/ActivityQuestionRow.es.js
> +		}
I think we should follow the pattern and create another MESSAGE_TYPE for bestAnswer.

My suggestion is to create: 

```
bestAnswer: {type: 4},
```

```suggestion
		if (question.showAsAnswer) {
			return {
				label: Liferay.Language.get('best-answer'),
				symbol: 'check-circle-full',
				text: stripHTML(question.articleBody).replace(
					MESSAGE_TYPES.answer.prefix,
					''
				),
				type: MESSAGE_TYPES.bestAnswer.type,
			};
		}
```

You need to create a language property for best-answer

2022-11-30 12:39 UTC, kevenleone commented on modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/components/ActivityQuestionRow.es.js
> +						messageType.isBestAnswer,
```suggestion
						messageType.type === MESSAGE_TYPES.bestAnswer.type,
```

2022-11-30 12:39 UTC, kevenleone commented on modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/components/ActivityUI.es.js
> +	messageType: {isBestAnswer, label, symbol, type},
Remove it

```suggestion
	messageType: {label, symbol, type},
```

2022-11-30 12:39 UTC, kevenleone commented on modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/components/ActivityUI.es.js
> +					!isBestAnswer && (
```suggestion
					!type !== MESSAGE_TYPES.bestAnswer.type && (
```

2022-11-30 12:39 UTC, kevenleone commented on modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/components/ActivityUI.es.js
> +								'text-success border border-success': isBestAnswer,
```suggestion
								'questions-reply': type === MESSAGE_TYPES.reply.type,
								'text-success border border-success': type === MESSAGE_TYPES.bestAnswer.type,
```

2022-11-30 12:39 UTC, kevenleone commented on modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/components/ActivityUI.es.js
> +	messageType: {isBestAnswer, symbol, type},
```suggestion
	messageType: {symbol, type},
```

2022-11-30 12:39 UTC, kevenleone commented on modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/components/ActivityUI.es.js
> +				{!isBestAnswer && (
```suggestion
				type !== MESSAGE_TYPES.bestAnswer.type && (
```

2022-11-30 12:39 UTC, kevenleone commented on modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/components/ArticleBodyAnwser.es.js
> +	isBestAnswer = false,
Remove it

```suggestion
	
```

2022-11-30 12:39 UTC, kevenleone commented on modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/components/ArticleBodyAnwser.es.js
> +				{'questions-answer questions-answer-success': isBestAnswer}
```suggestion
				{'questions-answer questions-answer-success': type === MESSAGE_TYPES.bestAnswer.type}
```

2022-11-30 12:39 UTC, kevenleone commented on modules/apps/questions/questions-web/src/main/resources/META-INF/resources/js/utils/client.es.js
> +				}
I didn't found this parentMessageBoardMessage being used, this is needed?

2022-11-30 18:30 UTC, kevenleone commented
Just starting reviewing :)

2022-12-01 17:24 UTC, kevenleone commented
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/2832

2022-12-01 17:24 UTC, closed without merging