Added edit button to MDF Request Listing
pt-liferay-solutions/liferay-portal pull request #2955
Opened 2022-12-16 20:32 UTC by Elvinho

2022-12-16 20:32 UTC, Elvinho commented
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

3 files changed, 73 insertions(+), 37 deletions(-)

![](https://raw.githubusercontent.com/kevenleone/gh/main/images/looks-good.gif)

2022-12-16 20:32 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-12-19 18:13 UTC, jairmedeiros requested changes

2022-12-19 18:13 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestList/utils/getMDFListColumns.tsx
> +				}
Melhor evitar usar a posicao como criterio de condicao

2022-12-19 18:13 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/components/Dropdown/Dropdown.tsx
> +		);
Acho que eh possivel usar outra logica para evitar o null

2022-12-20 11:53 UTC, closed without merging