LPS-171434 Fixed MDF Dashlet doesn't support long characters
pt-liferay-solutions/liferay-portal pull request #3012
Opened 2022-12-29 12:15 UTC by Elvinho

2022-12-29 12:16 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-12-29 14:50 UTC, jairmedeiros requested changes

2022-12-29 14:50 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/dashboard-collection/common/components/container/index.js
> +					<div className={`${positionButton ? 'd-flex' : ''}`}>
```suggestion
					<div className={classnames({
					  positionButton: 'd-flex'
					})}>
```

Eh interessante usarmos a lib do classnames.

2022-12-29 14:50 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/dashboard-collection/common/components/donut-chart/index.js
> +							title: ' ',
```suggestion
```

2022-12-29 14:50 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/dashboard-collection/common/components/donut-chart/index.js
> +	const chartTitle = `${title[1]} ${title[2]}`;
Ao inves do split, melhor receber o valueChart e chartTitle como props. Melhor evitar manipulacao das string que sao dinamicas e podem mudar

2022-12-29 14:50 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/dashboard-collection/common/components/container/index.js
> +						</div>
Eh interessante usarmos a lib do classnames.

2022-12-29 18:07 UTC, Elvinho commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/dashboard-collection/common/components/container/index.js
> +					<div className={`${positionButton ? 'd-flex' : ''}`}>
adicionado lib classNames

2022-12-29 18:07 UTC, Elvinho commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/dashboard-collection/common/components/donut-chart/index.js
> +	const chartTitle = `${title[1]} ${title[2]}`;
incluido prop chartValue

2023-01-03 14:39 UTC, JoMaAlves approved these changes
LGTM ​🦖​🌋​ 
Thank you @Elvinho

2023-01-03 14:39 UTC, JoMaAlves commented
ci:test:sf

2023-01-03 14:39 UTC, JoMaAlves commented
ci:forward

2023-01-03 14:39 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-01-03 14:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/7649/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7649/jenkins-report.html">here</a>.</b></p>

2023-01-03 14:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/4423/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4423/jenkins-report.html">here</a>.</b></p>

2023-01-03 14:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/951449dc2f2b7bd22d223aa3d887f74b20ee6434">951449dc2f2b7bd22d223aa3d887f74b20ee6434</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Elvinho/liferay-portal/tree/LPS-171434">LPS-171434</a><br/>Branch GIT ID: <a href="https://github.com/Elvinho/liferay-portal/commit/639fba6e43530a18eb40d9b6dd6d41b0be6ecf20">639fba6e43530a18eb40d9b6dd6d41b0be6ecf20</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/3537/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3537/jenkins-report.html">here</a>.</h5></details></html>

2023-01-03 14:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/951449dc2f2b7bd22d223aa3d887f74b20ee6434">951449dc2f2b7bd22d223aa3d887f74b20ee6434</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Elvinho/liferay-portal/tree/LPS-171434">LPS-171434</a><br/>Branch GIT ID: <a href="https://github.com/Elvinho/liferay-portal/commit/639fba6e43530a18eb40d9b6dd6d41b0be6ecf20">639fba6e43530a18eb40d9b6dd6d41b0be6ecf20</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/4423/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4423/jenkins-report.html">here</a>.</h5></details></html>

2023-01-03 15:52 UTC, liferay-continuous-integration commented
<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 48 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

Target exception: org.json.JSONException: JSONObject["testrayBuildId"] is not a int.
</code></pre><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/951449dc2f2b7bd22d223aa3d887f74b20ee6434">951449dc2f2b7bd22d223aa3d887f74b20ee6434</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/7649/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7649/jenkins-report.html">here</a>.</b></p>

2023-01-03 15:52 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/7649//consoleFull)

2023-01-03 15:52 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/128295
[Console](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/7649//consoleFull)

2023-01-03 15:52 UTC, closed without merging

2023-01-03 19:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/7649/">test-portal-acceptance-pullrequest(master)#7649</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7649/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3012">pt-liferay-solutions#3012</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2147502296">[master] ci:test:relevant - Elvinho &gt; pt-liferay-solutions - PR#3012 - 2023-01-03[06:39:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-1.liferay.com/job/publish-testray-report/17563/">publish-testray-report#17563</a><br/></div></div>

2023-01-03 19:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/4423/">test-portal-source-format#4423</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4423/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3012">pt-liferay-solutions#3012</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2147501596">[master] ci:test:sf - Elvinho &gt; pt-liferay-solutions - PR#3012 - 2023-01-03[06:39:51]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-19.liferay.com/job/publish-testray-report/3080/">publish-testray-report#3080</a><br/></div></div>

2023-01-03 20:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/3537/">test-portal-source-format#3537</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3537/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3012">pt-liferay-solutions#3012</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2147501580">[master] ci:test:sf - Elvinho &gt; pt-liferay-solutions - PR#3012 - 2023-01-03[06:39:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-7.liferay.com/job/publish-testray-report/2461/">publish-testray-report#2461</a><br/></div></div>