LPS-172458
pt-liferay-solutions/liferay-portal pull request #3086
Opened 2023-01-12 20:59 UTC by juliosilveira77

2023-01-12 20:59 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-01-12 21:07 UTC, juliosilveira77 commented
ci:test:sf

2023-01-12 21:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/4045/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4045/jenkins-report.html">here</a>.</b></p>

2023-01-12 21:11 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f7d0be51f4bf94f86b2d26116252233906761bdd">f7d0be51f4bf94f86b2d26116252233906761bdd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliosilveira77/liferay-portal/tree/LPS-172458">LPS-172458</a><br/>Branch GIT ID: <a href="https://github.com/juliosilveira77/liferay-portal/commit/a0a9ae58125994d847eb6655c27ca09cc14f0c0f">a0a9ae58125994d847eb6655c27ca09cc14f0c0f</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4045/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4045/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMHomePage.testcase expected:&lt;...is a test for LPS-17[2458. User can access Deal Registration Listing through Quick Links"
     [java]   @priority = "4"
     [java]   test CanAccessDealListingViaQuickLinks \{
     [java]     task ("When I click on 'MDF' button, on Quick Links section") \{
     [java]       PRMHomePage.gotoQuickLinksOption(
     [java]         buttonLink = "deal-registrations",
     [java]         buttonText = "Deal Registration");
     [java]     \}
     [java] 
     [java]     task ("Then I'm redirected to the 'MDF Request Listing' page") \{
     [java]       PRMPages.assertPageTitle(pageTitle = "Partner Deal Registration");
     [java]     \}
     [java]   \}
     [java] 
     [java]   @description = "This is a test for LPS-171642. User can access MDF Request Listing through Quick Links"
     [java]   @priority = "4"
     [java]   test CanAccessMDFRequestListingViaQuickLinks \{
     [java]     task ("When I click on 'MDF' button, on Quick Links section") \{
     [java]       PRMHomePage.gotoQuickLinksOption(
     [java]         buttonLink = "mdf-requests",
     [java]         buttonText = "MDF");
     [java]     \}
     [java] 
     [java]     task ("Then I'm redirected to the 'MDF Request Listing' page") \{
     [java]       PRMPages.assertPageTitle(pageTitle = "MDF Requests");
     [java]     \}
     [java]   \}]
     [java] 
     [java] \}&gt; but was:&lt;...is a test for LPS-17[1642. User can access MDF Request Listing through Quick Links"
     [java]   @priority = "4"
     [java]   test CanAccessMDFRequestListingViaQuickLinks \{
     [java]     task ("When I click on 'MDF' button, on Quick Links section") \{
     [java]       PRMHomePage.gotoQuickLinksOption(
     [java]         buttonLink = "mdf-requests",
     [java]         buttonText = "MDF");
     [java]     \}
     [java] 
     [java]     task ("Then I'm redirected to the 'MDF Request Listing' page") \{
     [java]       PRMPages.assertPageTitle(pageTitle = "MDF Requests");
     [java]     \}
     [java]   \}
     [java] 
     [java]  @description = "This is a test for LPS-172458. User can access Deal Registration Listing through Quick Links"
     [java]     @priority = "4"
     [java]     test CanAccessDealListingViaQuickLinks \{
     [java]     task ("When I click on 'MDF' button, on Quick Links section") \{</pre></details></html>

2023-01-12 21:15 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4045/">test-portal-source-format#4045</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4045/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3086">pt-liferay-solutions#3086</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2159886154">[master] ci:test:sf - juliosilveira77 &gt; pt-liferay-solutions - PR#3086 - 2023-01-12[13:08:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/3128/">publish-testray-report#3128</a><br/></div></div>

2023-01-12 21:27 UTC, juliosilveira77 commented
ci:test:sf

2023-01-12 21:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/4068/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4068/jenkins-report.html">here</a>.</b></p>

2023-01-12 21:31 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f7d0be51f4bf94f86b2d26116252233906761bdd">f7d0be51f4bf94f86b2d26116252233906761bdd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliosilveira77/liferay-portal/tree/LPS-172458">LPS-172458</a><br/>Branch GIT ID: <a href="https://github.com/juliosilveira77/liferay-portal/commit/64e17d26e9ac3e674f723c9b672960dcb8eaa8c4">64e17d26e9ac3e674f723c9b672960dcb8eaa8c4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4068/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4068/jenkins-report.html">here</a>.</h5></details></html>

2023-01-12 21:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4068/">test-portal-source-format#4068</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4068/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3086">pt-liferay-solutions#3086</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2159894217">[master] ci:test:sf - juliosilveira77 &gt; pt-liferay-solutions - PR#3086 - 2023-01-12[13:28:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/14843/">publish-testray-report#14843</a><br/></div></div>

2023-01-13 18:49 UTC, AfonsoHSantos requested changes

2023-01-13 18:49 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMHomePage.testcase
> +		task ("When I click on 'MDF' button, on Quick Links section") {
Hi @juliosilveira77, could you please rename this task to: "When I click on 'Deal Registration' button, on Quick Links section"?

2023-01-13 18:49 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMHomePage.testcase
> +			PRMPages.assertPageTitle(pageTitle = "Partner Deal Registration");
Hi @juliosilveira77, could you please rename this task to: "Then I'm redirected to the 'Deal Registration Listing' page"?

2023-01-13 21:53 UTC, juliosilveira77 commented
ci:test:sf

2023-01-13 21:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/4778/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4778/jenkins-report.html">here</a>.</b></p>

2023-01-13 21:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2e90975de71d444bca6598ccb242d80ef66aba5f">2e90975de71d444bca6598ccb242d80ef66aba5f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliosilveira77/liferay-portal/tree/LPS-172458">LPS-172458</a><br/>Branch GIT ID: <a href="https://github.com/juliosilveira77/liferay-portal/commit/92bbcc096823fb1b4ea9c9e73b8773aac2975137">92bbcc096823fb1b4ea9c9e73b8773aac2975137</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/4778/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4778/jenkins-report.html">here</a>.</h5></details></html>

2023-01-13 22:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/4778/">test-portal-source-format#4778</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4778/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3086">pt-liferay-solutions#3086</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2161369651">[master] ci:test:sf - juliosilveira77 &gt; pt-liferay-solutions - PR#3086 - 2023-01-13[13:54:04]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/18281/">publish-testray-report#18281</a><br/></div></div>

2023-01-16 12:40 UTC, juliosilveira77 commented
ci:test:sf

2023-01-16 12:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/6657/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6657/jenkins-report.html">here</a>.</b></p>

2023-01-16 17:22 UTC, AfonsoHSantos commented
Hi @juliosilveira77,I see that you have some duplicated commits, that aren't necessary. Could you please do a git reset e redo your commits? Thanks!

2023-01-16 17:32 UTC, juliosilveira77 commented
ci:test:sf

2023-01-16 17:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/3556/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3556/jenkins-report.html">here</a>.</b></p>

2023-01-16 17:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/923f924efd027680f0669216761d55546f07a9b0">923f924efd027680f0669216761d55546f07a9b0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliosilveira77/liferay-portal/tree/LPS-172458">LPS-172458</a><br/>Branch GIT ID: <a href="https://github.com/juliosilveira77/liferay-portal/commit/a688e74afda92d5ea89f515fc53620bcaf1f8e4a">a688e74afda92d5ea89f515fc53620bcaf1f8e4a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3556/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3556/jenkins-report.html">here</a>.</h5></details></html>

2023-01-16 17:42 UTC, AfonsoHSantos commented
ci:forward

2023-01-16 17:42 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-01-16 17:43 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-39.liferay.com/job/forward-pullrequest/233//consoleFull)

2023-01-16 17:43 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/128830
[Console](https://test-1-39.liferay.com/job/forward-pullrequest/233//consoleFull)

2023-01-16 17:43 UTC, closed without merging