LPS-172414
pt-liferay-solutions/liferay-portal pull request #3088
Opened 2023-01-13 15:04 UTC by eduardo-diniz

2023-01-13 15:09 UTC, eduardo-diniz commented
ci:test:sf

2023-01-13 15:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-source-format/6066/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6066/jenkins-report.html">here</a>.</b></p>

2023-01-13 15:14 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/19ed53589d68a9fe9743c3c83dce62a91aee02e0">19ed53589d68a9fe9743c3c83dce62a91aee02e0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eduardo-diniz/liferay-portal/tree/LPS-172414">LPS-172414</a><br/>Branch GIT ID: <a href="https://github.com/eduardo-diniz/liferay-portal/commit/69d0c6cf6e159c730fbb5b88c7cb2f55fe679af9">69d0c6cf6e159c730fbb5b88c7cb2f55fe679af9</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-source-format/6066/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6066/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/routes/policies/pages/components/PolicyDetail/index.scss expected:&lt;...data-panel-hide \{
     [java]     [align-items: center;
     [java]     justify-content: center;
     [java]     margin-top: 13px;
     [java]   \}
     [java] 
     [java]   .history-detail-border \{
     [java]     border-bottom-left-radius: 8px;
     [java]     border-bottom-right-radius: 8px;
     [java]     height: 100%;
     [java]     position: relative;
     [java]   \}
     [java] 
     [java]   .gsdc-panel::after \{
     [java]     background-image: linear-gradient(
     [java]       to right,
     [java]       #aaa 0%,
     [java]       #aaa 20%,
     [java]       transparent 20%
     [java]     );
     [java]     background-position: 0 0;
     [java]     background-repeat: repeat-x;
     [java]     background-size: 6px 1px;
     [java]     bottom: 0;
     [java]     box-sizing: border-box;
     [java]     content: '';
     [java]     height: 1px;
     [java]     left: 0;
     [java]     position: absolute;
     [java]     right: 0;
     [java]   \}
     [java] 
     [java]   .box \{
     [java]     max-height: 0px;
     [java]     opacity: 0;
     [java]     padding-bottom: 5px;
     [java]     transition: all 0.5s;
     [java]   \}
     [java] 
     [java]   .box.show-box \{
     [java]     max-height: 300px;
     [java]     opacity: 1;
     [java]     transition: all 0.5s;
     [java]   \}
     [java] 
     [java]   .button-panel:focus \{
     [java]     align-items: flex-start;
     [java]     color: #4c84ff;
     [java]   \}
     [java] 
     [java]   .button-panel \{
     [java]     padding: 0px;
     [java]   \}
     [java] 
     [java]   @media screen and (max-width: 700px) \{
     [java]     .layout-show-details \{
     [java]       display: flex !important;
     [java]       flex-wrap: wrap !important;
     [java]       float: none !important;
     [java]       width: auto !important;
     [java]     \}
     [java]   \}
     [java]   @media screen and (max-width: 700px) \{
     [java]     .history-detail-border \{
     [java]       display: flex !important;
     [java]       flex-wrap: wrap !important;
     [java]       float: none !important;
     [java]       width: auto !important;
     [java]     \}
     [java]   \}
     [java]   @media screen and (max-width: 700px) \{
     [java]     .layout-panel \{
     [java]       display: flex !important;
     [java]       flex-wrap: wrap !important;
     [java]       float: none !important;</pre></details></html>

2023-01-13 15:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-17.liferay.com/job/test-portal-source-format/6066/">test-portal-source-format#6066</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6066/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3088">pt-liferay-solutions#3088</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2161088078">[master] ci:test:sf - eduardo-diniz &gt; pt-liferay-solutions - PR#3088 - 2023-01-13[07:10:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-17.liferay.com/job/publish-testray-report/2845/">publish-testray-report#2845</a><br/></div></div>

2023-01-13 16:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/3631/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3631/jenkins-report.html">here</a>.</b></p>

2023-01-13 16:06 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/19ed53589d68a9fe9743c3c83dce62a91aee02e0">19ed53589d68a9fe9743c3c83dce62a91aee02e0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eduardo-diniz/liferay-portal/tree/LPS-172414">LPS-172414</a><br/>Branch GIT ID: <a href="https://github.com/eduardo-diniz/liferay-portal/commit/e2701565331d3e8ac6172519909068b6c0d79dbc">e2701565331d3e8ac6172519909068b6c0d79dbc</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/3631/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3631/jenkins-report.html">here</a>.</h5></details></html>

2023-01-13 16:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/3631/">test-portal-source-format#3631</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3631/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3088">pt-liferay-solutions#3088</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2161092398">[master] ci:test:sf - eduardo-diniz &gt; pt-liferay-solutions - PR#3088 - 2023-01-13[08:03:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/12702/">publish-testray-report#12702</a><br/></div></div>

2023-01-13 19:01 UTC, silasbsi requested changes
I added some suggestions.

2023-01-16 13:34 UTC, eduardo-diniz commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/routes/policies/pages/components/PolicyDetail/index.tsx
> +							curentVehicle: PolicyDetailsType,
Done!
Thanks!

2023-01-16 13:50 UTC, closed without merging