PRM Automated Test - LPS-171791  | master
pt-liferay-solutions/liferay-portal pull request #3121
Opened 2023-01-18 20:22 UTC by heiditrindade

[LPS-171791](https://issues.liferay.com/browse/LPS-171791)

2023-01-18 20:24 UTC, heiditrindade commented
ci:test:sf

2023-01-18 20:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/4836/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4836/jenkins-report.html">here</a>.</b></p>

2023-01-18 20:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/227ee819dfe37359878f5b4099455bcc59b66618">227ee819dfe37359878f5b4099455bcc59b66618</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/heiditrindade/liferay-portal/tree/LPS-171791">LPS-171791</a><br/>Branch GIT ID: <a href="https://github.com/heiditrindade/liferay-portal/commit/b9319bdb32ee79c7231bacee108d7ca3881c1d66">b9319bdb32ee79c7231bacee108d7ca3881c1d66</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/4836/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4836/jenkins-report.html">here</a>.</h5></details></html>

2023-01-18 20:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/4836/">test-portal-source-format#4836</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4836/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3121">pt-liferay-solutions#3121</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2165352164">[master] ci:test:sf - heiditrindade &gt; pt-liferay-solutions - PR#3121 - 2023-01-18[12:24:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/18548/">publish-testray-report#18548</a><br/></div></div>

2023-01-18 20:39 UTC, AfonsoHSantos requested changes

2023-01-18 20:39 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMSalesPage.testcase
> +		}
Hi @heiditrindade, this task could be a 'When', since you are doing an action that you result on the action that you expect on the 'Then' task.

2023-01-19 17:29 UTC, AfonsoHSantos commented
Hi @heiditrindade, thanks for working on it. The code looks good to me!
I'm forwading it!

2023-01-19 17:30 UTC, AfonsoHSantos commented
ci:forward

2023-01-19 17:30 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-01-19 17:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/7117/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7117/jenkins-report.html">here</a>.</b></p>

2023-01-19 17:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/1543/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1543/jenkins-report.html">here</a>.</b></p>

2023-01-19 17:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0005f7933515c08392cecc6c7dd75d523d8a4bb6">0005f7933515c08392cecc6c7dd75d523d8a4bb6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/heiditrindade/liferay-portal/tree/LPS-171791">LPS-171791</a><br/>Branch GIT ID: <a href="https://github.com/heiditrindade/liferay-portal/commit/8c7c2583b9ef81cdfa4df4e5874d04181eb9c5a3">8c7c2583b9ef81cdfa4df4e5874d04181eb9c5a3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1543/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1543/jenkins-report.html">here</a>.</h5></details></html>

2023-01-19 17:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1543/">test-portal-source-format#1543</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1543/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3121">pt-liferay-solutions#3121</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2166542656">[master] ci:test:sf - heiditrindade &gt; pt-liferay-solutions - PR#3121 - 2023-01-19[09:30:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/6212/">publish-testray-report#6212</a><br/></div></div>

2023-01-19 18:57 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/7117//consoleFull)

2023-01-19 18:58 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/129014
[Console](https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/7117//consoleFull)

2023-01-19 18:58 UTC, closed without merging

2023-01-19 19:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/7117/">test-portal-acceptance-pullrequest(master)#7117</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7117/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3121">pt-liferay-solutions#3121</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2166598023">[master] ci:test:relevant - heiditrindade &gt; pt-liferay-solutions - PR#3121 - 2023-01-19[09:30:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/17161/">publish-testray-report#17161</a><br/></div></div>