LPS-172957
pt-liferay-solutions/liferay-portal pull request #3179
Opened 2023-01-26 15:37 UTC by marinaasant0s

2023-01-26 15:37 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-01-26 15:37 UTC, marinaasant0s commented
ci:test:sf

2023-01-26 16:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/4056/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4056/jenkins-report.html">here</a>.</b></p>

2023-01-26 16:05 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 14 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9eb5b88373f6a7e8d1ea7365f197ae901c65f00f">9eb5b88373f6a7e8d1ea7365f197ae901c65f00f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marinaasant0s/liferay-portal/tree/LPS-172957">LPS-172957</a><br/>Branch GIT ID: <a href="https://github.com/marinaasant0s/liferay-portal/commit/6fb4e360eb258ae841773de4920db501defe89c4">6fb4e360eb258ae841773de4920db501defe89c4</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4056/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4056/jenkins-report.html">here</a>.</h5><pre>     [java] Caused by: java.lang.RuntimeException: Unable to format ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor._performTask(BaseSourceProcessor.java:717)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.access\$000(BaseSourceProcessor.java:77)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor\$1.call(BaseSourceProcessor.java:109)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor\$1.call(BaseSourceProcessor.java:105)
     [java]   ... 4 more
     [java] Caused by: java.lang.Exception
     [java]   at com.liferay.poshi.core.script.PoshiScriptParserException.throwExceptions(PoshiScriptParserException.java:79)
     [java]   at com.liferay.source.formatter.processor.PoshiSourceProcessor.parse(PoshiSourceProcessor.java:126)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.format(BaseSourceProcessor.java:313)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.format(BaseSourceProcessor.java:357)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.format(BaseSourceProcessor.java:276)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor._format(BaseSourceProcessor.java:603)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor._performTask(BaseSourceProcessor.java:705)
     [java]   ... 7 more
[stopwatch] [run.batch.test.action: 1:52.160 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:596: Java returned: 1
      [get] Getting: http://test-1-15/job/test-portal-source-format/4056//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230126080122917.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230126080122917.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1045958331.properties</pre></details></html>

2023-01-26 16:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4056/">test-portal-source-format#4056</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4056/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3179">pt-liferay-solutions#3179</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2174609819">[master] ci:test:sf - marinaasant0s &gt; pt-liferay-solutions - PR#3179 - 2023-01-26[07:50:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/3160/">publish-testray-report#3160</a><br/></div></div>

2023-01-26 17:06 UTC, marinaasant0s commented
ci:test:sf

2023-01-26 17:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/1567/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1567/jenkins-report.html">here</a>.</b></p>

2023-01-26 17:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1a66535412f4c9633ff0f9661e3b4b0389fe662e">1a66535412f4c9633ff0f9661e3b4b0389fe662e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marinaasant0s/liferay-portal/tree/LPS-172957">LPS-172957</a><br/>Branch GIT ID: <a href="https://github.com/marinaasant0s/liferay-portal/commit/7afede1f51a7add6a51e842728900243ff910167">7afede1f51a7add6a51e842728900243ff910167</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1567/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1567/jenkins-report.html">here</a>.</h5></details></html>

2023-01-26 17:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1567/">test-portal-source-format#1567</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1567/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3179">pt-liferay-solutions#3179</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2174772997">[master] ci:test:sf - marinaasant0s &gt; pt-liferay-solutions - PR#3179 - 2023-01-26[09:07:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/6308/">publish-testray-report#6308</a><br/></div></div>

2023-01-26 18:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/4632/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4632/jenkins-report.html">here</a>.</b></p>

2023-01-26 18:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/4632/">test-portal-source-format#4632</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4632/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3179">pt-liferay-solutions#3179</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2174880847">[master] ci:test:sf - marinaasant0s &gt; pt-liferay-solutions - PR#3179 - 2023-01-26[10:09:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/17457/">publish-testray-report#17457</a><br/></div></div>

2023-01-26 19:31 UTC, AfonsoHSantos requested changes

2023-01-26 19:31 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMarketing.macro
> +	@summary = "Verify the activity fills made by the user"
Hi @marinaasant0s, could you please update this summary to: "View the activity information on MDF Review Page"?

2023-01-26 19:31 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMarketing.macro
> +	@summary = "Verify the fills done by the user on the Campaign Information"
Hi @marinaasant0s, could you please update this summary to: "View the goals information on MDF Review Page

2023-01-26 19:31 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMarketing.macro
> +	macro viewMDFContent {
Hi @marinaasant0s, could you please rename this macro to: "viewMDFGoals"?

2023-01-26 19:31 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +		}
Hi @marinaasant0s, isn't necessary a task for this variable definitions. It should be before the previous task also.

2023-01-26 19:31 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +		task ("Then you get the appropriate results") {
Hi @marinaasant0s, could you please update this task to: "When I fill all fields from MDF Request"

2023-01-26 19:31 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +		task ("And verify that all the filled in fields are present") {
Hi @marinaasant0s, could you please update this task to: "Then all inputted information are displayed on Review Page"

2023-01-26 19:31 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +			Button.click(button = "Submit");
Hi @marinaasant0s, isn't necessary to submit the MDF

2023-01-26 20:15 UTC, marinaasant0s commented
ci:test:sf

2023-01-26 20:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3953/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3953/jenkins-report.html">here</a>.</b></p>

2023-01-26 20:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4444188757b32588356b95ec460f7ebadae6379b">4444188757b32588356b95ec460f7ebadae6379b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marinaasant0s/liferay-portal/tree/LPS-172957">LPS-172957</a><br/>Branch GIT ID: <a href="https://github.com/marinaasant0s/liferay-portal/commit/a2df5771d1ff2315313ea8562b909f038797e2f0">a2df5771d1ff2315313ea8562b909f038797e2f0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3953/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3953/jenkins-report.html">here</a>.</h5></details></html>

2023-01-26 22:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3953/">test-portal-source-format#3953</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3953/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3179">pt-liferay-solutions#3179</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2175140287">[master] ci:test:sf - marinaasant0s &gt; pt-liferay-solutions - PR#3179 - 2023-01-26[12:15:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/14763/">publish-testray-report#14763</a><br/></div></div>

2023-01-27 12:47 UTC, AfonsoHSantos commented
Hi @marinaasant0s, thanks for working on it. The code looks good to me! I'm forwarding it.

![giphy](https://user-images.githubusercontent.com/69267630/215090458-c6dc6727-731c-4e76-89f4-61f8190c5c84.gif)

2023-01-27 12:47 UTC, AfonsoHSantos commented
ci:forward

2023-01-27 12:47 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2023-01-27 16:13 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-12.liferay.com/job/forward-pullrequest/378//consoleFull)

2023-01-27 16:13 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/129347
[Console](https://test-1-12.liferay.com/job/forward-pullrequest/378//consoleFull)

2023-01-27 16:13 UTC, closed without merging