LPS-173539
pt-liferay-solutions/liferay-portal pull request #3228
Opened 2023-02-03 21:11 UTC by mateussandes23

2023-02-03 21:11 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-02-03 21:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/6701/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6701/jenkins-report.html">here</a>.</b></p>

2023-02-03 21:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/68f60a19687524dc689f2432ac8d070e2649fbde">68f60a19687524dc689f2432ac8d070e2649fbde</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-173539">LPS-173539</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/718be86d2205be2a2fef02250f2a39dea3131ddf">718be86d2205be2a2fef02250f2a39dea3131ddf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/6701/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6701/jenkins-report.html">here</a>.</h5></details></html>

2023-02-03 21:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/6701/">test-portal-source-format#6701</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6701/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3228">pt-liferay-solutions#3228</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2185427890">[master] ci:test:sf - mateussandes23 &gt; pt-liferay-solutions - PR#3228 - 2023-02-03[13:12:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/2750/">publish-testray-report#2750</a><br/></div></div>

2023-02-07 18:03 UTC, AfonsoHSantos requested changes

2023-02-07 18:03 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +		task ("Add Maneger Channel role to the user") {
Hi @mateussandes23, just a typo here. Could you please replace 'Maneger' for 'Manager'? Thanks!

2023-02-07 18:03 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +				rowNumber = "Status");
Hi @mateussandes23, here you are changing an existing test. You should add a new one.

2023-02-07 18:13 UTC, AfonsoHSantos requested changes

2023-02-07 18:13 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFRequest.macro
> +		var key_mdfName = "${mdfName}";
hi @mateussandes23, could you please replace the variable `mdfName` for `MDFName`? Thanks!

2023-02-07 18:13 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFRequest.macro
> +
Hi @mateussandes23, I think that this path doesn't exist. Could you please double check?

2023-02-07 18:13 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFRequest.macro
> +
Also, I need that you create a separated macro to enter on MDF. 
This macro should be only to change the MDF status.

2023-02-07 18:55 UTC, mateussandes23 commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFListing.macro
> +	}
Working on it

2023-02-09 20:27 UTC, mateussandes23 commented
ci:test:sf

2023-02-09 20:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/5198/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5198/jenkins-report.html">here</a>.</b></p>

2023-02-09 20:31 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b38777bdf00d43dcb9d978655717a3c5886179e1">b38777bdf00d43dcb9d978655717a3c5886179e1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-173539">LPS-173539</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/30c037dde41614b15537c9f2f682ce1a50fcb52c">30c037dde41614b15537c9f2f682ce1a50fcb52c</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/5198/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5198/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found formatting issues:
     [java] At least one commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, ISSITES, LCD, LHC, LOOP, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin ci.properties in the liferay-portal repository.
     [java]   at com.liferay.source.formatter.util.JIRAUtil.validateJIRAProjectNames(JIRAUtil.java:66)
     [java]   at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1278)
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:322)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:286)
[stopwatch] [run.batch.test.action: 53.988 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:596: Java returned: 1
      [get] Getting: http://test-1-37/job/test-portal-source-format/5198//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230209123052477.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230209123052477.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null213125431.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null989759982
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 148ms
[junitreport] Deleting: /tmp/null989759982
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results</pre></details></html>

2023-02-09 20:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/5198/">test-portal-source-format#5198</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5198/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3228">pt-liferay-solutions#3228</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2191491076">[master] ci:test:sf - mateussandes23 &gt; pt-liferay-solutions - PR#3228 - 2023-02-09[12:27:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/20001/">publish-testray-report#20001</a><br/></div></div>

2023-02-10 17:37 UTC, mateussandes23 commented
ci:test:sf

2023-02-10 17:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/5223/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5223/jenkins-report.html">here</a>.</b></p>

2023-02-10 17:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d48b4c356269b67c7c07fc44abf49cc4377b51b4">d48b4c356269b67c7c07fc44abf49cc4377b51b4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-173539">LPS-173539</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/c35844bf46895e0ecd7769bfdd28820a8c9eb2da">c35844bf46895e0ecd7769bfdd28820a8c9eb2da</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/5223/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5223/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found formatting issues:
     [java] At least one commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, ISSITES, LCD, LHC, LOOP, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin ci.properties in the liferay-portal repository.
     [java]   at com.liferay.source.formatter.util.JIRAUtil.validateJIRAProjectNames(JIRAUtil.java:66)
     [java]   at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1278)
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:322)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:286)
[stopwatch] [run.batch.test.action: 52.507 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:596: Java returned: 1
      [get] Getting: http://test-1-37/job/test-portal-source-format/5223//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230210094043945.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230210094043945.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null798419001.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null347804158
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 173ms
[junitreport] Deleting: /tmp/null347804158
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results</pre></details></html>

2023-02-10 17:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/5223/">test-portal-source-format#5223</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5223/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3228">pt-liferay-solutions#3228</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2192920445">[master] ci:test:sf - mateussandes23 &gt; pt-liferay-solutions - PR#3228 - 2023-02-10[09:38:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/20082/">publish-testray-report#20082</a><br/></div></div>

2023-02-10 17:59 UTC, mateussandes23 commented
ci:test:sf

2023-02-10 18:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/5595/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5595/jenkins-report.html">here</a>.</b></p>

2023-02-10 18:03 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d48b4c356269b67c7c07fc44abf49cc4377b51b4">d48b4c356269b67c7c07fc44abf49cc4377b51b4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-173539">LPS-173539</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/6a24ba10bdb05293ed038aa806c2a35a2e43a591">6a24ba10bdb05293ed038aa806c2a35a2e43a591</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/5595/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5595/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 5 formatting issues:
     [java] 1: Variable 'MDFStatus' in 'SubmittedMDFAppearsOnListing' should start with a lowercase letter: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase (SourceCheck:PoshiVariableNameCheck)
     [java] 2: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFListing.macro expected:&lt;...    var key_rowName = [\$\{key_rowNumber\};
     [java] 
     [java]     if (\$\{rowNumber\} == "Request ID") \{
     [java]       AssertVisible(
     [java]         key_rowNumber = "Request ID",
     [java]         key_rowValue = \$\{requestID\},
     [java]         locator1 = "PRMMDFListing#LISTING_TABLE");
     [java]     \}
     [java] 
     [java]     if (\$\{rowNumber\} == "Status") \{
     [java]       AssertVisible(
     [java]         key_rowNumber = "Status",
     [java]         key_rowValue = \$\{mdfStatus\},
     [java]         locator1 = "PRMMDFListing#LISTING_TABLE");
     [java]     \}
     [java] 
     [java]     if (\$\{rowNumber\} == "Activity Period") \{
     [java]       AssertVisible(
     [java]         key_rowNumber = "Activity Period",
     [java]         key_rowValue = \$\{activityPeriod\},
     [java]         locator1 = "PRMMDFListing#LISTING_TABLE");
     [java]     \}
     [java] 
     [java]     if (\$\{rowNumber\} == "Partner") \{
     [java]       AssertVisible(
     [java]         key_rowNumber = "Partner",
     [java]         key_rowValue = \$\{partnerName\},
     [java]         locator1 = "PRMMDFListing#LISTING_TABLE");
     [java]     \}
     [java] 
     [java]     if (\$\{rowNumber\} == "Total Cost") \{
     [java]       AssertVisible(
     [java]         key_rowNumber = "Total Cost",
     [java]         key_rowValue = \$\{totalCost\},
     [java]         locator1 = "PRMMDFListing#LISTING_TABLE");
     [java]     \}
     [java] 
     [java]     if (\$\{rowNumber\} == "Campaign Name") \{
     [java]       AssertVisible(
     [java]         key_rowNumber = "Campaign Name",
     [java]         key_rowValue = \$\{campaignName\},
     [java]         locator1 = "PRMMDFListing#LISTING_TABLE");
     [java]     \}
     [java] 
     [java]     if (\$\{rowNumber\} == "Requestd Value") \{
     [java]       AssertVisible(
     [java]         key_rowNumber = "Requestd Value",
     [java]         key_rowValue = \$\{requestedValue\},
     [java]         locator1 = "PRMMDFListing#LISTING_TABLE");
     [java]     \}
     [java] </pre></details></html>

2023-02-10 18:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/5595/">test-portal-source-format#5595</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5595/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3228">pt-liferay-solutions#3228</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2192927192">[master] ci:test:sf - mateussandes23 &gt; pt-liferay-solutions - PR#3228 - 2023-02-10[10:00:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/20201/">publish-testray-report#20201</a><br/></div></div>

2023-02-10 18:36 UTC, mateussandes23 commented
ci:test:sf

2023-02-10 18:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/3650/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3650/jenkins-report.html">here</a>.</b></p>

2023-02-10 18:40 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d48b4c356269b67c7c07fc44abf49cc4377b51b4">d48b4c356269b67c7c07fc44abf49cc4377b51b4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-173539">LPS-173539</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/6a24ba10bdb05293ed038aa806c2a35a2e43a591">6a24ba10bdb05293ed038aa806c2a35a2e43a591</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3650/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3650/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 5 formatting issues:
     [java] 1: Variable 'MDFStatus' in 'SubmittedMDFAppearsOnListing' should start with a lowercase letter: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase (SourceCheck:PoshiVariableNameCheck)
     [java] 2: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFListing.macro expected:&lt;...    var key_rowName = [\$\{key_rowNumber\};
     [java] 
     [java]     if (\$\{rowNumber\} == "Request ID") \{
     [java]       AssertVisible(
     [java]         key_rowNumber = "Request ID",
     [java]         key_rowValue = \$\{requestID\},
     [java]         locator1 = "PRMMDFListing#LISTING_TABLE");
     [java]     \}
     [java] 
     [java]     if (\$\{rowNumber\} == "Status") \{
     [java]       AssertVisible(
     [java]         key_rowNumber = "Status",
     [java]         key_rowValue = \$\{mdfStatus\},
     [java]         locator1 = "PRMMDFListing#LISTING_TABLE");
     [java]     \}
     [java] 
     [java]     if (\$\{rowNumber\} == "Activity Period") \{
     [java]       AssertVisible(
     [java]         key_rowNumber = "Activity Period",
     [java]         key_rowValue = \$\{activityPeriod\},
     [java]         locator1 = "PRMMDFListing#LISTING_TABLE");
     [java]     \}
     [java] 
     [java]     if (\$\{rowNumber\} == "Partner") \{
     [java]       AssertVisible(
     [java]         key_rowNumber = "Partner",
     [java]         key_rowValue = \$\{partnerName\},
     [java]         locator1 = "PRMMDFListing#LISTING_TABLE");
     [java]     \}
     [java] 
     [java]     if (\$\{rowNumber\} == "Total Cost") \{
     [java]       AssertVisible(
     [java]         key_rowNumber = "Total Cost",
     [java]         key_rowValue = \$\{totalCost\},
     [java]         locator1 = "PRMMDFListing#LISTING_TABLE");
     [java]     \}
     [java] 
     [java]     if (\$\{rowNumber\} == "Campaign Name") \{
     [java]       AssertVisible(
     [java]         key_rowNumber = "Campaign Name",
     [java]         key_rowValue = \$\{campaignName\},
     [java]         locator1 = "PRMMDFListing#LISTING_TABLE");
     [java]     \}
     [java] 
     [java]     if (\$\{rowNumber\} == "Requestd Value") \{
     [java]       AssertVisible(
     [java]         key_rowNumber = "Requestd Value",
     [java]         key_rowValue = \$\{requestedValue\},
     [java]         locator1 = "PRMMDFListing#LISTING_TABLE");
     [java]     \}
     [java] </pre></details></html>

2023-02-10 18:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3650/">test-portal-source-format#3650</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3650/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3228">pt-liferay-solutions#3228</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2192958764">[master] ci:test:sf - mateussandes23 &gt; pt-liferay-solutions - PR#3228 - 2023-02-10[10:37:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/13671/">publish-testray-report#13671</a><br/></div></div>

2023-02-13 14:11 UTC, mateussandes23 commented
ci:test:sf

2023-02-13 14:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/4950/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/4950/jenkins-report.html">here</a>.</b></p>

2023-02-13 14:16 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/563570e9d87f7485e613234f41363767c5c13749">563570e9d87f7485e613234f41363767c5c13749</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-173539">LPS-173539</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/b32afe98457f0b2ddc66066ae8186bedb101324a">b32afe98457f0b2ddc66066ae8186bedb101324a</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/4950/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/4950/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFClaim.testcase expected:&lt;...Type = "Business");
     [java] [
     [java]       JSONAccountEntryUser.addExistUsertoAccount(
     [java]         accountEntryName = "Company Name 1",
     [java]         userEmailAddress = "partner@liferay.com");
     [java]     \}
     [java] 
     [java]     task ("Create a new Partner Portal Site") \{
     [java]       PRMUtils.addPRMSite();
     [java]     \}
     [java] 
     [java]     task ("Go to Partner Portal and login with the created user") \{
     [java]       User.logoutAndLoginPG(
     [java]         userLoginEmailAddress = "partner@liferay.com",
     [java]         userLoginFullName = "partner");
     [java] 
     [java]       PRMUtils.gotoPRM();
     [java]     \}
     [java] 
     [java]     task ("Go to 'Marketing' page") \{
     [java]       PRMNavigator.goToNavItem(navItem = "Marketing");
     [java]     \}
     [java]   \}
     [java] 
     [java]   tearDown \{
     [java]     var testPortalInstance = PropsUtil.get("test.portal.instance");
     [java] 
     [java]     if (\$\{testPortalInstance\}] == "true") \{
     [java]       Por...&gt; but was:&lt;...Type = "Business");
     [java] [      JSONAccountEntryUser.addExistUsertoAccount(
     [java]         accountEntryName = "Company Name 1",
     [java]         userEmailAddress = "partner@liferay.com");
     [java]     \}
     [java]     task ("Create a new Partner Portal Site") \{
     [java]       PRMUtils.addPRMSite();
     [java]     \}
     [java] 
     [java]     task ("Go to Partner Portal and login with the created user") \{
     [java]       User.logoutAndLoginPG(
     [java]         userLoginEmailAddress = "partner@liferay.com",
     [java]         userLoginFullName = "partner");
     [java] 
     [java]       PRMUtils.gotoPRM();
     [java]     \}
     [java] 
     [java]     task ("Go to 'Marketing' page") \{
     [java]       PRMNavigator.goToNavItem(navItem = "Marketing");
     [java]     \}
     [java]   \}
     [java] 
     [java]   tearDown \{
     [java]     var testPortalInstance = PropsUtil.get("test.portal.instance");
     [java]     if ("\$\{testPortalInstance\}"] == "true") \{
     [java]       Por...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:444)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:286)</pre></details></html>

2023-02-13 14:20 UTC, mateussandes23 commented
ci:test:sf

2023-02-13 14:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/6724/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6724/jenkins-report.html">here</a>.</b></p>

2023-02-13 14:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/563570e9d87f7485e613234f41363767c5c13749">563570e9d87f7485e613234f41363767c5c13749</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-173539">LPS-173539</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/4603e5a23f99a3fd805031665a465f6fda224539">4603e5a23f99a3fd805031665a465f6fda224539</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/6724/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6724/jenkins-report.html">here</a>.</h5></details></html>

2023-02-13 15:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/6724/">test-portal-source-format#6724</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6724/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3228">pt-liferay-solutions#3228</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2195053233">[master] ci:test:sf - mateussandes23 &gt; pt-liferay-solutions - PR#3228 - 2023-02-13[06:35:04]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/2790/">publish-testray-report#2790</a><br/></div></div>

2023-02-13 16:56 UTC, AfonsoHSantos requested changes

2023-02-13 16:56 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFListing.macro
> +		}
Hi @mateussandes23, I think that this macro is incomplete. I asked you to add a condition for each column. Do you remember?

2023-02-13 16:56 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFListing.macro
> +		}
You should update the [commit message](https://github.com/pt-liferay-solutions/liferay-portal/pull/3228/commits/bed55d14d6c9d4b6bc32aae699b42173bd4f1a02#) too.

2023-02-13 16:56 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFRequest.macro
> +			value1 = "\TAB");
Hi @mateussandes23, the activity index should be a variable: `${activityIndex}`

2023-02-13 16:56 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFRequest.macro
> +			value1 = "\TAB");
Hi @mateussandes23, update the [commit message](https://github.com/pt-liferay-solutions/liferay-portal/pull/3228/commits/e3e644438527b1805f8ce129f67e92fdce7e29a0) too.

2023-02-13 16:56 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +		task ("Add Manager Channel role to the user") {
Hi @mateussandes23, update this task do 'Add a new user with a Manager role'

2023-02-13 16:56 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +		task ("Add Manager Channel role to the user") {
Also, update the [commit message](https://github.com/pt-liferay-solutions/liferay-portal/pull/3228/commits/27d75eb4e51c19d8611244d878e143db430b1c4d#)

2023-02-13 16:56 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +			Button.click(button = "Submit");
Hi @mateussandes23, here you should use the macro `PRMMDFRequest.createNewRequest`, like [this example](https://github.com/pt-liferay-solutions/liferay-portal/pull/3254/commits/148e4897327e4581b7d8582342a5d103e04cc204#diff-e11945b2c04a8939c4989e0fb72ed18189ee0dc2db85f67aadbd93fbd74a6f8dR294-R310).

2023-02-13 16:56 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +				buttonText = "MDF");
Hi @mateussandes23, this code should be inside another task, that could be 'And when I go back to the MDF Listing Page'

2023-02-13 16:56 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +		task ("Then a feedback message wiPRMMarketing.gotoAddNewMDF()ll appear") {
Hi @mateussandes23, I think that there is a typo. Could you please fix it?

2023-02-13 16:56 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFClaim.testcase
> +				locator1 = "PRMMDFRequest#TEXT_FIELD");
Hi @mateussandes23, this step isn't necessary, since you have applied the change that I asked o`n editTotalMDFValue` macro

2023-02-13 16:56 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFClaim.testcase
> +		task ("Then a error message displays") {
Hi @mateussandes23, could you please update this task to 'Then an error message is displayed'? Thanks!

2023-02-13 20:08 UTC, mateussandes23 commented
ci:test:sf

2023-02-13 21:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/6759/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6759/jenkins-report.html">here</a>.</b></p>

2023-02-13 21:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/920375b56810e78a6595b833f1c8dcfcb53d3bf4">920375b56810e78a6595b833f1c8dcfcb53d3bf4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-173539">LPS-173539</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/40647b0f6b95140d5f462dc40ce307666d318b3a">40647b0f6b95140d5f462dc40ce307666d318b3a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/6759/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6759/jenkins-report.html">here</a>.</h5></details></html>

2023-02-13 22:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/6759/">test-portal-source-format#6759</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6759/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3228">pt-liferay-solutions#3228</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2195555930">[master] ci:test:sf - mateussandes23 &gt; pt-liferay-solutions - PR#3228 - 2023-02-13[13:35:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/3557/">publish-testray-report#3557</a><br/></div></div>

2023-02-14 19:58 UTC, mateussandes23 commented
ci:test:sf

2023-02-14 20:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/4854/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4854/jenkins-report.html">here</a>.</b></p>

2023-02-14 20:03 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/05bb3c0b814b17ce8074afbd39569acbf79058c3">05bb3c0b814b17ce8074afbd39569acbf79058c3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-173539">LPS-173539</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/20330e926e20328e0fc17a3c8f942504987f58af">20330e926e20328e0fc17a3c8f942504987f58af</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/4854/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4854/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase expected:&lt;...utton = "Approve");
     [java] []
     [java]       PRMHomePage.goto...&gt; but was:&lt;...utton = "Approve");
     [java] [        ]
     [java]       PRMHomePage.goto...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:444)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:286)
[stopwatch] [run.batch.test.action: 1:21.070 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:596: Java returned: 1
      [get] Getting: http://test-1-26/job/test-portal-source-format/4854//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230214120249965.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230214120249965.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null2036390442.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1098986510
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 138ms
[junitreport] Deleting: /tmp/null1098986510
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 02-14-2023 12:02:51:937 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</pre></details></html>

2023-02-14 20:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/4854/">test-portal-source-format#4854</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4854/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3228">pt-liferay-solutions#3228</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2196871203">[master] ci:test:sf - mateussandes23 &gt; pt-liferay-solutions - PR#3228 - 2023-02-14[11:59:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/18323/">publish-testray-report#18323</a><br/></div></div>

2023-02-15 18:51 UTC, mateussandes23 commented
ci:test:sf

2023-02-15 19:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/6316/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6316/jenkins-report.html">here</a>.</b></p>

2023-02-15 19:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c1eda3b0d7b72cadab482e7724d464effe017bc9">c1eda3b0d7b72cadab482e7724d464effe017bc9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-173539">LPS-173539</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/bc1425492e9009df76a5cd266052d467d5ca37da">bc1425492e9009df76a5cd266052d467d5ca37da</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6316/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6316/jenkins-report.html">here</a>.</h5></details></html>

2023-02-15 20:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6316/">test-portal-source-format#6316</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6316/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3228">pt-liferay-solutions#3228</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2198209719">[master] ci:test:sf - mateussandes23 &gt; pt-liferay-solutions - PR#3228 - 2023-02-15[11:40:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/3714/">publish-testray-report#3714</a><br/></div></div>

2023-02-24 19:08 UTC, AfonsoHSantos commented
Hi @mateussandes23, this commit message isn't matching with the commit content. Could you please double-check it?

2023-02-24 19:15 UTC, AfonsoHSantos commented
Hi @mateussandes23, could you please rename this [commit message](https://github.com/pt-liferay-solutions/liferay-portal/pull/3228/commits/97a277e2ebb0a79d000194324b5a6772d30f1d94) to match the commit content?

2023-02-24 19:27 UTC, AfonsoHSantos commented
Hi @mateussandes23, could you please squash these commits? [commit 1](https://github.com/pt-liferay-solutions/liferay-portal/pull/3228/commits/d172aa152dfaa22fb780b84df44b567d09a258f8#), [commit 2](https://github.com/pt-liferay-solutions/liferay-portal/pull/3228/commits/985095b28e69326cd014197f05a2a8235f9f93e1)

2023-02-24 19:29 UTC, AfonsoHSantos commented
Hi @mateussandes23, [on this commit](https://github.com/pt-liferay-solutions/liferay-portal/pull/3228/commits/25042f4568b2d7fe50450f98fe14cb4fe2e2f91e) you are adding a new test, what not matches with the commit message, could you please double-check? Thanks?

2023-02-24 20:17 UTC, AfonsoHSantos requested changes

2023-02-27 17:40 UTC, mateussandes23 commented
ci:test:sf

2023-02-27 19:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-source-format/6142/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6142/jenkins-report.html">here</a>.</b></p>

2023-02-27 21:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-17.liferay.com/job/test-portal-source-format/6142/">test-portal-source-format#6142</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6142/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3228">pt-liferay-solutions#3228</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2211809634">[master] ci:test:sf - mateussandes23 &gt; pt-liferay-solutions - PR#3228 - 2023-02-27[11:40:51]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-17.liferay.com/job/publish-testray-report/2979/">publish-testray-report#2979</a><br/></div></div>

2023-02-28 12:26 UTC, AfonsoHSantos commented
![giphy](https://user-images.githubusercontent.com/69267630/221853831-08a2d79d-5a82-446a-8e18-084acb45d68b.gif)

2023-02-28 12:26 UTC, AfonsoHSantos commented
Hi @mateussandes23, thanks for working on it! The code looks good to me. I'm forwarding it

2023-02-28 12:26 UTC, AfonsoHSantos commented
ci:forward

2023-02-28 12:26 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-02-28 12:26 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2023-02-28 12:27 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/130924
[Console](https://test-1-31.liferay.com/job/forward-pullrequest/792//consoleFull)

2023-02-28 12:27 UTC, closed without merging