LPS-173731
pt-liferay-solutions/liferay-portal pull request #3270
Opened 2023-02-10 19:40 UTC by juliosilveira77

2023-02-10 19:40 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-02-10 19:41 UTC, juliosilveira77 commented
ci:test:sf

2023-02-10 19:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/4148/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4148/jenkins-report.html">here</a>.</b></p>

2023-02-10 19:45 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2d67882912ae10de759d5a5aaecbe50439f504d1">2d67882912ae10de759d5a5aaecbe50439f504d1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliosilveira77/liferay-portal/tree/LPS-173731">LPS-173731</a><br/>Branch GIT ID: <a href="https://github.com/juliosilveira77/liferay-portal/commit/f6dfe41022f98080b10cb4023daade0db60903bf">f6dfe41022f98080b10cb4023daade0db60903bf</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4148/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4148/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Truncated message :
     [java] ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase expected:&lt;...is a test for LPS-17[3731. Verify that is possible to export a searched MDF"
     [java]   @priority = 4
     [java]   test CanExportSearchedMDFs \{
     [java]     var campaignName = "Campaign Name";
     [java] 
     [java]     task ("Given I go to add a MDF Request") \{
     [java]       PRMMarketing.gotoAddNewMDF();
     [java]     \}
     [java] 
     [java]     task ("And I fill all Goals form with my informations") \{
     [java]       PRMMDFRequest.fillGoalsPage(
     [java]         accountName = "Company Name 1",
     [java]         additionalOptions = "6.x to DXP Migration/Upgrade,Migration from competitor platform",
     [java]         campaignDescription = "Campaign Description",
     [java]         campaignName = \$\{campaignName\},
     [java]         countryName = "Global",
     [java]         goalsOptions = "Lead generation",
     [java]         targetMarketOptions = "Education,Energy",
     [java]         targetRolesOptions = "Administrator");
     [java] 
     [java]       Button.click(button = "Continue");
     [java]     \}
     [java] 
     [java]     task ("And I add a new activity and fill it with my information") \{
     [java]       PRMMDFRequest.newActivity(
     [java]         activityDescription = "Activity Description",
     [java]         activityName = "Activity Name 1",
     [java]         budgetList = "Sponsorship Fee-2000,Room Rental-3000",
     [java]         followUpStrategy = "test",
     [java]         leadFollowUpList = "Other",
     [java]         leadList = "No",
     [java]         tactic = "Other",
     [java]         targetOfLeads = "test",
     [java]         typeOfActivity = "Miscellaneous Marketing");
     [java] 
     [java]       Button.click(button = "Continue");
     [java]     \}
     [java] 
     [java]     task ("Then I submit the MDF") \{
     [java]       Button.click(button = "Continue");
     [java] 
     [java]       Button.click(button = "Submit");
     [java]     \}
     [java] 
     [java]     task ("when i look for the file") \{
     [java]       Type(
     [java]         key_placeHolder = "Search",
     [java]         locator1 = "TextInput#ANY_PLACEHOLDER",
     [java]         value1 = "Company Name 1");
     [java] 
     [java]       Click(locator1 = "WorkflowMetricsProcessListView#METRICS_WORKFLOW_SEARCH_BAR_BUTTON");
     [java]     \}
     [java] </pre></details></html>

2023-02-10 19:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4148/">test-portal-source-format#4148</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4148/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3270">pt-liferay-solutions#3270</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2193022724">[master] ci:test:sf - juliosilveira77 &gt; pt-liferay-solutions - PR#3270 - 2023-02-10[11:41:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/15204/">publish-testray-report#15204</a><br/></div></div>

2023-02-13 19:05 UTC, juliosilveira77 commented
ci:test:sf

2023-02-13 19:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/4952/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/4952/jenkins-report.html">here</a>.</b></p>

2023-02-13 19:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0586c7999956c99c7484c299b2ef9628ce79e753">0586c7999956c99c7484c299b2ef9628ce79e753</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliosilveira77/liferay-portal/tree/LPS-173731">LPS-173731</a><br/>Branch GIT ID: <a href="https://github.com/juliosilveira77/liferay-portal/commit/4cc5580ab168914c4da7ed12dc5751baa31a1467">4cc5580ab168914c4da7ed12dc5751baa31a1467</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/4952/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/4952/jenkins-report.html">here</a>.</h5></details></html>

2023-02-13 19:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-7.liferay.com/job/test-portal-source-format/4952/">test-portal-source-format#4952</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/4952/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3270">pt-liferay-solutions#3270</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2195406371">[master] ci:test:sf - juliosilveira77 &gt; pt-liferay-solutions - PR#3270 - 2023-02-13[11:08:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-7.liferay.com/job/publish-testray-report/2586/">publish-testray-report#2586</a><br/></div></div>

2023-02-23 17:18 UTC, juliosilveira77 commented
ci:test:sf

2023-02-23 19:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/6781/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6781/jenkins-report.html">here</a>.</b></p>

2023-02-23 19:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3ed7586ba9663e841d1f547132e3e900ea529365">3ed7586ba9663e841d1f547132e3e900ea529365</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliosilveira77/liferay-portal/tree/LPS-173731">LPS-173731</a><br/>Branch GIT ID: <a href="https://github.com/juliosilveira77/liferay-portal/commit/1cf2f2ea15b98e218964f2f478520133a21a0c95">1cf2f2ea15b98e218964f2f478520133a21a0c95</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/6781/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6781/jenkins-report.html">here</a>.</h5></details></html>

2023-02-23 20:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/6781/">test-portal-source-format#6781</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6781/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3270">pt-liferay-solutions#3270</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2205136632">[master] ci:test:sf - juliosilveira77 &gt; pt-liferay-solutions - PR#3270 - 2023-02-23[11:08:08]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/3605/">publish-testray-report#3605</a><br/></div></div>

2023-03-07 15:35 UTC, AfonsoHSantos requested changes

2023-03-16 21:27 UTC, juliosilveira77 commented
ci:test:sf

2023-03-16 21:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/2195/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2195/jenkins-report.html">here</a>.</b></p>

2023-03-16 21:36 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b66908c48b31ca2d3b4b27bdaa1981a741dc879b">b66908c48b31ca2d3b4b27bdaa1981a741dc879b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliosilveira77/liferay-portal/tree/LPS-173731">LPS-173731</a><br/>Branch GIT ID: <a href="https://github.com/juliosilveira77/liferay-portal/commit/4ad71a42bd8ca29ae0195a888dc89b6431cf32e4">4ad71a42bd8ca29ae0195a888dc89b6431cf32e4</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2195/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2195/jenkins-report.html">here</a>.</h5><pre>     [exec]             &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/172.18.11.3] failed: connect timed out
     [exec] &gt; Could not resolve de.undercouch:gradle-download-task:3.3.0.
     [exec]   Required by:
     [exec]       unspecified:unspecified:unspecified
     [exec]    &gt; Could not resolve de.undercouch:gradle-download-task:3.3.0.
     [exec]       &gt; Could not get resource 'https://repository-cdn.liferay.com/nexus/content/groups/public/de/undercouch/gradle-download-task/3.3.0/gradle-download-task-3.3.0.pom'.
     [exec]          &gt; Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/de/undercouch/gradle-download-task/3.3.0/gradle-download-task-3.3.0.pom'.
     [exec]             &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/172.18.11.3] failed: connect timed out
     [exec] &gt; Could not resolve gradle.plugin.org.ysb33r.gradle:gradletest:2.0.
     [exec]   Required by:
     [exec]       unspecified:unspecified:unspecified
     [exec]    &gt; Could not resolve gradle.plugin.org.ysb33r.gradle:gradletest:2.0.
     [exec]       &gt; Could not get resource 'https://repository-cdn.liferay.com/nexus/content/groups/public/gradle/plugin/org/ysb33r/gradle/gradletest/2.0/gradletest-2.0.pom'.
     [exec]          &gt; Could not HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/gradle/plugin/org/ysb33r/gradle/gradletest/2.0/gradletest-2.0.pom'.
     [exec]             &gt; Connect to repository-cdn.liferay.com:443 [repository-cdn.liferay.com/172.18.11.3] failed: connect timed out
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration\$ArtifactResolveException: Could not resolve all artifacts for configuration 'classpath'.
     [exec]   at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1410)
     [exec]   at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access\$3600(DefaultConfiguration.java:149)
     [exec]   at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration\$DefaultResolutionHost.rethrowFailure(DefaultConfiguration.java:2015)</pre></details></html>

2023-03-16 21:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2195/">test-portal-source-format#2195</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2195/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3270">pt-liferay-solutions#3270</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2234998522">[master] ci:test:sf - juliosilveira77 &gt; pt-liferay-solutions - PR#3270 - 2023-03-16[14:27:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/8770/">publish-testray-report#8770</a><br/></div></div>

2023-03-17 12:51 UTC, juliosilveira77 commented
ci:test:sf

2023-03-17 12:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/2268/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2268/jenkins-report.html">here</a>.</b></p>

2023-03-17 12:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fd3f8a5444d77e437db62ebd1f89c4b0825b8334">fd3f8a5444d77e437db62ebd1f89c4b0825b8334</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliosilveira77/liferay-portal/tree/LPS-173731">LPS-173731</a><br/>Branch GIT ID: <a href="https://github.com/juliosilveira77/liferay-portal/commit/7e1a0a679de049dfa00ef6555ad4715f446a0032">7e1a0a679de049dfa00ef6555ad4715f446a0032</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/2268/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2268/jenkins-report.html">here</a>.</h5></details></html>

2023-03-17 12:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/2268/">test-portal-source-format#2268</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2268/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3270">pt-liferay-solutions#3270</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2235454389">[master] ci:test:sf - juliosilveira77 &gt; pt-liferay-solutions - PR#3270 - 2023-03-17[05:51:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/8219/">publish-testray-report#8219</a><br/></div></div>

2023-03-17 15:03 UTC, AfonsoHSantos requested changes

2023-03-17 15:03 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +	}
Hi @juliosilveira77, apply the same logic to these tasks

2023-03-17 18:48 UTC, juliosilveira77 commented
ci:test:sf

2023-03-17 18:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/424/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/424/jenkins-report.html">here</a>.</b></p>

2023-03-17 18:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0a996ed2d245477342cf8d3a99b5068f69b7eabd">0a996ed2d245477342cf8d3a99b5068f69b7eabd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliosilveira77/liferay-portal/tree/LPS-173731">LPS-173731</a><br/>Branch GIT ID: <a href="https://github.com/juliosilveira77/liferay-portal/commit/1e8edd71fb20bbf754df5679771e5b80c7572066">1e8edd71fb20bbf754df5679771e5b80c7572066</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/424/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/424/jenkins-report.html">here</a>.</h5></details></html>

2023-03-17 18:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/424/">test-portal-source-format#424</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/424/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3270">pt-liferay-solutions#3270</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2235733339">[master] ci:test:sf - juliosilveira77 &gt; pt-liferay-solutions - PR#3270 - 2023-03-17[11:49:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/1197/">publish-testray-report#1197</a><br/></div></div>

2023-03-22 16:45 UTC, AfonsoHSantos commented
![giphy](https://user-images.githubusercontent.com/69267630/226977115-0cbc556f-c57f-4e23-999c-3a52c6b71380.gif)

2023-03-22 16:45 UTC, AfonsoHSantos commented
Hi @juliosilveira77 , thanks for working on it!
The code looks good to me, so I'm forwarding it!

2023-03-22 16:45 UTC, AfonsoHSantos commented
ci:forward

2023-03-22 16:45 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-03-22 16:45 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2023-03-22 18:17 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-7.liferay.com/job/forward-pullrequest/352//consoleFull)

2023-03-22 18:17 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/132135
[Console](https://test-1-7.liferay.com/job/forward-pullrequest/352//consoleFull)

2023-03-22 18:17 UTC, closed without merging