LPS-176011 Fix Awaiting Payment Confirmation and kebab Pay button
pt-liferay-solutions/liferay-portal pull request #3338
Opened 2023-02-24 15:24 UTC by EuniceTravassos

2023-02-24 15:24 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-02-24 15:24 UTC, EuniceTravassos commented
ci:test:sf

2023-02-24 16:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/6008/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6008/jenkins-report.html">here</a>.</b></p>

2023-02-24 16:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/47122202b5b7d05b00237736e559449bacff9c76">47122202b5b7d05b00237736e559449bacff9c76</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/EuniceTravassos/liferay-portal/tree/LPS-176011">LPS-176011</a><br/>Branch GIT ID: <a href="https://github.com/EuniceTravassos/liferay-portal/commit/e31ed08cae5ada3fb8c379eda1e2d6af5d624d91">e31ed08cae5ada3fb8c379eda1e2d6af5d624d91</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6008/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6008/jenkins-report.html">here</a>.</h5></details></html>

2023-02-24 16:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6008/">test-portal-source-format#6008</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6008/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3338">pt-liferay-solutions#3338</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2206753081">[master] ci:test:sf - EuniceTravassos &gt; pt-liferay-solutions - PR#3338 - 2023-02-24[08:14:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/3074/">publish-testray-report#3074</a><br/></div></div>

2023-02-27 16:07 UTC, juliocezar96 commented
Just starting reviewing :)

2023-02-27 17:22 UTC, eliasantosf commented
Just starting reviewing :)

2023-02-27 17:26 UTC, juliocezar96 commented
Just starting reviewing :)

2023-02-27 17:52 UTC, eliasantosf requested changes
1. Mudar o nome da pasta **evp-button-save-payment-confirmation** para **evp-payment-save-button**.
2. Mudar o nome da pasta **evp-kebab-request** para **evp-request-kebab-button**.

2023-02-27 17:52 UTC, eliasantosf commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/fragments/group/evp/fragments/evp-kebab-request/index.html
> +<div id="evp-kebab-request">
```suggestion
<div id="evp-request-kebab-button">
```

2023-02-27 17:52 UTC, eliasantosf commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/fragments/group/evp/fragments/evp-kebab-request/index.html
> +<div id="evp-kebab-request">
Tudo que tiver referenciando o nome "evp-kebab-request" mudar para "evp-request-kebab-button".

2023-03-08 16:03 UTC, closed without merging