LPS-176748 [PRM] Changing activity status according mdf request status
pt-liferay-solutions/liferay-portal pull request #3370
Opened 2023-02-28 19:55 UTC by biellopes00

2023-03-01 14:41 UTC, thaynam commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/utils/constants/status.ts
> +		key: 'submited',
```suggestion
		key: 'submitted',
```

2023-03-01 15:39 UTC, thaynam commented
the typos are breaking the deploy, always test before sending the PR

2023-03-01 16:11 UTC, jairmedeiros requested changes

2023-03-01 16:11 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/mdf-request-detail-collection/fragments/activities-list-panel/index.js
> +	SUBMITED: 'submited',
```suggestion
	SUBMITTED: 'submitted',
```

2023-03-01 16:11 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/src/mdf-request-detail-collection/fragments/activities-list-panel/index.js
> +	[ActivityStatus.SUBMITED]: 'label label-tonal-warning ml-2',
```suggestion
	[ActivityStatus.SUBMITTED]: 'label label-tonal-warning ml-2',
```

2023-03-01 16:11 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/object-definitions/activity.json
> +								"key": "submited",
```suggestion
								"key": "submitted",
```

2023-03-01 16:11 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/object-definitions/activity.json
> +			"defaultValue": "submited",
```suggestion
			"defaultValue": "submitted",
```

2023-03-01 16:11 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/list-type-definitions/activity-status.list-type-entries.json
> +			"en-US": "Submited"
```suggestion
		"key": "submitted",
		"name": "Submitted",
		"name_i18n": {
			"en-US": "Submitted"
```

2023-03-03 13:41 UTC, thaynam requested changes

2023-03-09 19:12 UTC, closed without merging