LPS-172427
pt-liferay-solutions/liferay-portal pull request #3379
Opened 2023-03-01 16:46 UTC by mateussandes23

2023-03-01 16:49 UTC, mateussandes23 commented
ci:test:sf

2023-03-01 17:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-source-format/6371/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/6371/jenkins-report.html">here</a>.</b></p>

2023-03-01 17:18 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/319686997f28a7ca3425dff8a5a72f8b24741bc6">319686997f28a7ca3425dff8a5a72f8b24741bc6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-172427">LPS-172427</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/8c1d13644fa4b923fcd435da475c85c715341f60">8c1d13644fa4b923fcd435da475c85c715341f60</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-source-format/6371/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/6371/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase expected:&lt;....portal.instance");
     [java] [
     [java]     if (\$\{testPortalInstance\} == "true") \{
     [java]       PortalInstances.tearDownCP();
     [java]     \}
     [java]     else \{
     [java]       JSONGroup.deleteGroupByName(groupName = "Partner Portal");
     [java]   ]  \}
     [java]   \}
     [java] 
     [java]   @description...&gt; but was:&lt;....portal.instance");
     [java] [    if (\$\{testPortalInstance\} == "true") \{
     [java]       PortalInstances.tearDownCP();
     [java]   \}
     [java]     else \{
     [java]       JSONGroup.deleteGroupByName(groupName = "Partner Portal");
     [java] ]  \}
     [java]   \}
     [java] 
     [java]   @description...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:444)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:286)
[stopwatch] [run.batch.test.action: 2:06.822 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:596: Java returned: 1
      [get] Getting: http://test-1-16/job/test-portal-source-format/6371//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230301091815413.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230301091815413.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null2138807670.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1071173114
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl</pre></details></html>

2023-03-01 17:39 UTC, mateussandes23 commented
ci:test:sf

2023-03-01 17:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/4449/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4449/jenkins-report.html">here</a>.</b></p>

2023-03-01 17:58 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 19 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/319686997f28a7ca3425dff8a5a72f8b24741bc6">319686997f28a7ca3425dff8a5a72f8b24741bc6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-172427">LPS-172427</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/63ac94d249ea5b10a204f75382fa5005947c06b6">63ac94d249ea5b10a204f75382fa5005947c06b6</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/4449/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4449/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase expected:&lt;....portal.instance");
     [java] [
     [java]     if (\$\{testPortalInstance\} == "true") \{
     [java]       PortalInstances.tearDownCP();
     [java]     \}
     [java]     else \{
     [java]       JSONGroup.deleteGroupByName(groupName = "Partner Portal");
     [java]   ]  \}
     [java]   \}
     [java] 
     [java]   @description...&gt; but was:&lt;....portal.instance");
     [java] [    if (\$\{testPortalInstance\} == "true") \{
     [java]       PortalInstances.tearDownCP();
     [java]   \}
     [java]     else \{
     [java]       JSONGroup.deleteGroupByName(groupName = "Partner Portal");
     [java] ]  \}
     [java]   \}
     [java] 
     [java]   @description...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:444)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:286)
[stopwatch] [run.batch.test.action: 1:14.656 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:596: Java returned: 1
      [get] Getting: http://test-1-27/job/test-portal-source-format/4449//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230301095827631.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230301095827631.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1556416056.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1749729158
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl</pre></details></html>

2023-03-01 17:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/2241/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/2241/jenkins-report.html">here</a>.</b></p>

2023-03-01 18:00 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 19 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/319686997f28a7ca3425dff8a5a72f8b24741bc6">319686997f28a7ca3425dff8a5a72f8b24741bc6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-172427">LPS-172427</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/63ac94d249ea5b10a204f75382fa5005947c06b6">63ac94d249ea5b10a204f75382fa5005947c06b6</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/2241/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/2241/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase expected:&lt;....portal.instance");
     [java] [
     [java] ]    if (\$\{testPortalIn...&gt; but was:&lt;....portal.instance");
     [java] []    if (\$\{testPortalIn...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:444)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:286)
[stopwatch] [run.batch.test.action: 1:15.924 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:596: Java returned: 1
      [get] Getting: http://test-1-34/job/test-portal-source-format/2241//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230301100031838.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230301100031838.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1988757243.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null994903137
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 144ms
[junitreport] Deleting: /tmp/null994903137
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 03-01-2023 10:00:33:866 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</pre></details></html>

2023-03-01 18:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/4449/">test-portal-source-format#4449</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4449/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3379">pt-liferay-solutions#3379</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2217709125">[master] ci:test:sf - mateussandes23 &gt; pt-liferay-solutions - PR#3379 - 2023-03-01[09:40:04]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/16597/">publish-testray-report#16597</a><br/></div></div>

2023-03-01 18:03 UTC, mateussandes23 commented
ci:test:sf

2023-03-01 18:05 UTC, mateussandes23 commented
ci:test:sf

2023-03-01 18:07 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/319686997f28a7ca3425dff8a5a72f8b24741bc6">319686997f28a7ca3425dff8a5a72f8b24741bc6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-172427">LPS-172427</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/aa998454dc02454571ad717705397154cfbd0834">aa998454dc02454571ad717705397154cfbd0834</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/5562/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5562/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFRequest.macro expected:&lt;...dgetIndex\} + 1;
     [java]     \}
     [java] [  \}
     [java] 
     [java]   @summary = "Format the date that will be inputed on start and end date"
     [java]   macro formatDate \{
     [java]     var nextDayDate = DateUtil.getFormattedDate("+1", "MMddyyyy");
     [java] 
     [java]     if (isSet(endDate)) \{
     [java]       var nextDayDate = DateUtil.getFormattedDate("+2", "MMddyyyy");
     [java]     \}
     [java] 
     [java]     return \$\{nextDayDate\};
     [java]   \}
     [java] 
     [java]   @summary = "Go to MDF"
     [java]   macro goToMDF \{
     [java]     Click(
     [java]       key_MDFName = \$\{campaignName\},
     [java]       locator1 = "PRMMDFRequest#REQUEST_ID");
     [java]   \}
     [java] 
     [java]   @summary = "Fill the date fields on Activity Form"
     [java]   macro insertDate \{
     [java]     if (!(isSet(activityIndex))) \{
     [java]       var activityIndex = 0;
     [java]     \}
     [java] 
     [java]     var currentDate = DateUtil.getFormattedDate(\$\{dateRange\}, \$\{dateFormat\});
     [java] 
     [java]     if (\$\{fieldName\} == "startDate") \{
     [java]       Type.sendKeys(
     [java]         key_fieldName = "activities[\$\{activityIndex\}].startDate",
     [java]         locator1 = "PRMMDFRequest#TEXT_FIELD",
     [java]         value1 = \$\{currentDate\});
     [java] 
     [java]       Click(
     [java]         key_fieldName = "activities[\$\{activityIndex\}].endDate",
     [java]         locator1 = "PRMMDFRequest#TEXT_FIELD");
     [java]     \}
     [java] 
     [java]     if (\$\{fieldName\} == "endDate") \{
     [java]       Type.sendKeys(
     [java]         key_fieldName = "activities[\$\{activityIndex\}].endDate",
     [java]         locator1 = "PRMMDFRequest#TEXT_FIELD",
     [java]         value1 = \$\{currentDate\});
     [java] 
     [java]       Click(
     [java]         key_fieldName = "activities[\$\{activityIndex\}].startDate",
     [java]         locator1 = "PRMMDFRequest#TEXT_FIELD");
     [java]     \}
     [java]   \}
     [java] 
     [java]   @summary = "Add a new activity"
     [java]   macro newActivity \{
     [java]     if (!(isSet(activityIndex))) \{
     [java]       var activityIndex = 0;
     [java]     \}
     [java] 
     [java]     Click(
     [java]       key_buttonText = "Add Activity",
     [java]       locator1 = "PRMMDFRequest#ADD_BUTTON");
     [java] 
     [java]     Type(</pre></details></html>

2023-03-01 18:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/3703/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3703/jenkins-report.html">here</a>.</b></p>

2023-03-01 18:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/319686997f28a7ca3425dff8a5a72f8b24741bc6">319686997f28a7ca3425dff8a5a72f8b24741bc6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-172427">LPS-172427</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/aa998454dc02454571ad717705397154cfbd0834">aa998454dc02454571ad717705397154cfbd0834</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3703/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3703/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFRequest.macro expected:&lt;...dgetIndex\} + 1;
     [java]     \}
     [java] [  \}
     [java] 
     [java]   @summary = "Format the date that will be inputed on start and end date"
     [java]   macro formatDate \{
     [java]     var nextDayDate = DateUtil.getFormattedDate("+1", "MMddyyyy");
     [java] 
     [java]     if (isSet(endDate)) \{
     [java]       var nextDayDate = DateUtil.getFormattedDate("+2", "MMddyyyy");
     [java]     \}
     [java] 
     [java]     return \$\{nextDayDate\};
     [java]   \}
     [java] 
     [java]   @summary = "Go to MDF"
     [java]   macro goToMDF \{
     [java]     Click(
     [java]       key_MDFName = \$\{campaignName\},
     [java]       locator1 = "PRMMDFRequest#REQUEST_ID");
     [java]   \}
     [java] 
     [java]   @summary = "Fill the date fields on Activity Form"
     [java]   macro insertDate \{
     [java]     if (!(isSet(activityIndex))) \{
     [java]       var activityIndex = 0;
     [java]     \}
     [java] 
     [java]     var currentDate = DateUtil.getFormattedDate(\$\{dateRange\}, \$\{dateFormat\});
     [java] 
     [java]     if (\$\{fieldName\} == "startDate") \{
     [java]       Type.sendKeys(
     [java]         key_fieldName = "activities[\$\{activityIndex\}].startDate",
     [java]         locator1 = "PRMMDFRequest#TEXT_FIELD",
     [java]         value1 = \$\{currentDate\});
     [java] 
     [java]       Click(
     [java]         key_fieldName = "activities[\$\{activityIndex\}].endDate",
     [java]         locator1 = "PRMMDFRequest#TEXT_FIELD");
     [java]     \}
     [java] 
     [java]     if (\$\{fieldName\} == "endDate") \{
     [java]       Type.sendKeys(
     [java]         key_fieldName = "activities[\$\{activityIndex\}].endDate",
     [java]         locator1 = "PRMMDFRequest#TEXT_FIELD",
     [java]         value1 = \$\{currentDate\});
     [java] 
     [java]       Click(
     [java]         key_fieldName = "activities[\$\{activityIndex\}].startDate",
     [java]         locator1 = "PRMMDFRequest#TEXT_FIELD");
     [java]     \}
     [java]   \}
     [java] 
     [java]   @summary = "Add a new activity"
     [java]   macro newActivity \{
     [java]     if (!(isSet(activityIndex))) \{
     [java]       var activityIndex = 0;
     [java]     \}
     [java] 
     [java]     Click(
     [java]       key_buttonText = "Add Activity",
     [java]       locator1 = "PRMMDFRequest#ADD_BUTTON");
     [java] 
     [java]     Type(</pre></details></html>

2023-03-01 18:16 UTC, mateussandes23 commented
ci:test:sf

2023-03-01 18:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/5562/">test-portal-source-format#5562</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5562/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3379">pt-liferay-solutions#3379</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2217722955">[master] ci:test:sf - mateussandes23 &gt; pt-liferay-solutions - PR#3379 - 2023-03-01[10:03:40]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/21339/">publish-testray-report#21339</a><br/></div></div>

2023-03-01 18:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3703/">test-portal-source-format#3703</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3703/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3379">pt-liferay-solutions#3379</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2217744837">[master] ci:test:sf - mateussandes23 &gt; pt-liferay-solutions - PR#3379 - 2023-03-01[10:06:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/13951/">publish-testray-report#13951</a><br/></div></div>

2023-03-01 19:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-portal-source-format/5851/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/5851/jenkins-report.html">here</a>.</b></p>

2023-03-01 19:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2b15c918bb8da8c921c21bba5c50545ff3cf9a75">2b15c918bb8da8c921c21bba5c50545ff3cf9a75</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/mateussandes23/liferay-portal/tree/LPS-172427">LPS-172427</a><br/>Branch GIT ID: <a href="https://github.com/mateussandes23/liferay-portal/commit/8bf04b8a6b10b8988bc00a2497eb2b9e826d02e9">8bf04b8a6b10b8988bc00a2497eb2b9e826d02e9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-source-format/5851/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/5851/jenkins-report.html">here</a>.</h5></details></html>

2023-03-01 20:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-4.liferay.com/job/test-portal-source-format/5851/">test-portal-source-format#5851</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/5851/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3379">pt-liferay-solutions#3379</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2217851427">[master] ci:test:sf - mateussandes23 &gt; pt-liferay-solutions - PR#3379 - 2023-03-01[11:24:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-4.liferay.com/job/publish-testray-report/3834/">publish-testray-report#3834</a><br/></div></div>

2023-03-07 15:06 UTC, AfonsoHSantos commented
Hi @mateussandes23, could you please rename [this commit](https://github.com/pt-liferay-solutions/liferay-portal/pull/3379/commits/aa998454dc02454571ad717705397154cfbd0834) to match with the commit content? Thanks!

2023-03-07 15:23 UTC, AfonsoHSantos requested changes

2023-03-07 15:23 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFRequest.macro
> +	@summary = "verify if the requested amount is equal to the mdf values"
Hi @mateussandes23, could you please rename this summary to 'Verify if the MDF Requested amount is equal to 50% of the total value'?

2023-03-07 15:23 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFRequest.macro
> +			value1 = ${discountedValue});
Hi @mateussandes23, this macro should calculate the Total MDF Requested Amount. The calculation must be done by dividing the budget value by 2.

After this, you should assert that the value on the field is equals to your result.

2023-03-07 15:23 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +		task ("Given a new MDF request") {
Hi @mateussandes23, could you please rename this task to 'Given that I fill the MDF until Activity page'

2023-03-07 15:23 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +		task ("When I create a new activity") {
Hi @mateussandes23, could you please rename this task to 'When I go to add a new activity'

2023-03-07 15:23 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +		task ("And When I add a new expense") {
Hi @mateussandes23, could you please rename this task to 'And I add a new expense'

2023-03-07 15:23 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +				budgetList = "Direct Mail-100000,Room Rental-3000");
Hi @mateussandes23, here isn't necessary to add two budgets. Could you please add just one? Thanks!

2023-03-07 15:23 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +		task ("Then the requested amount is equal to 50% of the MDF value"){
Hi @mateussandes23, could you please rename this task to 'Then the Total MDF Requested Amount is equals to 50% of the MDF value'

2023-03-07 15:23 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFRequest.macro
> +			value1 = ${discountedValue});
Hi @mateussandes23, could you please rename this variable to `requestedAmount`?

2023-03-17 14:21 UTC, closed without merging