LPS-177859 Save user selected columns
pt-liferay-solutions/liferay-portal pull request #3430
Opened 2023-03-08 20:58 UTC by rafaelfs98

2023-03-08 20:58 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-03-08 21:00 UTC, rafaelfs98 commented
ci:test:sf

2023-03-08 21:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-source-format/5522/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/5522/jenkins-report.html">here</a>.</b></p>

2023-03-08 21:30 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7167fb45ee3ac3dc7e131e36c7a8d06997a43cf3">7167fb45ee3ac3dc7e131e36c7a8d06997a43cf3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaelfs98/liferay-portal/tree/LPS-177821">LPS-177821</a><br/>Branch GIT ID: <a href="https://github.com/rafaelfs98/liferay-portal/commit/a4b791e244a7a06f0db4d9bc92d28191da8fb9f4">a4b791e244a7a06f0db4d9bc92d28191da8fb9f4</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-source-format/5522/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/5522/jenkins-report.html">here</a>.</h5><pre>     [exec] &gt; Task :npmInstall SKIPPED
     [exec] 
     [exec] &gt; Task :yarnInstall
     [exec] Using registry http://mirrors.lax.liferay.com:4873
     [exec] yarn install v1.13.0
     [exec] [1/4] Resolving packages...
     [exec] warning Resolution field "@types/html-minifier-terser@5.1.0" is incompatible with requested version "@types/html-minifier-terser@^6.0.0"
     [exec] success Already up-to-date.
     [exec] Done in 1.49s.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ liferay-npm-scripts check
     [exec] apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/context/ListViewContext.tsx: BAD
     [exec] Prettier checked 14 files, 1 file has problems
     [exec] 
     [exec] 1 of 3 jobs failed
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2023-03-08 21:27:32.002.
     [exec] 3 actionable tasks: 2 executed, 1 up-to-date
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2023-03-08-13-27-10.html
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$3(ExecuteActionsTaskExecuter.java:186)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:268)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)</pre></details></html>

2023-03-09 01:12 UTC, kevenleone requested changes
@rafaelfs98 good job on that!!

I left few comments for you with suggestions.

Take a look!

2023-03-09 01:12 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/ManagementToolbar/ManagementToolbarColumns.tsx
> +type CollumnsState = {
```suggestion
type ColumnsState = {
```

2023-03-09 01:12 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/ManagementToolbar/ManagementToolbarColumns.tsx
> +	const [selectedColumns, setSelectedColumns] = useState<CollumnsState>(
```suggestion
	const [selectedColumns, setSelectedColumns] = useState<ColumnsState>(
```

2023-03-09 01:12 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/ManagementToolbar/ManagementToolbarColumns.tsx
> +			const newColumns: CollumnsState = {};
```suggestion
			const newColumns: ColumnsState = {};
```

2023-03-09 01:12 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/ManagementToolbar/ManagementToolbarColumns.tsx
> +			<div className="body-toolbar">
I think the name `body-toolbar` is too vague.

Put a classname that emphasizes the behavior

```suggestion
			<div className="body-toolbar">
```

2023-03-09 01:12 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/ManagementToolbar/ManagementToolbarColumns.tsx
> +				</div>
Simplify

```suggestion
					{columnsNotFixed.map((column, index) => <
					                 Form.Checkbox
								checked={selectedColumns[column.key]}
								key={index}
								label={column.value}
								onChange={(event) =>
									setSelectedColumns({
										...selectedColumns,
										[column.key]: event.target.checked,
									})
								}
								value={
									(selectedColumns[
										column.key
									] as unknown) as string
								}
							/>
							)}
				</div>
```

2023-03-09 01:12 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/ManagementToolbar/ManagementToolbarColumns.tsx
> +								},
Simplify

```suggestion
								columns: selectedColumns,
```

2023-03-09 01:12 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/ManagementToolbar/ManagementToolbarFilter.tsx
> +			<div className="body-toolbar">
find a better name

2023-03-09 01:12 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/ManagementToolbar/ManagementToolbarRight.tsx
> +					className="body-columns popover-management-toolbar"
Those classnames are too vague

```suggestion
					className="body-columns popover-management-toolbar"
```

2023-03-09 01:12 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/ManagementToolbar/ManagementToolbarRight.tsx
> +	const [visible, setVisible] = useState(false);
Would be good to add context to this state, I know it's visible, but basically anything could be visible here.

Maybe: `columnsDropdownVisible` clear than this

2023-03-09 01:12 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/context/ListViewContext.tsx
> +	const [columnsStorage] = useStorage<ListViewColumns>(
Move this variable to before `filterPinnedStorage`

2023-03-09 01:12 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/core/Storage.ts
> +	LIST_VIEW_COLUMNS = '@testray/listview-columns-',
Sort

```suggestion
        LIST_VIEW_COLUMNS = '@testray/listview-columns-',
	LIST_VIEW_PIN = '@testray/listview-pin-',
```

2023-03-09 13:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/4256/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4256/jenkins-report.html">here</a>.</b></p>

2023-03-09 13:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4256/">test-portal-source-format#4256</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4256/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3430">pt-liferay-solutions#3430</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2226180421">[master] ci:test:sf - rafaelfs98 &gt; pt-liferay-solutions - PR#3430 - 2023-03-09[05:01:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/15662/">publish-testray-report#15662</a><br/></div></div>

2023-03-09 16:24 UTC, closed without merging