LPS-177869 [PRM] Manager only can edit MDF in draft status
pt-liferay-solutions/liferay-portal pull request #3494
Opened 2023-03-14 15:35 UTC by Manda-vit

2023-03-14 15:35 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-03-14 15:36 UTC, Manda-vit commented
ci:test:sf

2023-03-14 15:37 UTC, Manda-vit commented
ci:test:stable

2023-03-14 15:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/5766/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5766/jenkins-report.html">here</a>.</b></p>

2023-03-14 15:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/625d6136e0f5181d8701c36ef8bf4b87a630223d">625d6136e0f5181d8701c36ef8bf4b87a630223d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Manda-vit/liferay-portal/tree/LPS-177869">LPS-177869</a><br/>Branch GIT ID: <a href="https://github.com/Manda-vit/liferay-portal/commit/8240807f7a9060f105b913037429b6e4fb37946f">8240807f7a9060f105b913037429b6e4fb37946f</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/5766/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5766/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/resource-permissions.json expected:&lt;...
     [java]   \{
     [java]     "actionIds": [[
     [java]       "VIEW"
     [java]     ],
     [java]     "resourceName": "com.liferay.journal.model.JournalFolder",
     [java]     "roleName": "User",
     [java]     "scope": "1"
     [java]   \},
     [java]   \{
     [java]     "actionIds": [
     [java]       "SUBSCRIBE",
     [java]       "VIEW"
     [java]     ],
     [java]     "resourceName": "com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet",
     [java]     "roleName": "User",
     [java]     "scope": "1"
     [java]   \},
     [java]   \{
     [java]     "actionIds": [
     [java]       "VIEW"
     [java]     ],
     [java]     "resourceName": "com.liferay.list.type.model.ListTypeDefinition",
     [java]     "roleName": "User",
     [java]     "scope": "1"
     [java]   \},
     [java]   \{
     [java]     "actionIds": [
     [java]       "VIEW"
     [java]     ],
     [java]     "primKey": "[\$OBJECT_DEFINITION_ID:MDFRequest\$]",
     [java]     "resourceName": "com.liferay.object.model.ObjectDefinition",
     [java]     "roleName": "User",
     [java]     "scope": "4"
     [java]   \},
     [java]   \{
     [java]     "actionIds": [
     [java]       "UPDATE",
     [java]       "VIEW"
     [java]     ],
     [java]     "primKey": 0,
     [java]     "resourceName": "com.liferay.portal.kernel.model.Role",
     [java]     "roleName": "Channel General Manager",
     [java]     "scope": "1"
     [java]   \},
     [java]   \{
     [java]     "actionIds": [
     [java]       "UPDATE",
     [java]       "VIEW"
     [java]     ],
     [java]     "primKey": 0,
     [java]     "resourceName": "com.liferay.portal.kernel.model.Role",
     [java]     "roleName": "Channel Account Manager",
     [java]     "scope": "1"
     [java]   \},
     [java]   \{
     [java]     "actionIds": [
     [java]       "UPDATE",
     [java]       "VIEW"
     [java]     ],
     [java]     "primKey": 0,
     [java]     "resourceName": "com.liferay.portal.kernel.model.Role",
     [java]     "roleName": "Channel Regional Marketing Manager",
     [java]     "scope": "1"
     [java]   \},
     [java]   \{
     [java]     "actionIds": [
     [java]       "UPDATE",
     [java]       "VIEW"
     [java]     ],
     [java]     "primKey": 0,
     [java]     "resourceName": "com.liferay.portal.kernel.model.Role",
     [java]     "roleName": "Channel Global Marketing Manager",
     [java]     "scope": "1"</pre></details></html>

2023-03-14 15:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>stable</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/8578/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8578/jenkins-report.html">here</a>.</b></p>

2023-03-14 15:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/5766/">test-portal-source-format#5766</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5766/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3494">pt-liferay-solutions#3494</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2232016128">[master] ci:test:sf - Manda-vit &gt; pt-liferay-solutions - PR#3494 - 2023-03-14[08:37:22]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/20890/">publish-testray-report#20890</a><br/></div></div>

2023-03-14 15:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/5730/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5730/jenkins-report.html">here</a>.</b></p>

2023-03-14 15:54 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/625d6136e0f5181d8701c36ef8bf4b87a630223d">625d6136e0f5181d8701c36ef8bf4b87a630223d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Manda-vit/liferay-portal/tree/LPS-177869">LPS-177869</a><br/>Branch GIT ID: <a href="https://github.com/Manda-vit/liferay-portal/commit/0de0ca476e9b197289c40a40303c922e761255b3">0de0ca476e9b197289c40a40303c922e761255b3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/5730/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5730/jenkins-report.html">here</a>.</h5></details></html>

2023-03-14 15:56 UTC, Manda-vit commented
ci:test:stable

2023-03-14 15:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/5730/">test-portal-source-format#5730</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/5730/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3494">pt-liferay-solutions#3494</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2232030697">[master] ci:test:sf - Manda-vit &gt; pt-liferay-solutions - PR#3494 - 2023-03-14[08:50:52]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/21943/">publish-testray-report#21943</a><br/></div></div>

2023-03-14 16:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>stable</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/8196/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8196/jenkins-report.html">here</a>.</b></p>

2023-03-14 17:29 UTC, Manda-vit commented
ci:test:sf

2023-03-14 18:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed in 3 hours 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/625d6136e0f5181d8701c36ef8bf4b87a630223d">625d6136e0f5181d8701c36ef8bf4b87a630223d</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/96b19a9b4ed02d8a09b33977cdadf1ced4399f73">96b19a9b4ed02d8a09b33977cdadf1ced4399f73</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2231442557">EE Development Acceptance (master) - 4375 - 2023-03-13[20:18:53]</a></p><details><summary><strong>ci:test:stable - 28 out of 28 jobs PASSED</strong></summary><details><summary><strong>28 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/8578/">test-portal-acceptance-pullrequest(master)</a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/170594/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/519436/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/453795/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/179424/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/519438/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/164996/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/453796/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/471752/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/167156/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/16271/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/471753/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/183953/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/497010/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/497011/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/16277/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/428574/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/421668/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/16274/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/497013/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/497015/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/453798/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/178962/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/519437/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/471751/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/142424/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/174850/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/6733/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8578/jenkins-report.html">here</a>.</h5></details></html>

2023-03-14 18:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/8578/">test-portal-acceptance-pullrequest(master)#8578</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8578/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>stable<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3494">pt-liferay-solutions#3494</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2232227048">[master] ci:test:stable - Manda-vit &gt; pt-liferay-solutions - PR#3494 - 2023-03-14[08:41:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/20898/">publish-testray-report#20898</a><br/></div></div>

2023-03-14 20:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4211/">test-portal-source-format#4211</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4211/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3494">pt-liferay-solutions#3494</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2232308872">[master] ci:test:sf - Manda-vit &gt; pt-liferay-solutions - PR#3494 - 2023-03-14[11:56:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/3388/">publish-testray-report#3388</a><br/></div></div>

2023-03-14 21:26 UTC, jairmedeiros commented
ci:forward

2023-03-14 21:26 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:sf`

2023-03-14 22:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/3722/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3722/jenkins-report.html">here</a>.</b></p>

2023-03-15 01:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 26 out of 26 jobs passed</h3><h3>:x: ci:test:relevant - 49 out of 51 jobs passed in 2 hours 34 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/099b4aadf9d904cf56725c3a55ed1b49a217fc40">099b4aadf9d904cf56725c3a55ed1b49a217fc40</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/099b4aadf9d904cf56725c3a55ed1b49a217fc40">099b4aadf9d904cf56725c3a55ed1b49a217fc40</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2232682563">EE Development Acceptance (master) - 4378 - 2023-03-14[12:38:24]</a></p><details><summary><strong>ci:test:stable - 26 out of 26 jobs PASSED</strong></summary><details><summary><strong>26 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 49 out of 51 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/3722/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/429624/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454677/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/429630/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/424592/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/17278/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/437657/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/520422/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/424593/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/274201/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/274202/"><strike>functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</strike></a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/429628/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/274203/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/179279/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/274208/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/497991/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/399304/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/437658/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/497990/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454676/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>lpkg-controller-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/429625/">lpkg-controller-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/487200/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/429627/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/498074/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/437656/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/487202/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/429629/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/274207/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/422565/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/497989/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454675/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/274204/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/274206/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/427129/">modules-integration-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/424594/">modules-integration-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/520423/">modules-integration-mysql57-jdk8/0/2</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/427128/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-d [...]

2023-03-15 01:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/3722/">test-portal-acceptance-pullrequest(master)#3722</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3722/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3494">pt-liferay-solutions#3494</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2232768744">[master] ci:test:relevant - Manda-vit &gt; pt-liferay-solutions - PR#3494 - 2023-03-14[15:42:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/8842/">publish-testray-report#8842</a><br/></div></div>

2023-03-17 15:53 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-03-17 16:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/8640/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8640/jenkins-report.html">here</a>.</b></p>

2023-03-17 19:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/8640/">test-portal-acceptance-pullrequest(master)#8640</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8640/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3494">pt-liferay-solutions#3494</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2235752101">[master] ci:test:relevant - Manda-vit &gt; pt-liferay-solutions - PR#3494 - 2023-03-17[09:39:22]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/20998/">publish-testray-report#20998</a><br/></div></div>

2023-03-17 20:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/6363/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6363/jenkins-report.html">here</a>.</b></p>

2023-03-17 20:50 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0a996ed2d245477342cf8d3a99b5068f69b7eabd">0a996ed2d245477342cf8d3a99b5068f69b7eabd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Manda-vit/liferay-portal/tree/LPS-177869">LPS-177869</a><br/>Branch GIT ID: <a href="https://github.com/Manda-vit/liferay-portal/commit/a53f6dcff780b8e727627173ffe8d151a9d4c2a2">a53f6dcff780b8e727627173ffe8d151a9d4c2a2</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6363/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6363/jenkins-report.html">here</a>.</h5><pre>     [exec] Configuration on demand is an incubating feature.
     [exec] &gt; Task :downloadNode UP-TO-DATE
     [exec] &gt; Task :npmInstall SKIPPED
     [exec] 
     [exec] &gt; Task :yarnInstall
     [exec] Using registry http://mirrors.lax.liferay.com:4873
     [exec] yarn install v1.13.0
     [exec] [1/4] Resolving packages...
     [exec] warning Resolution field "@types/html-minifier-terser@5.1.0" is incompatible with requested version "@types/html-minifier-terser@^6.0.0"
     [exec] success Already up-to-date.
     [exec] Done in 1.32s.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ liferay-npm-scripts check
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/utils/dto/mdf-request-activity/getDTOFromMDFRequestActivity.ts: BAD
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Activities/Activities.tsx: BAD
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Goals/Goals.tsx: BAD
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/utils/submitForm.ts: BAD
     [exec] Prettier checked 5 files, 4 files have problems
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] 
     [exec] 1 of 3 jobs failed
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] error Command failed with exit code 1.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2023-03-17 20:50:19.297.
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec] 3 actionable tasks: 2 executed, 1 up-to-date
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$3(ExecuteActionsTaskExecuter.java:186)</pre></details></html>

2023-03-17 21:37 UTC, Manda-vit commented
ci:test:sf

2023-03-17 22:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6363/">test-portal-source-format#6363</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6363/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3494">pt-liferay-solutions#3494</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2235834953">[master] ci:test:sf - Manda-vit &gt; pt-liferay-solutions - PR#3494 - 2023-03-17[13:47:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/3846/">publish-testray-report#3846</a><br/></div></div>

2023-03-17 22:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/5037/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5037/jenkins-report.html">here</a>.</b></p>

2023-03-17 22:51 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0a996ed2d245477342cf8d3a99b5068f69b7eabd">0a996ed2d245477342cf8d3a99b5068f69b7eabd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Manda-vit/liferay-portal/tree/LPS-177869">LPS-177869</a><br/>Branch GIT ID: <a href="https://github.com/Manda-vit/liferay-portal/commit/7cd6641970c1fc0c27f3ff34988e346b59af8345">7cd6641970c1fc0c27f3ff34988e346b59af8345</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/5037/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5037/jenkins-report.html">here</a>.</h5><pre>     [exec] yarn run v1.13.0
     [exec] \$ liferay-npm-scripts check
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/utils/dto/mdf-request-activity/getDTOFromMDFRequestActivity.ts: BAD
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Activities/Activities.tsx: BAD
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Goals/Goals.tsx: BAD
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/utils/submitForm.ts: BAD
     [exec] Prettier checked 9 files, 4 files have problems
     [exec] 
     [exec] 1 of 3 jobs failed
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2023-03-17 22:51:02.018.
     [exec] 3 actionable tasks: 2 executed, 1 up-to-date
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2023-03-17-15-50-45.html
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$3(ExecuteActionsTaskExecuter.java:186)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:268)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)</pre></details></html>

2023-03-17 23:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-7.liferay.com/job/test-portal-source-format/5037/">test-portal-source-format#5037</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5037/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3494">pt-liferay-solutions#3494</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2235952571">[master] ci:test:sf - Manda-vit &gt; pt-liferay-solutions - PR#3494 - 2023-03-17[15:47:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-7.liferay.com/job/publish-testray-report/2711/">publish-testray-report#2711</a><br/></div></div>

2023-03-18 19:55 UTC, jairmedeiros requested changes

2023-03-18 19:55 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/utils/isLiferayManager.ts
> +	return roles?.some((role) => allowedRoles.includes(role.name as RoleTypes));
```suggestion
	return roles.some((role) => allowedRoles.includes(role.name as RoleTypes));
```

2023-03-18 19:55 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/utils/submitForm.ts
> +	if (currentRequestStatus && !values.id) {
@Manda-vit, check if we can remove this.

2023-03-20 16:37 UTC, Manda-vit commented
ci:test:sf

2023-03-20 16:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ba4a83196357493468c96bda3b635d55425754be">ba4a83196357493468c96bda3b635d55425754be</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Manda-vit/liferay-portal/tree/LPS-177869">LPS-177869</a><br/>Branch GIT ID: <a href="https://github.com/Manda-vit/liferay-portal/commit/f4dc9c1026e283f275a568084a9d6fe2cb9d98e4">f4dc9c1026e283f275a568084a9d6fe2cb9d98e4</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/4915/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4915/jenkins-report.html">here</a>.</h5><pre>     [exec] yarn run v1.13.0
     [exec] \$ liferay-npm-scripts check
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/utils/dto/mdf-request-activity/getDTOFromMDFRequestActivity.ts: BAD
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Activities/Activities.tsx: BAD
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Goals/Goals.tsx: BAD
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/utils/submitForm.ts: BAD
     [exec] Prettier checked 9 files, 4 files have problems
     [exec] 
     [exec] 1 of 3 jobs failed
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2023-03-20 16:41:15.068.
     [exec] 3 actionable tasks: 2 executed, 1 up-to-date
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2023-03-20-09-41-02.html
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$3(ExecuteActionsTaskExecuter.java:186)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:268)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)</pre></details></html>

2023-03-20 16:41 UTC, Manda-vit commented
ci:test:sf

2023-03-20 17:15 UTC, Manda-vit commented
ci:test:sf

2023-03-20 17:42 UTC, Manda-vit commented
ci:test:sf

2023-03-20 18:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-source-format/6398/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/6398/jenkins-report.html">here</a>.</b></p>

2023-03-20 18:04 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a171fa1c8b718a064fcf8d86f219edf334972631">a171fa1c8b718a064fcf8d86f219edf334972631</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Manda-vit/liferay-portal/tree/LPS-177869">LPS-177869</a><br/>Branch GIT ID: <a href="https://github.com/Manda-vit/liferay-portal/commit/d7c6606d2a94d748d9b905f0fee78e29fe3af454">d7c6606d2a94d748d9b905f0fee78e29fe3af454</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-source-format/6398/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/6398/jenkins-report.html">here</a>.</h5><pre>     [exec] &gt; Task :downloadNode UP-TO-DATE
     [exec] &gt; Task :npmInstall SKIPPED
     [exec] 
     [exec] &gt; Task :yarnInstall
     [exec] Using registry http://mirrors.lax.liferay.com:4873
     [exec] yarn install v1.13.0
     [exec] [1/4] Resolving packages...
     [exec] warning Resolution field "@types/html-minifier-terser@5.1.0" is incompatible with requested version "@types/html-minifier-terser@^6.0.0"
     [exec] success Already up-to-date.
     [exec] Done in 1.43s.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ liferay-npm-scripts check
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/utils/dto/mdf-request-activity/getDTOFromMDFRequestActivity.ts: BAD
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Activities/Activities.tsx: BAD
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Goals/Goals.tsx: BAD
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/utils/submitForm.ts: BAD
     [exec] Prettier checked 9 files, 4 files have problems
     [exec] 
     [exec] 1 of 3 jobs failed
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$3(ExecuteActionsTaskExecuter.java:186)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:268)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)</pre></details></html>

2023-03-20 18:12 UTC, Manda-vit commented
ci:test:sf

2023-03-20 18:16 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a171fa1c8b718a064fcf8d86f219edf334972631">a171fa1c8b718a064fcf8d86f219edf334972631</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Manda-vit/liferay-portal/tree/LPS-177869">LPS-177869</a><br/>Branch GIT ID: <a href="https://github.com/Manda-vit/liferay-portal/commit/d95d05bf742a5514377113946cb2be1aef4c4394">d95d05bf742a5514377113946cb2be1aef4c4394</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/450/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/450/jenkins-report.html">here</a>.</h5><pre>     [exec] yarn run v1.13.0
     [exec] \$ liferay-npm-scripts check
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/common/utils/dto/mdf-request-activity/getDTOFromMDFRequestActivity.ts: BAD
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Activities/Activities.tsx: BAD
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/steps/Goals/Goals.tsx: BAD
     [exec] dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFRequestForm/utils/submitForm.ts: BAD
     [exec] Prettier checked 9 files, 4 files have problems
     [exec] 
     [exec] 1 of 3 jobs failed
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2023-03-20 18:16:16.425.
     [exec] 3 actionable tasks: 2 executed, 1 up-to-date
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2023-03-20-11-16-01.html
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$3(ExecuteActionsTaskExecuter.java:186)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:268)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)</pre></details></html>

2023-03-20 18:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/450/">test-portal-source-format#450</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/450/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3494">pt-liferay-solutions#3494</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2237599270">[master] ci:test:sf - Manda-vit &gt; pt-liferay-solutions - PR#3494 - 2023-03-20[11:13:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/1296/">publish-testray-report#1296</a><br/></div></div>

2023-03-20 19:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-16.liferay.com/job/test-portal-source-format/6398/">test-portal-source-format#6398</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/6398/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3494">pt-liferay-solutions#3494</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2237649353">[master] ci:test:sf - Manda-vit &gt; pt-liferay-solutions - PR#3494 - 2023-03-20[11:01:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-16.liferay.com/job/publish-testray-report/3048/">publish-testray-report#3048</a><br/></div></div>

2023-03-20 22:10 UTC, thaynam commented
PR resent [3552](https://github.com/pt-liferay-solutions/liferay-portal/pull/3552)

2023-03-21 10:39 UTC, thaynam commented
Waiting for [3552](https://github.com/pt-liferay-solutions/liferay-portal/pull/3552)

2023-03-21 17:18 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ee181b9c5405808971f0d33fe641f35a64e58981">ee181b9c5405808971f0d33fe641f35a64e58981</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Manda-vit/liferay-portal/tree/LPS-177869">LPS-177869</a><br/>Branch GIT ID: <a href="https://github.com/Manda-vit/liferay-portal/commit/bbcf9565016863da4dbdef687ba6157e2b00cd68">bbcf9565016863da4dbdef687ba6157e2b00cd68</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5157/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5157/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/resource-permissions.json expected:&lt;...
     [java]   \{
     [java]     "actionIds": [[
     [java]       "VIEW"
     [java]     ],
     [java]     "resourceName": "com.liferay.journal.model.JournalFolder",
     [java]     "roleName": "User",
     [java]     "scope": "1"
     [java]   \},
     [java]   \{
     [java]     "actionIds": [
     [java]       "SUBSCRIBE",
     [java]       "VIEW"
     [java]     ],
     [java]     "resourceName": "com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet",
     [java]     "roleName": "User",
     [java]     "scope": "1"
     [java]   \},
     [java]   \{
     [java]     "actionIds": [
     [java]       "VIEW"
     [java]     ],
     [java]     "resourceName": "com.liferay.list.type.model.ListTypeDefinition",
     [java]     "roleName": "User",
     [java]     "scope": "1"
     [java]   \},
     [java]   \{
     [java]     "actionIds": [
     [java]       "VIEW"
     [java]     ],
     [java]     "primKey": "[\$OBJECT_DEFINITION_ID:MDFRequest\$]",
     [java]     "resourceName": "com.liferay.object.model.ObjectDefinition",
     [java]     "roleName": "User",
     [java]     "scope": "4"
     [java]   \},
     [java]   \{
     [java]     "actionIds": [
     [java]       "VIEW"
     [java]     ],
     [java]     "resourceName": "com.liferay.portal.kernel.model.Role",
     [java]     "roleName": "Channel General Manager",
     [java]     "scope": "1"
     [java]   \},
     [java]   \{
     [java]     "actionIds": [
     [java]       "VIEW"
     [java]     ],
     [java]     "resourceName": "com.liferay.portal.kernel.model.Role",
     [java]     "roleName": "Channel Account Manager",
     [java]     "scope": "1"
     [java]   \},
     [java]   \{
     [java]     "actionIds": [
     [java]       "VIEW"
     [java]     ],
     [java]     "resourceName": "com.liferay.portal.kernel.model.Role",
     [java]     "roleName": "Channel Regional Marketing Manager",
     [java]     "scope": "1"
     [java]   \},
     [java]   \{
     [java]     "actionIds": [
     [java]       "VIEW"
     [java]     ],
     [java]     "resourceName": "com.liferay.portal.kernel.model.Role",
     [java]     "roleName": "Channel Global Marketing Manager",
     [java]     "scope": "1"
     [java]   \},
     [java]   \{
     [java]     "actionIds": [
     [java]       "VIEW"
     [java]     ],
     [java]     "resourceName": "com.liferay.portal.kernel.model.Role",</pre></details></html>

2023-03-21 17:27 UTC, Manda-vit commented
ci:test:sf

2023-03-21 17:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/4924/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4924/jenkins-report.html">here</a>.</b></p>

2023-03-21 17:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ee181b9c5405808971f0d33fe641f35a64e58981">ee181b9c5405808971f0d33fe641f35a64e58981</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Manda-vit/liferay-portal/tree/LPS-177869">LPS-177869</a><br/>Branch GIT ID: <a href="https://github.com/Manda-vit/liferay-portal/commit/d4d0620e10337fe94449486d5c4254ae5843ecf6">d4d0620e10337fe94449486d5c4254ae5843ecf6</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/4924/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4924/jenkins-report.html">here</a>.</h5></details></html>

2023-03-21 17:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5157/">test-portal-source-format#5157</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5157/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3494">pt-liferay-solutions#3494</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2239366803">[master] ci:test:sf - Manda-vit &gt; pt-liferay-solutions - PR#3494 - 2023-03-21[10:15:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/19540/">publish-testray-report#19540</a><br/></div></div>

2023-03-21 17:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/4924/">test-portal-source-format#4924</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4924/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3494">pt-liferay-solutions#3494</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2239366814">[master] ci:test:sf - Manda-vit &gt; pt-liferay-solutions - PR#3494 - 2023-03-21[10:27:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/18353/">publish-testray-report#18353</a><br/></div></div>

2023-03-21 18:09 UTC, thaynam commented
resent [3559](https://github.com/pt-liferay-solutions/liferay-portal/pull/3559)

2023-03-21 18:09 UTC, closed without merging

2023-03-21 18:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>default</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/3916/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3916/jenkins-report.html">here</a>.</b></p>

2023-03-22 00:11 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 1346 out of 1487 jobs passed in 5 hours 30 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4400">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1357401_3916</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ee181b9c5405808971f0d33fe641f35a64e58981">ee181b9c5405808971f0d33fe641f35a64e58981</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4b5a5717fe780fe7a9e6051e1a6e6d5f2604d1ff">4b5a5717fe780fe7a9e6051e1a6e6d5f2604d1ff</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2238974079">EE Development Acceptance (master) - 4399 - 2023-03-21[00:38:46]</a></p><details><summary><strong>ci:test:default - 1346 out of 1487 jobs PASSED</strong></summary><div><h4>141 Failed Jobs:</h4><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/3916/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>archived-module-smoke-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/432831/">archived-module-smoke-jdk8/0/0</a></li></ul></li><li>archived-modules-test-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/188947/">archived-modules-test-jdk8/0/0</a></li></ul></li><li>build-lib-versions-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/175919/"><strike>build-lib-versions-jdk8/0/0</strike></a></li></ul></li><li>bundle-blacklist-restart-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/19171/">bundle-blacklist-restart-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/170698/">central-requirements-jdk8/0/0</a></li></ul></li><li>compile-jsp-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/170702/">compile-jsp-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/286232/">empty-osgi-core-dir-jdk8/0/0</a></li></ul></li><li>functional-smoke-jboss73-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/29473/">functional-smoke-jboss73-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-jboss74-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/29402/">functional-smoke-jboss74-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2111-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/161826/">functional-smoke-tomcat90-db2111-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/19348/"><strike>functional-smoke-tomcat90-db2115-jdk8/0/0</strike></a></li></ul></li><li>functional-smoke-tomcat90-mariadb102-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/178511/">functional-smoke-tomcat90-mariadb102-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/174044/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/183257/">functional-smoke-tomcat90-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql80-jdk8<ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151657/">functional-smoke-tomcat90-mysql80-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/532528/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql121-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/169162/">functional-smoke-tomcat90-postgresql121-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql134-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/186718/">functional-smoke-tomcat90-postgresql134-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/158251/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2017-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/438263/">functional-smoke-tomcat90-sqlserver2017-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/483722/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-weblogic122-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/29447/">functional-smoke-weblogic122-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-weblogic141-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/19125/">functional-smoke-weblogic141-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-websphere90-mysql57-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/174035/">functional-smoke-websphere90-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/29420/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/483747/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly230-mariadb104-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/29399/">functional-smoke-wildfly230-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly230-mariadb106-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448513/">functional-smoke-wildfly230-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-db2111-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/188647/">functional-tomcat90-db2111-jdk8/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448516/"><strike>functional-tomcat90-db2111-jdk8/0/1</strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullreq [...]

2023-03-22 00:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/3916/">test-portal-acceptance-pullrequest(master)#3916</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3916/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>default<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3494">pt-liferay-solutions#3494</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2240119177">[master] ci:test:default - Manda-vit &gt; pt-liferay-solutions - PR#3494 - 2023-03-21[11:38:24]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/8865/">publish-testray-report#8865</a><br/></div></div>