LPS-AVATAR
pt-liferay-solutions/liferay-portal pull request #3562
Opened 2023-03-21 19:37 UTC by raquelpaiva

2023-03-21 20:34 UTC, joanagrego commented
Hi @raquelpaiva, please rename your branch to _LPS-174056_ and your PR to _LPS-174056 [Raylife AP] Enable Account Functionality for User Avatar_

2023-03-21 20:36 UTC, joanagrego requested changes

2023-03-21 20:36 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/src/main/resources/site-initializer/fragments/group/src/raylife-ap-fragments/fragments/avatar-dropdown-menu/index.js
> +// };
Please delete it.

2023-03-21 20:36 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/src/main/resources/site-initializer/fragments/group/src/raylife-ap-fragments/fragments/avatar-dropdown-menu/index.js
> +// const dropdownItems = document.querySelector('.dropdown-items');
Please delete it.

2023-03-21 20:36 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/src/main/resources/site-initializer/fragments/group/src/raylife-ap-fragments/fragments/avatar-dropdown-menu/index.js
> +// console.log('user', userId);
Please delete it.

2023-03-21 21:08 UTC, joanagrego commented
ci:test:sf

2023-03-21 21:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/3770/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3770/jenkins-report.html">here</a>.</b></p>

2023-03-21 21:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ee181b9c5405808971f0d33fe641f35a64e58981">ee181b9c5405808971f0d33fe641f35a64e58981</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/raquelpaiva/liferay-portal/tree/LPS-AVATAR">LPS-AVATAR</a><br/>Branch GIT ID: <a href="https://github.com/raquelpaiva/liferay-portal/commit/c0fcb06866a716feb6b11bc47acfa45117a9d352">c0fcb06866a716feb6b11bc47acfa45117a9d352</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3770/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3770/jenkins-report.html">here</a>.</h5></details></html>

2023-03-21 21:15 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/3770/">test-portal-source-format#3770</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/3770/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3562">pt-liferay-solutions#3562</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2239858234">[master] ci:test:sf - raquelpaiva &gt; pt-liferay-solutions - PR#3562 - 2023-03-21[14:09:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/14218/">publish-testray-report#14218</a><br/></div></div>

2023-03-22 14:00 UTC, raquelpaiva commented on modules/apps/site-initializer/site-initializer-raylife-ap/src/main/resources/site-initializer/fragments/group/src/raylife-ap-fragments/fragments/avatar-dropdown-menu/index.js
> +// };
Done

2023-03-22 20:35 UTC, closed without merging