LPS-174067
pt-liferay-solutions/liferay-portal pull request #3594
Opened 2023-03-23 22:47 UTC by eduardo-diniz

2023-03-23 22:47 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-03-24 11:29 UTC, eduardo-diniz commented
ci:test:sf

2023-03-24 11:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/515/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/515/jenkins-report.html">here</a>.</b></p>

2023-03-24 11:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/728238ed9d0089c081ec94129918e7f6c3159048">728238ed9d0089c081ec94129918e7f6c3159048</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eduardo-diniz/liferay-portal/tree/LPS-174067">LPS-174067</a><br/>Branch GIT ID: <a href="https://github.com/eduardo-diniz/liferay-portal/commit/5c603976eb21f8c7d693bed083fe14aecd175985">5c603976eb21f8c7d693bed083fe14aecd175985</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/515/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/515/jenkins-report.html">here</a>.</h5></details></html>

2023-03-24 11:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/515/">test-portal-source-format#515</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/515/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3594">pt-liferay-solutions#3594</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2244213395">[master] ci:test:sf - eduardo-diniz &gt; pt-liferay-solutions - PR#3594 - 2023-03-24[04:29:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/1547/">publish-testray-report#1547</a><br/></div></div>

2023-03-27 14:38 UTC, eduardo-diniz commented
ci:test:sf

2023-03-27 14:42 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b24a3bd6a43c1df280188b12b2361deaeb78115b">b24a3bd6a43c1df280188b12b2361deaeb78115b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eduardo-diniz/liferay-portal/tree/LPS-174067">LPS-174067</a><br/>Branch GIT ID: <a href="https://github.com/eduardo-diniz/liferay-portal/commit/2ceaf0d79301128b4d84c57bd67d27dc7f014186">2ceaf0d79301128b4d84c57bd67d27dc7f014186</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1753/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1753/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/common/components/notification-sidebar/index.scss expected:&lt;...ner \{
     [java]     .title \{
     [java]       [align-items: center;
     [java]       color: #a8a8a8;
     [java]       display: flex;
     [java]       font-size: 8px;
     [java]       font-weight: 400;
     [java]       height: 10px;
     [java]       letter-spacing: 0.1em;
     [java]       letter-spacing: 0.1em;
     [java]       line-height: 10px;
     [java]       text-align: left;
     [java]       text-transform: uppercase;
     [java]       width: 270px;
     [java]     \}
     [java]     padding-bottom: 1px;
     [java]     padding-left: 20]px;
     [java] 
     [java]     a \{
     [java]       cursor...&gt; but was:&lt;...ner \{
     [java]     .title \{
     [java]       [width: 270px;
     [java]       height: 10px;
     [java]       display: flex;
     [java]       align-items: center;
     [java]       letter-spacing: 0.1em;
     [java]       text-transform: uppercase;
     [java]       font-size: 8px;
     [java]       font-weight: 400;
     [java]       line-height: 10px;
     [java]       letter-spacing: 0.1em;
     [java]       text-align: left;
     [java]       color: #a8a8a8;
     [java]     \}
     [java]     padding-left: 20px;
     [java]     padding-bottom: 1]px;
     [java] 
     [java]     a \{
     [java]       cursor...&gt;
     [java] 2: ./modules/apps/site-initializer/site-initializer-raylife-ap/src/main/resources/site-initializer/fragments/group/src/raylife-ap-fragments/fragments/layout/index.css expected:&lt;...con-tools \{
     [java]   margin-[right: 20px;
     [java]   margin-top: 3px !important;
     [java] \}
     [java] 
     [java] .layout-container .notification-span \{
     [java]   margin-left: 20px;
     [java] \}
     [java] 
     [java] .layout-container .notifications-sidebar-header \{
     [java]   box-shadow: 0 5px 15px rgb(77 133 255 / 12%);
     [java]   padding-bottom: 18px;
     [java]   padding-top]: 18px;
     [java] \}
     [java] &gt; but was:&lt;...con-tools \{
     [java]   margin-[top: 3px !important;
     [java]   margin-right: 20px;
     [java] \}
     [java] 
     [java] .layout-container .notification-span \{
     [java]   margin-left: 20px;
     [java] \}
     [java] 
     [java] .layout-container .notifications-sidebar-header \{
     [java]   box-shadow: 0 5px 15px rgb(77 133 255 / 12%);
     [java]   padding-top: 18px;
     [java]   padding-bottom]: 18px;
     [java] \}
     [java] &gt;</pre></details></html>

2023-03-27 14:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1753/">test-portal-source-format#1753</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1753/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3594">pt-liferay-solutions#3594</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2246738237">[master] ci:test:sf - eduardo-diniz &gt; pt-liferay-solutions - PR#3594 - 2023-03-27[07:38:54]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/7131/">publish-testray-report#7131</a><br/></div></div>

2023-03-27 16:24 UTC, eduardo-diniz commented
ci:test:sf

2023-03-27 16:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/154/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/154/jenkins-report.html">here</a>.</b></p>

2023-03-27 16:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/616cf2e9385ce497795d56b1c8253f66367f0ef5">616cf2e9385ce497795d56b1c8253f66367f0ef5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eduardo-diniz/liferay-portal/tree/LPS-174067">LPS-174067</a><br/>Branch GIT ID: <a href="https://github.com/eduardo-diniz/liferay-portal/commit/45c1d883e1d722312684b0d74b2b69599c657838">45c1d883e1d722312684b0d74b2b69599c657838</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/154/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/154/jenkins-report.html">here</a>.</h5></details></html>

2023-03-27 16:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/154/">test-portal-source-format#154</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/154/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3594">pt-liferay-solutions#3594</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2247010806">[master] ci:test:sf - eduardo-diniz &gt; pt-liferay-solutions - PR#3594 - 2023-03-27[09:25:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/528/">publish-testray-report#528</a><br/></div></div>

2023-03-27 19:36 UTC, joanagrego requested changes
Nice job! I added some suggestions :)

2023-03-27 19:36 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/common/components/notification-sidebar/index.tsx
> +		const arrayRead: any = [];
Please type it correctly.

2023-03-27 19:36 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/common/components/notification-sidebar/index.tsx
> +	const markAsReadState = (_post: PostType, index: number) => {
Do you really need this "post" parameter?

2023-03-27 19:36 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/common/components/notification-sidebar/index.tsx
> +	const [isRead, setIsRead] = useState<any>([]);
Please type it correctly.

2023-03-27 19:36 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/common/components/notification-sidebar/index.scss
> +		}
Try to use bootstrap here.

2023-03-28 12:04 UTC, eduardo-diniz commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/common/components/notification-sidebar/index.tsx
> +		const arrayRead: any = [];
Done!

2023-03-28 12:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/4972/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4972/jenkins-report.html">here</a>.</b></p>

2023-03-28 13:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/82cd446a220a5fc79300f0335a965480ca4342c6">82cd446a220a5fc79300f0335a965480ca4342c6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eduardo-diniz/liferay-portal/tree/LPS-174067">LPS-174067</a><br/>Branch GIT ID: <a href="https://github.com/eduardo-diniz/liferay-portal/commit/9ab14c27c6f7f49965018f5991286341899fae8f">9ab14c27c6f7f49965018f5991286341899fae8f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/4972/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/4972/jenkins-report.html">here</a>.</h5></details></html>

2023-03-28 13:15 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/src/main/resources/site-initializer/fragments/group/src/raylife-ap-fragments/fragments/layout/index.html
> +	<div class="bg-white d-flex flex-column loaded notification-panel notification-sidebar sticky-top" id="panel-sidebar">
Could you check the ray-sticky-top class?

2023-03-28 13:18 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/common/services/notification.ts
>  	}
Try to use the `parametersFormater()` function here.

2023-03-28 13:18 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/common/components/notification-sidebar/index.tsx
> +	useEffect(() => {}, [isRead]);
Do you really need it?

2023-03-28 13:19 UTC, joanagrego commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/common/components/notification-sidebar/index.scss
> +			font-size: 8px;
I believe we have this font-size in Dialect.

2023-03-28 13:23 UTC, eduardo-diniz commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/common/components/notification-sidebar/index.scss
>  		border-radius: 50%;
Nope, because it's a before.

2023-03-28 13:25 UTC, eduardo-diniz commented on modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/common/components/notification-sidebar/index.tsx
> +	useEffect(() => {}, [isRead]);
Thx!

2023-03-28 14:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/2397/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2397/jenkins-report.html">here</a>.</b></p>

2023-03-28 14:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/69049f4216818f70a89fcfd5e7ab189673d9b763">69049f4216818f70a89fcfd5e7ab189673d9b763</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eduardo-diniz/liferay-portal/tree/LPS-174067">LPS-174067</a><br/>Branch GIT ID: <a href="https://github.com/eduardo-diniz/liferay-portal/commit/7e1c54d6779d6d231fc4ade01197f527017c77b1">7e1c54d6779d6d231fc4ade01197f527017c77b1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/2397/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2397/jenkins-report.html">here</a>.</h5></details></html>

2023-03-28 14:12 UTC, joanagrego approved these changes

2023-03-28 14:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/2397/">test-portal-source-format#2397</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2397/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3594">pt-liferay-solutions#3594</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2248640249">[master] ci:test:sf - eduardo-diniz &gt; pt-liferay-solutions - PR#3594 - 2023-03-28[07:07:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/8683/">publish-testray-report#8683</a><br/></div></div>

2023-03-28 14:13 UTC, joanagrego commented
ci:forward

2023-03-28 14:13 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:sf`

2023-03-28 15:53 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/7503//consoleFull)

2023-03-28 15:53 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/132496
[Console](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/7503//consoleFull)

2023-03-28 15:53 UTC, closed without merging