membership
pt-liferay-solutions/liferay-portal pull request #3653
Opened 2023-03-31 14:19 UTC by nNilton

2023-03-31 14:19 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-03-31 14:20 UTC, nNilton commented
ci:test:sf

2023-03-31 14:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/634/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/634/jenkins-report.html">here</a>.</b></p>

2023-03-31 14:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/634/">test-portal-source-format#634</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/634/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3653">pt-liferay-solutions#3653</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2253840293">[master] ci:test:sf - nNilton &gt; pt-liferay-solutions - PR#3653 - 2023-03-31[07:20:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/1957/">publish-testray-report#1957</a><br/></div></div>

2023-03-31 16:48 UTC, nNilton commented
ci:test:sf

2023-03-31 16:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/640/">test-portal-source-format#640</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/640/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3653">pt-liferay-solutions#3653</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2253960907">[master] ci:test:sf - nNilton &gt; pt-liferay-solutions - PR#3653 - 2023-03-31[09:48:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/1969/">publish-testray-report#1969</a><br/></div></div>

2023-04-08 02:49 UTC, joseabelenda requested changes

2023-04-08 02:49 UTC, joseabelenda commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender-test-bundle-2/src/main/resources/site-initializer/user-accounts.json
> +		"externalReferenceCode": "USER-1",
Should it be TESTUSER1?

2023-04-08 02:49 UTC, joseabelenda commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender-test-bundle-2/src/main/resources/site-initializer/user-accounts.json
> +				"externalReferenceCode": "TESTACC0002"
Remove zeros.

2023-04-10 21:17 UTC, joseabelenda commented
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/3707

2023-04-10 21:18 UTC, closed without merging