LPS-179357
pt-liferay-solutions/liferay-portal pull request #3655
Opened 2023-03-31 19:58 UTC by marinaasant0s

2023-03-31 19:58 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-03-31 20:01 UTC, marinaasant0s commented
ci:test:sf

2023-03-31 20:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/2432/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2432/jenkins-report.html">here</a>.</b></p>

2023-03-31 20:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7d8d71f0f1b79e79144593c38e3faa285cd3405d">7d8d71f0f1b79e79144593c38e3faa285cd3405d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marinaasant0s/liferay-portal/tree/LPS-179357">LPS-179357</a><br/>Branch GIT ID: <a href="https://github.com/marinaasant0s/liferay-portal/commit/afba265ae238539af260fb92146925f98015a64c">afba265ae238539af260fb92146925f98015a64c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/2432/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2432/jenkins-report.html">here</a>.</h5></details></html>

2023-03-31 20:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/2432/">test-portal-source-format#2432</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2432/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3655">pt-liferay-solutions#3655</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2254110942">[master] ci:test:sf - marinaasant0s &gt; pt-liferay-solutions - PR#3655 - 2023-03-31[13:01:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/8841/">publish-testray-report#8841</a><br/></div></div>

2023-03-31 20:25 UTC, AfonsoHSantos requested changes

2023-03-31 20:25 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFClaim.macro
> +	}
Hi @marinaasant0s, you can't use this path here, because I want you to click in the Claim ID, instead of click in the first Claim

2023-03-31 20:25 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMDashboards.testcase
> +		}
Hi @marinaasant0s, here you could use the macro to approve the MDF via API: `JSONPRM.changeMDFStatus`

2023-03-31 20:25 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMDashboards.testcase
> +		task ("And I go back to Dashboard page and get the new amount of approved MDF Claims approved Value") {
Hi @marinaasant0s, here should be the When

2023-04-06 17:55 UTC, marinaasant0s commented
ci:test:sf

2023-04-06 17:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/5278/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5278/jenkins-report.html">here</a>.</b></p>

2023-04-06 17:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0f6774641388bb7ede8e1c80bc8bb6510e0e7585">0f6774641388bb7ede8e1c80bc8bb6510e0e7585</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marinaasant0s/liferay-portal/tree/LPS-179357">LPS-179357</a><br/>Branch GIT ID: <a href="https://github.com/marinaasant0s/liferay-portal/commit/6bfc70b26e8d0eda08105c9c23f3aa10072d17b1">6bfc70b26e8d0eda08105c9c23f3aa10072d17b1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5278/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5278/jenkins-report.html">here</a>.</h5></details></html>

2023-04-06 18:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5278/">test-portal-source-format#5278</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5278/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3655">pt-liferay-solutions#3655</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2260560857">[master] ci:test:sf - marinaasant0s &gt; pt-liferay-solutions - PR#3655 - 2023-04-06[10:55:24]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/20087/">publish-testray-report#20087</a><br/></div></div>

2023-04-11 10:58 UTC, AfonsoHSantos requested changes

2023-04-11 10:58 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFClaim.macro
> +			key_index = ${goClaim},
Hi @marinaasant0s, please replace this 'goClaim' with 'claimId'.

2023-04-11 10:58 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFClaim.macro
> +		return ${orderID};
Hi @marinaasant0s, please replace the variable 'orderId' with 'claimId'

2023-04-11 10:58 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMDashboards.testcase
> +		task ("And I search for Claim ID") {
Hi @marinaasant0s, rename this task to 'And I search for the Claim ID'

2023-04-11 10:58 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMDashboards.testcase
> +		task ("When I go back to Dashboard page and get the new amount of approved MDF Claims approved Value") {
Hi @marinaasant0s, there is a typo. Please rename your task to 'When I go back to Dashboard page and get the new amount of approved MDF Claims Value'

2023-04-11 10:58 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMDashboards.testcase
> +		task ("When I go back to Dashboard page and get the new amount of Claim MDF Value") {
Hi @marinaasant0s, please replace 'Claim' with 'Claimed'

2023-04-11 10:58 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMDashboards.testcase
> +		task ("Then the actual amount of Claim MDF value was increased") {
Hi @marinaasant0s, please replace 'Claim' with 'Claimed'

2023-04-17 20:31 UTC, closed without merging