LPS-177320
pt-liferay-solutions/liferay-portal pull request #3778
Opened 2023-04-18 14:49 UTC by MGabriellaS

2023-04-18 15:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/5959/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/5959/jenkins-report.html">here</a>.</b></p>

2023-04-18 15:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9afe8f199d919ab223ae0a54e4a9d42fddb3b898">9afe8f199d919ab223ae0a54e4a9d42fddb3b898</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MGabriellaS/liferay-portal/tree/LPS-177320">LPS-177320</a><br/>Branch GIT ID: <a href="https://github.com/MGabriellaS/liferay-portal/commit/8450cbc5007518773477ba3b968e27a02d2beb59">8450cbc5007518773477ba3b968e27a02d2beb59</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/5959/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/5959/jenkins-report.html">here</a>.</h5></details></html>

2023-04-18 15:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/5959/">test-portal-source-format#5959</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/5959/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3778">pt-liferay-solutions#3778</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2273238454">[master] ci:test:sf - MGabriellaS &gt; pt-liferay-solutions - PR#3778 - 2023-04-18[08:10:08]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/3449/">publish-testray-report#3449</a><br/></div></div>

2023-04-18 20:37 UTC, AfonsoHSantos requested changes

2023-04-18 20:37 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase
> +				typeOfActivity = "Miscellaneous Marketing");
Hi @MGabriellaS, could you please change it to create the MDF via API?

2023-04-18 20:37 UTC, AfonsoHSantos commented on test.properties
> +
Hi @MGabriellaS, it shouldn't be sent with your test. It's a change that remains only locally.

2023-04-19 16:55 UTC, MGabriellaS commented
ci:test:sf

2023-04-19 16:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/2606/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2606/jenkins-report.html">here</a>.</b></p>

2023-04-19 17:00 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f37b1ce60e91915c4b3b60abcd88c47acac7c9cb">f37b1ce60e91915c4b3b60abcd88c47acac7c9cb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MGabriellaS/liferay-portal/tree/LPS-177320">LPS-177320</a><br/>Branch GIT ID: <a href="https://github.com/MGabriellaS/liferay-portal/commit/b49ee3f27b0abab8e62d317aecdea296948a3d80">b49ee3f27b0abab8e62d317aecdea296948a3d80</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/2606/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2606/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMMDFRequest.testcase expected:&lt;...s a test for LPS-177[043. Verify that If all claims (two) were made, so the message 'No more claim can be submitted' and the claim button will be not displayed anymore"
     [java]   @priority = 5
     [java]   test VerifyMessageWhenTwoClaimsWasMade \{
     [java]     property test.name.skip.portal.instance = "PRMMDFRequest#VerifyMessageWhenTwoClaimsWasMade";
     [java] 
     [java]     // Temporarily skip portal instances to get tests running for pending release. LRQA-80052
     [java] 
     [java]     task ("Given that a partner submit a new MDF Request") \{
     [java]       JSONPRM.createMDFRequest(
     [java]         secondActivityName = "Activity Name 2",
     [java]         secondBudgetValueList = 1000);
     [java]     \}
     [java] 
     [java]     task ("When a manager approves the submitted MDF") \{
     [java]       User.logoutAndLoginPG(
     [java]         userLoginEmailAddress = "manager@liferay.com",
     [java]         userLoginFullName = "manager");
     [java] 
     [java]       PRMUtils.gotoPRM();
     [java] 
     [java]       PRMHomePage.gotoQuickLinksOption(
     [java]         buttonLink = "mdf-requests",
     [java]         buttonText = "MDF");
     [java] 
     [java]       PRMMDFRequest.goToMDF(campaignName = "Campaign Name");
     [java] 
     [java]       PRMMDFRequest.changeMDFStatus(key_statusButton = "Approve");
     [java]     \}
     [java] 
     [java]     task ("And a partner makes two claims") \{
     [java]       User.logoutAndLoginPG(
     [java]         userLoginEmailAddress = "partner@liferay.com",
     [java]         userLoginFullName = "partner");
     [java] 
     [java]       PRMUtils.gotoPRM();
     [java] 
     [java]       PRMHomePage.gotoQuickLinksOption(
     [java]         buttonLink = "mdf-requests",
     [java]         buttonText = "MDF");
     [java] 
     [java]       PRMMDFRequest.goToMDF(campaignName = "Campaign Name");
     [java] 
     [java]       PRMMDFClaim.createNewClaim(
     [java]         listLeads = "Document_1.xlsx",
     [java]         reimbursementInvoice = "Document_1.png",
     [java]         thirdInvoice = "Document_1.png");
     [java] 
     [java]       PRMMDFClaim.createNewClaim(
     [java]         activityIndex = 1,
     [java]         listLeads = "Document_1.xlsx",
     [java]         reimbursementInvoice = "Document_1.png",</pre></details></html>

2023-04-19 17:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/2606/">test-portal-source-format#2606</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2606/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3778">pt-liferay-solutions#3778</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2274707280">[master] ci:test:sf - MGabriellaS &gt; pt-liferay-solutions - PR#3778 - 2023-04-19[09:56:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/9461/">publish-testray-report#9461</a><br/></div></div>

2023-04-19 18:29 UTC, MGabriellaS commented
ci:test:sf

2023-04-19 18:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-source-format/6232/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6232/jenkins-report.html">here</a>.</b></p>

2023-04-19 18:35 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f37b1ce60e91915c4b3b60abcd88c47acac7c9cb">f37b1ce60e91915c4b3b60abcd88c47acac7c9cb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MGabriellaS/liferay-portal/tree/LPS-177320">LPS-177320</a><br/>Branch GIT ID: <a href="https://github.com/MGabriellaS/liferay-portal/commit/ffb94c719fbe19672a07de48e3212738a610b61f">ffb94c719fbe19672a07de48e3212738a610b61f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-source-format/6232/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6232/jenkins-report.html">here</a>.</h5></details></html>

2023-04-19 18:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-17.liferay.com/job/test-portal-source-format/6232/">test-portal-source-format#6232</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6232/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3778">pt-liferay-solutions#3778</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2274820979">[master] ci:test:sf - MGabriellaS &gt; pt-liferay-solutions - PR#3778 - 2023-04-19[11:30:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-17.liferay.com/job/publish-testray-report/3139/">publish-testray-report#3139</a><br/></div></div>

2023-04-27 15:15 UTC, AfonsoHSantos commented
Hi @MGabriellaS, thanks for working on it!
I've resent this test with some improvements here: #3854

2023-04-27 15:16 UTC, closed without merging