wip
pt-liferay-solutions/liferay-portal pull request #3853
Opened 2023-04-27 14:38 UTC by rafaelfs98

2023-04-27 14:38 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-04-27 14:39 UTC, rafaelfs98 commented
@kevenleone

2023-04-27 17:23 UTC, kevenleone requested changes
see

2023-04-27 17:23 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Suites/SuiteForm.tsx
> +		context.suiteCasesItems ? context.suiteCasesItems : []
```suggestion
		context.suiteCasesItems ??  []
```

2023-04-27 17:23 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Suites/SuiteForm.tsx
> +		if (caseParametersWath) {
```suggestion
	const caseParametersWatch = watch('caseParameters');

	const useCaseFilter = () => {
		if (caseParametersWatch) {
```

2023-04-27 17:23 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Suites/SuiteForm.tsx
> +			const caseParameters = JSON.parse(caseParametersWath as string);
```suggestion
			const caseParameters = JSON.parse(caseParametersWatch as string);
```

2023-04-27 17:23 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Suites/SuiteForm.tsx
> +			if (caseParameters?.testrayCaseTypes) {
Add priority here

2023-04-27 17:23 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Suites/SuiteForm.tsx
> +	const useCaseFilter = () => {
```suggestion
	const getCaseParametersFilter = useCallback... / useMemo
```

if callback = getCaseParametersFilter()
if memo = caseParametersFilter

2023-04-27 17:23 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Suites/SuiteForm.tsx
> +	const listViewViseble = !!cases.length || !!caseParametersWath;
```suggestion
	const listViewVisible = !!(cases.length || caseParametersWatch);
```

2023-04-27 17:23 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Suites/SuiteForm.tsx
> +			{caseParametersWath || !!cases.length ? (
```suggestion
			{listViewVisible ? (
```

2023-04-27 17:23 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Suites/SuiteForm.tsx
> +			{caseParametersWath || !!cases.length ? (
try to remove this  `<div  />` and use `&&` instead of `?`

2023-04-27 17:23 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Suites/SuiteForm.tsx
> +			{listViewViseble && (
```suggestion
			{listViewVisible && (
```

2023-04-27 17:23 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Suites/SuiteOutlet.tsx
> +				filter,
add pageSize

2023-04-28 17:03 UTC, kevenleone requested changes

2023-04-28 17:03 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Suites/SuiteForm.tsx
> +						getCaseValues(caseParameters.testrayComponents)
```suggestion
						getCaseValues(caseParameters.testrayPriorities)
```

2023-04-28 17:52 UTC, kevenleone commented
Just starting reviewing :)

2023-04-28 20:14 UTC, kevenleone commented
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/3870#issuecomment-1528041725

2023-04-28 20:14 UTC, closed without merging