LPS-183125 Adding Users Page Restriction
pt-liferay-solutions/liferay-portal pull request #3856
Opened 2023-04-27 18:08 UTC by EugenioAntunes

2023-04-27 18:08 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-04-27 18:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c22d14967bf01c8efa5642362418d6394a8574dc">c22d14967bf01c8efa5642362418d6394a8574dc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/EugenioAntunes/liferay-portal/tree/pr-3839">pr-3839</a><br/>Branch GIT ID: <a href="https://github.com/EugenioAntunes/liferay-portal/commit/5844af66a0f56d691cfb181e1139b2c53f9220d0">5844af66a0f56d691cfb181e1139b2c53f9220d0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/423/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/423/jenkins-report.html">here</a>.</h5></details></html>

2023-04-27 18:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/423/">test-portal-source-format#423</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/423/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3856">pt-liferay-solutions#3856</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2283017466">[master] ci:test:sf - EugenioAntunes &gt; pt-liferay-solutions - PR#3856 - 2023-04-27[11:12:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/1417/">publish-testray-report#1417</a><br/></div></div>

2023-04-27 18:20 UTC, rafaelfs98 approved these changes
Nice Joob man :fire:

2023-04-27 18:32 UTC, Elvinho approved these changes
Nice 💾

2023-04-27 18:56 UTC, welitonpe approved these changes
Good Job!!! :fire: :fire: :fire:

2023-04-27 19:02 UTC, alvarolealdl approved these changes
Good Job @EugenioAntunes

2023-04-28 12:27 UTC, kevenleone requested changes
@EugenioAntunes thank you for the hard work, it looks really good!

the suggestions I made was just `typo` to keep the consistence to the project

2023-04-28 12:27 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Cases/index.tsx
> +				testrayCaseRestImpl.transformDataFromList(response)
```suggestion
				testrayCaseImpl.transformDataFromList(response)
```

2023-04-28 12:27 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/services/rest/TestrayRequirement.ts
> +class TestrayRequirementsImpl extends Rest<Requirement, TestrayRequirement> {
Add space

```suggestion

class TestrayRequirementsImpl extends Rest<Requirement, TestrayRequirement> {
```

2023-04-28 12:27 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/services/rest/TestraySuite.ts
> +export {testraySuiteImpl};
```suggestion
const testraySuiteImpl = new TestraySuiteImpl();

export {testraySuiteImpl};
```

2023-04-28 12:46 UTC, EugenioAntunes commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/CompareRuns/CompareRunsCases.tsx
> +import {testrayCaseRestImpl} from '~/services/rest/TestrayCase';
Done!

2023-04-28 12:49 UTC, EugenioAntunes commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/CompareRuns/CompareRunsCases.tsx
> +						testrayCaseRestImpl.uri
Done

2023-04-28 12:52 UTC, EugenioAntunes commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Cases/CaseForm.tsx
> +	testrayCaseRestImpl,
Done!

2023-04-28 12:53 UTC, EugenioAntunes commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Suites/Suite.tsx
> +	testrayCaseRestImpl,
Done!

2023-04-28 12:55 UTC, EugenioAntunes commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/services/rest/TestrayCase.ts
> +export {testrayCaseRestImpl};
Done!

2023-04-28 12:56 UTC, EugenioAntunes commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Cases/CaseForm.tsx
> +				update: (id, data) => testrayCaseRestImpl.update(id, data),
Done!

2023-04-28 12:57 UTC, EugenioAntunes commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Cases/CaseForm.tsx
> +	restImpl: testrayCaseRestImpl,
Done!

2023-04-28 13:01 UTC, EugenioAntunes commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Cases/CaseOutlet.tsx
> +				testrayCaseRestImpl.transformData(response),
Done!

2023-04-28 13:05 UTC, EugenioAntunes commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Cases/Export.tsx
> +				testrayCaseRestImpl.transformDataFromList(response),
Done!

2023-04-28 13:06 UTC, EugenioAntunes commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Cases/index.tsx
> +import {testrayCaseRestImpl} from '../../../services/rest';
Done!

2023-04-28 13:06 UTC, EugenioAntunes commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Cases/index.tsx
> +			resource={testrayCaseRestImpl.resource}
Done!

2023-04-28 13:07 UTC, EugenioAntunes commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Project/Cases/index.tsx
> +				testrayCaseRestImpl.transformDataFromList(response)
Done!

2023-04-28 13:14 UTC, EugenioAntunes commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/pages/Manage/User/UserForm.tsx
> +});
Done!

2023-04-28 17:00 UTC, kevenleone approved these changes
LGTM 🔥 

Well done @EugenioAntunes

2023-04-28 17:00 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-04-28 17:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/6436/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6436/jenkins-report.html">here</a>.</b></p>

2023-04-28 17:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/df115f11c69bb28a7915435bb7ff559d233a5369">df115f11c69bb28a7915435bb7ff559d233a5369</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/EugenioAntunes/liferay-portal/tree/pr-3839">pr-3839</a><br/>Branch GIT ID: <a href="https://github.com/EugenioAntunes/liferay-portal/commit/9ec5dd9d5c9ccb65dc36784f9484d27e3312d5f4">9ec5dd9d5c9ccb65dc36784f9484d27e3312d5f4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/6436/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6436/jenkins-report.html">here</a>.</h5></details></html>

2023-04-28 17:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/6436/">test-portal-source-format#6436</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6436/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3856">pt-liferay-solutions#3856</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2284745738">[master] ci:test:sf - EugenioAntunes &gt; pt-liferay-solutions - PR#3856 - 2023-04-28[10:00:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/24380/">publish-testray-report#24380</a><br/></div></div>

2023-04-28 17:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/11018/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11018/jenkins-report.html">here</a>.</b></p>

2023-04-28 19:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 27 out of 28 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 56 out of 57 jobs passed in 1 hour 15 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/df115f11c69bb28a7915435bb7ff559d233a5369">df115f11c69bb28a7915435bb7ff559d233a5369</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7abd98a75d206c23f6a78182a8ee657975b4e17f">7abd98a75d206c23f6a78182a8ee657975b4e17f</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2284596536">EE Development Acceptance (master) - 4494 - 2023-04-28[04:35:55]</a></p><details><summary><strong>ci:test:stable - 27 out of 28 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>build-iw-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/503348/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/196273/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/496501/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/199716/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/194448/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/196272/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/365196/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/514136/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/503350/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495185/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/101516/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/513146/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/195358/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/204242/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/514137/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/553502/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495184/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/75784/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495187/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/75785/"><strike>modules-integration-mysql57-jdk8_stable/0/1</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/463232/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/195359/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/489508/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-mysql57-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/365199/">portal-license-smoke-mysql57-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/194449/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/503351/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495186/">unit-jdk8_stable/0/0</a></li></ul></li><li>workspace-compile-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/189957/">workspace-compile-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>27 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 55 out of 57 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/11018/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/503348/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/196273/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/576178/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/101518/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/365198/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/186547/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/496501/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/576179/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/553499/">functional-smoke-tomcat90-postgresq [...]

2023-04-28 19:10 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/11018//consoleFull)

2023-04-28 19:13 UTC, liferay-continuous-integration commented
Error has occurred while attempting to forward pull request to `brianchandotcom`. Retrying in 1 minute...
See console log for detail:[Full Console](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/11018//consoleFull)

2023-04-28 19:15 UTC, liferay-continuous-integration commented
Error has occurred while attempting to forward pull request to `brianchandotcom`. Retrying in 1 minute...
See console log for detail:[Full Console](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/11018//consoleFull)

2023-04-28 19:19 UTC, liferay-continuous-integration commented
Error has occurred while forwarding pull request to `brianchandotcom`.
Please try again later or contact the CI team for assistance.
See console log for details: [Full Console](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/11018//consoleFullconsoleText)

2023-04-28 20:13 UTC, kevenleone commented
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/3870#issuecomment-1528041725

2023-04-28 20:13 UTC, closed without merging