Add Logic in Table to Sort itens
pt-liferay-solutions/liferay-portal pull request #3861
Opened 2023-04-27 19:11 UTC by Elvinho

2023-04-27 19:11 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-04-27 19:46 UTC, EugenioAntunes approved these changes
Nice job, man 👊🏼 👊🏼 👊🏼

2023-04-27 19:51 UTC, rafaelfs98 approved these changes
LGTM :fire:

2023-04-27 21:11 UTC, welitonpe approved these changes
LGTM :fire:

2023-04-28 12:50 UTC, kevenleone requested changes

2023-04-28 12:50 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/Table/index.tsx
> +										className="cursor-pointer"
No need to add cursor pointer if the column is not sortable, will give a false impression to the user that he can perform an action.

```suggestion
										className={classNames({'cursor-pointer': column.sortable})}
```

2023-04-28 12:50 UTC, kevenleone commented
The rest looks good, thank you @Elvinho

2023-04-28 12:51 UTC, kevenleone commented
@Elvinho 

❌ The LPS is missing on your commit message

2023-04-28 13:12 UTC, kevenleone commented
ci:test:sf

2023-04-28 13:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/4496/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4496/jenkins-report.html">here</a>.</b></p>

2023-04-28 13:16 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7abd98a75d206c23f6a78182a8ee657975b4e17f">7abd98a75d206c23f6a78182a8ee657975b4e17f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Elvinho/liferay-portal/tree/LPS-182937">LPS-182937</a><br/>Branch GIT ID: <a href="https://github.com/Elvinho/liferay-portal/commit/ea891d20b92b119028b5885d3f4d3d9551342172">ea891d20b92b119028b5885d3f4d3d9551342172</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4496/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4496/jenkins-report.html">here</a>.</h5><pre>     [exec] yarn install v1.13.0
     [exec] warning Missing name in workspace at "/opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-faro", ignoring.
     [exec] [1/4] Resolving packages...
     [exec] warning Resolution field "@types/html-minifier-terser@5.1.0" is incompatible with requested version "@types/html-minifier-terser@^6.0.0"
     [exec] success Already up-to-date.
     [exec] Done in 1.28s.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ liferay-npm-scripts check
     [exec] apps/site-initializer/site-initializer-testray/site-initializer-testray/extra/remote-app/src/components/Table/index.tsx: BAD
     [exec] Prettier checked 2 files, 1 file has problems
     [exec] 
     [exec] 1 of 3 jobs failed
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2023-04-28 13:16:21.144.
     [exec] 3 actionable tasks: 2 executed, 1 up-to-date
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2023-04-28-06-16-07.html
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$3(ExecuteActionsTaskExecuter.java:186)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:268)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)</pre></details></html>

2023-04-28 13:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4496/">test-portal-source-format#4496</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4496/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3861">pt-liferay-solutions#3861</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2284452848">[master] ci:test:sf - Elvinho &gt; pt-liferay-solutions - PR#3861 - 2023-04-28[06:13:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/16579/">publish-testray-report#16579</a><br/></div></div>

2023-04-28 17:45 UTC, kevenleone commented
Just starting reviewing :)

2023-04-28 20:14 UTC, closed without merging