LPS-183744 Add Account Group On Site Initializer
pt-liferay-solutions/liferay-portal pull request #3926
Opened 2023-05-08 17:56 UTC by joaodamasceno2001

2023-05-08 17:57 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-05-08 17:57 UTC, joaodamasceno2001 commented
ci:test:sf

2023-05-08 18:01 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/576a6c09f5f21bd0fb6d556c08bf678c242f34f6">576a6c09f5f21bd0fb6d556c08bf678c242f34f6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joaodamasceno2001/liferay-portal/tree/LPS-183744">LPS-183744</a><br/>Branch GIT ID: <a href="https://github.com/joaodamasceno2001/liferay-portal/commit/058354314af9641e1836c92b40e268db9ef07532">058354314af9641e1836c92b40e268db9ef07532</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/4930/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4930/jenkins-report.html">here</a>.</h5></details></html>

2023-05-08 18:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/4930/">test-portal-source-format#4930</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4930/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3926">pt-liferay-solutions#3926</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2297672113">[master] ci:test:sf - joaodamasceno2001 &gt; pt-liferay-solutions - PR#3926 - 2023-05-08[10:57:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/3477/">publish-testray-report#3477</a><br/></div></div>

2023-05-08 19:48 UTC, nNilton requested changes

2023-05-08 19:48 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender-test-bundle-1/src/main/resources/site-initializer/account-groups.json
> +		"externalReferenceCode": "ERC-01",
please rename ERC to TESTACCOUNTGROUP1 ...

2023-05-08 19:48 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/BundleSiteInitializer.java
> +		AccountGroupResource.Factory accountGroupResourceFactory,
sort

2023-05-08 19:48 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/BundleSiteInitializer.java
> +		_accountGroupResourceFactory = accountGroupResourceFactory;
sort

2023-05-08 19:48 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender-test/src/testIntegration/java/com/liferay/site/initializer/extender/internal/test/BundleSiteInitializerTest.java
> +		_assertAccountGroups1();
sort

2023-05-08 19:48 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender-test/src/testIntegration/java/com/liferay/site/initializer/extender/internal/test/BundleSiteInitializerTest.java
> +		_assertAccountGroups2();
sort

2023-05-08 19:48 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/BundleSiteInitializer.java
> +			_invoke(() -> _addAccountGroups(serviceContext));
sort

2023-05-08 19:48 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/SiteInitializerExtension.java
> +			accountResourceFactory, accountGroupResourceFactory,
sort

2023-05-08 19:48 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/SiteInitializerFactoryImpl.java
> +			_accountResourceFactory, _accountGroupResourceFactory,
sort

2023-05-08 19:48 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender-test-bundle-1/src/main/resources/site-initializer/account-groups.json
> +		"name": "Test 1"
please rename to Test Account Group 1

2023-05-08 21:38 UTC, joaodamasceno2001 commented
ci:test:sf

2023-05-08 21:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/4890/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4890/jenkins-report.html">here</a>.</b></p>

2023-05-08 21:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/576a6c09f5f21bd0fb6d556c08bf678c242f34f6">576a6c09f5f21bd0fb6d556c08bf678c242f34f6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joaodamasceno2001/liferay-portal/tree/LPS-183744">LPS-183744</a><br/>Branch GIT ID: <a href="https://github.com/joaodamasceno2001/liferay-portal/commit/bece713f1d9692ac1f1ffdf52faf29a0b8de8db8">bece713f1d9692ac1f1ffdf52faf29a0b8de8db8</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/4890/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4890/jenkins-report.html">here</a>.</h5></details></html>

2023-05-08 21:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/4890/">test-portal-source-format#4890</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4890/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3926">pt-liferay-solutions#3926</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2297879415">[master] ci:test:sf - joaodamasceno2001 &gt; pt-liferay-solutions - PR#3926 - 2023-05-08[14:38:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/18264/">publish-testray-report#18264</a><br/></div></div>

2023-05-09 12:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/4898/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4898/jenkins-report.html">here</a>.</b></p>

2023-05-09 12:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/56ea09f602ee231f3292ead33b58caf70c02a67d">56ea09f602ee231f3292ead33b58caf70c02a67d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joaodamasceno2001/liferay-portal/tree/LPS-183744">LPS-183744</a><br/>Branch GIT ID: <a href="https://github.com/joaodamasceno2001/liferay-portal/commit/373f8315d8b4a209a66a5ecfeec88820b4cd2d97">373f8315d8b4a209a66a5ecfeec88820b4cd2d97</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/4898/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4898/jenkins-report.html">here</a>.</h5></details></html>

2023-05-09 12:52 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/4898/">test-portal-source-format#4898</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4898/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3926">pt-liferay-solutions#3926</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2298752910">[master] ci:test:sf - joaodamasceno2001 &gt; pt-liferay-solutions - PR#3926 - 2023-05-09[05:45:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/18286/">publish-testray-report#18286</a><br/></div></div>

2023-05-09 14:12 UTC, joaodamasceno2001 commented
ci:test:sf

2023-05-09 14:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/2796/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2796/jenkins-report.html">here</a>.</b></p>

2023-05-09 14:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/56ea09f602ee231f3292ead33b58caf70c02a67d">56ea09f602ee231f3292ead33b58caf70c02a67d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joaodamasceno2001/liferay-portal/tree/LPS-183744">LPS-183744</a><br/>Branch GIT ID: <a href="https://github.com/joaodamasceno2001/liferay-portal/commit/6796dd1fe93955b9c2f0442e4785cf39b3ecbc24">6796dd1fe93955b9c2f0442e4785cf39b3ecbc24</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/2796/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2796/jenkins-report.html">here</a>.</h5></details></html>

2023-05-09 14:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/2796/">test-portal-source-format#2796</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2796/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3926">pt-liferay-solutions#3926</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2298807219">[master] ci:test:sf - joaodamasceno2001 &gt; pt-liferay-solutions - PR#3926 - 2023-05-09[07:12:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/10143/">publish-testray-report#10143</a><br/></div></div>

2023-05-09 18:07 UTC, nNilton approved these changes

2023-05-09 18:07 UTC, nNilton commented
waiting for @joseabelenda review

2023-05-10 17:13 UTC, joaodamasceno2001 commented
ci:test:sf

2023-05-10 17:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/6624/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6624/jenkins-report.html">here</a>.</b></p>

2023-05-10 17:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/73ab9bf82e0d38f99fabc6a51416cfe7bc2f07d1">73ab9bf82e0d38f99fabc6a51416cfe7bc2f07d1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joaodamasceno2001/liferay-portal/tree/LPS-183744">LPS-183744</a><br/>Branch GIT ID: <a href="https://github.com/joaodamasceno2001/liferay-portal/commit/d7fe6cb6f16e7ceae1e41a3c756de8c846fd7898">d7fe6cb6f16e7ceae1e41a3c756de8c846fd7898</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/6624/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6624/jenkins-report.html">here</a>.</h5></details></html>

2023-05-10 17:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/6624/">test-portal-source-format#6624</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/6624/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3926">pt-liferay-solutions#3926</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2300221352">[master] ci:test:sf - joaodamasceno2001 &gt; pt-liferay-solutions - PR#3926 - 2023-05-10[10:14:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/25066/">publish-testray-report#25066</a><br/></div></div>

2023-05-12 14:55 UTC, nNilton commented
ci:test:relevant

2023-05-12 14:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fe3c34314ebba0343bb825d9ca88b405c2a1f96d">fe3c34314ebba0343bb825d9ca88b405c2a1f96d</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/576a6c09f5f21bd0fb6d556c08bf678c242f34f6">576a6c09f5f21bd0fb6d556c08bf678c242f34f6</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2297678127">EE Development Acceptance (master) - 4518 - 2023-05-08[08:35:25]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/966/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/966/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/966/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>Please fix <strong>rebase errors</strong> on <strong><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/3926">joaodamasceno2001/LPS-183744</a></strong><pre>Unable to rebase master-temp-1683903385628 to master
Rebasing (1/7)
error: could not apply 512b01ec445f... LPS-183744 Create Method To Add Account Group On site Initializer
Resolve all conflicts manually, mark them as resolved with
"git add/rm &lt;conflicted_files&gt;", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 512b01ec445f... LPS-183744 Create Method To Add Account Group On site Initializer</pre></p></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2023-05-12 17:43 UTC, closed without merging