LPS-182727
pt-liferay-solutions/liferay-portal pull request #4041
Opened 2023-05-17 20:54 UTC by juliosilveira77

2023-05-17 20:54 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-05-17 21:07 UTC, juliosilveira77 commented
ci:test:sf

2023-05-17 21:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/5191/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5191/jenkins-report.html">here</a>.</b></p>

2023-05-17 21:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/86809550c8495c489b6a1d5d47b2d0995084b4cd">86809550c8495c489b6a1d5d47b2d0995084b4cd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliosilveira77/liferay-portal/tree/LPS-182727">LPS-182727</a><br/>Branch GIT ID: <a href="https://github.com/juliosilveira77/liferay-portal/commit/34ea35a3daf0c781c6bc04ff05573410529426f9">34ea35a3daf0c781c6bc04ff05573410529426f9</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5191/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5191/jenkins-report.html">here</a>.</h5><div><p>POSHI Validation Failure<pre>     [exec] 4 errors in POSHI
     [exec] 
     [exec] Invalid path name EVPNavigation at:
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPHomePage.testcase:64
     [exec]   57 |        \}
     [exec]   58 |    \}
     [exec]   59 |
     [exec]   60 |    @description = "This is a test for LPS-182727. Verify that Requests option only will be displayed to logged-in users."
     [exec]   61 |    @priority = 4
     [exec]   62 |    test CannotSeeRequestPageWithoutBeLoggedIn \{
     [exec]   63 |        task ("When the element is found") \{
     [exec] &gt; 64 |            AssertElementPresent(
     [exec]   65 |                key_navItem = "Request",
     [exec]   66 |                locator1 = "EVPNavigation#NAV_LINK");
     [exec]   67 |        \}
     [exec]   68 |
     [exec]   69 |        task ("Then logout") \{
     [exec]   70 |            User.logoutPG();
     [exec]   71 |        \}
     [exec] 
     [exec] 
     [exec] Invalid path name EVPNavigation at:
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPHomePage.testcase:80
     [exec]   73 |        task ("And enter the URL logged out") \{
     [exec]   74 |            var portalURL = PropsUtil.get("portal.url");
     [exec]   75 |
     [exec]   76 |            Navigator.openSpecificURL(url = "\$\{portalURL\}/web/evp");
     [exec]   77 |        \}
     [exec]   78 |
     [exec]   79 |        task ("Then the element is not found") \{
     [exec] &gt; 80 |            AssertElementNotPresent(
     [exec]   81 |                key_navItem = "Request",
     [exec]   82 |                locator1 = "EVPNavigation#NAV_LINK");
     [exec]   83 |        \}
     [exec]   84 |    \}
     [exec]   85 |
     [exec]   86 |\}
     [exec] 
     [exec] 
     [exec] Unable to find class EVPUtils at:
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPHomePage.testcase:21
     [exec]   14 |        task ("Set up instance and sign in") \{
     [exec]   15 |            TestCase.setUpPortalInstance();
     [exec]   16 |
     [exec]   17 |            User.firstLoginPG();
     [exec]   18 |        \}
     [exec]   19 |
     [exec]   20 |        task ("Create a new EVP Site") \{
     [exec] &gt; 21 |            EVPUtils.addEVPSite();
     [exec]   22 |        \}
     [exec]   23 |
     [exec]   24 |        task ("Add a Employee user") \{
     [exec]   25 |            JSONUser.addUser(
     [exec]   26 |                userEmailAddress = "Employee@liferay.com",
     [exec]   27 |                userFirstName = "Employee",
     [exec]   28 |                userLastName = "Employee",
     [exec] 
     [exec] 
     [exec] Unable to find class EVPUtils at:
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPHomePage.testcase:46
     [exec]   39 |                roleTitle = "Employee",
     [exec]   40 |                userEmailAddress = "Employee@liferay.com",
     [exec]   41 |                userFirstName = "Employee",
     [exec]   42 |                userLastName = "Employee",
     [exec]   43 |                userScreenName = "Employee");
     [exec]   44 |        \}
     [exec]   45 |
     [exec] &gt; 46 |        EVPUtils.gotoEVP();
     [exec]   47 |    \}
     [exec]   48 |
     [exec]   49 |    tearDown \{
     [exec]   50 |        var testPortalInstance = PropsUtil.get("test.portal.instance");
     [exec]   51 |
     [exec]   52 |        if (\$\{testPortalInstance\} == "true") \{
     [exec]   53 |            PortalInstances.tearDownCP();
     [exec] 
     [exec] 
     [exec] 
     [exec] Exception in thread "main" java.lang.Exception
     [exec]   at com.liferay.poshi.core.PoshiValidation._throwExceptions(PoshiValidation.java:2028)
     [exec]   at com.liferay.poshi.core.PoshiValidation.validate(PoshiValidation.java:144)
     [exec]   at com.liferay.poshi.core.PoshiValidation.main(PoshiValidation.java:75)
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':validatePoshi'.
     [exec] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Get more help at https://help.gradle.org
     [exec] 
     [exec] BUILD FAILED</pre></p></div></details></html>

2023-05-17 21:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5191/">test-portal-source-format#5191</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5191/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4041">pt-liferay-solutions#4041</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2308006064">[master] ci:test:sf - juliosilveira77 &gt; pt-liferay-solutions - PR#4041 - 2023-05-17[14:07:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/19408/">publish-testray-report#19408</a><br/></div></div>

2023-05-25 21:57 UTC, juliosilveira77 commented
ci:test:sf

2023-05-25 21:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/2951/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2951/jenkins-report.html">here</a>.</b></p>

2023-05-25 22:01 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f350a1cd720339741f646ad8041e7e0f7fec6158">f350a1cd720339741f646ad8041e7e0f7fec6158</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliosilveira77/liferay-portal/tree/LPS-182727">LPS-182727</a><br/>Branch GIT ID: <a href="https://github.com/juliosilveira77/liferay-portal/commit/77a225f57e590e78c7bd7ab31e646b1e9a06bfff">77a225f57e590e78c7bd7ab31e646b1e9a06bfff</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/2951/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2951/jenkins-report.html">here</a>.</h5></details></html>

2023-05-25 22:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/2951/">test-portal-source-format#2951</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/2951/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4041">pt-liferay-solutions#4041</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2320396612">[master] ci:test:sf - juliosilveira77 &gt; pt-liferay-solutions - PR#4041 - 2023-05-25[14:58:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/10657/">publish-testray-report#10657</a><br/></div></div>

2023-05-26 01:57 UTC, nikki-pru commented
ci:test:site-initializer-evp

2023-05-26 01:57 UTC, liferay-continuous-integration commented
The test suite specified is not a valid test suite.
Please refer to the available test suites below.
#### ci:test[:suite][:SHA|nocompile|norebase|gist-SHA]
&nbsp;&nbsp;&nbsp;&nbsp;Test the pull request. Optionally specify the name of the test suite and/or optionally specify the upstream SHA to test against or use "nocompile" to test with a prebuilt bundle or use "norebase" to test without rebasing.
<details><summary><strong>Available test suites:</strong></summary>

- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance** - Test acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-functional** - Test acceptance functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-functional-db-partition** - Test acceptance functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-release** - Compile a release bundle and execute acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-upstream** - Test acceptance upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**accessibility** - Test all accessibility tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**account** - Test Account tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud** - Test Analytics Cloud tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud-acceptance** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud-quarantine** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**app-servers** - Test Deployments on App Servers.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**auto-tagging** - Test Auto Tagging tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend** - Test backend tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend-hypersonic** - Test backend tests on Hypersonic.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blade** - Test Blade samples tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blogs** - Test Blogs tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bulk-editing** - Test Bulk Editing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bundle** - Saves a compiled tomcat bundle.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**calendar** - Test Calendar tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**clay** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**click-to-chat** - Test Click to Chat tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**clustering** - Test clustering tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**comment** - Test Comment tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce** - Test only Commerce tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-database** - Test only Commerce Database tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-es7-remote** - Test only Commerce tests with the latest compatible remote Elasticsearch 7 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-functional** - Test only Commerce functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-upgrade** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**content-page-review** - Test Content Page Review (comments) tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**continuous-integration** - Test Continuous Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**cookies** - Test Cookie Preferences tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-engine** - Test Data Engine functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-engine-db-partition** - Test Data Engine functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-integration** - Test only Data Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-integration-functional** - Test only functional Data Integration tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**db-partition** - Test Database Partitioning functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**depot** - Test Depot tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**digital-signature** - Test Digital Signature tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dl-store** - Test Document Library Store tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**document** - Test Document and Media tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**drools** - Test Drools tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dummy** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo** - Test all Echo (WCM) team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-acceptance** - Test Echo (WCM) team acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-accessibility** - Test Echo (WCM) team accessibility tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-analytics-cloud** - Test segmentation and personalization with Analytics Cloud.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-db-partition** - Test Echo (WCM) team acceptance tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-headless** - Test Echo (WCM) team headless components.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-upgrade** - Test Echo (WCM) team upgrade tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**environments** - Test environment acceptance functional tests on all available environment stacks.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**export-import** - Test exportimport tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms** - Test forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms-db-partition** - Test forms functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms-functional** - Test only functional forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**friendly-url** - Test Friendly URL tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend** - Test all Frontend Infra team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-client-extensions** - Test frontend client extensions tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-data-set** - Test frontend data set tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-dev-exp** - Test frontend developer experience tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-ui** - Test frontend ui tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend-walkthrough** - Test frontend walkthrough tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet** - Test upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet-bucket** - Test a subset of upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gradle-plugins** - Test Gradle Plugins tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless** - Test all headless team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-acceptance** - Test headless team acceptance tests considering Headless and Rest Builder.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-functional** - Headless Team functional API tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**item-selector** - Test item selector tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**jacoco-report** - Test integration and unit tests to generate JaCoCo reports.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**jdk11** - Test acceptance, smoke, and upgrade functional tests against JDK11.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**jsf** - Test Liferay Faces tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**kaleo-forms** - Test Kaleo Forms admin tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**knowledge-base** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**ldap** - Test LDAP tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**license** - Compile a release bundle and execute tests for licensing.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**license-cluster** - Compile a release bundle and execute tests for cluster licensing on 32GB slaves.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**liferay-online** - Compile a release bundle and execute tests with liferay online properties.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**liferay-sample-workspace** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lima** - Test Lima tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lima-acceptance** - Test Lima acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lima-db-partition** - Test Lima functional tests with Database Partitioning.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lima-headless** - Test Lima headless tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lima-lxc** - Lima functional tests with Lifera [...]

2023-05-26 02:00 UTC, nikki-pru commented
ci:test:osb-site-initializer-evp

2023-05-26 02:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>osb-site-initializer-evp</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8363/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8363/jenkins-report.html">here</a>.</b></p>

2023-05-26 03:31 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:osb-site-initializer-evp - 0 out of 2 jobs passed in 1 hour 31 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f350a1cd720339741f646ad8041e7e0f7fec6158">f350a1cd720339741f646ad8041e7e0f7fec6158</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f350a1cd720339741f646ad8041e7e0f7fec6158">f350a1cd720339741f646ad8041e7e0f7fec6158</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2320076545">EE Development Acceptance (master) - 4564 - 2023-05-25[08:36:04]</a></p><details><summary><strong>ci:test:osb-site-initializer-evp - 0 out of 2 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8363/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/144712/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li></ul></li></ul></div></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8363/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/144712//consoleText">functional-tomcat90-mysql57-jdk8/0/0</a><ol><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/144712//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPHeaderAndFooter_CanNavigateToPages_">LocalFile.EVPHeaderAndFooter#CanNavigateToPages</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8363/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPHeaderAndFooter_CanNavigateToPages/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8363/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPHeaderAndFooter_CanNavigateToPages/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8363/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/144712//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPHomePage_CannotSeeRequestPageWithoutBeLoggedIn_">LocalFile.EVPHomePage#CannotSeeRequestPageWithoutBeLoggedIn</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8363/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPHomePage_CannotSeeRequestPageWithoutBeLoggedIn/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8363/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPHomePage_CannotSeeRequestPageWithoutBeLoggedIn/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8363/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/144712//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPRequestListing_CanViewColumnsOnListing_">LocalFile.EVPRequestListing#CanViewColumnsOnListing</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8363/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPRequestListing_CanViewColumnsOnListing/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8363/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPRequestListing_CanViewColumnsOnListing/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8363/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li>...</li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2023-05-26 03:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8363/">test-portal-acceptance-pullrequest(master)#8363</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8363/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>osb-site-initializer-evp<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4041">pt-liferay-solutions#4041</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2320762688">[master] ci:test:osb-site-initializer-evp - juliosilveira77 &gt; pt-liferay-solutions - PR#4041 - 2023-05-25[19:00:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/18804/">publish-testray-report#18804</a><br/></div></div>

2023-05-26 12:53 UTC, juliosilveira77 commented
ci:test:sf

2023-05-26 12:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/1483/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1483/jenkins-report.html">here</a>.</b></p>

2023-05-26 12:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bfbd85b5d2cc7ca4a5b4d5efc1d5c59b5ed13d5c">bfbd85b5d2cc7ca4a5b4d5efc1d5c59b5ed13d5c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliosilveira77/liferay-portal/tree/LPS-182727">LPS-182727</a><br/>Branch GIT ID: <a href="https://github.com/juliosilveira77/liferay-portal/commit/4ed1785b9a9e0439e64deb11110bf01afeb37597">4ed1785b9a9e0439e64deb11110bf01afeb37597</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1483/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1483/jenkins-report.html">here</a>.</h5></details></html>

2023-05-26 13:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1483/">test-portal-source-format#1483</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1483/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4041">pt-liferay-solutions#4041</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2320981238">[master] ci:test:sf - juliosilveira77 &gt; pt-liferay-solutions - PR#4041 - 2023-05-26[05:54:04]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/5008/">publish-testray-report#5008</a><br/></div></div>

2023-05-29 14:13 UTC, juliosilveira77 commented
ci:test:osb-site-initializer-evp

2023-05-29 14:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>osb-site-initializer-evp</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8383/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8383/jenkins-report.html">here</a>.</b></p>

2023-05-29 16:03 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:osb-site-initializer-evp - 0 out of 2 jobs passed in 1 hour 49 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6632af54295fb2d4589e6366ee10b000c2f8568a">6632af54295fb2d4589e6366ee10b000c2f8568a</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6a945c943be10b1157f9c7d127a3ef987e59e6c0">6a945c943be10b1157f9c7d127a3ef987e59e6c0</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2323380128">EE Development Acceptance (master) - 4567 - 2023-05-29[04:35:02]</a></p><details><summary><strong>ci:test:osb-site-initializer-evp - 0 out of 2 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8383/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121608/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li></ul></li></ul></div></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8383/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121608//consoleText">functional-tomcat90-mysql57-jdk8/0/0</a><ol><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121608//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPHeaderAndFooter_CanNavigateToPages_">LocalFile.EVPHeaderAndFooter#CanNavigateToPages</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8383/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPHeaderAndFooter_CanNavigateToPages/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8383/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPHeaderAndFooter_CanNavigateToPages/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8383/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121608//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPHomePage_CannotSeeRequestPageWithoutBeLoggedIn_">LocalFile.EVPHomePage#CannotSeeRequestPageWithoutBeLoggedIn</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8383/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPHomePage_CannotSeeRequestPageWithoutBeLoggedIn/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8383/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPHomePage_CannotSeeRequestPageWithoutBeLoggedIn/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8383/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121608//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPOrganizationListing_ManagerCanViewColumnsOnListing_">LocalFile.EVPOrganizationListing#ManagerCanViewColumnsOnListing</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8383/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPOrganizationListing_ManagerCanViewColumnsOnListing/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8383/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPOrganizationListing_ManagerCanViewColumnsOnListing/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8383/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li>...</li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2023-05-29 16:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8383/">test-portal-acceptance-pullrequest(master)#8383</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8383/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>osb-site-initializer-evp<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4041">pt-liferay-solutions#4041</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2323458106">[master] ci:test:osb-site-initializer-evp - juliosilveira77 &gt; pt-liferay-solutions - PR#4041 - 2023-05-29[07:13:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/18851/">publish-testray-report#18851</a><br/></div></div>

2023-05-29 18:16 UTC, juliosilveira77 commented
ci:test:sf

2023-05-29 18:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/6395/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/6395/jenkins-report.html">here</a>.</b></p>

2023-05-29 18:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4140e7c386f40547f0d0ef9e3c97f4f58811849d">4140e7c386f40547f0d0ef9e3c97f4f58811849d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliosilveira77/liferay-portal/tree/LPS-182727">LPS-182727</a><br/>Branch GIT ID: <a href="https://github.com/juliosilveira77/liferay-portal/commit/7f995e4375691ab22c3a3b9b8f3dea77c2434a21">7f995e4375691ab22c3a3b9b8f3dea77c2434a21</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/6395/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/6395/jenkins-report.html">here</a>.</h5></details></html>

2023-05-29 18:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/6395/">test-portal-source-format#6395</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/6395/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4041">pt-liferay-solutions#4041</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2323574867">[master] ci:test:sf - juliosilveira77 &gt; pt-liferay-solutions - PR#4041 - 2023-05-29[11:16:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/23200/">publish-testray-report#23200</a><br/></div></div>

2023-06-01 22:14 UTC, nikki-pru commented
ci:test:osb-site-initializer-evp

2023-06-01 22:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>osb-site-initializer-evp</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/9873/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9873/jenkins-report.html">here</a>.</b></p>

2023-06-01 23:49 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:osb-site-initializer-evp - 0 out of 2 jobs passed in 1 hour 32 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b5d3cf7b928ddefe98e4120138bb2f778caba664">b5d3cf7b928ddefe98e4120138bb2f778caba664</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b5d3cf7b928ddefe98e4120138bb2f778caba664">b5d3cf7b928ddefe98e4120138bb2f778caba664</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2327868777">EE Development Acceptance (master) - 4576 - 2023-06-01[04:35:51]</a></p><details><summary><strong>ci:test:osb-site-initializer-evp - 0 out of 2 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/9873/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/155869/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li></ul></li></ul></div></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9873/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/155869//consoleText">functional-tomcat90-mysql57-jdk8/0/0</a><ol><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/155869//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPHeaderAndFooter_CanNavigateToPages_">LocalFile.EVPHeaderAndFooter#CanNavigateToPages</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-32/test-portal-acceptance-pullrequest(master)/9873/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPHeaderAndFooter_CanNavigateToPages/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-32/test-portal-acceptance-pullrequest(master)/9873/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPHeaderAndFooter_CanNavigateToPages/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-32/test-portal-acceptance-pullrequest(master)/9873/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/155869//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPHomePage_CannotSeeRequestPageWithoutBeLoggedIn_">LocalFile.EVPHomePage#CannotSeeRequestPageWithoutBeLoggedIn</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-32/test-portal-acceptance-pullrequest(master)/9873/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPHomePage_CannotSeeRequestPageWithoutBeLoggedIn/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-32/test-portal-acceptance-pullrequest(master)/9873/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPHomePage_CannotSeeRequestPageWithoutBeLoggedIn/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-32/test-portal-acceptance-pullrequest(master)/9873/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/155869//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPOrganizationListing_ManagerCanViewColumnsOnListing_">LocalFile.EVPOrganizationListing#ManagerCanViewColumnsOnListing</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-32/test-portal-acceptance-pullrequest(master)/9873/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPOrganizationListing_ManagerCanViewColumnsOnListing/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-32/test-portal-acceptance-pullrequest(master)/9873/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPOrganizationListing_ManagerCanViewColumnsOnListing/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-32/test-portal-acceptance-pullrequest(master)/9873/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li>...</li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2023-06-01 23:52 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/9873/">test-portal-acceptance-pullrequest(master)#9873</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9873/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>osb-site-initializer-evp<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4041">pt-liferay-solutions#4041</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2328610450">[master] ci:test:osb-site-initializer-evp - juliosilveira77 &gt; pt-liferay-solutions - PR#4041 - 2023-06-01[15:17:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/23381/">publish-testray-report#23381</a><br/></div></div>

2023-06-09 19:07 UTC, nikki-pru requested changes

2023-06-15 13:34 UTC, joelrocha68 commented
Just starting reviewing :)

2023-06-23 19:15 UTC, juliosilveira77 commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/paths/EVPUtils.path
> +	<td>KEBAB_OPTION</td>
@nikki-pru a path existente voce esta se referindo a substituir o KEBAB_OPTION ou REQUEST_COLUMNS ?

2023-06-29 20:25 UTC, closed without merging

2023-06-30 21:06 UTC, juliosilveira77 commented
Nikki, I'm sorry, I accidentally closed it, when I send the PR of the corrections I will open a new one

2023-06-30 21:07 UTC, juliosilveira77 commented
Nikki, I'm sorry, I accidentally closed it, when I send the PR of the corrections I will open a new one

2023-07-03 12:22 UTC, juliosilveira77 commented
Sorry, I closed it by mistake