LPS-180871
pt-liferay-solutions/liferay-portal pull request #4052
Opened 2023-05-18 17:42 UTC by thiagooliveiraaa

2023-05-18 17:42 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-05-19 16:30 UTC, thiagooliveiraaa commented
@nNilton

2023-05-22 14:22 UTC, nNilton requested changes

2023-05-22 14:22 UTC, nNilton commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-script/src/main/java/com/liferay/marketplace/Main.java
> +		System.out.println("Liferay URL: " + _liferayURL);
switch to log.info

2023-05-22 14:22 UTC, nNilton commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-script/src/main/java/com/liferay/marketplace/Main.java
> +		_liferayOAuthClientSecret = liferayMarketplaceOAuthClientSecret;
sort

2023-05-22 14:22 UTC, nNilton commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-script/src/main/java/com/liferay/marketplace/Main.java
> +					appProps.getProperty("LIFERAY_MARKETPLACE_LIFERAY_URL")));
let's try with a void method

2023-08-14 11:44 UTC, closed without merging