LPS-184711 Zendesk JWT integration
pt-liferay-solutions/liferay-portal pull request #4059
Opened 2023-05-19 12:41 UTC by Odrakir1

2023-05-19 12:47 UTC, Odrakir1 commented
ci:test:sf

2023-05-19 13:58 UTC, nNilton commented
ci:test:sf

2023-05-19 14:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d5acbbe09acba11b870bdc908d1393a9bd12d543">d5acbbe09acba11b870bdc908d1393a9bd12d543</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Odrakir1/liferay-portal/tree/c2c">c2c</a><br/>Branch GIT ID: <a href="https://github.com/Odrakir1/liferay-portal/commit/6bffb43dd9e99f9441b2bc209bb7ebc4eeabcb4b">6bffb43dd9e99f9441b2bc209bb7ebc4eeabcb4b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-source-format/6503/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/6503/jenkins-report.html">here</a>.</h5></details></html>

2023-05-19 14:40 UTC, nNilton requested changes

2023-05-19 14:40 UTC, nNilton commented on modules/apps/click-to-chat/click-to-chat-web/src/main/java/com/liferay/click/to/chat/web/internal/configuration/ClickToChatConfiguration.java
> +
sort alphabetically by method name

2023-05-22 13:05 UTC, nNilton commented
ci:test:sf

2023-05-22 13:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/4998/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4998/jenkins-report.html">here</a>.</b></p>

2023-05-22 13:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6a6966ccb6e75619188c96e13970d28279ae38bc">6a6966ccb6e75619188c96e13970d28279ae38bc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Odrakir1/liferay-portal/tree/c2c">c2c</a><br/>Branch GIT ID: <a href="https://github.com/Odrakir1/liferay-portal/commit/963841233935dfeaacf760a27cfe82b05c6ca413">963841233935dfeaacf760a27cfe82b05c6ca413</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/4998/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4998/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/click-to-chat/click-to-chat-web/src/main/java/com/liferay/click/to/chat/web/internal/configuration/ClickToChatConfiguration.java expected:&lt;...roviderAccountId();
     [java] [
     [java]   public String chatProviderKeyId();
     [java] 
     [java]   public String chatProviderSecretKey();
     [java] 
     [java]   public boolean guestUsersAllowed();
     [java] 
     [java]   public boolean hideInControlPanel();
     [java] 
     [java]   public String siteSettingsStrategy();
     [java] 
     [java] \}]&gt; but was:&lt;...roviderAccountId();
     [java] [  
     [java]   public String chatProviderKeyId();
     [java] 
     [java]   public String chatProviderSecretKey();
     [java] 
     [java]   public boolean guestUsersAllowed();
     [java] 
     [java]   public boolean hideInControlPanel();
     [java] 
     [java]   public String siteSettingsStrategy();
     [java] 
     [java] \}
     [java] ]&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:466)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
[stopwatch] [run.batch.test.action: 2:12.670 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:597: Java returned: 1
      [get] Getting: http://test-1-27/job/test-portal-source-format/4998//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230522061032341.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230522061032341.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null240959196.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1834670294</pre></details></html>

2023-05-22 13:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/4998/">test-portal-source-format#4998</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/4998/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4059">pt-liferay-solutions#4059</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2315257391">[master] ci:test:sf - Odrakir1 &gt; pt-liferay-solutions - PR#4059 - 2023-05-22[06:06:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/18651/">publish-testray-report#18651</a><br/></div></div>

2023-05-22 18:12 UTC, nNilton commented
ci:test:sf

2023-05-22 18:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/1394/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1394/jenkins-report.html">here</a>.</b></p>

2023-05-22 18:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6a6966ccb6e75619188c96e13970d28279ae38bc">6a6966ccb6e75619188c96e13970d28279ae38bc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Odrakir1/liferay-portal/tree/c2c">c2c</a><br/>Branch GIT ID: <a href="https://github.com/Odrakir1/liferay-portal/commit/690d393fa100e5b33ba57de2c644e723cb598812">690d393fa100e5b33ba57de2c644e723cb598812</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1394/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1394/jenkins-report.html">here</a>.</h5></details></html>

2023-05-22 18:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1394/">test-portal-source-format#1394</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1394/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4059">pt-liferay-solutions#4059</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2315550221">[master] ci:test:sf - Odrakir1 &gt; pt-liferay-solutions - PR#4059 - 2023-05-22[11:13:04]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/4693/">publish-testray-report#4693</a><br/></div></div>

2023-05-22 19:11 UTC, nNilton approved these changes

2023-05-23 02:12 UTC, nNilton commented
Could you please look at this @joseabelenda ?

2023-05-23 12:14 UTC, joseabelenda commented
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/4087

2023-05-23 12:14 UTC, closed without merging