LPS-184945 Add commerce catalog test
pt-liferay-solutions/liferay-portal pull request #4074
Opened 2023-05-22 17:15 UTC by joanagrego

2023-05-22 17:15 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-05-22 17:15 UTC, joanagrego commented
ci:test:sf

2023-05-22 17:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/6315/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/6315/jenkins-report.html">here</a>.</b></p>

2023-05-22 17:18 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6a6966ccb6e75619188c96e13970d28279ae38bc">6a6966ccb6e75619188c96e13970d28279ae38bc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joanagrego/liferay-portal/tree/LPS-184945">LPS-184945</a><br/>Branch GIT ID: <a href="https://github.com/joanagrego/liferay-portal/commit/439e4953e0b13aa127a8a8415cc4fd22d9505401">439e4953e0b13aa127a8a8415cc4fd22d9505401</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/6315/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/6315/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/taxonomy-vocabularies/company/marketplace-app-tags/business-use.json expected:&lt;...wableBy": "Anyone"
     [java] \}[]&gt; but was:&lt;...wableBy": "Anyone"
     [java] \}[
     [java] ]&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:466)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
[stopwatch] [run.batch.test.action: 1:04.638 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:597: Java returned: 1
      [get] Getting: http://test-1-32/job/test-portal-source-format/6315//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230522101821490.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230522101821490.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null715886374.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1751051166
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 149ms
[junitreport] Deleting: /tmp/null1751051166
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 05-22-2023 10:18:23:642 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</pre></details></html>

2023-05-22 17:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/6315/">test-portal-source-format#6315</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/6315/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4074">pt-liferay-solutions#4074</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2315511805">[master] ci:test:sf - joanagrego &gt; pt-liferay-solutions - PR#4074 - 2023-05-22[10:15:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/22930/">publish-testray-report#22930</a><br/></div></div>

2023-05-23 13:32 UTC, nNilton requested changes

2023-05-23 13:32 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender-test-bundle-2/src/main/resources/site-initializer/commerce-catalogs/test-commerce-catalog-1.json
> +	"name": "Test Commerce Catalog 1 update"
Use capital letter for U

2023-05-23 13:32 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender-test-bundle-2/src/main/resources/site-initializer/commerce-catalogs/test-commerce-catalog-1.products.specifications.json
> +		"title": "Test Product Specification 1 update"
capital letter u

2023-05-23 13:32 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender-test/src/testIntegration/java/com/liferay/site/initializer/extender/internal/test/BundleSiteInitializerTest.java
> +	}
please add one more catalog

2023-05-23 13:32 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender-test/src/testIntegration/java/com/liferay/site/initializer/extender/internal/test/BundleSiteInitializerTest.java
> +			productSpecification.getSpecificationKey());
move this logic to a method to assert the relation between products and spectifications using localservice

2023-05-23 13:32 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender-test/src/testIntegration/java/com/liferay/site/initializer/extender/internal/test/BundleSiteInitializerTest.java
> +		CPSpecificationOption cpSpecificationOption2 =
```suggestion
		CPSpecificationOption cpSpecificationOption =
```

2023-05-23 13:32 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender-test/src/testIntegration/java/com/liferay/site/initializer/extender/internal/test/BundleSiteInitializerTest.java
> +		CommerceCatalog commerceCatalog2 =
```suggestion
		commerceCatalog =
```

2023-05-23 20:14 UTC, joanagrego commented
ci:test:sf

2023-05-23 20:17 UTC, closed without merging

2023-05-23 20:18 UTC, joanagrego commented
Resent --> [PR](https://github.com/pt-liferay-solutions/liferay-portal/pull/4095)

2023-05-23 20:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/5172/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5172/jenkins-report.html">here</a>.</b></p>

2023-05-23 20:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/db81ab7fa06c006f5dd92437b58c370fefe67e4b">db81ab7fa06c006f5dd92437b58c370fefe67e4b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joanagrego/liferay-portal/tree/LPS-184945">LPS-184945</a><br/>Branch GIT ID: <a href="https://github.com/joanagrego/liferay-portal/commit/9d6e28bf0166a378a2a9ccd0261212e4c42881b6">9d6e28bf0166a378a2a9ccd0261212e4c42881b6</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/5172/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5172/jenkins-report.html">here</a>.</h5></details></html>

2023-05-23 20:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-7.liferay.com/job/test-portal-source-format/5172/">test-portal-source-format#5172</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5172/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4074">pt-liferay-solutions#4074</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2317303740">[master] ci:test:sf - joanagrego &gt; pt-liferay-solutions - PR#4074 - 2023-05-23[13:17:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-7.liferay.com/job/publish-testray-report/2908/">publish-testray-report#2908</a><br/></div></div>