Add possibility to associate Accounts with Organizations
pt-liferay-solutions/liferay-portal pull request #4233
Opened 2023-06-05 14:39 UTC by joaodamasceno2001

2023-06-05 14:39 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-06-05 14:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/5813/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5813/jenkins-report.html">here</a>.</b></p>

2023-06-05 14:55 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a13062369e24073e50142d397614e9d331ee0546">a13062369e24073e50142d397614e9d331ee0546</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joaodamasceno2001/liferay-portal/tree/LPS-186204">LPS-186204</a><br/>Branch GIT ID: <a href="https://github.com/joaodamasceno2001/liferay-portal/commit/2ee0b65a8395f590f7d2396621790814118370cc">2ee0b65a8395f590f7d2396621790814118370cc</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5813/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5813/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-extender/site-initializer-extender-test/src/testIntegration/java/com/liferay/site/initializer/extender/internal/test/BundleSiteInitializerTest.java expected:&lt;...odel.TemplateEntry;
     [java] [
     [java] import java.io.File;
     [java] import java.io.IOException;
     [java] import java.io.InputStream;
     [java] import java.io.Serializable;
     [java] 
     [java] import java.math.BigDecimal;
     [java] 
     [java] import java.util.Arrays;
     [java] import java.util.Dictionary;
     [java] import java.util.List;
     [java] import java.util.Map;
     [java] import java.util.Objects;
     [java] 
     [java] import javax.servlet.ServletContext;
     [java] 
     [java] import org.junit.After;
     [java] import org.junit.Assert;
     [java] import org.junit.Before;
     [java] import org.junit.ClassRule;
     [java] import org.junit.Rule;
     [java] import org.junit.Test;
     [java] import org.junit.runner.RunWith;
     [java] 
     [java] import org.osgi.framework.Bundle;
     [java] import org.osgi.framework.BundleContext;
     [java] import org.osgi.framework.FrameworkUtil;
     [java] import org.osgi.framework.InvalidSyntaxException;
     [java] import org.osgi.service.cm.Configuration;
     [java] import org.osgi.service.cm.ConfigurationAdmin;
     [java] 
     [java] import org.springframework.mock.web.MockHttpServletRequest;
     [java] import org.springframework.mock.web.MockHttpServletResponse];
     [java] 
     [java] /**
     [java]  * @author Br...&gt; but was:&lt;...odel.TemplateEntry;
     [java] [import org.junit.After;
     [java] import org.junit.Assert;
     [java] import org.junit.Before;
     [java] import org.junit.ClassRule;
     [java] import org.junit.Rule;
     [java] import org.junit.Test;
     [java] import org.junit.runner.RunWith;
     [java] import org.osgi.framework.Bundle;
     [java] import org.osgi.framework.BundleContext;
     [java] import org.osgi.framework.FrameworkUtil;
     [java] import org.osgi.framework.InvalidSyntaxException;
     [java] import org.osgi.service.cm.Configuration;
     [java] import org.osgi.service.cm.ConfigurationAdmin;
     [java] import org.springframework.mock.web.MockHttpServletRequest;
     [java] import org.springframework.mock.web.MockHttpServletResponse;
     [java] 
     [java] import javax.servlet.ServletContext;
     [java] import java.io.File;</pre></details></html>

2023-06-05 16:00 UTC, joaodamasceno2001 commented
ci:test:sf

2023-06-05 16:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-source-format/6910/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/6910/jenkins-report.html">here</a>.</b></p>

2023-06-05 16:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9ecd675f0c56497b00d1a78660a0b915a5827d86">9ecd675f0c56497b00d1a78660a0b915a5827d86</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joaodamasceno2001/liferay-portal/tree/LPS-186204">LPS-186204</a><br/>Branch GIT ID: <a href="https://github.com/joaodamasceno2001/liferay-portal/commit/34b8619259ef190c56637f102f807c33d570d7ab">34b8619259ef190c56637f102f807c33d570d7ab</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/6910/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/6910/jenkins-report.html">here</a>.</h5></details></html>

2023-06-06 18:51 UTC, nNilton requested changes

2023-06-06 18:51 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/BundleSiteInitializer.java
> +			_invoke(() -> _addOrganizationsOnAccounts(serviceContext));
add blank line before calling the method _addOrganizationsOnAccounts

2023-06-06 18:51 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/BundleSiteInitializer.java
> +			"/site-initializer/organizations-assignments.json",
rename json to accounts-organizations.json

2023-06-06 18:51 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/BundleSiteInitializer.java
> +	private void _addOrganizationsOnAccounts(ServiceContext serviceContext)
```suggestion
	private void _addAccountsOrganizations(ServiceContext serviceContext)
```

2023-06-06 18:51 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender-test-bundle-1/src/main/resources/site-initializer/organizations-assignments.json
> +		"organizationExternalReferenceCode": [
```suggestion
		"organizations": [
```

2023-06-06 20:20 UTC, joaodamasceno2001 commented
ci:test:sf

2023-06-06 20:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/7110/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/7110/jenkins-report.html">here</a>.</b></p>

2023-06-06 20:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b03a89c3de45dd65f14d86425ccff44f234ee0d6">b03a89c3de45dd65f14d86425ccff44f234ee0d6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joaodamasceno2001/liferay-portal/tree/LPS-186204">LPS-186204</a><br/>Branch GIT ID: <a href="https://github.com/joaodamasceno2001/liferay-portal/commit/e27672c525c2f7bd62e408cef72b9f64ce0a09a0">e27672c525c2f7bd62e408cef72b9f64ce0a09a0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/7110/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/7110/jenkins-report.html">here</a>.</h5></details></html>

2023-06-06 20:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/7110/">test-portal-source-format#7110</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/7110/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4233">pt-liferay-solutions#4233</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2342083192">[master] ci:test:sf - joaodamasceno2001 &gt; pt-liferay-solutions - PR#4233 - 2023-06-06[13:20:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/26732/">publish-testray-report#26732</a><br/></div></div>

2023-06-09 18:20 UTC, joaodamasceno2001 commented
ci:forward

2023-06-09 18:20 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-06-09 18:20 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:sf`

2023-06-09 20:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/5287/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5287/jenkins-report.html">here</a>.</b></p>

2023-06-09 20:29 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 1 minute</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a5dc906f7ab190d5ce0893b31f306fa00a2d7d35">a5dc906f7ab190d5ce0893b31f306fa00a2d7d35</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a13062369e24073e50142d397614e9d331ee0546">a13062369e24073e50142d397614e9d331ee0546</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2340589766">EE Development Acceptance (master) - 4581 - 2023-06-05[08:36:10]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/5287/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5287/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/5287/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>HOSTNAME=test-1-39-60.lax.liferay.com
JAVA_HOME=/opt/java/jdk8
MASTER_HOSTNAME=test-1-39
ORACLE_HOME=/u01/app/oracle/product/12.2.0/db_1
ORACLE_SID=oracl
PATH=/opt/java/ant/bin:/opt/java/jdk8/bin:/opt/java/maven/bin:/usr/lib64/qt-3.3/bin:/opt/sybase/OCS-16_0/bin/:/u01/app/oracle/product/12.2.0/db_1/bin:/opt/ibm/db2/V11.1/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/bin
SYBASE_ASE=ASE-16_0
Execute: ant -f commands/build-common.xml run-ant-target -Dant.file.name=build-test-portal-acceptance-pullrequest.xml -Dant.target= -lib commands/../lib/jenkins -propertyfile /opt/dev/projects/github/liferay-jenkins-ee/start.properties
Build step 'Execute shell' marked build as failure
[PostBuildScript] - [INFO] Executing post build scripts.
[liferay-jenkins-ee] \$ /bin/bash -e -x /tmp/jenkins9050252952949036532.sh
+ echo 'Execute: build-test-portal-acceptance-pullrequest.sh stop-current-job'
Execute: build-test-portal-acceptance-pullrequest.sh stop-current-job
+ commands/build-test-portal-acceptance-pullrequest.sh stop-current-job
ANT_OPTS=-Dhttp.nonProxyHosts="cloud*|files.liferay.org.es|it.liferay.com|localhost|mirrors-no-cache.lax.liferay.com|release*|test*" -server -verbose:gc -Xloggc:/tmp/ant-gc.log -Xms1024m -Xmx4096m -Xss2m -Xverify:none -XX:+DisableExplicitGC -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCCause -XX:+PrintGCDetails -XX:+UseParallelOldGC -XX:HeapDumpPath=/tmp/ant-oom-heap-dump.bin -XX:MaxNewSize=512m -XX:MaxMetaspaceSize=512m -XX:MaxTenuringThreshold=0 -XX:NewSize=256m -XX:MetaspaceSize=100m -XX:SurvivorRatio=65536 -XX:TargetSurvivorRatio=0
HOSTNAME=test-1-39-60.lax.liferay.com
JAVA_HOME=/opt/java/jdk8
MASTER_HOSTNAME=test-1-39
ORACLE_HOME=/u01/app/oracle/product/12.2.0/db_1
ORACLE_SID=oracl
PATH=/opt/java/ant/bin:/opt/java/jdk8/bin:/opt/java/maven/bin:/usr/lib64/qt-3.3/bin:/opt/sybase/OCS-16_0/bin/:/u01/app/oracle/product/12.2.0/db_1/bin:/opt/ibm/db2/V11.1/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/bin
SYBASE_ASE=ASE-16_0
Execute: ant -f commands/build-common.xml run-ant-target -Dant.file.name=build-test-portal-acceptance-pullrequest.xml -Dant.target=stop-current-job -lib commands/../lib/jenkins -propertyfile /opt/dev/projects/github/liferay-jenkins-ee/start.properties</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2023-06-12 15:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/12280/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12280/jenkins-report.html">here</a>.</b></p>

2023-06-12 15:16 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7f3d45d92df2ec969b7722ba6bf9063873051870">7f3d45d92df2ec969b7722ba6bf9063873051870</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a13062369e24073e50142d397614e9d331ee0546">a13062369e24073e50142d397614e9d331ee0546</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2340589766">EE Development Acceptance (master) - 4581 - 2023-06-05[08:36:10]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/12280/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12280/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/12280/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>Please fix <strong>rebase errors</strong> on <strong><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4233">joaodamasceno2001/LPS-186204</a></strong><pre>Unable to rebase master-temp-1686582939197 to master
Rebasing (1/4)
error: could not apply 79a473f0077c... LPS-186204 Create method to associate accounts to organizations
Resolve all conflicts manually, mark them as resolved with
"git add/rm &lt;conflicted_files&gt;", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 79a473f0077c... LPS-186204 Create method to associate accounts to organizations</pre></p></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2023-06-13 13:44 UTC, closed without merging