PRM Automated Tests - LPS-179357 & LPS-180526 |master
pt-liferay-solutions/liferay-portal pull request #4295
Opened 2023-06-12 20:38 UTC by marinaasant0s

[LPS-179357](https://issues.liferay.com/browse/LPS-179357) - ClaimApprovedValueAppearInDashboard
[LPS-180526](https://issues.liferay.com/browse/LPS-180526) - MDFClaimedValueAppearInDashboard

2023-06-12 20:38 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-06-12 20:42 UTC, marinaasant0s commented
ci:test:sf

2023-06-12 20:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/6252/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6252/jenkins-report.html">here</a>.</b></p>

2023-06-12 20:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b39cfc02f86bcd5f711b997e5ffd2c72ad30764b">b39cfc02f86bcd5f711b997e5ffd2c72ad30764b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marinaasant0s/liferay-portal/tree/LPS-179357">LPS-179357</a><br/>Branch GIT ID: <a href="https://github.com/marinaasant0s/liferay-portal/commit/bde2a74ed5e2f6fb1fdcb8bfe45d0a78f9f7ac49">bde2a74ed5e2f6fb1fdcb8bfe45d0a78f9f7ac49</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6252/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6252/jenkins-report.html">here</a>.</h5></details></html>

2023-06-13 15:12 UTC, AfonsoHSantos requested changes

2023-06-13 15:12 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFClaim.macro
> +
Hi @marinaasant0s, the path `PRMMDFClaim.getClaimIdOnDetailPage` already do it

2023-06-13 15:12 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMDashboards.macro
> +
Hi @marinaasant0s, the scroll should be added inside the macro `PRMDashboards.getLegendValue`. Using the path `PRMDashboards#LEGEND_VALUE`

2023-06-13 15:12 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMDashboards.testcase
> +		task ("Given the Channel Marketing Manager get the current amount of Claim MDF Value") {
Hi @marinaasant0s, please do this action with the PMU user

2023-06-13 15:12 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMDashboards.testcase
> +		task ("And a new MDF Request created and approved it") {
Hi @marinaasant0s, please rename this task to `And a new MDF Request is created and approved`

2023-06-13 15:12 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMDashboards.testcase
> +		}
Hi @marinaasant0s, please add all these steps inside the same task `And the PMU creates a new claim in the submitted MDF`

2023-06-13 15:12 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/tests/PRMDashboards.testcase
> +
Hi @marinaasant0s, please apply the request changes from the previous commit here.

2023-06-13 22:04 UTC, marinaasant0s commented
ci:test:sf

2023-06-13 22:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/6265/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6265/jenkins-report.html">here</a>.</b></p>

2023-06-13 22:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cf31ede49b05f3603a76bfc55b6109113c691db8">cf31ede49b05f3603a76bfc55b6109113c691db8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marinaasant0s/liferay-portal/tree/LPS-179357">LPS-179357</a><br/>Branch GIT ID: <a href="https://github.com/marinaasant0s/liferay-portal/commit/e4678f228ee3e038c5a263b1a27b1bf083bf93c4">e4678f228ee3e038c5a263b1a27b1bf083bf93c4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6265/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6265/jenkins-report.html">here</a>.</h5></details></html>

2023-06-13 22:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6265/">test-portal-source-format#6265</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6265/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4295">pt-liferay-solutions#4295</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2350010710">[master] ci:test:sf - marinaasant0s &gt; pt-liferay-solutions - PR#4295 - 2023-06-13[15:06:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/3446/">publish-testray-report#3446</a><br/></div></div>

2023-06-15 14:22 UTC, AfonsoHSantos approved these changes
Hi @marinaasant0s, thanks for working on it!
The code looks good to me, so I'm forwarding it.

![giphy](https://github.com/pt-liferay-solutions/liferay-portal/assets/69267630/503607f1-6196-4e36-ba0a-3736e2167560)

2023-06-15 14:22 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-06-15 14:22 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2023-06-15 14:24 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-7.liferay.com/job/forward-pullrequest/387//consoleFull)

2023-06-15 14:27 UTC, liferay-continuous-integration commented
Error has occurred while attempting to forward pull request to `brianchandotcom`. Retrying in 1 minute...
See console log for detail:[Full Console](https://test-1-7.liferay.com/job/forward-pullrequest/387//consoleFull)

2023-06-15 14:30 UTC, closed without merging

2023-06-15 14:30 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/136422
[Console](https://test-1-7.liferay.com/job/forward-pullrequest/387//consoleFull)