LPS-185656 [PRM] Add Due Date email Templates
pt-liferay-solutions/liferay-portal pull request #4324
Opened 2023-06-15 20:46 UTC by luisacmn

2023-06-15 20:47 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-06-15 20:47 UTC, luisacmn commented
ci:test:sf

2023-06-15 20:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/4394/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4394/jenkins-report.html">here</a>.</b></p>

2023-06-15 20:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fee78629cedfb9a042d7f49485dba6a99bb58628">fee78629cedfb9a042d7f49485dba6a99bb58628</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/luisacmn/liferay-portal/tree/LPS-185656">LPS-185656</a><br/>Branch GIT ID: <a href="https://github.com/luisacmn/liferay-portal/commit/fac07d889c42ee4cf6b85c0099dc6d0c7f9ee216">fac07d889c42ee4cf6b85c0099dc6d0c7f9ee216</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4394/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4394/jenkins-report.html">here</a>.</h5></details></html>

2023-06-15 20:54 UTC, luisacmn commented
ci:test:acceptance

2023-06-15 20:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4394/">test-portal-source-format#4394</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4394/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4324">pt-liferay-solutions#4324</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2352519221">[master] ci:test:sf - luisacmn &gt; pt-liferay-solutions - PR#4324 - 2023-06-15[13:47:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/3944/">publish-testray-report#3944</a><br/></div></div>

2023-06-15 22:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>acceptance</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8724/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8724/jenkins-report.html">here</a>.</b></p>

2023-06-16 03:56 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:acceptance - 1381 out of 1522 jobs passed in 5 hours 54 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fee78629cedfb9a042d7f49485dba6a99bb58628">fee78629cedfb9a042d7f49485dba6a99bb58628</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fee78629cedfb9a042d7f49485dba6a99bb58628">fee78629cedfb9a042d7f49485dba6a99bb58628</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2352920685">EE Development Acceptance (master) - 4618 - 2023-06-15[16:40:02]</a></p><details><summary><strong>ci:test:acceptance - 1381 out of 1522 jobs PASSED</strong></summary><div><h4>141 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8724/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>archived-module-smoke-mysql57-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/217775/">archived-module-smoke-mysql57-jdk8/0/0</a></li></ul></li><li>archived-modules-test-mysql57-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233616/">archived-modules-test-mysql57-jdk8/0/0</a></li></ul></li><li>build-lib-versions-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/224941/"><strike>build-lib-versions-jdk8/0/0</strike></a></li></ul></li><li>bundle-blacklist-restart-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/183433/"><strike>bundle-blacklist-restart-mysql57-jdk8/0/0</strike></a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/537343/">central-requirements-jdk8/0/0</a></li></ul></li><li>compile-jsp-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/527256/">compile-jsp-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/608481/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-jboss73-mysql57-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/212857/">functional-smoke-jboss73-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-jboss74-mysql57-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/230745/">functional-smoke-jboss74-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2111-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233602/">functional-smoke-tomcat90-db2111-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/157325/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mariadb102-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/236421/">functional-smoke-tomcat90-mariadb102-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/217763/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/440803/">functional-smoke-tomcat90-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql80-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208510/">functional-smoke-tomcat90-mysql80-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/539913/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql121-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/215451/">functional-smoke-tomcat90-postgresql121-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql134-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/440828/">functional-smoke-tomcat90-postgresql134-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/658080/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2017-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233618/">functional-smoke-tomcat90-sqlserver2017-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/217767/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2022-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/211114/">functional-smoke-tomcat90-sqlserver2022-jdk8/0/0</a></li></ul></li><li>functional-smoke-weblogic122-mysql57-jdk8<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/220491/">functional-smoke-weblogic122-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-weblogic141-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/433791/">functional-smoke-weblogic141-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-websphere90-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/658089/"><strike>functional-smoke-websphere90-mysql57-jdk8/0/0</strike></a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/217766/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/563603/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly230-mariadb104-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/539920/">functional-smoke-wildfly230-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly230-mariadb106-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/658082/">functional-smoke-wildfly230-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly261-mariadb104-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208287/">functional-smoke-wildfly261-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly261-mariadb106-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/236417/">functional-smoke-wildfly261-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-db2111-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-accepta [...]

2023-06-16 04:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8724/">test-portal-acceptance-pullrequest(master)#8724</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8724/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>acceptance<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4324">pt-liferay-solutions#4324</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2352987861">[master] ci:test:acceptance - luisacmn &gt; pt-liferay-solutions - PR#4324 - 2023-06-15[15:00:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/19473/">publish-testray-report#19473</a><br/></div></div>

2023-06-16 11:30 UTC, thaynam requested changes
**We need to set email reminder for 15 days, 5 days, 1 day before the Due Date of the MDF Activity.**

@luisacmn segue os padroes sugeridos na PR para nomear as notifications.

2023-06-16 11:30 UTC, thaynam commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/notification-templates/claim-due-date-1-template/notification-template.json
> +	"name": "Claim Due Date Notification Template",
```suggestion
	"name": "Claim 1 Day Due Date Notification Template",
```

2023-06-16 11:30 UTC, thaynam commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/notification-templates/claim-due-date-1-template/notification-template.object-actions.json
> +		"externalReferenceCode": "CLAIM-DUE-DATE-NOTIFICATION",
```suggestion
		"externalReferenceCode": "CLAIM-1-DAY-DUE-DATE-NOTIFICATION",
```

2023-06-16 11:30 UTC, thaynam commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/notification-templates/claim-due-date-1-template/notification-template.object-actions.json
> +			"en_US": "Notification Due Date Template Action"
```suggestion
			"en_US": "Claim 1 Day Notification Due Date Template Action"
```

2023-06-16 11:30 UTC, thaynam commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/notification-templates/claim-due-date-1-template/notification-template.object-actions.json
> +		"name": "notificationDueDateTemplateAction",
```suggestion
		"name": "notification1DayDueDateTemplateAction",
```

2023-06-16 20:48 UTC, luisacmn commented
ci:test:sf

2023-06-16 20:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/4587/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4587/jenkins-report.html">here</a>.</b></p>

2023-06-16 20:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/06bb208378b620831f17c1edf48a413a9df71a2c">06bb208378b620831f17c1edf48a413a9df71a2c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/luisacmn/liferay-portal/tree/LPS-185656">LPS-185656</a><br/>Branch GIT ID: <a href="https://github.com/luisacmn/liferay-portal/commit/c455e46656fc70ca73e7e95c1d391efa167fe84b">c455e46656fc70ca73e7e95c1d391efa167fe84b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/4587/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4587/jenkins-report.html">here</a>.</h5></details></html>

2023-06-16 20:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/4587/">test-portal-source-format#4587</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4587/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4324">pt-liferay-solutions#4324</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2353788307">[master] ci:test:sf - luisacmn &gt; pt-liferay-solutions - PR#4324 - 2023-06-16[13:48:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/17237/">publish-testray-report#17237</a><br/></div></div>

2023-06-21 19:26 UTC, thaynam commented
[resent](https://github.com/pt-liferay-solutions/liferay-portal/pull/4306)

2023-06-21 19:26 UTC, closed without merging