LPS-188812
pt-liferay-solutions/liferay-portal pull request #4378
Opened 2023-06-26 14:58 UTC by joelrocha68

2023-06-26 14:58 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-06-26 15:00 UTC, joelrocha68 commented
ci:test:sf

2023-06-26 15:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/5263/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5263/jenkins-report.html">here</a>.</b></p>

2023-06-26 15:06 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c3fe88e9e5b6c7bb2bff8fb3f4ff1f4a35c92b75">c3fe88e9e5b6c7bb2bff8fb3f4ff1f4a35c92b75</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joelrocha68/liferay-portal/tree/LPS-188812">LPS-188812</a><br/>Branch GIT ID: <a href="https://github.com/joelrocha68/liferay-portal/commit/d26009623cf998f8427e5589fb81296044e32f9f">d26009623cf998f8427e5589fb81296044e32f9f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5263/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5263/jenkins-report.html">here</a>.</h5></details></html>

2023-06-26 23:09 UTC, joelrocha68 commented
ci:test:osb-site-initializer-evp

2023-06-26 23:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>osb-site-initializer-evp</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8908/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8908/jenkins-report.html">here</a>.</b></p>

2023-06-27 00:45 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:osb-site-initializer-evp - 0 out of 3 jobs passed in 1 hour 35 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0047fb7926cc001c8c9f5dc9482375a8b43b36d7">0047fb7926cc001c8c9f5dc9482375a8b43b36d7</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0047fb7926cc001c8c9f5dc9482375a8b43b36d7">0047fb7926cc001c8c9f5dc9482375a8b43b36d7</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2361852786">EE Development Acceptance (master) - 4648 - 2023-06-26[12:38:53]</a></p><details><summary><strong>ci:test:osb-site-initializer-evp - 0 out of 3 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8908/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452411/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221159/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li></ul></li></ul></div></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8908/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452411//consoleText">functional-tomcat90-mysql57-jdk8/0/0</a><ol><li><div><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452411//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPOrganization_ManagerCannotEditOrganizationInAwatingApprovalStatus_">LocalFile.EVPOrganization#ManagerCannotEditOrganizationInAwatingApprovalStatus</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-27/test-portal-acceptance-pullrequest(master)/8908/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPOrganization_ManagerCannotEditOrganizationInAwatingApprovalStatus/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-27/test-portal-acceptance-pullrequest(master)/8908/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPOrganization_ManagerCannotEditOrganizationInAwatingApprovalStatus/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-27/test-portal-acceptance-pullrequest(master)/8908/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452411//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPOrganizationStatus_EmployeeCanNotSeeReviewInAwaitingEVPStatus_">LocalFile.EVPOrganizationStatus#EmployeeCanNotSeeReviewInAwaitingEVPStatus</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-27/test-portal-acceptance-pullrequest(master)/8908/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPOrganizationStatus_EmployeeCanNotSeeReviewInAwaitingEVPStatus/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-27/test-portal-acceptance-pullrequest(master)/8908/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPOrganizationStatus_EmployeeCanNotSeeReviewInAwaitingEVPStatus/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-27/test-portal-acceptance-pullrequest(master)/8908/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452411//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPOrganizationStatus_ManagerCanRejectOrganization_">LocalFile.EVPOrganizationStatus#ManagerCanRejectOrganization</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-27/test-portal-acceptance-pullrequest(master)/8908/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPOrganizationStatus_ManagerCanRejectOrganization/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-27/test-portal-acceptance-pullrequest(master)/8908/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPOrganizationStatus_ManagerCanRejectOrganization/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-27/test-portal-acceptance-pullrequest(master)/8908/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li>...</li></ol></div></li><li><div><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221159//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><ol><li><div><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221159//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPOrganization_EmployeeCannotEditOrganizationInAwatingApprovalStatus_">LocalFile.EVPOrganization#EmployeeCannotEditOrganizationInAwatingApprovalStatus</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-27/test-portal-acceptance-pullrequest(master)/8908/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.EVPOrganization_EmployeeCannotEditOrganizationInAwatingApprovalStatus/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-27/test-portal-acceptance-pullrequest(master)/8908/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.EVPOrganization_EmployeeCannotEditOrganizationInAwatingApprovalStatus/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-27/test-portal-acceptance-pullrequest(master)/8908/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221159//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPOrganization_FinanceCanEditOrganization_">LocalFile.EVPOrganization#FinanceCanEditOrganization</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-27/test-portal-acceptance-pullrequest(master)/8908/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.EVPOrganization_FinanceCanEditOrganization/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-27/test-portal-acceptance-pullrequest(master)/8908/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.EVPOrganization_FinanceCanEditOrganization/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-27/test-portal-acceptance-pullrequest(master)/8908/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221159//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPOrganizationStatus_FinanceCanNotSeeReviewInAwaitingEVPStatus_">LocalFile.EVPOrganizationStatus#FinanceCanNotSeeReviewInAwaitingEVPStatus</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-27/test-portal-acceptance-pullrequest(master)/8908/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.EVPOrganizationStatus_FinanceCanNotSeeReviewInAwa [...]

2023-06-27 00:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8908/">test-portal-acceptance-pullrequest(master)#8908</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8908/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>osb-site-initializer-evp<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4378">pt-liferay-solutions#4378</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2362112471">[master] ci:test:osb-site-initializer-evp - joelrocha68 &gt; pt-liferay-solutions - PR#4378 - 2023-06-26[16:09:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/19768/">publish-testray-report#19768</a><br/></div></div>

2023-06-27 14:12 UTC, renato-araujo-liferay commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPOrganization.testcase
> +	@description = "This is a test for LPS-172949. Verify that is possible finance user can edit the Organization with 'Awaiting Finance Review' status"
Hey @joelrocha68, what you think about this new Scenario description
`"LPS-172949. Verify that is possible finance user can edit the Organization with 'Awaiting Finance Review' status"`

2023-06-27 14:14 UTC, renato-araujo-liferay requested changes
Hey @joelrocha68, what you think about this new Scenario description
"LPS-172949. Verify that is possible finance user can edit the Organization with 'Awaiting Finance Review' status"

2023-06-27 14:31 UTC, renato-araujo-liferay requested changes
"LPS-172949 - Finance user should edit Organizations with 'Awaiting Finance Review' status"

2023-06-27 14:31 UTC, renato-araujo-liferay commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPOrganization.testcase
> +	@description = "This is a test for LPS-172949. Verify that is possible finance user can edit the Organization with 'Awaiting Finance Review' status"
Hey @joelrocha68, what you think about this new Scenario description
"LPS-172949 - Finance user should edit Organizations with 'Awaiting Finance Review' status"

2023-06-27 16:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/1889/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1889/jenkins-report.html">here</a>.</b></p>

2023-06-27 16:35 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f91568295e98592365a19124becd9df4d09b3779">f91568295e98592365a19124becd9df4d09b3779</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joelrocha68/liferay-portal/tree/LPS-188812">LPS-188812</a><br/>Branch GIT ID: <a href="https://github.com/joelrocha68/liferay-portal/commit/597fa0e0b0ee2574b85e6d6ea2d196cfb1dddd1e">597fa0e0b0ee2574b85e6d6ea2d196cfb1dddd1e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1889/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1889/jenkins-report.html">here</a>.</h5></details></html>

2023-06-27 16:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1889/">test-portal-source-format#1889</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1889/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4378">pt-liferay-solutions#4378</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2362569888">[master] ci:test:sf - joelrocha68 &gt; pt-liferay-solutions - PR#4378 - 2023-06-27[09:31:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/6829/">publish-testray-report#6829</a><br/></div></div>

2023-06-29 20:45 UTC, LuanaKSilva requested changes
Hey @joelrocha68, thanks for working on it!
I have requested some adjustments, please take a look.

2023-06-29 20:45 UTC, LuanaKSilva commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPOrganization.testcase
> +	test FinanceUserCanEditOrganization {
Hey @joelrocha68, the test name must begin with an action. Could you change it please?
Sugestion: `CanFinanceUserEditOrganization`

2023-06-29 21:58 UTC, joelrocha68 commented
ci:forward

2023-06-29 21:58 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-06-29 22:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/5295/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5295/jenkins-report.html">here</a>.</b></p>

2023-06-29 22:03 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/032c27b5c6c6849682394873d67a9e274bd5e26e">032c27b5c6c6849682394873d67a9e274bd5e26e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joelrocha68/liferay-portal/tree/LPS-188812">LPS-188812</a><br/>Branch GIT ID: <a href="https://github.com/joelrocha68/liferay-portal/commit/e0907321010ab766905ec899b8f417e3cf44b713">e0907321010ab766905ec899b8f417e3cf44b713</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5295/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5295/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/macros/EVPOrganization.macro expected:&lt;definition \{
     [java] 
     [java]   [macro changeStatus \{
     [java]     Type(
     [java]       key_fieldId = "messageDescribed",
     [java]       locator1 = "TextArea#ANY_ID",
     [java]       value1 = \$\{typeMessage\});
     [java] 
     [java]     Button.click(button = \$\{button\});
     [java]   \}
     [java] 
     [java]   macro fillOrganizationForm \{
     [java]     WaitForPageLoad();
     [java] 
     [java]     if (isSet(organizationName)) \{
     [java]       Type(
     [java]         key_fieldLabel = "Organization Name",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{organizationName\});
     [java]     \}
     [java] 
     [java]     if (isSet(organizationSite)) \{
     [java]       Type(
     [java]         key_fieldLabel = "Organization Site/Social Media Link",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{organizationSite\});
     [java]     \}
     [java] 
     [java]     if (isSet(smallDescription)) \{
     [java]       Type(
     [java]         key_fieldLabel = "Small Description",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{smallDescription\});
     [java]     \}
     [java] 
     [java]     if (isSet(street)) \{
     [java]       Type(
     [java]         key_fieldLabel = "Street",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{street\});
     [java]     \}
     [java] 
     [java]     if (isSet(city)) \{
     [java]       Type(
     [java]         key_fieldLabel = "City",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{city\});
     [java]     \}
     [java] 
     [java]     if (isSet(state)) \{
     [java]       Type(
     [java]         key_fieldLabel = "State",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{state\});
     [java]     \}
     [java] 
     [java]     if (isSet(country)) \{
     [java]       Type(
     [java]         key_fieldLabel = "Country",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{country\});
     [java]     \}
     [java] 
     [java]     if (isSet(zipCode)) \{
     [java]       Type(
     [java]         key_fieldLabel = "Zip",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{zipCode\});</pre></details></html>

2023-06-29 22:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/6899/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6899/jenkins-report.html">here</a>.</b></p>

2023-06-29 22:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5295/">test-portal-source-format#5295</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5295/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4378">pt-liferay-solutions#4378</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2365497186">[master] ci:test:sf - joelrocha68 &gt; pt-liferay-solutions - PR#4378 - 2023-06-29[14:58:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/19866/">publish-testray-report#19866</a><br/></div></div>

2023-06-29 22:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/6899/">test-portal-acceptance-pullrequest(master)#6899</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6899/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4378">pt-liferay-solutions#4378</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2365497288">[master] ci:test:relevant - joelrocha68 &gt; pt-liferay-solutions - PR#4378 - 2023-06-29[15:11:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/15638/">publish-testray-report#15638</a><br/></div></div>

2023-06-29 22:24 UTC, joelrocha68 commented
ci:test:sf

2023-06-29 22:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/3309/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3309/jenkins-report.html">here</a>.</b></p>

2023-06-29 22:29 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/032c27b5c6c6849682394873d67a9e274bd5e26e">032c27b5c6c6849682394873d67a9e274bd5e26e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joelrocha68/liferay-portal/tree/LPS-188812">LPS-188812</a><br/>Branch GIT ID: <a href="https://github.com/joelrocha68/liferay-portal/commit/c82fce52b00db4797dbc15260105bb0570d26bf3">c82fce52b00db4797dbc15260105bb0570d26bf3</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/3309/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3309/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/macros/EVPOrganization.macro expected:&lt;definition \{
     [java] 
     [java]   [macro changeStatus \{
     [java]     Type(
     [java]       key_fieldId = "messageDescribed",
     [java]       locator1 = "TextArea#ANY_ID",
     [java]       value1 = \$\{typeMessage\});
     [java] 
     [java]     Button.click(button = \$\{button\});
     [java]   \}
     [java] 
     [java]   macro fillOrganizationForm \{
     [java]     WaitForPageLoad();
     [java] 
     [java]     if (isSet(organizationName)) \{
     [java]       Type(
     [java]         key_fieldLabel = "Organization Name",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{organizationName\});
     [java]     \}
     [java] 
     [java]     if (isSet(organizationSite)) \{
     [java]       Type(
     [java]         key_fieldLabel = "Organization Site/Social Media Link",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{organizationSite\});
     [java]     \}
     [java] 
     [java]     if (isSet(smallDescription)) \{
     [java]       Type(
     [java]         key_fieldLabel = "Small Description",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{smallDescription\});
     [java]     \}
     [java] 
     [java]     if (isSet(street)) \{
     [java]       Type(
     [java]         key_fieldLabel = "Street",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{street\});
     [java]     \}
     [java] 
     [java]     if (isSet(city)) \{
     [java]       Type(
     [java]         key_fieldLabel = "City",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{city\});
     [java]     \}
     [java] 
     [java]     if (isSet(state)) \{
     [java]       Type(
     [java]         key_fieldLabel = "State",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{state\});
     [java]     \}
     [java] 
     [java]     if (isSet(country)) \{
     [java]       Type(
     [java]         key_fieldLabel = "Country",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{country\});
     [java]     \}
     [java] 
     [java]     if (isSet(zipCode)) \{
     [java]       Type(
     [java]         key_fieldLabel = "Zip",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{zipCode\});</pre></details></html>

2023-06-29 22:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/3309/">test-portal-source-format#3309</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3309/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4378">pt-liferay-solutions#4378</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2365498350">[master] ci:test:sf - joelrocha68 &gt; pt-liferay-solutions - PR#4378 - 2023-06-29[15:24:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/11965/">publish-testray-report#11965</a><br/></div></div>

2023-06-30 01:01 UTC, joelrocha68 commented
ci:forward

2023-06-30 01:01 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-06-30 01:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8966/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8966/jenkins-report.html">here</a>.</b></p>

2023-06-30 01:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/6048/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6048/jenkins-report.html">here</a>.</b></p>

2023-06-30 01:06 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/032c27b5c6c6849682394873d67a9e274bd5e26e">032c27b5c6c6849682394873d67a9e274bd5e26e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joelrocha68/liferay-portal/tree/LPS-188812">LPS-188812</a><br/>Branch GIT ID: <a href="https://github.com/joelrocha68/liferay-portal/commit/41c76e239dc66640e9de7a572b89d7c7ead5e566">41c76e239dc66640e9de7a572b89d7c7ead5e566</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/6048/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6048/jenkins-report.html">here</a>.</h5></details></html>

2023-06-30 01:06 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/6048//consoleFull)

2023-06-30 01:07 UTC, closed without merging

2023-06-30 01:07 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/137137
[Console](https://test-1-26.liferay.com/job/test-portal-source-format/6048//consoleFull)

2023-06-30 01:07 UTC, liferay-continuous-integration commented
This pull request already has open forwarded pull request(s):
https://github.com/brianchandotcom/liferay-portal/pull/137137

Pull request will not be forwarded to `brianchandotcom`.
[Console](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8966//consoleFull)

2023-06-30 01:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/6048/">test-portal-source-format#6048</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6048/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4378">pt-liferay-solutions#4378</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2365661921">[master] ci:test:sf - joelrocha68 &gt; pt-liferay-solutions - PR#4378 - 2023-06-29[18:01:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/23227/">publish-testray-report#23227</a><br/></div></div>

2023-06-30 01:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8966/">test-portal-acceptance-pullrequest(master)#8966</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8966/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4378">pt-liferay-solutions#4378</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2365684679">[master] ci:test:relevant - joelrocha68 &gt; pt-liferay-solutions - PR#4378 - 2023-06-29[18:01:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/19875/">publish-testray-report#19875</a><br/></div></div>