LPS-188837
pt-liferay-solutions/liferay-portal pull request #4380
Opened 2023-06-26 17:06 UTC by joelrocha68

2023-06-26 17:08 UTC, joelrocha68 commented
ci:test:sf

2023-06-26 17:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/6012/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6012/jenkins-report.html">here</a>.</b></p>

2023-06-26 17:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/de8908e3c4314cd5dbfc02fc64db17172ef902a2">de8908e3c4314cd5dbfc02fc64db17172ef902a2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joelrocha68/liferay-portal/tree/LPS-188837">LPS-188837</a><br/>Branch GIT ID: <a href="https://github.com/joelrocha68/liferay-portal/commit/923cff306121c7a15d697ea63f8ef2a1722e60fd">923cff306121c7a15d697ea63f8ef2a1722e60fd</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/6012/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6012/jenkins-report.html">here</a>.</h5></details></html>

2023-06-26 17:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/6012/">test-portal-source-format#6012</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/6012/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4380">pt-liferay-solutions#4380</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2361650474">[master] ci:test:sf - joelrocha68 &gt; pt-liferay-solutions - PR#4380 - 2023-06-26[10:09:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/23076/">publish-testray-report#23076</a><br/></div></div>

2023-06-26 23:09 UTC, joelrocha68 commented
ci:test:osb-site-initializer-evp

2023-06-26 23:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>osb-site-initializer-evp</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/3957/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3957/jenkins-report.html">here</a>.</b></p>

2023-06-27 00:54 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:osb-site-initializer-evp - 0 out of 3 jobs passed in 1 hour 44 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0047fb7926cc001c8c9f5dc9482375a8b43b36d7">0047fb7926cc001c8c9f5dc9482375a8b43b36d7</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0047fb7926cc001c8c9f5dc9482375a8b43b36d7">0047fb7926cc001c8c9f5dc9482375a8b43b36d7</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2361852786">EE Development Acceptance (master) - 4648 - 2023-06-26[12:38:53]</a></p><details><summary><strong>ci:test:osb-site-initializer-evp - 0 out of 3 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/3957/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/703231/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221160/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li></ul></li></ul></div></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3957/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/703231//consoleText">functional-tomcat90-mysql57-jdk8/0/0</a><ol><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/703231//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPOrganization_EmployeeCannotEditOrganizationInAwatingApprovalStatus_">LocalFile.EVPOrganization#EmployeeCannotEditOrganizationInAwatingApprovalStatus</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(master)/3957/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPOrganization_EmployeeCannotEditOrganizationInAwatingApprovalStatus/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(master)/3957/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPOrganization_EmployeeCannotEditOrganizationInAwatingApprovalStatus/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(master)/3957/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/703231//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPOrganization_ManagerCannotEditOrganizationInAwatingApprovalStatus_">LocalFile.EVPOrganization#ManagerCannotEditOrganizationInAwatingApprovalStatus</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(master)/3957/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPOrganization_ManagerCannotEditOrganizationInAwatingApprovalStatus/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(master)/3957/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPOrganization_ManagerCannotEditOrganizationInAwatingApprovalStatus/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(master)/3957/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/703231//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPOrganizationStatus_ManagerCanApproveOrganization_">LocalFile.EVPOrganizationStatus#ManagerCanApproveOrganization</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(master)/3957/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPOrganizationStatus_ManagerCanApproveOrganization/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(master)/3957/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.EVPOrganizationStatus_ManagerCanApproveOrganization/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(master)/3957/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li>...</li></ol></div></li><li><div><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221160//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><ol><li><div><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221160//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPOrganizationStatus_EmployeeCanNotSeeReviewInAwaitingEVPStatus_">LocalFile.EVPOrganizationStatus#EmployeeCanNotSeeReviewInAwaitingEVPStatus</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(master)/3957/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.EVPOrganizationStatus_EmployeeCanNotSeeReviewInAwaitingEVPStatus/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(master)/3957/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.EVPOrganizationStatus_EmployeeCanNotSeeReviewInAwaitingEVPStatus/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(master)/3957/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221160//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPOrganizationStatus_FinanceCanNotSeeReviewInAwaitingEVPStatus_">LocalFile.EVPOrganizationStatus#FinanceCanNotSeeReviewInAwaitingEVPStatus</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(master)/3957/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.EVPOrganizationStatus_FinanceCanNotSeeReviewInAwaitingEVPStatus/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(master)/3957/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.EVPOrganizationStatus_FinanceCanNotSeeReviewInAwaitingEVPStatus/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(master)/3957/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/221160//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EVPOrganizationStatus_ManagerCannotSeeReviewButtonInAwaitingFinanceStatus_">LocalFile.EVPOrganizationStatus#ManagerCannotSeeReviewButtonInAwaitingFinanceStatus</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(m [...]

2023-06-27 01:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/3957/">test-portal-acceptance-pullrequest(master)#3957</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3957/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>osb-site-initializer-evp<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4380">pt-liferay-solutions#4380</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2362115322">[master] ci:test:osb-site-initializer-evp - joelrocha68 &gt; pt-liferay-solutions - PR#4380 - 2023-06-26[16:10:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/8752/">publish-testray-report#8752</a><br/></div></div>

2023-06-27 14:48 UTC, renato-araujo-liferay commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPReport.testcase
> +	@description = "This is a test for LPS-164731. Verify that Reports page is not visible on top menu for Employee users."
Hey @joelrocha68 , Could you change the test description as previously align?

2023-06-27 14:50 UTC, renato-araujo-liferay commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPReport.testcase
> +	@description = "This is a test for LPS-164731. Verify that Reports page is not visible on top menu for Employee users."
Sugestion: "LPS-164731 - Reports bar Should not be visible on top menu for Employee users."

2023-06-27 14:55 UTC, renato-araujo-liferay commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPReport.testcase
> +	@description = "This is a test for LPS-164731. Verify that user can access Reports page through 'Reports' Tab on top menu and it is visible to EVP Finance"
Hey @joelrocha68 , Could you change the test description as previously align?



Sugestion: "LPS-164731 - Finance user should be able to see the Report card through 'Reports' Tab on top menu"

2023-06-27 15:01 UTC, renato-araujo-liferay commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPReport.testcase
> +	@description = "This is a test for LPS-164731. Verify that user can access Reports page through 'Reports' Tab on top menu and it is visible to EVP Manager"
Hey @joelrocha68 , Could you change the test description as previously align?

2023-06-27 15:03 UTC, renato-araujo-liferay commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPReport.testcase
> +	test ManagerCanAccessReportPage {
Please check with gabi if this testcase name rings a bell

2023-06-27 15:03 UTC, renato-araujo-liferay requested changes
Joel, Please check these previous comments.

2023-06-27 16:30 UTC, joelrocha68 commented
ci:test:sf

2023-06-27 16:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/1888/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1888/jenkins-report.html">here</a>.</b></p>

2023-06-27 16:35 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f91568295e98592365a19124becd9df4d09b3779">f91568295e98592365a19124becd9df4d09b3779</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joelrocha68/liferay-portal/tree/LPS-188837">LPS-188837</a><br/>Branch GIT ID: <a href="https://github.com/joelrocha68/liferay-portal/commit/88d72a7a3ed9102c30aebb6b2a0032e01c7f241b">88d72a7a3ed9102c30aebb6b2a0032e01c7f241b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1888/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1888/jenkins-report.html">here</a>.</h5></details></html>

2023-06-27 16:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1888/">test-portal-source-format#1888</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1888/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4380">pt-liferay-solutions#4380</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2362569872">[master] ci:test:sf - joelrocha68 &gt; pt-liferay-solutions - PR#4380 - 2023-06-27[09:31:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/6828/">publish-testray-report#6828</a><br/></div></div>

2023-06-27 21:05 UTC, joelrocha68 commented
ci:test:sf

2023-06-27 21:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/5412/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5412/jenkins-report.html">here</a>.</b></p>

2023-06-27 21:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ace1093b28066b77dd3a705615518b4bb1fd6496">ace1093b28066b77dd3a705615518b4bb1fd6496</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joelrocha68/liferay-portal/tree/LPS-188837">LPS-188837</a><br/>Branch GIT ID: <a href="https://github.com/joelrocha68/liferay-portal/commit/ed90fa7b87b80173bce64fd0bc1bf112a62ad9b5">ed90fa7b87b80173bce64fd0bc1bf112a62ad9b5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5412/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5412/jenkins-report.html">here</a>.</h5></details></html>

2023-06-27 21:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5412/">test-portal-source-format#5412</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5412/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4380">pt-liferay-solutions#4380</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2362818235">[master] ci:test:sf - joelrocha68 &gt; pt-liferay-solutions - PR#4380 - 2023-06-27[14:05:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/20308/">publish-testray-report#20308</a><br/></div></div>

2023-06-29 21:02 UTC, LuanaKSilva requested changes
Hey @joelrocha68, thanks for working on it!
I have requested some adjustments, please take a look.

2023-06-29 21:02 UTC, LuanaKSilva commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPReport.testcase
> +			EVPUtils.assertCardTitle(listcardTitle = "EVP Requests Listing,EVP Financial Report");
After changing the macro name, remember to change the macro calls.

2023-06-29 21:02 UTC, LuanaKSilva commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPReport.testcase
> +			EVPUtils.assertCardTitle(listcardTitle = "EVP Requests Listing,EVP Financial Report");
Same comment as above.

2023-06-29 22:17 UTC, joelrocha68 commented
ci:forward

2023-06-29 22:17 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-06-29 22:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/545/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/545/jenkins-report.html">here</a>.</b></p>

2023-06-29 22:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/6692/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/6692/jenkins-report.html">here</a>.</b></p>

2023-06-29 22:22 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/032c27b5c6c6849682394873d67a9e274bd5e26e">032c27b5c6c6849682394873d67a9e274bd5e26e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joelrocha68/liferay-portal/tree/LPS-188837">LPS-188837</a><br/>Branch GIT ID: <a href="https://github.com/joelrocha68/liferay-portal/commit/024ee47e43ca3b6a9fc4fb1f4bbba301201141d7">024ee47e43ca3b6a9fc4fb1f4bbba301201141d7</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/6692/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/6692/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/macros/EVPUtils.macro expected:&lt;definition \{
     [java] 
     [java]   [macro addEVPSite \{
     [java]     Site.openSitesAdmin();
     [java] 
     [java]     TeamExtranet.addSiteTemplateCP(
     [java]       siteName = "EVP Portal",
     [java]       siteTemplateName = "EVP");
     [java]   \}
     [java] 
     [java]   macro assertCardsTitle \{
     [java]     for (var cardTitle : list \$\{listcardTitle\}) \{
     [java]       AssertElementPresent(
     [java]         key_card = \$\{cardTitle\},
     [java]         locator1 = "Card#CARD_TITLE");
     [java]     \}
     [java]   \}
     [java] 
     [java]   macro downloadFileViaCurl \{
     [java]     var currentURL = selenium.getCurrentUrl();
     [java]     var testDependenciesDir = PropsUtil.get("output.dir.name");
     [java] 
     [java]     var curl = '''\$\{currentURL\} --create-dirs -o \$\{testDependenciesDir\}/\$\{fileName\}''';
     [java] 
     [java]     echo("curl = \$\{curl\}");
     [java] 
     [java]     com.liferay.poshi.runner.util.JSONCurlUtil.get(\$\{curl\});
     [java]   \}
     [java] 
     [java]   macro generateFinancialReport \{
     [java]     LexiconCard.clickCardTitle(card = \$\{cardTitle\});
     [java] 
     [java]     EVPUtils.insertDate(
     [java]       dateRange = \$\{dateRange\},
     [java]       endDateLabel = \$\{endDateLabel\},
     [java]       initialDateLabel = \$\{initialDateLabel\});
     [java] 
     [java]     Button.click(button = "Generate");
     [java]   \}
     [java] 
     [java]   macro generateRequestsListing \{
     [java]     LexiconCard.clickCard(card = \$\{cardTitle\});
     [java] 
     [java]     WaitForPageLoad();
     [java] 
     [java]     EVPUtils.insertDate(
     [java]       dateRange = \$\{dateRange\},
     [java]       endDateLabel = \$\{endDateLabel\},
     [java]       initialDateLabel = \$\{initialDateLabel\});
     [java] 
     [java]     if (isSet(fullName)) \{
     [java]       Type(
     [java]         key_fieldLabel = "Full Name",
     [java]         locator1 = "TextInput#GENERIC_TEXT_INPUT",
     [java]         value1 = \$\{fullName\});
     [java]     \}
     [java] 
     [java]     if (isSet(initialCompanyId)) \{
     [java]       Type(
     [java]         inputFieldId = "initialCompanyId",
     [java]         locator1 = "TextInput#INPUT_ID",
     [java]         value1 = \$\{initialCompanyId\});
     [java]     \}
     [java] 
     [java]     if (isSet(finalCompanyId)) \{
     [java]       Type(</pre></details></html>

2023-06-29 22:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/545/">test-portal-acceptance-pullrequest(master)#545</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/545/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4380">pt-liferay-solutions#4380</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2365497997">[master] ci:test:relevant - joelrocha68 &gt; pt-liferay-solutions - PR#4380 - 2023-06-29[15:18:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/24410/">publish-testray-report#24410</a><br/></div></div>

2023-06-29 22:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/6692/">test-portal-source-format#6692</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/6692/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4380">pt-liferay-solutions#4380</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2365498325">[master] ci:test:sf - joelrocha68 &gt; pt-liferay-solutions - PR#4380 - 2023-06-29[15:17:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/24411/">publish-testray-report#24411</a><br/></div></div>

2023-06-29 22:49 UTC, joelrocha68 commented
ci:close

2023-06-29 22:49 UTC, closed without merging

2023-06-29 22:51 UTC, joelrocha68 commented
Resent  #4412