LPS-188177
pt-liferay-solutions/liferay-portal pull request #4383
Opened 2023-06-26 20:44 UTC by pedroliveirav

2023-06-26 20:44 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-06-27 13:48 UTC, kevenleone requested changes

2023-06-27 21:17 UTC, pedroliveirav commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/common/services/liferay/graphql/queries.js
> +			type
Done.

2023-06-27 21:18 UTC, pedroliveirav commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/common/services/liferay/graphql/queries.js
> +export const getTemplateByExternalReferenceCode = gql`
Done.

2023-06-27 21:18 UTC, pedroliveirav commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/common/containers/setup-forms/SetupDXPCloudForm/index.jsx
> +				}
Done.

2023-06-27 21:18 UTC, pedroliveirav commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/common/containers/setup-forms/SetupDXPCloudForm/index.jsx
> +				const emailDataList = {
Done.

2023-06-27 21:20 UTC, Aline160 commented
Just starting reviewing :)

2023-06-27 21:20 UTC, pedroliveirav commented
ci:test:sf

2023-06-27 21:21 UTC, Aline160 commented
Just starting reviewing :)

2023-06-27 21:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-source-format/5745/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/5745/jenkins-report.html">here</a>.</b></p>

2023-06-27 21:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/71b8416aa3970501a39c7242e26d6c7d8948b846">71b8416aa3970501a39c7242e26d6c7d8948b846</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedroliveirav/liferay-portal/tree/LPS-188177">LPS-188177</a><br/>Branch GIT ID: <a href="https://github.com/pedroliveirav/liferay-portal/commit/05c7857134e39f94406b42cdc2f4e4e162f77638">05c7857134e39f94406b42cdc2f4e4e162f77638</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-source-format/5745/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/5745/jenkins-report.html">here</a>.</h5></details></html>

2023-06-27 21:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-13.liferay.com/job/test-portal-source-format/5745/">test-portal-source-format#5745</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/5745/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4383">pt-liferay-solutions#4383</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2362824355">[master] ci:test:sf - pedroliveirav &gt; pt-liferay-solutions - PR#4383 - 2023-06-27[14:21:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-13.liferay.com/job/publish-testray-report/4007/">publish-testray-report#4007</a><br/></div></div>

2023-06-27 22:13 UTC, kevenleone commented
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/4393

2023-06-27 22:13 UTC, closed without merging