LPS-188968 | Add test ManagerCanEditVeriifiedOrganization
pt-liferay-solutions/liferay-portal pull request #4400
Opened 2023-06-29 07:40 UTC by bronsonsoda

https://liferay.atlassian.net/browse/LPS-188968

2023-06-29 07:40 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-06-29 07:41 UTC, bronsonsoda commented
ci:test:osb-site-initializer-evp

2023-06-29 13:19 UTC, bronsonsoda commented
ci:stop

2023-06-29 13:19 UTC, bronsonsoda commented
ci:test:osb-site-initializer-evp

2023-06-29 16:06 UTC, nikki-pru requested changes

2023-06-29 16:06 UTC, nikki-pru commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPOrganization.testcase
> +	test ManagerCanEditVeriifiedOrganization {
Please fix typo "Veriified" should be "Verified"

2023-06-29 16:06 UTC, nikki-pru commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPOrganization.testcase
> +			AssertElementPresent(
This only checks that the Edit option is available. Please check that the manager is able to edit the organization.
1. Navigate into the organization
2. Make edits
3. Save edits
4. View organization that the edits are applied/persist.

2023-06-29 16:06 UTC, nikki-pru commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPOrganization.testcase
> +		task ("Then the manger is able to make changes") {
Typo on 'manager'

2023-06-29 16:06 UTC, nikki-pru commented
@bronsonsoda , please see requested changes above

2023-07-03 08:33 UTC, bronsonsoda commented
How do i go about resolving conflicts when using an old commit to work from 🤔

2023-07-05 22:03 UTC, bronsonsoda commented
Believe I did it

2023-07-12 16:52 UTC, joelrocha68 commented
This task is still in conflict

2023-09-21 23:47 UTC, kevenleone commented
Archiving due inactivity

2023-09-21 23:47 UTC, closed without merging