LPS-188083 [EVP] Implementing Organization and Request status handler fragment
pt-liferay-solutions/liferay-portal pull request #4403
Opened 2023-06-29 16:59 UTC by EugenioAntunes

[LPS-188083](https://liferay.atlassian.net/browse/LPS-188083)

2023-06-29 16:59 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-06-29 17:05 UTC, EugenioAntunes commented
ci:test:sf

2023-06-29 17:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/5291/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5291/jenkins-report.html">here</a>.</b></p>

2023-06-29 17:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 11 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/750e011d7e99551333b02e48db0b65fbdcd221cd">750e011d7e99551333b02e48db0b65fbdcd221cd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/EugenioAntunes/liferay-portal/tree/LPS-188083">LPS-188083</a><br/>Branch GIT ID: <a href="https://github.com/EugenioAntunes/liferay-portal/commit/7649e537cc777e39810c856fa07fe89a28ae8719">7649e537cc777e39810c856fa07fe89a28ae8719</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5291/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5291/jenkins-report.html">here</a>.</h5></details></html>

2023-06-29 17:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5291/">test-portal-source-format#5291</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5291/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4403">pt-liferay-solutions#4403</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2365168783">[master] ci:test:sf - EugenioAntunes &gt; pt-liferay-solutions - PR#4403 - 2023-06-29[10:05:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/19853/">publish-testray-report#19853</a><br/></div></div>

2023-06-30 13:19 UTC, eliasantosf commented
Just starting reviewing :)

2023-06-30 14:48 UTC, eliasantosf requested changes

2023-06-30 14:48 UTC, eliasantosf commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/fragments/group/evp/fragments/evp-organization-status-handler/index.js
> +const EVPOrganizationStatus = document.querySelector(
O nome desse const está fora de padrão. Sugiro mudar o nome dela.

2023-06-30 14:48 UTC, eliasantosf commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/fragments/group/evp/fragments/evp-request-status-handler/index.js
> +const EVPRequestStatus = document.querySelector(
O nome desse const está fora de padrão. Sugiro mudar o nome dela.

2023-06-30 14:48 UTC, eliasantosf commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/layouts/02_request/01_request-form/page-definition.json
> +								"EVPRequestStatus"
O nome dessa classe CSS está fora de padrão. Sugiro mudar o nome dela.

2023-06-30 14:48 UTC, eliasantosf commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/layouts/02_request/01_request-form/page-definition.json
> +							"customCSS": ".EVPRequestStatus {\ndisplay:none\n}",
O nome dessa classe CSS está fora de padrão. Sugiro mudar o nome dela.

2023-06-30 14:48 UTC, eliasantosf commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/layouts/03_organization/01_organization-form/page-definition.json
> +								"EVPOrganizationStatus"
O nome dessa classe CSS está fora de padrão. Sugiro mudar o nome dela.

2023-06-30 14:48 UTC, eliasantosf commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/layouts/03_organization/01_organization-form/page-definition.json
> +							"customCSS": ".EVPOrganizationStatus {\ndisplay:none;\n}",
O nome dessa classe CSS está fora de padrão. Sugiro mudar o nome dela.

2023-06-30 18:42 UTC, EugenioAntunes commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/fragments/group/evp/fragments/evp-organization-status-handler/index.js
> +const EVPOrganizationStatus = document.querySelector(
Done!

2023-06-30 18:45 UTC, EugenioAntunes commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/fragments/group/evp/fragments/evp-request-status-handler/index.js
> +const EVPRequestStatus = document.querySelector(
Done!

2023-06-30 18:48 UTC, EugenioAntunes commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/layouts/02_request/01_request-form/page-definition.json
> +								"EVPRequestStatus"
Done!

2023-06-30 18:51 UTC, EugenioAntunes commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/layouts/02_request/01_request-form/page-definition.json
> +							"customCSS": ".EVPRequestStatus {\ndisplay:none\n}",
Done!

2023-06-30 18:54 UTC, EugenioAntunes commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/layouts/03_organization/01_organization-form/page-definition.json
> +								"EVPOrganizationStatus"
Done!

2023-06-30 18:55 UTC, EugenioAntunes commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/layouts/03_organization/01_organization-form/page-definition.json
> +							"customCSS": ".EVPOrganizationStatus {\ndisplay:none;\n}",
Done!

2023-07-03 13:37 UTC, EugenioAntunes commented
Just taking a look!

2023-07-04 13:37 UTC, EugenioAntunes commented
Just taking a look!

2023-07-04 14:32 UTC, EugenioAntunes commented
ci:test:sf

2023-07-04 14:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/6559/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6559/jenkins-report.html">here</a>.</b></p>

2023-07-04 14:46 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 13 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0d3aa3a0581823adfd4d56e68475755a17183ffa">0d3aa3a0581823adfd4d56e68475755a17183ffa</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/EugenioAntunes/liferay-portal/tree/LPS-188083">LPS-188083</a><br/>Branch GIT ID: <a href="https://github.com/EugenioAntunes/liferay-portal/commit/7b243c2806e5b4a72aa7cdcbb6612f1b6e6a5491">7b243c2806e5b4a72aa7cdcbb6612f1b6e6a5491</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6559/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6559/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Expected a ':' after a key at 5228 [character 8 line 232], see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/json_validation_check.markdown: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/layouts/02_request/01_request-form/page-definition.json (SourceCheck:JSONValidationCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:466)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
[stopwatch] [run.batch.test.action: 1:37.728 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:466: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:610: Java returned: 1
      [get] Getting: http://test-1-6/job/test-portal-source-format/6559//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230704074541313.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230704074541313.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1243581345.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null473799768
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 354ms
[junitreport] Deleting: /tmp/null473799768
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results</pre></details></html>

2023-07-04 15:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6559/">test-portal-source-format#6559</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6559/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4403">pt-liferay-solutions#4403</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2370406991">[master] ci:test:sf - EugenioAntunes &gt; pt-liferay-solutions - PR#4403 - 2023-07-04[07:33:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/4132/">publish-testray-report#4132</a><br/></div></div>

2023-07-04 15:25 UTC, EugenioAntunes commented
ci:test:sf

2023-07-04 15:25 UTC, EugenioAntunes commented
ci:test:sf

2023-07-04 15:32 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ad90a1348db79102d7cbe39e8b2cb3250a67cb1c">ad90a1348db79102d7cbe39e8b2cb3250a67cb1c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/EugenioAntunes/liferay-portal/tree/LPS-188083">LPS-188083</a><br/>Branch GIT ID: <a href="https://github.com/EugenioAntunes/liferay-portal/commit/7b243c2806e5b4a72aa7cdcbb6612f1b6e6a5491">7b243c2806e5b4a72aa7cdcbb6612f1b6e6a5491</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5085/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5085/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Expected a ':' after a key at 5228 [character 8 line 232], see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/json_validation_check.markdown: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/layouts/02_request/01_request-form/page-definition.json (SourceCheck:JSONValidationCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:466)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
[stopwatch] [run.batch.test.action: 1:28.142 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:466: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:610: Java returned: 1
      [get] Getting: http://test-1-12/job/test-portal-source-format/5085//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230704083151336.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230704083151336.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1498719389.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null964568901
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 365ms
[junitreport] Deleting: /tmp/null964568901
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results</pre></details></html>

2023-07-04 15:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5085/">test-portal-source-format#5085</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5085/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4403">pt-liferay-solutions#4403</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2370409695">[master] ci:test:sf - EugenioAntunes &gt; pt-liferay-solutions - PR#4403 - 2023-07-04[08:26:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/3702/">publish-testray-report#3702</a><br/></div></div>

2023-07-04 15:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/5084/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5084/jenkins-report.html">here</a>.</b></p>

2023-07-04 15:42 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 17 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ad90a1348db79102d7cbe39e8b2cb3250a67cb1c">ad90a1348db79102d7cbe39e8b2cb3250a67cb1c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/EugenioAntunes/liferay-portal/tree/LPS-188083">LPS-188083</a><br/>Branch GIT ID: <a href="https://github.com/EugenioAntunes/liferay-portal/commit/7b243c2806e5b4a72aa7cdcbb6612f1b6e6a5491">7b243c2806e5b4a72aa7cdcbb6612f1b6e6a5491</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5084/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5084/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Expected a ':' after a key at 5228 [character 8 line 232], see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/json_validation_check.markdown: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/layouts/02_request/01_request-form/page-definition.json (SourceCheck:JSONValidationCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:466)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
[stopwatch] [run.batch.test.action: 1:21.326 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:466: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:610: Java returned: 1
      [get] Getting: http://test-1-12/job/test-portal-source-format/5084//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230704084151363.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230704084151363.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null2128254517.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1274026253
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 303ms
[junitreport] Deleting: /tmp/null1274026253
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results</pre></details></html>

2023-07-04 15:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5084/">test-portal-source-format#5084</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5084/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4403">pt-liferay-solutions#4403</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2370410229">[master] ci:test:sf - EugenioAntunes &gt; pt-liferay-solutions - PR#4403 - 2023-07-04[08:25:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/3703/">publish-testray-report#3703</a><br/></div></div>

2023-07-04 16:17 UTC, EugenioAntunes commented
ci:test:sf

2023-07-04 16:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/6980/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6980/jenkins-report.html">here</a>.</b></p>

2023-07-04 16:23 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ad90a1348db79102d7cbe39e8b2cb3250a67cb1c">ad90a1348db79102d7cbe39e8b2cb3250a67cb1c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/EugenioAntunes/liferay-portal/tree/LPS-188083">LPS-188083</a><br/>Branch GIT ID: <a href="https://github.com/EugenioAntunes/liferay-portal/commit/7b243c2806e5b4a72aa7cdcbb6612f1b6e6a5491">7b243c2806e5b4a72aa7cdcbb6612f1b6e6a5491</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/6980/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6980/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Expected a ':' after a key at 5228 [character 8 line 232], see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/json_validation_check.markdown: ./modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/src/main/resources/site-initializer/layouts/02_request/01_request-form/page-definition.json (SourceCheck:JSONValidationCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:466)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
[stopwatch] [run.batch.test.action: 1:19.632 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:466: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:610: Java returned: 1
      [get] Getting: http://test-1-19/job/test-portal-source-format/6980//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230704092304987.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230704092304987.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1054857485.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1790538655
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 173ms
[junitreport] Deleting: /tmp/null1790538655
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results</pre></details></html>

2023-07-04 16:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-19.liferay.com/job/test-portal-source-format/6980/">test-portal-source-format#6980</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6980/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4403">pt-liferay-solutions#4403</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2370436415">[master] ci:test:sf - EugenioAntunes &gt; pt-liferay-solutions - PR#4403 - 2023-07-04[09:17:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-19.liferay.com/job/publish-testray-report/3666/">publish-testray-report#3666</a><br/></div></div>

2023-07-04 17:08 UTC, closed without merging