LPS-189274 [Marketplace] Fix App Marketplace Dashboard Style Adjustments
pt-liferay-solutions/liferay-portal pull request #4461
Opened 2023-07-10 11:59 UTC by claricebrasil

2023-07-10 11:59 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-07-10 16:53 UTC, silasbsi requested changes
I added some suggestions.

2023-07-10 16:53 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/solutions-search-results/ddm-template.ftl
> +}
It needs to be formatted.

2023-07-10 16:53 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/solutions-search-results/ddm-template.ftl
>  				</#list>
It needs to be formatted.

2023-07-10 20:07 UTC, claricebrasil commented
ci:test:sf

2023-07-10 20:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/3412/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3412/jenkins-report.html">here</a>.</b></p>

2023-07-10 20:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f18b6b9631a79db27829ce933b66d963bcd9e3d6">f18b6b9631a79db27829ce933b66d963bcd9e3d6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/claricebrasil/liferay-portal/tree/LPS-189274">LPS-189274</a><br/>Branch GIT ID: <a href="https://github.com/claricebrasil/liferay-portal/commit/159e09c5d053cde83fddbf9b5493bcef28f8f9ba">159e09c5d053cde83fddbf9b5493bcef28f8f9ba</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/3412/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3412/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/apps-vocabulary-facets/ddm-template.ftl expected:&lt;...          type="checkbox"[
     [java]               /&gt;
     [java] ]
     [java]               &lt;span class=...&gt; but was:&lt;...          type="checkbox"[ 
     [java]               /&gt;
     [java]               ]
     [java]               &lt;span class=...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:466)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
[stopwatch] [run.batch.test.action: 1:09.685 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:466: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:610: Java returned: 1
      [get] Getting: http://test-1-39/job/test-portal-source-format/3412//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230710130951895.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230710130951895.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1797746844.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1240203993
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 177ms
[junitreport] Deleting: /tmp/null1240203993
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 07-10-2023 13:09:54:540 PDT</pre></details></html>

2023-07-10 20:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/3412/">test-portal-source-format#3412</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3412/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4461">pt-liferay-solutions#4461</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2376907333">[master] ci:test:sf - claricebrasil &gt; pt-liferay-solutions - PR#4461 - 2023-07-10[13:07:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/12349/">publish-testray-report#12349</a><br/></div></div>

2023-07-10 20:19 UTC, silasbsi approved these changes

2023-07-13 17:15 UTC, joanagrego commented
Just starting reviewing :)

2023-07-13 17:22 UTC, closed without merging

2023-07-13 19:51 UTC, joanagrego commented
Resent --> [PR](https://github.com/pt-liferay-solutions/liferay-portal/pull/4485)