LPS-143163 PoC to add React Fragment in site-initializer
pt-liferay-solutions/liferay-portal pull request #449
Opened 2021-12-06 20:41 UTC by jairmedeiros

2021-12-06 20:41 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-12-12 21:14 UTC, kevenleone commented
It's look real good, @jairmedeiros 

Is this working?

Dreaming with that for Raylife 🥰🥰🥰

2021-12-13 16:40 UTC, claricebrasil commented
Just starting reviewing :)

2021-12-13 16:40 UTC, claricebrasil commented
Just starting reviewing :)

2021-12-17 13:24 UTC, kevenleone requested changes

2021-12-17 13:24 UTC, kevenleone commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/fragments/liferay-npm-bundler.config.js
> +/* eslint-disable @liferay/imports-first */
Remove this line

2021-12-17 13:24 UTC, kevenleone commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/fragments/package.json
> +  "name": "extra-liferay-fragments",
Probably, this is a bad name.

Following the existing pattern, would be:

`@liferay/osb-site-initializer-customer-portal-fragments`

2021-12-17 13:24 UTC, kevenleone commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/fragments/src/select-project/index.js
> +      searchable={true}
```suggestion
      searchable
```

2021-12-17 13:24 UTC, kevenleone commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/fragments/src/select-project/index.js
> +  const [value, setValue] = useState('');
What value means??

Maybe a different name

2021-12-17 13:24 UTC, kevenleone commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/fragments/src/select-project/index.js
> +    window.addEventListener('customer-portal-select-user-loading', ({ detail: {accountBriefs} }) => {
You need to remove the eventListener, inside the useEffect

2021-12-17 13:26 UTC, closed without merging