LPS-189917 [Marketplace] Refactor App Dashboard Filter Results
pt-liferay-solutions/liferay-portal pull request #4501
Opened 2023-07-18 13:28 UTC by claricebrasil

2023-07-18 13:28 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-07-18 13:30 UTC, claricebrasil commented
ci:test:sf

2023-07-18 13:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/6835/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/6835/jenkins-report.html">here</a>.</b></p>

2023-07-18 13:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/6835/">test-portal-source-format#6835</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/6835/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4501">pt-liferay-solutions#4501</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2385993090">[master] ci:test:sf - claricebrasil &gt; pt-liferay-solutions - PR#4501 - 2023-07-18[06:30:51]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/25036/">publish-testray-report#25036</a><br/></div></div>

2023-07-18 14:12 UTC, claricebrasil commented
ci:test:sf

2023-07-18 14:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/5110/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5110/jenkins-report.html">here</a>.</b></p>

2023-07-18 14:17 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e14870250c24bcbdb5f04c1d22050822e984dbc2">e14870250c24bcbdb5f04c1d22050822e984dbc2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/claricebrasil/liferay-portal/tree/LPS-189917">LPS-189917</a><br/>Branch GIT ID: <a href="https://github.com/claricebrasil/liferay-portal/commit/696476863224d1e94821cbf25b453ead139b5d48">696476863224d1e94821cbf25b453ead139b5d48</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5110/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5110/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/apps-search-results/ddm-template.ftl expected:&lt;...?filter(category -&gt; [stringUtil.equals(category.name, "App")) as category&gt;
     [java]     &lt;#assign filteredProducts = filteredProducts + 1 /&gt;
     [java]   &lt;/#list&gt;
     [java] &lt;/#list&gt;
     [java] 
     [java] &lt;div class="adt-apps-search-results"&gt;
     [java]   &lt;#if productsList?has_content&gt;
     [java]     &lt;div class="color-neutral-3 d-md-block d-none pb-4"&gt;
     [java]       &lt;strong class='color-black'&gt;\$\{filteredProducts\}&lt;/strong&gt; Apps Available
     [java]     &lt;/div&gt;
     [java] 
     [java]     &lt;div class="cards-container pb-6"&gt;
     [java]       &lt;#list productsList as product&gt;
     [java] 
     [java]         &lt;#assign
     [java]           productCategories = product.categories
     [java]           portalURL = portalUtil.getLayoutURL(themeDisplay)
     [java]           productURL = portalURL?replace("home", "p") + "/" + product.urls.en_US
     [java]         /&gt;
     [java] 
     [java]         &lt;#list product.categories?filter(category -&gt; stringUtil.equals(category.name, "App")]) as category&gt;
     [java]          ...&gt; but was:&lt;...?filter(category -&gt; [category.name == "App") as category&gt;
     [java]     &lt;#assign filteredProducts = filteredProducts + 1 /&gt;
     [java]   &lt;/#list&gt;
     [java] &lt;/#list&gt;
     [java] 
     [java] &lt;div class="adt-apps-search-results"&gt;
     [java]   &lt;#if productsList?has_content&gt;
     [java]     &lt;div class="color-neutral-3 d-md-block d-none pb-4"&gt;
     [java]       &lt;strong class='color-black'&gt;\$\{filteredProducts\}&lt;/strong&gt; Apps Available
     [java]     &lt;/div&gt;
     [java] 
     [java]     &lt;div class="cards-container pb-6"&gt;
     [java]       &lt;#list productsList as product&gt;
     [java] 
     [java]         &lt;#assign
     [java]           productCategories = product.categories
     [java]           portalURL = portalUtil.getLayoutURL(themeDisplay)
     [java]           productURL = portalURL?replace("home", "p") + "/" + product.urls.en_US
     [java]         /&gt;
     [java] 
     [java]         &lt;#list product.categories?filter(category -&gt; category.name == "App"]) as category&gt;
     [java]          ...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:466)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
[stopwatch] [run.batch.test.action: 1:25.601 sec]</pre></details></html>

2023-07-18 14:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5110/">test-portal-source-format#5110</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5110/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4501">pt-liferay-solutions#4501</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2386037484">[master] ci:test:sf - claricebrasil &gt; pt-liferay-solutions - PR#4501 - 2023-07-18[07:13:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/3741/">publish-testray-report#3741</a><br/></div></div>

2023-07-18 14:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/6838/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/6838/jenkins-report.html">here</a>.</b></p>

2023-07-18 14:26 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e14870250c24bcbdb5f04c1d22050822e984dbc2">e14870250c24bcbdb5f04c1d22050822e984dbc2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/claricebrasil/liferay-portal/tree/LPS-189917">LPS-189917</a><br/>Branch GIT ID: <a href="https://github.com/claricebrasil/liferay-portal/commit/d7dea18950fbbca3211df852b8f9d9ba6e2f9d5c">d7dea18950fbbca3211df852b8f9d9ba6e2f9d5c</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/6838/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/6838/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/apps-search-results/ddm-template.ftl expected:&lt;...?filter(category -&gt; [stringUtil.equals(category.name, "App")) as category&gt;
     [java]     &lt;#assign filteredProducts = filteredProducts + 1 /&gt;
     [java]   &lt;/#list&gt;
     [java] &lt;/#list&gt;
     [java] 
     [java] &lt;div class="adt-apps-search-results"&gt;
     [java]   &lt;#if productsList?has_content&gt;
     [java]     &lt;div class="color-neutral-3 d-md-block d-none pb-4"&gt;
     [java]       &lt;strong class='color-black'&gt;\$\{filteredProducts\}&lt;/strong&gt; Apps Available
     [java]     &lt;/div&gt;
     [java] 
     [java]     &lt;div class="cards-container pb-6"&gt;
     [java]       &lt;#list productsList as product&gt;
     [java] 
     [java]         &lt;#assign
     [java]           productCategories = product.categories
     [java]           portalURL = portalUtil.getLayoutURL(themeDisplay)
     [java]           productURL = portalURL?replace("home", "p") + "/" + product.urls.en_US
     [java]         /&gt;
     [java] 
     [java]         &lt;#list product.categories?filter(category -&gt; stringUtil.equals(category.name, "App")]) as category&gt;
     [java]          ...&gt; but was:&lt;...?filter(category -&gt; [category.name == "App") as category&gt;
     [java]     &lt;#assign filteredProducts = filteredProducts + 1 /&gt;
     [java]    &lt;/#list&gt;
     [java] &lt;/#list&gt;
     [java] 
     [java] &lt;div class="adt-apps-search-results"&gt;
     [java]   &lt;#if productsList?has_content&gt;
     [java]     &lt;div class="color-neutral-3 d-md-block d-none pb-4"&gt;
     [java]       &lt;strong class='color-black'&gt;\$\{filteredProducts\}&lt;/strong&gt; Apps Available
     [java]     &lt;/div&gt;
     [java] 
     [java]     &lt;div class="cards-container pb-6"&gt;
     [java]       &lt;#list productsList as product&gt;
     [java] 
     [java]         &lt;#assign
     [java]           productCategories = product.categories
     [java]           portalURL = portalUtil.getLayoutURL(themeDisplay)
     [java]           productURL = portalURL?replace("home", "p") + "/" + product.urls.en_US
     [java]         /&gt;
     [java] 
     [java]         &lt;#list product.categories?filter(category -&gt; category.name == "App"]) as category&gt;
     [java]          ...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:466)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
[stopwatch] [run.batch.test.action: 59.657 sec]</pre></details></html>

2023-07-18 14:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/7648/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/7648/jenkins-report.html">here</a>.</b></p>

2023-07-18 14:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e14870250c24bcbdb5f04c1d22050822e984dbc2">e14870250c24bcbdb5f04c1d22050822e984dbc2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/claricebrasil/liferay-portal/tree/LPS-189917">LPS-189917</a><br/>Branch GIT ID: <a href="https://github.com/claricebrasil/liferay-portal/commit/30f59fd9e01ff5937725f3c0784a3f610658fc5e">30f59fd9e01ff5937725f3c0784a3f610658fc5e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/7648/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/7648/jenkins-report.html">here</a>.</h5></details></html>

2023-07-18 16:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/7648/">test-portal-source-format#7648</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/7648/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4501">pt-liferay-solutions#4501</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2386239863">[master] ci:test:sf - claricebrasil &gt; pt-liferay-solutions - PR#4501 - 2023-07-18[07:43:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/28686/">publish-testray-report#28686</a><br/></div></div>

2023-07-19 18:08 UTC, joanagrego approved these changes

2023-07-19 19:26 UTC, silasbsi requested changes
I added a suggestion.

2023-07-19 19:59 UTC, closed without merging