LPS-192014
pt-liferay-solutions/liferay-portal pull request #4547
Opened 2023-07-28 19:54 UTC by marinaasant0s

2023-07-28 19:55 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-07-28 20:00 UTC, marinaasant0s commented
ci:test:sf

2023-07-28 20:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/4538/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4538/jenkins-report.html">here</a>.</b></p>

2023-07-28 20:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/be2015fbf5e2097b92588151ac64221f06c23b60">be2015fbf5e2097b92588151ac64221f06c23b60</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marinaasant0s/liferay-portal/tree/LPS-192014">LPS-192014</a><br/>Branch GIT ID: <a href="https://github.com/marinaasant0s/liferay-portal/commit/eac428cdd3419f71f751e29ba17b1e92ae9cb598">eac428cdd3419f71f751e29ba17b1e92ae9cb598</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4538/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4538/jenkins-report.html">here</a>.</h5></details></html>

2023-07-28 20:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4538/">test-portal-source-format#4538</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4538/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4547">pt-liferay-solutions#4547</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2396567752">[master] ci:test:sf - marinaasant0s &gt; pt-liferay-solutions - PR#4547 - 2023-07-28[13:01:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/4207/">publish-testray-report#4207</a><br/></div></div>

2023-07-31 10:43 UTC, AfonsoHSantos requested changes

2023-07-31 10:43 UTC, AfonsoHSantos commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/osb-site-initializer-partner-portal-test/src/testFunctional/macros/PRMMDFRequest.macro
> +		if ((${typeOfActivity} == "Content Marketing") && ((${tactic} == "Blog or Article") || (${tactic} == "Business White Paper or eBook") || (${tactic} == "Infographic") || (${tactic} == "Social Conten
Hi @marinaasant0s, as all the fields are the same to all these tactics, you don't need to put all these conditions. Your logic could be just for the typeOfActivity.

2023-07-31 10:44 UTC, AfonsoHSantos commented
Hi @marinaasant0s, to avoid [this type of commit](https://github.com/pt-liferay-solutions/liferay-portal/pull/4547/commits/eac428cdd3419f71f751e29ba17b1e92ae9cb598), please remember to run `ant format-source-local-changes` before start your commits.

2023-07-31 20:59 UTC, marinaasant0s commented
ci:test:sf

2023-07-31 21:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1170/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1170/jenkins-report.html">here</a>.</b></p>

2023-07-31 21:03 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6788ad965784d2fe7b477380b8f50047e8c73775">6788ad965784d2fe7b477380b8f50047e8c73775</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marinaasant0s/liferay-portal/tree/LPS-192014">LPS-192014</a><br/>Branch GIT ID: <a href="https://github.com/marinaasant0s/liferay-portal/commit/f16f933ca6f6faa6b464a5108ddf59824a1de8d6">f16f933ca6f6faa6b464a5108ddf59824a1de8d6</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1170/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1170/jenkins-report.html">here</a>.</h5></details></html>

2023-07-31 21:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1170/">test-portal-source-format#1170</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1170/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/4547">pt-liferay-solutions#4547</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2397534779">[master] ci:test:sf - marinaasant0s &gt; pt-liferay-solutions - PR#4547 - 2023-07-31[13:59:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/4584/">publish-testray-report#4584</a><br/></div></div>

2023-08-03 22:05 UTC, closed without merging

2023-08-03 22:06 UTC, marinaasant0s commented
Resent #4572