LPS-142860 and LPS-142942 Creating the Activation Keys page for Commerce and Enterprise Search
pt-liferay-solutions/liferay-portal pull request #481
Opened 2021-12-09 18:25 UTC by jairmedeiros

2021-12-09 18:25 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-12-09 18:29 UTC, jairmedeiros commented
ci:test:sf

2021-12-09 18:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/354/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/354/jenkins-report.html">here</a>.</b></p>

2021-12-09 18:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2a94d9af2a0e84c518f2d94f49e8ecd5041c37b7">2a94d9af2a0e84c518f2d94f49e8ecd5041c37b7</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jairmedeiros/liferay-portal/tree/pr-434">pr-434</a><br/>Branch GIT ID: <a href="https://github.com/jairmedeiros/liferay-portal/commit/3a245696dd7563ff099d445db804d2e9914e5d70">3a245696dd7563ff099d445db804d2e9914e5d70</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/354/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/354/jenkins-report.html">here</a>.</h5></details></html>

2021-12-09 18:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/354/">test-portal-source-format#354</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/354/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/481">pt-liferay-solutions#481</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1589010014">[master] ci:test:sf - jairmedeiros &gt; pt-liferay-solutions - PR#481 - 2021-12-09[10:30:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/1250/">publish-testray-report#1250</a><br/></div></div>

2021-12-09 18:41 UTC, jairmedeiros commented
ci:test:relevant

2021-12-09 18:41 UTC, jairmedeiros commented
ci:test:stable

2021-12-09 18:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/349/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/349/jenkins-report.html">here</a>.</b></p>

2021-12-09 18:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>stable</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/350/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/350/jenkins-report.html">here</a>.</b></p>

2021-12-09 20:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 10 out of 10 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 23 out of 25 jobs passed in 1 hour 32 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2a94d9af2a0e84c518f2d94f49e8ecd5041c37b7">2a94d9af2a0e84c518f2d94f49e8ecd5041c37b7</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2a94d9af2a0e84c518f2d94f49e8ecd5041c37b7">2a94d9af2a0e84c518f2d94f49e8ecd5041c37b7</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2675">Acceptance Upstream DXP (master) #2675</a></p><details><summary><strong>ci:test:stable - 10 out of 10 jobs PASSED</strong></summary><details><summary><strong>10 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19620/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8832/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/20678/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7304/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7301/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7305/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1076/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7302/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1075/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19622/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 22 out of 25 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/349/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/18077/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16433/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>22 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8833/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7300/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8834/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1077/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19620/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1079/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8832/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7303/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/20678/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19623/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7304/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19621/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1078/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7301/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8831/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/18072/">test-portal-acceptance-pullrequest-batch(master)/patching-tool-jdk8/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7305/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1076/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7302/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1075/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8830/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19622/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-35.liferay.co [...]

2021-12-09 20:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/349/">test-portal-acceptance-pullrequest(master)#349</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/349/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/481">pt-liferay-solutions#481</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1589022451">[master] ci:test:relevant - jairmedeiros &gt; pt-liferay-solutions - PR#481 - 2021-12-09[10:49:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/1007/">publish-testray-report#1007</a><br/></div></div>

2021-12-09 20:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 12 out of 12 jobs passed in 1 hour 44 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2a94d9af2a0e84c518f2d94f49e8ecd5041c37b7">2a94d9af2a0e84c518f2d94f49e8ecd5041c37b7</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2a94d9af2a0e84c518f2d94f49e8ecd5041c37b7">2a94d9af2a0e84c518f2d94f49e8ecd5041c37b7</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2675">Acceptance Upstream DXP (master) #2675</a></p><details><summary><strong>ci:test:stable - 12 out of 12 jobs PASSED</strong></summary><details><summary><strong>12 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/350/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1070/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1074/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19618/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/20940/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/20939/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1071/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/20677/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1072/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1073/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/20941/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19619/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/350/jenkins-report.html">here</a>.</h5></details></html>

2021-12-09 20:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/350/">test-portal-acceptance-pullrequest(master)#350</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/350/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>stable<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/481">pt-liferay-solutions#481</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1589022684">[master] ci:test:stable - jairmedeiros &gt; pt-liferay-solutions - PR#481 - 2021-12-09[10:49:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/1008/">publish-testray-report#1008</a><br/></div></div>

2021-12-10 17:31 UTC, iagochaves commented
Just starting reviewing :)

2021-12-10 17:32 UTC, iagochaves commented
Just starting reviewing :)

2021-12-12 21:03 UTC, kevenleone requested changes
@jairmedeiros , @iagochaves can you guys take a look in my suggestions?

2021-12-12 21:03 UTC, kevenleone commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/index.js
>  	if (page === 'overview') {
Can we create a constant for all available pages? to avoid bad spelling

```suggestion
	if (page === pages.OVERVIEW) {
```

2021-12-12 21:03 UTC, kevenleone commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/index.js
> +	if (page === 'enterprise_search') {
```suggestion
	if (page === pages.ENTERPRISE_SEARCH) {
```

2021-12-12 21:03 UTC, kevenleone commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/index.js
> +	if (page === 'commerce') {
```suggestion
	if (page === pages.COMMERCE) {
```

2021-12-13 13:10 UTC, closed without merging

2021-12-13 18:29 UTC, iagochaves commented
resent https://github.com/pt-liferay-solutions/liferay-portal/pull/515