LPS-144992 Refactor quote-navbar for mobile view
pt-liferay-solutions/liferay-portal pull request #746
Opened 2022-01-20 18:25 UTC by samuelleolopes

2022-01-20 18:25 UTC, samuelleolopes commented
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-144992 Refactor quote-navbar for mobile view</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-144992">Refactor quote-navbar for mobile view</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Média</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Samuel Lopes</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Ilza Medeiros</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

7 files changed, 332 insertions(+), 72 deletions(-)

![](https://raw.githubusercontent.com/kevenleone/gh/main/images/looks-good.gif)

2022-01-20 18:33 UTC, silasbsi commented
ci:test:sf

2022-01-20 18:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/1363/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1363/jenkins-report.html">here</a>.</b></p>

2022-01-20 18:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/913ca167487ca02e81320c53f6de59497c7cc98c">913ca167487ca02e81320c53f6de59497c7cc98c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/samuelleolopes/liferay-portal/tree/LPS-144992">LPS-144992</a><br/>Branch GIT ID: <a href="https://github.com/samuelleolopes/liferay-portal/commit/b9dd6f92fc2486b199b097b5f7ccb6ad054043d2">b9dd6f92fc2486b199b097b5f7ccb6ad054043d2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1363/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1363/jenkins-report.html">here</a>.</h5></details></html>

2022-01-20 18:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1363/">test-portal-source-format#1363</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1363/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/746">pt-liferay-solutions#746</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1602070238">[master] ci:test:sf - samuelleolopes &gt; pt-liferay-solutions - PR#746 - 2022-01-20[10:34:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/4441/">publish-testray-report#4441</a><br/></div></div>

2022-01-20 20:42 UTC, silasbsi requested changes
LGTM :fire: But need some adjustments.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/public-navbar/index.css
> +.show-icon {
Add a space between classes 

Example:

```css
.hiden-menu {
	opacity: 0;
	transform: translateY(-5px);
	transition: cubic-bezier(0.215, 0.61, 0.355, 1) 0.3s;
	visibility: hidden;
}

.show-icon {
        opacity: 1;
	transition: cubic-bezier(0.215, 0.61, 0.355, 1) 0.3s;
	visibility: visible;
}
```

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/public-navbar/index.css
> +	transition: cubic-bezier(0.215, 0.61, 0.355, 1) 0.3s;
Create a variable for ```transition```, because there are repeated values in some classes.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/public-navbar/index.css
> +.hiden-menu {
Please, change class name ```hiden-menu``` to ```hidden-menu``` and modify this class in all files that its used.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/public-navbar/index.css
> +.show-menu {
Please, encapsulate all classes so there is no css leak.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/public-navbar/index.js
> +	['show-menu', 'hiden-menu'].map((cssClass) => {
Create a variable for ```['show-menu', 'hiden-menu']``` and use ```forEach``` instead ```map```.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/public-navbar/index.js
> +	['show-icon', 'hiden-icon'].map((cssClass) => {
Create a variable for ```['show-icon', 'hiden-icon']``` and use ```forEach``` instead ```map```.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/public-navbar/index.js
> +	['show-icon', 'hiden-icon'].map((cssClass) => {
Create a variable for ```['show-icon', 'hiden-icon']``` and use ```forEach``` instead ```map```.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/public-navbar/index.js
> +	});
Add a space here.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/public-navbar/index.js
> +		['show-menu', 'hiden-menu'].map((cssClass) => {
Create a variable for ```['show-menu', 'hiden-menu']``` and use ```forEach``` instead ```map```.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/public-navbar/index.js
> +		['show-icon', 'hiden-icon'].map((cssClass) => {
Create a variable for ```['show-icon', 'hiden-icon']``` and use ```forEach``` instead ```map```.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/public-navbar/index.js
> +		['show-icon', 'hiden-icon'].map((cssClass) => {
Create a variable for ```['show-icon', 'hiden-icon']``` and use ```forEach``` instead ```map```.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/public-navbar/index.js
> +		});
Add a space here.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/quote-navbar/index.css
> +.background-icon-close {
Please, encapsulate all classes so there is no css leak.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/quote-navbar/index.html
> +		<div class="bg-neutral-0 mr-2 pb-2 pl-2 pr-2 pt-1 rounded-pill shadow-lg voice-chat-icon">
Could you change this classes?

```css
pl-2 pr-2
```

to 

```css
px-2
```

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/quote-navbar/index.html
> +					<span class="background-icon-grid" id="button-men-icon">
Try to specify the ```id``` better. I think it should be ```button-menu-icon``` instead ```button-men-icon```. Please modify this information in all files that it is used.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/quote-navbar/index.js
> +	['show-menu', 'hiden-menu'].map((cssClass) => {
Create a variable for ```['show-menu', 'hiden-menu']``` and use ```forEach``` instead ```map```.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/quote-navbar/index.js
> +	['background-icon-close', 'background-icon-grid'].map((cssClass) => {
Create a variable for ```['background-icon-close', 'background-icon-grid']``` and use ```forEach``` instead ```map```.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/quote-navbar/index.js
> +	else {
Could you remove ```else``` conditional?

Example:

```javascript
if (myDropdown.classList.contains('show-menu')) {
    return fragmentElement.querySelector(
	'.raylife-navbar-button div span'
        ).innerText = 'CLOSE';
}
	
fragmentElement.querySelector(
    '.raylife-navbar-button div span'
    ).innerText = 'MENU';

```

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/quote-navbar/index.js
> +		['show-menu', 'hiden-menu'].map((cssClass) => {
Create a variable for ```['show-menu', 'hiden-menu']``` and use ```forEach``` instead ```map```.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/quote-navbar/index.js
> +		['background-icon-close', 'background-icon-grid'].map((cssClass) => {
Create a variable for ```['background-icon-close', 'background-icon-grid']``` and use ```forEach``` instead ```map```.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/quote-navbar/index.js
> +		});
Add a space here.

2022-01-20 20:42 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/quote-navbar/index.js
> +		else {
Could you remove ```else``` conditional?

Example:

```javascript
if (myDropdown.classList.contains('show-menu')) {
	return fragmentElement.querySelector(
		'.raylife-navbar-button div span'
	).innerText = 'CLOSE';
}

fragmentElement.querySelector(
		'.raylife-navbar-button div span'
	).innerText = 'MENU';

```

2022-01-26 12:55 UTC, welitonpe commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/public-navbar/index.js
> +	});
jusd add a breakline.

2022-01-26 12:56 UTC, welitonpe commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/public-navbar/index.js
> +		});
Just add a breakline.

2022-01-26 13:00 UTC, welitonpe commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/public-navbar/index.html
>  <nav class="navbar navbar-expand-lg navbar-light pb-3 pt-2 public-site-navbar">
Fix the formation of this file.

2022-01-26 13:01 UTC, welitonpe commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/quote-navbar/index.html
> -[#assign
Fix the formation of this file.

2022-01-26 13:29 UTC, silasbsi requested changes
LGTM :fire: But need some adjustments

2022-01-26 13:29 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/public-navbar/index.css
> +		filter: invert(54%) sepia(9%) saturate(246%) hue-rotate(195deg)
Please sort the css

2022-01-26 13:29 UTC, silasbsi commented on modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/quote-navbar/index.js
> +	}
Add a space here

2022-01-26 17:15 UTC, silasbsi approved these changes

2022-01-26 17:16 UTC, silasbsi commented
ci:test:sf

2022-01-26 17:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-source-format/4907/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/4907/jenkins-report.html">here</a>.</b></p>

2022-01-26 17:19 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9fd78fc1b8473979bce33aae9e1aa57b18d63461">9fd78fc1b8473979bce33aae9e1aa57b18d63461</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/samuelleolopes/liferay-portal/tree/LPS-144992">LPS-144992</a><br/>Branch GIT ID: <a href="https://github.com/samuelleolopes/liferay-portal/commit/31f6397b2cef27a81b85cb6ed925f6cbbde8cb4b">31f6397b2cef27a81b85cb6ed925f6cbbde8cb4b</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-source-format/4907/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/4907/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-raylife/src/main/zippableResources/fragments/raylife/fragments/quote-navbar/index.html expected:&lt;...n-menu-icon"&gt;&lt;/span&gt;[]
     [java]         &lt;/div&gt;
     [java]       &lt;/but...&gt; but was:&lt;...n-menu-icon"&gt;&lt;/span&gt;[          ]
     [java]         &lt;/div&gt;
     [java]       &lt;/but...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:403)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:249)
[stopwatch] [run.batch.test.action: 1:09.322 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:450: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:590: Java returned: 1
      [get] Getting: http://test-1-13/job/test-portal-source-format/4907//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20220126091917392.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20220126091917392.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1786158066.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null940312553
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 194ms
[junitreport] Deleting: /tmp/null940312553
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 01-26-2022 09:19:20:531 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</code></pre></details></html>

2022-01-26 18:08 UTC, silasbsi commented
ci:test:sf

2022-01-26 18:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/23/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/23/jenkins-report.html">here</a>.</b></p>

2022-01-26 18:11 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9fd78fc1b8473979bce33aae9e1aa57b18d63461">9fd78fc1b8473979bce33aae9e1aa57b18d63461</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/samuelleolopes/liferay-portal/tree/LPS-144992">LPS-144992</a><br/>Branch GIT ID: <a href="https://github.com/samuelleolopes/liferay-portal/commit/3bd92f1857c53e50b4b169879af4e4f5f171fdb4">3bd92f1857c53e50b4b169879af4e4f5f171fdb4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/23/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/23/jenkins-report.html">here</a>.</h5></details></html>

2022-01-26 18:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/23/">test-portal-source-format#23</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/23/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/746">pt-liferay-solutions#746</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1604275544">[master] ci:test:sf - samuelleolopes &gt; pt-liferay-solutions - PR#746 - 2022-01-26[10:08:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/74/">publish-testray-report#74</a><br/></div></div>

2022-01-26 20:26 UTC, kevenleone approved these changes
LGTM 🔥

2022-01-26 20:27 UTC, kevenleone commented
ci:forward

2022-01-26 20:27 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-01-26 20:27 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:sf`

2022-01-26 20:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/1903/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1903/jenkins-report.html">here</a>.</b></p>

2022-01-26 21:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 21 out of 23 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 23 out of 25 jobs passed in 1 hour 29 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/50f0a00e82945e30c6be683c283b2df982458dee">50f0a00e82945e30c6be683c283b2df982458dee</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9fd78fc1b8473979bce33aae9e1aa57b18d63461">9fd78fc1b8473979bce33aae9e1aa57b18d63461</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2855">Acceptance Upstream DXP (master) #2855</a></p><details><summary><strong>ci:test:stable - 21 out of 23 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29394/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26737/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>21 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16437/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29387/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19249/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14128/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29388/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475274/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29389/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16436/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/321/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/447083/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16434/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14129/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14126/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29390/">test-portal-acceptance-pullrequest-batch(master)/patching-tool-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/487401/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14127/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16435/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14130/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16433/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/320/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26736/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 22 out of 25 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/1903/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29394/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26737/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>22 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16437/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29387/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19249/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14128/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29388/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475274/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29389/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16436/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/321/">tes [...]

2022-01-26 21:58 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/1903//consoleFull)

2022-01-26 21:58 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/112697
[Console](https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/1903//consoleFull)

2022-01-26 21:58 UTC, closed without merging

2022-01-26 22:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/1903/">test-portal-acceptance-pullrequest(master)#1903</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1903/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/746">pt-liferay-solutions#746</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1604404718">[master] ci:test:relevant - samuelleolopes &gt; pt-liferay-solutions - PR#746 - 2022-01-26[12:27:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/5676/">publish-testray-report#5676</a><br/></div></div>