LPS-146012 [CP 2.0] Fix subscriptions navbar to show only products with subscriptions
pt-liferay-solutions/liferay-portal pull request #760
Opened 2022-01-26 18:18 UTC by claricebrasil

2022-01-26 18:18 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-01-26 20:52 UTC, iagochaves requested changes

2022-01-26 20:52 UTC, iagochaves commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/Overview/index.js
> +
```suggestion
	const [subscriptionsGroups, setSubscriptionsGroups] = useState([]);

```

Let's reduce the number of states, I saw that the allSubscription state is only used in useEffect

2022-01-26 20:52 UTC, iagochaves commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/Overview/index.js
> +					accountSubscriptionGroups
Convert this useEffect to an useMemo. return an object with the accountSubscriptionGroups and the dataAllsubscriptions
```suggestion
			return {
			accountSubscriptionGroups,
			allSubscriptions: dataAllSubscriptions
			}
```

2022-01-26 20:52 UTC, iagochaves commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/Overview/index.js
> +					accountSubscriptionGroups
```suggestion

```

2022-01-26 20:52 UTC, iagochaves commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/Overview/index.js
> +		const subscriptionsToRender = allSubscriptions
Use here the useMemo variable suggested below, example:
```suggestion
		const subscriptionsCards = accountSubscriptionsData?.allSubscriptions
```
Also, I've renamed to subscriptionsCards, what do you think?

2022-01-26 20:52 UTC, iagochaves commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/Overview/index.js
> +		setAccountSubscriptions(subscriptionsToRender);
```suggestion
		setSubscriptionsGroups(subscriptionsCards);
```

2022-01-26 20:52 UTC, iagochaves commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/extra/remote-app/src/routes/customer-portal/pages/Overview/index.js
> +								subscriptionGroupsWithSubscriptions.length > 4,
```suggestion
								accountSubscriptionsData?.accountSubscriptionGroups.length < 5,
							'justify-content-evenly':
								accountSubscriptionsData?.accountSubscriptionGroups.length > 4,
```

2022-01-27 19:51 UTC, jairmedeiros commented
LGTM 🔥

2022-01-27 19:51 UTC, jairmedeiros commented
@kevenleone

2022-01-27 21:54 UTC, jairmedeiros commented
ci:test:sf

2022-01-27 21:54 UTC, jairmedeiros commented
ci:test:stable

2022-01-27 21:54 UTC, jairmedeiros commented
ci:test:relevant

2022-01-27 21:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/1923/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1923/jenkins-report.html">here</a>.</b></p>

2022-01-27 21:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>stable</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/1924/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1924/jenkins-report.html">here</a>.</b></p>

2022-01-27 21:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/1640/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/1640/jenkins-report.html">here</a>.</b></p>

2022-01-27 21:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/29e67c44d338be860c2c25a0715ec37b6a2436df">29e67c44d338be860c2c25a0715ec37b6a2436df</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/claricebrasil/liferay-portal/tree/LPS-146012">LPS-146012</a><br/>Branch GIT ID: <a href="https://github.com/claricebrasil/liferay-portal/commit/4d0eab1055cf2f36acdd5803618bd399d4684819">4d0eab1055cf2f36acdd5803618bd399d4684819</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/1640/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/1640/jenkins-report.html">here</a>.</h5></details></html>

2022-01-27 22:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/1640/">test-portal-source-format#1640</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/1640/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/760">pt-liferay-solutions#760</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1604835725">[master] ci:test:sf - claricebrasil &gt; pt-liferay-solutions - PR#760 - 2022-01-27[13:54:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/5725/">publish-testray-report#5725</a><br/></div></div>

2022-01-27 23:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 12 out of 12 jobs passed in 1 hour 28 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/29e67c44d338be860c2c25a0715ec37b6a2436df">29e67c44d338be860c2c25a0715ec37b6a2436df</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/29e67c44d338be860c2c25a0715ec37b6a2436df">29e67c44d338be860c2c25a0715ec37b6a2436df</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2862">Acceptance Upstream DXP (master) #2862</a></p><details><summary><strong>ci:test:stable - 12 out of 12 jobs PASSED</strong></summary><details><summary><strong>12 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/1924/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25344/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29711/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29709/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25347/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25343/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25346/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/30591/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29708/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29710/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25345/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/30590/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1924/jenkins-report.html">here</a>.</h5></details></html>

2022-01-27 23:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/1924/">test-portal-acceptance-pullrequest(master)#1924</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1924/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>stable<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/760">pt-liferay-solutions#760</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1604848287">[master] ci:test:stable - claricebrasil &gt; pt-liferay-solutions - PR#760 - 2022-01-27[13:54:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/5726/">publish-testray-report#5726</a><br/></div></div>

2022-01-27 23:35 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 21 out of 22 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 24 out of 25 jobs passed in 1 hour 40 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/29e67c44d338be860c2c25a0715ec37b6a2436df">29e67c44d338be860c2c25a0715ec37b6a2436df</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/29e67c44d338be860c2c25a0715ec37b6a2436df">29e67c44d338be860c2c25a0715ec37b6a2436df</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2862">Acceptance Upstream DXP (master) #2862</a></p><details><summary><strong>ci:test:stable - 21 out of 22 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16688/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>21 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/30596/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28799/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29716/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29714/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28800/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19475/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/30595/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19474/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28801/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/337125/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8624/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16684/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29712/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29715/">test-portal-acceptance-pullrequest-batch(master)/patching-tool-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/30597/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29713/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/30594/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/426351/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/30592/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16681/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16683/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 23 out of 25 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/1923/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16688/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>23 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/30596/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28799/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29716/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29714/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28800/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19475/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/30595/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19474/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/28801/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/337125/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8624/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jd [...]

2022-01-27 23:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/1923/">test-portal-acceptance-pullrequest(master)#1923</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1923/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/760">pt-liferay-solutions#760</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1604848960">[master] ci:test:relevant - claricebrasil &gt; pt-liferay-solutions - PR#760 - 2022-01-27[13:54:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/5727/">publish-testray-report#5727</a><br/></div></div>

2022-01-28 01:36 UTC, kevenleone approved these changes
LGTM 🔥

2022-01-28 01:36 UTC, kevenleone commented
ci:forward

2022-01-28 01:36 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-01-28 01:36 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-01-28 01:37 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-31.liferay.com/job/forward-pullrequest/271//consoleFull)

2022-01-28 01:37 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/112785
[Console](https://test-1-31.liferay.com/job/forward-pullrequest/271//consoleFull)

2022-01-28 01:37 UTC, closed without merging