LPS-147477 update Congrats Actions Fragment to Mobile and Tablet View
pt-liferay-solutions/liferay-portal pull request #902
Opened 2022-02-17 21:35 UTC by Mylena-Rodrigues

2022-02-17 21:35 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-02-17 21:36 UTC, Mylena-Rodrigues commented
ci:test:sf

2022-02-17 21:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/1834/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1834/jenkins-report.html">here</a>.</b></p>

2022-02-17 21:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/39854b66e0a99c152d6c1fbe4b60fcb237e6ca39">39854b66e0a99c152d6c1fbe4b60fcb237e6ca39</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Mylena-Rodrigues/liferay-portal/tree/LPS-147477">LPS-147477</a><br/>Branch GIT ID: <a href="https://github.com/Mylena-Rodrigues/liferay-portal/commit/27eeeeb10871e1141a68233ef23ff36e954df0ba">27eeeeb10871e1141a68233ef23ff36e954df0ba</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/1834/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1834/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-raylife/src/main/resources/site-initializer/fragments/raylife/fragments/congrats-actions/index.css expected:&lt;...ngrats-actions\{    
     [java]     [align-items: center;
     [java]     flex-direction: column];
     [java]   \}
     [java]   
     [java]   .congrats-ac...&gt; but was:&lt;...ngrats-actions\{    
     [java]     [flex-direction: column;
     [java]     align-items: center];
     [java]   \}
     [java]   
     [java]   .congrats-ac...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:435)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:281)
[stopwatch] [run.batch.test.action: 1:22.696 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:450: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:593: Java returned: 1
      [get] Getting: http://test-1-30/job/test-portal-source-format/1834//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20220217134053359.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20220217134053359.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null965089998.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null20672641
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 486ms
[junitreport] Deleting: /tmp/null20672641
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results</code></pre></details></html>

2022-02-17 21:42 UTC, Mylena-Rodrigues commented
ci:test:sf

2022-02-17 21:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/1834/">test-portal-source-format#1834</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1834/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/902">pt-liferay-solutions#902</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1613545752">[master] ci:test:sf - Mylena-Rodrigues &gt; pt-liferay-solutions - PR#902 - 2022-02-17[13:38:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/6532/">publish-testray-report#6532</a><br/></div></div>

2022-02-17 21:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/1610/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1610/jenkins-report.html">here</a>.</b></p>

2022-02-17 21:46 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c2f52d5bbf5ab0e28768b9d37f0942f41631bea3">c2f52d5bbf5ab0e28768b9d37f0942f41631bea3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Mylena-Rodrigues/liferay-portal/tree/LPS-147477">LPS-147477</a><br/>Branch GIT ID: <a href="https://github.com/Mylena-Rodrigues/liferay-portal/commit/27eeeeb10871e1141a68233ef23ff36e954df0ba">27eeeeb10871e1141a68233ef23ff36e954df0ba</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1610/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1610/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-raylife/src/main/resources/site-initializer/fragments/raylife/fragments/congrats-actions/index.css expected:&lt;...ngrats-actions\{    
     [java]     [align-items: center;
     [java]     flex-direction: column];
     [java]   \}
     [java]   
     [java]   .congrats-ac...&gt; but was:&lt;...ngrats-actions\{    
     [java]     [flex-direction: column;
     [java]     align-items: center];
     [java]   \}
     [java]   
     [java]   .congrats-ac...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:435)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:281)
[stopwatch] [run.batch.test.action: 56.624 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:450: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:593: Java returned: 1
      [get] Getting: http://test-1-27/job/test-portal-source-format/1610//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20220217134550216.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20220217134550216.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null679043693.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1578614282
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 309ms
[junitreport] Deleting: /tmp/null1578614282
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results</code></pre></details></html>

2022-02-18 19:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/1843/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/1843/jenkins-report.html">here</a>.</b></p>

2022-02-18 19:17 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/52b12ece8816ce8dc1a2042a651b7d809f39faab">52b12ece8816ce8dc1a2042a651b7d809f39faab</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Mylena-Rodrigues/liferay-portal/tree/LPS-147477">LPS-147477</a><br/>Branch GIT ID: <a href="https://github.com/Mylena-Rodrigues/liferay-portal/commit/4b3dfef5681b2e356cd8f521b466881787732ee3">4b3dfef5681b2e356cd8f521b466881787732ee3</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/1843/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/1843/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-raylife/src/main/resources/site-initializer/fragments/raylife/fragments/congrats-actions/index.css expected:&lt;...ngrats-actions\{    
     [java]     [align-items: center;
     [java]     flex-direction: column];
     [java]   \}
     [java]   
     [java]   .congrats-ac...&gt; but was:&lt;...ngrats-actions\{    
     [java]     [flex-direction: column;
     [java]     align-items: center];
     [java]   \}
     [java]   
     [java]   .congrats-ac...&gt;
     [java] 2: ./modules/apps/site-initializer/site-initializer-raylife/src/main/resources/site-initializer/fragments/raylife/fragments/congrats-actions/index.html expected:&lt;... DETAILS
     [java]   &lt;/button&gt;
     [java] [
     [java] ]  &lt;button class="bord...&gt; but was:&lt;... DETAILS
     [java]   &lt;/button&gt;
     [java] []  &lt;button class="bord...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:435)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:281)
[stopwatch] [run.batch.test.action: 50.059 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:450: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:593: Java returned: 1
      [get] Getting: http://test-1-31/job/test-portal-source-format/1843//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20220218111645726.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20220218111645726.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1991493956.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1790508997
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl</code></pre></details></html>

2022-02-18 20:48 UTC, Mylena-Rodrigues commented
ci:test:sf

2022-02-18 20:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/1847/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/1847/jenkins-report.html">here</a>.</b></p>

2022-02-18 20:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/52b12ece8816ce8dc1a2042a651b7d809f39faab">52b12ece8816ce8dc1a2042a651b7d809f39faab</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Mylena-Rodrigues/liferay-portal/tree/LPS-147477">LPS-147477</a><br/>Branch GIT ID: <a href="https://github.com/Mylena-Rodrigues/liferay-portal/commit/a03409de7cd833caf6c985008197b5372849fe0d">a03409de7cd833caf6c985008197b5372849fe0d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/1847/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/1847/jenkins-report.html">here</a>.</h5></details></html>

2022-02-18 20:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/1847/">test-portal-source-format#1847</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/1847/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/902">pt-liferay-solutions#902</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1614530806">[master] ci:test:sf - Mylena-Rodrigues &gt; pt-liferay-solutions - PR#902 - 2022-02-18[12:49:04]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/6820/">publish-testray-report#6820</a><br/></div></div>

2022-02-20 21:22 UTC, kevenleone requested changes
@Mylena-Rodrigues PR looks good, just format sourcing the CSS file

2022-02-20 21:22 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-raylife/src/main/resources/site-initializer/fragments/raylife/fragments/congrats-actions/index.css
> +	.congrats-actions button{
```suggestion
	.congrats-actions button {
```

2022-02-20 21:22 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-raylife/src/main/resources/site-initializer/fragments/raylife/fragments/congrats-actions/index.css
> +	.congrats-actions{
```suggestion
	.congrats-actions {		
```

2022-02-20 21:22 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-raylife/src/main/resources/site-initializer/fragments/raylife/fragments/congrats-actions/index.css
> +@media screen and (max-width: 767.98px){
```suggestion
@media screen and (max-width: 767.98px) {
```

2022-02-21 11:12 UTC, Mylena-Rodrigues commented
@kevenleone, I uploaded the requested changes, please, check if is ok

2022-02-21 12:57 UTC, kevenleone commented
ci:forward

2022-02-21 12:57 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-02-21 12:57 UTC, kevenleone approved these changes
LGTM 🔥 

Thanks @Mylena-Rodrigues

2022-02-21 12:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/1129/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1129/jenkins-report.html">here</a>.</b></p>

2022-02-21 12:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/6208/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6208/jenkins-report.html">here</a>.</b></p>

2022-02-21 13:01 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/687d7dfd609b7727d307edba457477fa2b9de9f5">687d7dfd609b7727d307edba457477fa2b9de9f5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Mylena-Rodrigues/liferay-portal/tree/LPS-147477">LPS-147477</a><br/>Branch GIT ID: <a href="https://github.com/Mylena-Rodrigues/liferay-portal/commit/1701137e20f2402f06092d871eaae65444963842">1701137e20f2402f06092d871eaae65444963842</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/6208/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6208/jenkins-report.html">here</a>.</h5></details></html>

2022-02-21 13:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/6208/">test-portal-source-format#6208</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6208/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/902">pt-liferay-solutions#902</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1615819821">[master] ci:test:sf - Mylena-Rodrigues &gt; pt-liferay-solutions - PR#902 - 2022-02-21[04:57:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/2115/">publish-testray-report#2115</a><br/></div></div>

2022-02-21 13:51 UTC, Mylena-Rodrigues commented
ci:stop

2022-02-21 13:53 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 44 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/687d7dfd609b7727d307edba457477fa2b9de9f5">687d7dfd609b7727d307edba457477fa2b9de9f5</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/809bd94c7b016bafe6f08a451732c6c06399d37b">809bd94c7b016bafe6f08a451732c6c06399d37b</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2940">Acceptance Upstream DXP (master) #2940</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1129/jenkins-report.html">here</a>.</h5></details></html>

2022-02-21 13:55 UTC, Mylena-Rodrigues commented
ci:forward

2022-02-21 13:55 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-02-21 13:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/1905/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1905/jenkins-report.html">here</a>.</b></p>

2022-02-21 13:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/1129/">test-portal-acceptance-pullrequest(master)#1129</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1129/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/902">pt-liferay-solutions#902</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1615890936">[master] ci:test:relevant - Mylena-Rodrigues &gt; pt-liferay-solutions - PR#902 - 2022-02-21[04:58:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/3257/">publish-testray-report#3257</a><br/></div></div>

2022-02-21 13:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-22.liferay.com/job/test-portal-source-format/6820/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6820/jenkins-report.html">here</a>.</b></p>

2022-02-21 14:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/687d7dfd609b7727d307edba457477fa2b9de9f5">687d7dfd609b7727d307edba457477fa2b9de9f5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Mylena-Rodrigues/liferay-portal/tree/LPS-147477">LPS-147477</a><br/>Branch GIT ID: <a href="https://github.com/Mylena-Rodrigues/liferay-portal/commit/81dedc72647193062620f3efd9343af5322f8db6">81dedc72647193062620f3efd9343af5322f8db6</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-22.liferay.com/job/test-portal-source-format/6820/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6820/jenkins-report.html">here</a>.</h5></details></html>

2022-02-21 14:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-22.liferay.com/job/test-portal-source-format/6820/">test-portal-source-format#6820</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6820/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/902">pt-liferay-solutions#902</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1615894133">[master] ci:test:sf - Mylena-Rodrigues &gt; pt-liferay-solutions - PR#902 - 2022-02-21[05:56:40]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-22.liferay.com/job/publish-testray-report/1627/">publish-testray-report#1627</a><br/></div></div>

2022-02-21 16:03 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/1905//consoleFull)

2022-02-21 16:03 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/113703
[Console](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/1905//consoleFull)

2022-02-21 16:04 UTC, closed without merging

2022-02-21 16:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/1905/">test-portal-acceptance-pullrequest(master)#1905</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1905/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/pt-liferay-solutions/liferay-portal/pull/902">pt-liferay-solutions#902</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1615977035">[master] ci:test:relevant - Mylena-Rodrigues &gt; pt-liferay-solutions - PR#902 - 2022-02-21[05:55:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/5670/">publish-testray-report#5670</a><br/></div></div>